### ISSUE TITLE
More Granular Filters in Notes View

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1005]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Currently you can only filter on all of the auto notes and all of the user notes. It would be good to have more granular filters e.g. only show auto notes for plugins with a specific tag.

**Expected behaviour:** Have more granular filters to be able to filter notes on

**Actual behaviour:** Only able to filter on all auto notes and all user notes

**Reproduces how often:** 100%

### Additional Information

If done with or after #1004, this could also include filtering on notes relating to specific nodes or transactions.

**Comment by GammaVel** [comment]
Suggestion to add in a time based filter for the Notes

**Comment by antares1470** [comment]
Being able to filter by tags may allow more appropriate default filters to be set for the auto notes as well

**Comment by GammaVel** [comment]
Thanks for implementing the new filters @Delphinus8821 . They are working a treat!
