### ISSUE TITLE
Update Apache License Year from 2020 to 2021

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#1008]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Use search and replace to change all dates in the license to reflect the new year.

**Comment by antares1470** [comment]
This was done in #1017
