### ISSUE TITLE
Migrate + Update dependencies to NB21

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#1009]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The current code allows running from Netbeans 8, although it is not currently developed in it. 
Ideally, we should move towards supporting only NB20. This would mean incrementing the minimum version to 20

The second part of this ticket is to update any included external jars used. This may involve looking up the most recent available file on maven? and selecting that as the one Constellation downloads.

Careful consideration should be exercised incase of deprecated methods or differing functionality.

**Comment by aldebaran30701** [comment]
Possibly adding a maximum to restrict new implementations of those jars could be defensive.

**Comment by GammaVel** [comment]
hi ! There is a newer version available - version 14, released June 2022
