### ISSUE TITLE
Default Font Issue

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#1016]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

When Constellation launches the font I think is Arial throughout the application. However, when I go into Setup -> Options -> Constellation to change a preference and apply it, it also picks up the font setting in the Misc tab and changes everything to Monospaced.

### Steps to Reproduce

1. Go to Setup -> Options -> Constellation -> Application
2. Untick the Freeze Graph View
3. Click on OK

**Expected behaviour:** [What you expect to happen]
The fonts should remain as Arial

**Actual behaviour:** [What actually happens]
The font changes to Monospaced

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Additional Information

The Miscellaneous tab is what we use to change the font in Constellation. Refer to `FontUtilities.class` to how that works. The Misc tab is actually meant to be for the Output window so we shouldn't really be listening to this for Application font changes.

I would like to have a Font selection option in the Application preferences tab and perhaps somehow hide the Misc tab altogether.

**Comment by GammaVel** [comment]
On track for PR to be ready by the end of the week
