### ISSUE TITLE
Fix SonarCloud Issues

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1022]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

With the recent work done to move to Github Actions, we now have CI again which means we once again have SonarCloud picking up issues with the code base. Since the last time we had SonarCloud regularly reviewing the code, we have seen an increase in detected issues (note that this is partially due to new rules being added). It would be good then to take some time to go through and reduce these numbers again.

Ideally we will aim for the following:
- as close to 0 bugs as we can
- as close to 0 vulnerabilities as we can 
- \>= 80% security hotspots reviewed
- code smells down as low as possible
- < 3% code duplication

https://sonarcloud.io/dashboard?id=constellation-app_constellation

### Additional Information

Anyone working on this ticket should add a comment stating which rules they are working on so that there isn't any accidental doubling up

**Comment by antares1470** [comment]
Working on cleaning up the following rules:
- Math operands should be cast before assignment

**Comment by Delphinus8821** [comment]
Working on cleaning up code smells in CoreHelp.

**Comment by aldebaran30701** [comment]
I'm working my way through the MapView package for any code smells I can resolve

**Comment by aldebaran30701** [comment]
Working on:
- Add a private constructor to hide implicit public

**Comment by Delphinus8821** [comment]
Working on:
- final classes should not have protected members 
- String literals should be placed on the left side when checking for equality

**Comment by Delphinus8821** [comment]
Working on:
- Redundant casts should not be used

**Comment by Auriga2** [comment]
Working on:

- Refactor the code to eliminate nested `switch`
- Exceptions should be either logged or rethrown but not both
- Open curly brace locate at the end of a line
- Local variables should not be declared and then immediately returned or thrown

**Comment by Auriga2** [comment]
- Remaining: static base class members should not be accessed via derived types (Except Map.Entry)
- String literals should not be duplicated
- New:"String#replace" should be preferred to "String#replaceAll"
