### ISSUE TITLE
Code Test Coverage

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#1023]
### Description

It is a good idea to increase the coverage of testing on the most commonly used features of Constellation.
From this came the idea to aim for 100% test coverage on the following list of most commonly used features. The list of classes that are involved in the execution of that feature must also be tested.

Mark the class as in progress before you take on any test development.

## Plugin Framework

* [ ] DefaultPluginEnvironment (au.gov.asd.tac.constellation.graph.node.plugins.DefaultPluginEnvironment.java)
    * [x]  In Progress
* [x] DefaultPluginInteraction (au.gov.asd.tac.constellation.graph.node.plugins.DefaultPluginInteraction.java)
    * [x]  In Progress

## Common Plugins

* [x] Select In Box (au.gov.asd.tac.constellation.graph.interaction.plugins.select.BoxSelectionPlugin.java)
    * [x]  In Progress
* [x] PointSelectionPlugin (au.gov.asd.tac.constellation.graph.interaction.plugins.select.PointSelectionPlugin.java)
    * [x]  In Progress
* [x] QualityControlAutoVetter (au.gov.asd.tac.constellation.views.qualitycontrol.daemon.QualityControlAutoVetter.java)
    * [x]  In Progress
* [x] DataAccessViewTopComponent (au.gov.asd.tac.constellation.views.dataaccess.panes.DataAccessViewTopComponent.java)
    * [x]  In Progress
* [x] QualityControlViewPane (au.gov.asd.tac.constellation.views.qualitycontrol.QualityControlViewPane.java)
    * [x]  In Progress
* [x] QualityControlViewTopComponent (au.gov.asd.tac.constellation.views.qualitycontrol.QualityControlViewTopComponent.java)
    * [x]  In Progress
* [x] DefaultQualityControlAutoButton (au.gov.asd.tac.constellation.views.qualitycontrol.widget.DefaultQualityControlAutoButton.java)
    * [x]  In Progress
* [ ] ClusteringManager (au.gov.asd.tac.constellation.views.timeline.clustering.ClusteringManager.java)
    * [ ]  In Progress
* [x] DefaultInteractionEventHandler (au.gov.asd.tac.constellation.graph.interaction.visual.DefaultInteractionEventHandler.java)
    * [x]  In Progress
* [x] AutosaveGraphPlugin (au.gov.asd.tac.constellation.graph.interaction.plugins.io.AutosaveGraphPlugin.java)
    * [x]  In Progress

## Untested Classes with High Cyclomatic Complexity
* [ ] GraphVisualAccess (au.gov.asd.tac.constellation.graph.visual.framework.GraphVisualAccess.java)
    * [x]  In Progress
* [ ] TableViewPane (au.gov.asd.tac.constellation.views.tableview2.TableViewPane.java)
    * [ ]  In Progress
* [ ] MapViewTileRenderer (au.gov.asd.tac.constellation.views.mapview.MapViewTileRenderer.java)
    * [ ]  In Progress
* [ ] DataAccessPane (au.gov.asd.tac.constellation.views.dataaccess.panes.DataAccessPane.java)
    * [ ]  In Progress
* [ ] ComponentSubgraph (au.gov.asd.tac.constellation.plugins.arrangements.subgraph.ComponentSubgraph.java)
    * [ ]  In Progress
* [ ] AttributeType (au.gov.asd.tac.constellation.views.histogram.AttributeType.java)
    * [ ]  In Progress
* [ ] AttributeEditorPanel (au.gov.asd.tac.constellation.views.attributeeditor.AttributeEditorPanel.java)
    * [ ]  In Progress

### Additional Information
Refer to #413 for extra information on the push to improve unit testing.
You can check out the overview of classes tested by visiting [SonarCloud ](https://sonarcloud.io/component_measures?id=constellation-app_constellation&metric=Coverage&view=list)

**Comment by antares1470** [comment]
Have just taken a look at `QualityControlViewTopComponent` and it seems there isn't really anything that can be tested (most of it is either one line functions or calls functions that will be tested in other classes). I suspect it will be similar for the `DataAcessViewTopComponent` (and most of the top components for that matter)

**Comment by Auriga2** [comment]
Looks like `DefaultQualityControlAutoButton` is also similar.

**Comment by Auriga2** [comment]
`DefaultInteractionEventHandler` seems way too complicated to add Unit tests. I managed to mock the `EventState`, hence added 2 tests to verify the `gatherSelectedNodes` method. (feature/DefaultInteractionEventHandlerTest branch)
But having trouble mocking the `BlockingQueue<GestureHandler>` (queue), mainly because `GestureHandler ` is a private static interface. Attempted different approaches with no luck. Looks like it needs more effort, and some refactoring as well.

**Comment by GammaVel** [comment]
Will keep this open until all the PRs are reviewed
