### ISSUE TITLE
Unable to create a sample image graph using Experimental > Build Graph > From Image

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1043]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Users are unable to create a sample image graph using Experimental > Build Graph > From Image. The open dialog does not find any of the image files, even though they exist in the saved location that is being navigated to. 

### Steps to Reproduce

1. Go to Experimental on the main menu
2. Click on Build Graph > Select From Image
3. Confirm images are available for selection -> None are shown, even though they exist in the location. 

**Expected behaviour:** 
Image files can be selected, make sure jpg, gif and png are available

**Actual behaviour:** [No files are available for selection]

**Reproduces how often:** [100%]

**Comment by CrucisGamma** [comment]
Looking at this (and the graph from image plugin more broadly).

**Comment by GammaVel** [comment]
Hello @CrucisGamma. Thanks for enabling this functionality which will be great when it is working. 
I can now select the different types of image files however they are not creating a graph for me. The graph stays blank. 
Is it because my images are too large or my laptop is not powerful enough?  If you could let me know that would be great. Thanks :-)

**Comment by GammaVel** [comment]
This has been working for me with the new nightly release. I was able to create graphs from all the different types of image files: png, jpg and gif and there were no issues. I was using smaller files so there might be an issue with very high resolution images, that one just didn't build a graph for me. Thanks @CrucisGamma for figuring this one out and fixing it up!!
