### ISSUE TITLE
Quality Control Rule to Handle Blank Types

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1050]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Currently we have qc rules for missing type (type = null) and unknown type (type = "Unknown") but we don't have one for a blank type (type = "", type = "      ", etc) which I think is just as problematic (a node with a blank type doesn't trigger either of the missing or unknown type rules). I propose doing one of two things:

1) Create a new qc rule which checks if a node has a blank type, or
2) Expand the definition of the missing type rule to include blank types since specifying a blank type is effectively specifying no type

### Additional Information

Nil

**Comment by ShubhamPalriwala** [comment]
Do we just need the same qc rules for type:"" as there are for the other ones?

**Comment by antares1470** [comment]
> Do we just need the same qc rules for type:"" as there are for the other ones?

@ShubhamPalriwala I suspect the implementation of a empty type rule would be similar to that of the unknown type rule. 

As I think out loud though, given an empty type is effectively missing type, maybe expanding the definition of the missing type rule to include blank types (e.g. "", " ", "     ") would be sufficient. I'll update the ticket to include that
