### ISSUE TITLE
Open autosaved file has two different date time formats, suggest updating

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1059]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The Open Autosaved file message dialog opens when there is a autosaved file located in the autosave location which is more recent than the graph being opened. In the dialog there are two different date time formats. It would be great if they were in the same format to make it easier for the end user to see the difference in the timing. 
![image](https://user-images.githubusercontent.com/83679004/119298412-5a420f00-bca0-11eb-98ab-2c821e51136e.png)

### Steps to Reproduce

1. Open existing graph file
2. Make some changes but deliberately don't save them
3. Wait 5 mins or so
4. Browse to the autosave location and make a copy of these files
5. Close Constellation. Do not select Yes on the message that asks "do you want to save the most recent files"
6. Copy the autosave files back into the autosave location
7. Open constellation and the graph that was open previously
8. The "Open Autosaved file" message box should be displayed
9. review contents of message 

**Expected behaviour:** Date timestamps are in the same format

**Actual behaviour:** Different formats

**Reproduces how often:**Always reproducible

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by GammaVel** [comment]
Very close - there is a minor typo with AEDT instead of AEST. @aldebaran30701 would you be able to fix this?
![image](https://user-images.githubusercontent.com/83679004/151909172-01a55e64-4650-4492-b97e-27af317e54dd.png)

**Comment by aldebaran30701** [comment]
Could this maybe be because the file was created outside of daylight time and now it is autosaved within the daylight time? Just a theory!
