### ISSUE TITLE
Small Typo on the Constellation Website under Download Constellation Core - Constellation Module Suites Explained

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1063]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

There is a typo on the text for "Constellation "Core" - Constellation Module Suites Explained. It currently states "Note that this version is designed to work offline as is self contained."

This should be "Note that this version is designed to work offline as **it** is self contained."

### Steps to Reproduce

1.  Go to the Constellation app website  download section, Constellation "Core" and review the text on under Constellation Module Suites Explained

**Expected behaviour:** No Typos

**Actual behaviour:** Small typo present
![image](https://user-images.githubusercontent.com/83679004/119911530-c8d2e580-bf9c-11eb-9f8d-bcb39b5f91d2.png)

**Reproduces how often:** 100%

**Comment by arcturus2** [comment]
The wording has been changed slightly and will be deployed tonight.

**Comment by GammaVel** [comment]
Thanks @arcturus2 for making the update!
