### ISSUE TITLE
Open Recent Files list is duplicated

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1069]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

When you go File > Open Recent, the list of recent graphs is duplicated (i.e. you see each entry twice). Once you open a graph from that menu, the duplicate item for that graph disappears. The duplicate then comes back when you restart Constellation.

### Steps to Reproduce

1.  Go File > Open Recent

**Expected behaviour:** One menu item per recent graph

**Actual behaviour:** Two menu items per recent graph you haven't opened yet (in that session)

**Reproduces how often:** 100%

**Comment by serpens24** [comment]
This is no longer occuring for me. Build master brnach and tested - all good.
