### ISSUE TITLE
The Default Blaze settings under Settings are not functioning 

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1072]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The default blaze options under Setup > Options > Constellation >Graph are not updating the blazes on the graph as expected. If I change the Blaze size or Opacity and Apply, and then close and restart Constellation, the blazes are not shown with the new settings.

This issue is present in version 2.1.1 and version 2.3.

### Steps to Reproduce

1.  Open an existing graph or a new one and add some blazes to it. Take note of the size and Opacity under the blaze menu settings. 

2. Navigate to Setup > Options > Constellation >Graph

3. Adjust the Size and the Opacity to be something quite different to what was set under the blazes menu

4. Apply and restart Constellation, reopen the same graph

5. Check the size of the blazes -> they have not changed to the new setting specified

**Expected behaviour:** Blaze size and Opacity changes to the new setting that was specified under Constellation Settings.

**Actual behaviour:** Settings don't appear to have any impact

**Reproduces how often:**100%, this also happens with version 2.1.1. and with different graphs. 

### Additional Information

This is not a major issue, I can adjust the settings under the Blaze menu.

**Comment by arcturus2** [comment]
So the idea behind this feature was the default settings for adding *new* blazes is updated. See the screenshot below.

Existing blazed on the graph will be unaffected. They have already been defined and the opacity set.

![image](https://user-images.githubusercontent.com/39325530/120425031-d9c29300-c3b0-11eb-91d8-2e1e9916e6c7.png)

If you save a graph with after making the changes I see that graph keep its settings on open despite the default blaze settings.

Therefore to me this is working as intended. What do you think @GammaVel ?

If there is something confusing about how it works and needs clarification then happy to address it so its more obvious.

**Comment by GammaVel** [comment]
Thank you for reviewing my issue. I now understand the logic with having a default blaze however it doesn't come into effect for me. New blazes are not picking up the default settings as I would expect, either on a new graph or an existing one.

**Comment by GammaVel** [comment]
Reviewed my earlier comment and now understand this will only apply to a new graph and not a new blaze on an existing graph. Withdrawing this issue!   Thanks @arcturus2 for your feedback again.
