### ISSUE TITLE
Scatter Plot pop out is lacking a Maximize button

### ISSUE THREAD

**Issue by spjspj** [constellation-app/constellation#108]
You currently have to manually resize the Scatter plot when it's undocked (probably other windows as well).  Would be nice to not have to do this and have a maximize button instead.

**Comment by cygnus-x-1** [comment]
This appears to be a problem with all the views and so must be standard Netbeans TopComponent behaviour - i'm not sure if this is something we can fix.

**Comment by arcturus2** [comment]
@spjspj can you test this too now that we are using NetBeans 11 + Java 11? (https://github.com/constellation-app/constellation/releases/tag/v2.0.0-beta)

**Comment by CrucisGamma** [comment]
I don't know whom @spjspj is, but I can have a look!

**Comment by CrucisGamma** [comment]
This looks like it's still an issue.

**Comment by serpens24** [comment]
I've gone through a heap of views from the Views menu and dragged them out of Constellation to undock them and discovered none give the minimize/maximize icons .... HOWEVEr dundocking a graph DOES provide the minimiz/maximize buttons in the header ... see image below:
 
![image](https://user-images.githubusercontent.com/58677108/82769902-b6980600-9e75-11ea-8adc-1e1b5e685ba5.png)

I'll do some digging and see if theres any obvious differences... noting off the bat that the graph view code inherits from CoenableTopComponent while the other views I checked inherits from Topcomponent directly.

**Comment by aldebaran30701** [comment]
I did a quick look of this, it seems like a NetBeans window handler setting. It only allows you to maximize the topcomponent which has central focus. If you drag the Layers View into that centre window, it also shares a maximize button. Same with the tutorial view.
![image](https://user-images.githubusercontent.com/58677759/93733921-67d95d80-fc16-11ea-89d1-e45cd38278c5.png)

@arcturus2 @antares1470 
Thoughts on closing this on the basis that the user can un-dock a view and expand it themselves?

**Comment by antares1470** [comment]
> @arcturus2 @antares1470
> Thoughts on closing this on the basis that the user can un-dock a view and expand it themselves?

@aldebaran30701 based on what you've said and the fact that this seems to be a netbeans issue, I'm happy to close this
