### ISSUE TITLE
Update parameter name and description formatting on the geo exporters dialog boxes

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1082]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The geo exporters (which use PluginExecution interactively(true)) generate dialog boxes where the parameter name and description is all the same size and blends together. There is enough space available in the dialog box to add more spacing in.  Below is an image of older Constellation v1.2 compared to v2.3.
![image](https://user-images.githubusercontent.com/83679004/120724949-32f90680-c518-11eb-84a0-03b20785b9b6.png)

### Steps to Reproduce

1. Launch Constellation and open graph file
2. Open the Map View
3. Click on the download arrow that is available
4.  Inspect the text that is show in the Export to Geo.. Dialog box 

**Expected behaviour:** Text is more spaced out and easier to differentiate the parameter name and description. 

**Actual behaviour:** as per above screenshot

**Reproduces how often:** 100%

### Additional Information
Previously the description was a smaller font size, here is a look at the first version of Constellation
![image](https://user-images.githubusercontent.com/83679004/120725558-920b4b00-c519-11eb-9e5c-d452e9975cc2.png)

**Comment by antares1470** [comment]
I suspect this is probably an issue for all plugins that run interactively, not just the geo exporters

**Comment by cygnus-x-1** [comment]
> I suspect this is probably an issue for all plugins that run interactively, not just the geo exporters

Almost certainly.

**Comment by antares1470** [comment]
With the recent changes made to parameter formatting, I wonder if you are still seeing this @GammaVel?

**Comment by GammaVel** [comment]
Thanks @antares1470, you are right. It is much better with the recent changes in Release 2.4. I do wonder why there is a different colour on the bottom of the dialog box?
I'll close this issue as the font issues have been resolved. 
![image](https://user-images.githubusercontent.com/83679004/133348041-d39f5e9d-9c23-4a62-8c44-88f95df71d6d.png)
