### ISSUE TITLE
Consider moving Quick Start Guide from the What's New page

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1083]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Constellation 2.3 has introduced a new Welcome Page and What's New page. The What's New has quick-start guide which may be better placed in the online docs.

### Steps to Reproduce

1.  Launch Constellation 2.3 and navigate to the What's New Page, inspect content. 

**Expected behaviour:** The "quick-start guide" may not be needed on the "what's new" page as it conflicts a little with "what's new" and might be better placed in the online docs.  In saying that there is still a new to explain how to use the application for new starters. 

**Actual behaviour:** as per description

**Reproduces how often:** 100%

### Additional Information

Open for discussion for the wider constellation community.

**Comment by antares1470** [comment]
Could this alternatively be consolidated into a help page?

**Comment by cygnus-x-1** [comment]
> Could this alternatively be consolidated into a help page?

It feels like it belongs in a help page to me.

**Comment by antares1470** [comment]
>
> It feels like it belongs in a help page to me.

A lot of the quick start guide instructions are found the in the Graph Window help page and the Add and Selection Mode help page. Consequently, I think it should be enough to just remove the guide from the what's new page

**Comment by GammaVel** [comment]
If it gets removed can we include a link to where to find it?  I think that would be really handy.

**Comment by antares1470** [comment]
Perhaps we could include a link to the relevant help page from the Welcome page?

**Comment by arcturus2** [comment]
Yep I like that @antares1470

**Comment by GammaVel** [comment]
I agree it would be good to link to it from the Welcome page for people that are running constellation for the first time.

**Comment by GammaVel** [comment]
Thanks @antares1470 for making those updates!  Sorry to be picky but I'm just wondering if we could add in a bit of text centering and side margins?  Just so it doesn't take up the whole screen and it will be easier to read:

![image](https://user-images.githubusercontent.com/83679004/134106202-21cba18f-c948-4e7f-8ca6-2c459a1168b8.png)
I've added an example here from the git release notes so you can see what I mean: 
![image](https://user-images.githubusercontent.com/83679004/134106276-cdd85272-32ac-4520-bea2-bb56c9e45cbd.png)

Just moving this back to in Progress for your feedback

**Comment by GammaVel** [comment]
Brilliant, thanks for fixing that @antares1470. I really like it! Looks great and I like the scroll bar that pops up too.
