### ISSUE TITLE
Consolidate Constellation Font settings for the Application, Graph Labels and Logging

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1086]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Release 2.3 has introduced a new Default Application Font settings under Setup > Options> Constellation > Application Font. 
Font options are also available under Setup > Options>Miscellaneous > for the Output Window settings.
Suggestion to consolidate these into one tab to manage font settings. menu for application fonts, another menu for graph fonts, and a third menu for log fonts.

![image](https://user-images.githubusercontent.com/83679004/120729057-9471a300-c521-11eb-8d8d-856a9e88244f.png)

### Steps to Reproduce

1.  Check the Default Application Font settings under Setup > Options> Constellation > Application Font

2.  Compare to  Setup > Options>Miscellaneous > Output Window settings

**Expected behaviour:** There is a difference between the Application Font settings and the Output Window Font settings. The Application Font settings update the font throughout the application but they don't do the Output Window as seen in the log window. 
![image](https://user-images.githubusercontent.com/83679004/120729886-9dfc0a80-c523-11eb-9c31-9497b320c258.png)

**Actual behaviour:** Related functionality exists in different menu options

**Reproduces how often:** 100%
reproduce?\]

### Additional Information

Any additional information, configuration or data that might be
necessary to reproduce the issue.

**Comment by cygnus-x-1** [comment]
There's also similar font settings for the rendered text in the graph under `Setup > Options> Constellation > Label Fonts`.

**Comment by Delphinus8821** [comment]
Closing this ticket as it is not currently possible to complete. The Output Font tab is located within the Netbeans settings so we cannot move the Constellation settings to be under the same tab. The Application Font and Label Font tabs are both Constellation settings but are located in different modules and have a lot of dependencies, so moving them to combine the tabs creates multiple cyclic dependencies.
