### ISSUE TITLE
Module categories and descriptions for the new Plugins need to be added

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1087]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The module categories and descriptions for the new plugins need to be added 
![image](https://user-images.githubusercontent.com/83679004/120731142-52972b80-c526-11eb-9d84-7f21af77b05f.png)

### Steps to Reproduce

1.  Open Constellation 2.3 and go to Setup > Plugins > Installed and scroll down the list to see the new ones - Adaptors, Whats New, Welcome and the Notes view

2.  Click on the Plugin to see the description

**Expected behaviour:** New Plugins have a Category and a Description

**Actual behaviour:** Missing Category and Description

**Reproduces how often:** 100%

### Additional Information
NA

**Comment by cygnus-x-1** [comment]
I've added this for the core modules in [this PR](https://github.com/constellation-app/constellation/pull/1084).

**Comment by GammaVel** [comment]
Thanks @cygnus-x-1 for adding this in. Looks great in Release 2.4 :-)

**Comment by GammaVel** [comment]
...and here is a screenshot to fully close out this issue. 
![image](https://user-images.githubusercontent.com/83679004/130382461-363da79b-b10a-4bdf-b556-0a07ce88ed4f.png)
