### ISSUE TITLE
Improve Logging where autosave file can't be opened due to corruption

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1091]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

New functionality has been added to Constellation to improve the experience when there are corruptions in the Autosave, Star or backup files (see #19).  When there is a corruption with the Autosaved file and I select to open it, Constellation is opening up the STAR file which is the correct behaviour (as the logic detects an issue with the Autosave file), however the log file is not accurate as it states that the backup file is being opened. In this case the STAR file was opened as the autosaved file could not be. 

### Steps to Reproduce
**SET UP FILES**
1.  To reproduce this issue you need to have the right files in place. Create a graph or open an existing one. Make some changes to it and confirm in your Save location you have a STAR and .BAK file
2.  Open up the autosave location which is under the userprofile
3.  Make some changes to the graph, don't save them. When you have the autosave file and autosave file pointer created, copy them to another location for later use
4. Close Constellation. Don't save the changes to the file.
5. Now make a corruption to the autosave file. You can do this by creating a text file that is blank and giving it the same file name as the autosave file. 

**SET UP SCENARIO**
1. Copy the corrupt autosave file back into the autosave location along with the autosave pointer
2. Open up the graph from File Recent
3. Confirm you get a message asking to open up a more recent file (if not, don't proceed as you won't get the right log)
4. Click OK to open up the more recent file
5. Check the STAR file is the one that actually opens
6. Check the log files under Help Show logs

**Expected behaviour:** Log file states that the Autosaved file was attempted to be opened and could not, so the .STAR file was opened

**Actual behaviour:** The log file states that the .STAR file could not be opened so the backup was opened instead. 
![image](https://user-images.githubusercontent.com/83679004/120951688-bfabfa80-c78c-11eb-9eea-2b002c7b0f47.png)

**Reproduces how often:** This can be reproduced for these scenarios which is where there is a corruption with the autosave file and the user selects to open it:
![image](https://user-images.githubusercontent.com/83679004/120951541-7196f700-c78c-11eb-82cf-ca67f4f47c3a.png)

### Additional Information

NA

**Comment by serpens24** [comment]
Will take a look

**Comment by serpens24** [comment]
@antares1470  - I've 'prototypically' added some additional logging to both demonstrate what is really happening, and satisfy the original ticket request. Ie - if you are happy <I beleive committing this comment change would resolve the ticket.

As can be seen below, the attempt to load autosave moves star file to a .bak, and copies autosave over top of star. When attempting to open 'new' star, fails, the backup is loaded.
An alternative would be to 'try' to verify the autosave is valid before copying it over the star, but we found originally this is troublesome for big files.

INFO [au.gov.asd.tac.constellation.graph.file.save.AutosaveUtilities]: Processing request to open autosave file: C:\Users\##########\.CONSTELLATION\Autosave\4d74d1e5-dcfa-48cc-a5fb-5df47bf9cc39.star
INFO [au.gov.asd.tac.constellation.graph.file.save.AutosaveUtilities]: Backing up C:\Users\##########\Desktop\analyticgraph1.star to C:\Users\##########\Desktop\analyticgraph1.star.bak
INFO [au.gov.asd.tac.constellation.graph.file.save.AutosaveUtilities]: Replacing C:\Users\##########\Desktop\analyticgraph1.star with autosave file prior to opening
INFO [au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphOpener]: Attempting to open C:\Users\##########\Desktop\analyticgraph1.star
WARNING [au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphOpener]: Unable to open requested file, attempting to open backup C:\Users\##########\Desktop\analyticgraph1.star.bak
WARNING [au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphOpener]: Successfully opened backup file: C:\Users\##########\Desktop\analyticgraph1.star.bak, replacing star file

**Comment by antares1470** [comment]
@serpens24 That looks fine

**Comment by arcturus2** [comment]
I've given this a test and it the logs seem fine to me and explain the different scenarios like

* opening the file normally
* opening the backup file if the main file was corrupted
* failing to open the file and then the backup if both are corrupted

```
INFO [au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphOpener]: Attempting to open C:\Users\arcturus\Documents\breaking test.star
INFO [au.gov.asd.tac.constellation.graph.file.io.GraphJsonReader]: immutableObjectCache=ImmutableObjectCache[entries = 23]
INFO [au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphOpener]: breaking test read complete (0.0s)
INFO [au.gov.asd.tac.constellation.visual.opengl.utilities.SharedDrawable]: Took 0 seconds to retrieve a GL3 profile
INFO [au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphOpener]: Attempting to open C:\Users\arcturus\Documents\breaking test.star
INFO [au.gov.asd.tac.constellation.graph.file.io.GraphJsonReader]: immutableObjectCache=ImmutableObjectCache[entries = 23]
INFO [au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphOpener]: breaking test read complete (0.0s)
INFO [au.gov.asd.tac.constellation.visual.opengl.utilities.SharedDrawable]: Took 0 seconds to retrieve a GL3 profile
INFO [au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphOpener]: Attempting to open C:\Users\arcturus\Documents\breaking test.star
WARNING [au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphOpener]: Unable to open requested file, attempting to open backup C:\Users\arcturus\Documents\breaking test.star.bak
INFO [au.gov.asd.tac.constellation.graph.file.io.GraphJsonReader]: immutableObjectCache=ImmutableObjectCache[entries = 23]
INFO [au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphOpener]: Successfully opened backup file: C:\Users\arcturus\Documents\breaking test.star.bak, replacing star file
INFO [au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphOpener]: breaking test read complete (0.0s)
INFO [au.gov.asd.tac.constellation.visual.opengl.utilities.SharedDrawable]: Took 0 seconds to retrieve a GL3 profile
INFO [au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphOpener]: Attempting to open C:\Users\arcturus\Documents\breaking test.star
WARNING [au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphOpener]: Unable to open requested file, attempting to open backup C:\Users\arcturus\Documents\breaking test.star.bak
INFO [au.gov.asd.tac.constellation.graph.file.io.GraphJsonReader]: immutableObjectCache=ImmutableObjectCache[entries = 23]
INFO [au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphOpener]: Successfully opened backup file: C:\Users\arcturus\Documents\breaking test.star.bak, replacing star file
INFO [au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphOpener]: breaking test read complete (0.0s)
INFO [au.gov.asd.tac.constellation.visual.opengl.utilities.SharedDrawable]: Took 0 seconds to retrieve a GL3 profile
INFO [au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphOpener]: Attempting to open C:\Users\arcturus\Documents\breaking test.star
WARNING [au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphOpener]: Unable to open requested file, attempting to open backup C:\Users\arcturus\Documents\breaking test.star.bak
WARNING [au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphOpener]: Unable to open requested file (C:\Users\arcturus\Documents\breaking test.star) or any associated backup
INFO [au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphOpener$GraphFileOpener]: Opening D:/Users/arcturus/Documents/breaking test.star
au.gov.asd.tac.constellation.graph.file.io.GraphParseException: Entry graph.txt not found in graph file
	at au.gov.asd.tac.constellation.graph.file.io.GraphJsonReader.readGraphZip(GraphJsonReader.java:122)
	at au.gov.asd.tac.constellation.graph.file.io.GraphJsonReader.readGraphZip(GraphJsonReader.java:101)
	at au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphOpener$GraphFileOpener.doInBackground(VisualGraphOpener.java:208)
	at au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphOpener$GraphFileOpener.doInBackground(VisualGraphOpener.java:158)
	at java.desktop/javax.swing.SwingWorker$1.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.desktop/javax.swing.SwingWorker.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[catch] at java.base/java.lang.Thread.run(Unknown Source)
INFO [au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphOpener]: Attempting to open C:\Users\arcturus\Documents\breaking test.star
WARNING [au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphOpener]: Unable to open requested file, attempting to open backup C:\Users\arcturus\Documents\breaking test.star.bak
WARNING [au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphOpener]: Unable to open requested file (C:\Users\arcturus\Documents\breaking test.star) or any associated backup
INFO [au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphOpener$GraphFileOpener]: Opening D:/Users/arcturus/Documents/breaking test.star
au.gov.asd.tac.constellation.graph.file.io.GraphParseException: Entry graph.txt not found in graph file
	at au.gov.asd.tac.constellation.graph.file.io.GraphJsonReader.readGraphZip(GraphJsonReader.java:122)
	at au.gov.asd.tac.constellation.graph.file.io.GraphJsonReader.readGraphZip(GraphJsonReader.java:101)
	at au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphOpener$GraphFileOpener.doInBackground(VisualGraphOpener.java:208)
	at au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphOpener$GraphFileOpener.doInBackground(VisualGraphOpener.java:158)
	at java.desktop/javax.swing.SwingWorker$1.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.desktop/javax.swing.SwingWorker.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[catch] at java.base/java.lang.Thread.run(Unknown Source)
```
