### ISSUE TITLE
Welcome page - Missing Images for Recent files

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1094]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The Welcome page has a section for Recent Files which shows a small image of the graph and File name.  I can click on this to open the file. There is a slight issue - the image is only appearing for Files that have been previously saved and I use "Save As" to save them with a different file name. If I use " Save" or Save As" on a new graph there is no image created. There is only the file name in this section. 

There is a secondary related issue where the images are very zoomed in and appear to be a random part of the graph. It would be great if it was a full snap shot or it wasn't as zoomed in. 

### Steps to Reproduce

1.  Open a New Graph and add a node. Use Control S, File Save or Save As. 

2.  Close the graph. It won't be on the Welcome page yet. Close Constellation

3.  Reopen Constellation and check the Recent section -> the file name is shown but not the icon

4. Open the graph and make a few updates and Save it as a new graph using "File - Save As"

5. Close graph and Constellation - Check the Recent section. An image is shown for the graph

6.  Repeat these steps for an existing graph.

**Expected behaviour:**I have a small image for all of the graphs I have opened and saved in the Recent section, not just the ones that have previously been saved and saved again with "Save AS"
![image](https://user-images.githubusercontent.com/83679004/120961012-57ffaa80-c7a0-11eb-8f32-f08791b460d5.png)

The images are also not zoomed in to a small section of the graph. 

**Actual behaviour:** as per the Repro steps

**Reproduces how often:** 100%

**Comment by GammaVel** [comment]
Same area as #1097

**Comment by cygnus-x-1** [comment]
The images that are there are also zoomed in for some reason.

**Comment by GammaVel** [comment]
Great point @cygnus-x-1 , I have updated the bug description so your comments don't get overlooked and this gets fixed :-)

**Comment by Atlas139mkm** [comment]
While attempting to solve this I have discovered a few things.
- I have a solution for images not appearing on all recent graphs ( I just ensured it takes a new screen shot on a normal save as well instead of just a save as)
- The image resizing however is an issue. The Screen shot taken is of the entire window that you have open. So if you zoom really far out, you will hardly be able to see the graph. The opposite occurs for close up. examples below.
![image](https://user-images.githubusercontent.com/88649439/131769191-ea45ed73-8f8c-4563-aacc-3eb79343ca63.png)
- The screen shots are also not a square, they are horizontal rectangles so the image provided also only takes the center of the screen shot hence why sometimes the sides are cut off. 
- To properly get the full graph a lot more effort would have to go into the screen shot calculation ensuring it resizes the window to show all graph elements with limited empty space

**Comment by Atlas139mkm** [comment]
Thinking about it now, if we can reset the view of the graph before taking the screen shot it will probably work the best.

**Comment by arcturus2** [comment]
Good points @Atlas139mkm. Currently the screenshot is actually using whats on the OpenGL buffers so to get the entire graph by resetting the view will mean that the graph does have to reset for the user too. This could be annoying.

If there was a way to do all this behind the scenes in a sub graph the user can never see then that would be good. However thinking about memory, if they are working on a large graph then that will use up a lot of memory unnecessarily (i.e double) just to get the screenshot.

Please note that with your solution, please keep in mind that auto save kicks off every 5 minutes and if a screenshot is taken that often it can be a performance drain.

**Comment by Atlas139mkm** [comment]
I did have that realization while testing that taking a screen shot on a save would cause issues especially if it reset the view. My other thought was doing it every time on the graph being closed. This would mean it would only take a screen shot once, when the user was done with the graph. This might also mean resetting the view of the graph would not have an impact upon the user as they are effectively ending their session. The down side would be the graph might snap to reset just before closing which could potentially look mildly strange (only if I made it reset the view and I'm yet to test it).

**Comment by Atlas139mkm** [comment]
Thinking about it some more, probably the best option is to:
1: Have it take a screen shot on every manual save (no auto save)
2: Have it not resize (due to obvious user irritation)
3: Have to deal with the potentially oddly snapped images if the user happened to last save when the camera angle wasn't ideal

The main purpose of the ticket was to ensure a screen shot was on each recent item and this seems like the best solution.

Its a pretty minor issue, however its pretty nice to have the image be updated when the user updates the graph. But I definitely don't think its worth it dealing with ensuring the image looks flawless on the welcome screen. 

Let me know your thoughts.

**Comment by arcturus2** [comment]
@Atlas139mkm I agree with your points above. We can keep refining this in the future but I think to start with your focus to get an image there for all graphs is a good idea. I was also thinking that for some reason if the preview image no longer exists, having a nice looking placeholder image would be better than no image.

If you agree can you consider this in your solution please?

**Comment by GammaVel** [comment]
This is really interesting. I love that better images will be captured. So far with a new build I am getting an odd section on the left.  @Atlas139mkm keen to know what you think of this:
![image](https://user-images.githubusercontent.com/83679004/133375207-70ebc3e4-0175-464b-814b-6b6ee61d3754.png)

**Comment by Atlas139mkm** [comment]
hmmm interesting. Can you tell me more about those files? are they new graphs you created? are they old ones you have recently uploaded? You're currently only a laptop as well aren't you? @GammaVel

**Comment by GammaVel** [comment]
The two testing ones are new ones and the other ones are ones that I've been working on before and saved. Thanks for getting back to me fast @Atlas139mkm

**Comment by Atlas139mkm** [comment]
@GammaVel I know why... its again a smaller monitor issue.  It works by getting roughly the center of the image and displaying a window of the bigger screen shot. This is done to roughly get the most content on the image. HOWEVER this was designed for the larger monitors by the looks of things. So if the screen is smaller, the screenshot is smaller. So going 700px inwards on a smaller screenshot gets you near the opposite edge of it. hence why you only see a snippet of the right edge. 700px in on a larger screenshot must have been what was calculated to get near the middle on a bigger monitor.
![image](https://user-images.githubusercontent.com/88649439/133376924-737e2aa9-54d6-440e-b108-b1fd57f9b9c8.png)

 Ill have a look if there is a better way to design it.

**Comment by GammaVel** [comment]
That is really interesting to find out. Thanks for figuring out that information @Atlas139mkm. I will be keen to know if there is a better way of determining the screenshot image.

**Comment by arcturus2** [comment]
@GammaVel the image resize feature has been made and should be ready for you to test in the next build.

**Comment by GammaVel** [comment]
Thanks @arcturus2 and @Atlas139mkm !  Looks brilliant. I am getting really nice images for new and existing graphs.

 The only issue is when I am going between graphs I'm getting a momentary flash of the Welcome screen which wasn't there in Release 2.4. I can see this when clicking between the graph tabs. Would this be related in any way?  I'll move this ticket back to in progress while you review.
Thanks :-)

**Comment by Atlas139mkm** [comment]
hmmm interesting. The welcome page should not do anything past the start up of the application. All the recent graphs don't even update until you have closed constellation then opened it again. I'll have a look today and see if mine replicates it. If you find yourself testing it again. Can you close the welcome page tab then try swapping graphs to see if it still happens then?

**Comment by Atlas139mkm** [comment]
I just had a quick test and I am not receiving the same issue. 
What I did:
- open 2 graphs
- swap between the two

I tried on a smaller screen as well just incase and it wasn't doing it then either.

**Comment by GammaVel** [comment]
Thanks for being super speedy in getting back to me, it still happens with the Welcome page closed. Not sure why.  Thanks for looking into it.

**Comment by arcturus2** [comment]
@GammaVel if its happening with the welcome page closed then I think the flashing issue is a different issue unrelated to this change. I'm going to move this back to testing and there is some regression improvements made to this feature (backend optimisations #1430) and that has been merged in and should be ready for testing tomorrow.

**Comment by GammaVel** [comment]
Thanks @arcturus2 for the feedback. I'm definitely still getting a flash of the welcome page but it is happening too fast for a gif. I'll investigate a bit more. 

I love the new images on the Welcome page and they are nicely reflecting my graph now. That is super exciting that it is working even for smaller screens. Thanks!
