### ISSUE TITLE
Graph view being rendered with an offset - NB11JDK11 issue

### ISSUE THREAD

**Issue by rsabhi** [constellation-app/constellation#11]
### Description

When running NB11+JDK11 codebase Graph view being rendered with an offset.
Reproduced in: HP laptop with Intel on-board graphics
This need to be tested in on-board/dedicated graphic card laptops.

Screen shot attached:
![image](https://user-images.githubusercontent.com/37701541/61422403-d48c0480-a94e-11e9-9afa-41aa0375b1d2.png)

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behaviour:** [What you expect to happen]

**Actual behaviour:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsabhi** [comment]
As per the recent conversation with JOGL team, v2.4 is compatible with java11. So it can be build from their <java11> branch until its published officially.

**Comment by arcturus2** [comment]
Interesting to note that the offset problem only appears to occur when I have the scale set to 125% in Windows. If I change it to 100% then there is no offset issue.

![image](https://user-images.githubusercontent.com/39325530/66270961-a27ea480-e8a4-11e9-854e-d3b24866f06c.png)

**Comment by aldebaran30701** [comment]
Current version of [JOGL](https://jogamp.org/deployment/archive/rc/v2.4.0-rc-20200202/) - 2.4.0 Feb 2020 does not currently fix the rendering with an offset on scaled displays.
A workaround which will require decompilation of the JOGL 2.4.0 .jar code and addition of the lines in the following thread. http://forum.jogamp.org/canvas-not-filling-frame-tp4040092p4040210.html

This may be possible, but would not be useful if we decided to retrieve the files from maven, as our own copy would be the only modified file available online AFAIK.

**Comment by aldebaran30701** [comment]
Confirmed that the release version of JOGL 2.4.0 will now have fixes for High DPI scaling as seen in this issue
>Since I finally have been known which issue we are talking about,
>please notice that Bug 1374 has been reopened
><https://jogamp.org/bugzilla//show_bug.cgi?id=1374#c3>.

>In general all High-DPI issues shall be fixed for 2.4.0 release
><https://jogamp.org/wiki/index.php?title=SW_Tracking_Report_Feature_Objectives_Overview#High_DPI>.

^^ Above was commented [here](http://forum.jogamp.org/Upgrading-from-JOGL-2-3-2-to-Current-master-for-Java-11-support-tp4040335p4040348.html) on the JOGL forums.
Until then, we may be left to wait on the new release if the decompilation fix mentioned above does not deliver results.

**Comment by arcturus2** [comment]
Nice work @aldebaran30701 following this up with the JOGL devs. Very excited and its looking like we may be getting close to move to NB 11 (or NB 12 soon 😄 )
