### ISSUE TITLE
Update Issue Template

### ISSUE THREAD

**Issue by sol695510** [constellation-app/constellation#1103]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Issues lack enough concise information in the case of expected performance. For example tickets just state in the issue description:

**Description:** Plugin "X" is too slow and should be optimised to execute faster.

When they should use more measurable metrics that we can work towards in the expected/actual behaviour such as:

**Expected Behaviour:** Plugin "X" takes 5 seconds to complete execution.

**Actual Behaviour:** Plugin "X" takes 10 seconds to complete execution.

The "Steps to Reproduce" should outline the steps required to reproduce the 10 second example metric above. The rest should filled out accordingly.

The new issue ticket template needs to be updated to include instructions to do the above in the requirements and/or the sub-heading descriptions.

**Comment by danger-ahead** [comment]
I can do this. Please assign.

**Comment by sol695510** [comment]
> I can do this. Please assign.

Make the changes on the file ISSUE_TEMPLATE.md and create a PR.

**Comment by danger-ahead** [comment]
@sol695510 possibly you were referring to this change. Please have a look.
Do let me know if there are other changes necessary.
