### ISSUE TITLE
Constellation Web - broken image on ReadMe - Install guide

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1107]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

There is a broken image on Constellation Web under constellation-app/constellation-web. I am not sure what this should be an image of but it looks like a pre-requisite which is important. 

### Steps to Reproduce

1.  Go to https://github.com/constellation-app/constellation-web

2.  Scroll down to Installation Guide -> broken image

**Expected behaviour:** Image displays 

**Actual behaviour:** 
![image](https://user-images.githubusercontent.com/83679004/121476597-37d32400-ca0a-11eb-9db8-b7829a727df8.png)

**Reproduces how often:** 100%

### Additional Information
NA - Raising under this section as I am not sure how often the Web Constellation issues are checked

**Comment by antares1470** [comment]
@GammaVel I've removed the images from that section, opting instead to specify the names of the prerequisites themselves

**Comment by GammaVel** [comment]
Thanks @antares1470, that is a good idea. The page looks much better now, I was wondering what that second pre-requisite was before. Now there is only one but presumably that is enough to get up and running.
