### ISSUE TITLE
Minor typos on Constellation github website

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1108]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

There are a couple of small typos on our Github information. 
**On constellation-app/constellation-app.github.io > under File Structure Explained** 
![image](https://user-images.githubusercontent.com/83679004/121478113-0196a400-ca0c-11eb-91dd-67e9ac564367.png)

**On Constellation Adaptors/List of Adaptors ?Adaptor Functionality** 
![image](https://user-images.githubusercontent.com/83679004/121478503-6f42d000-ca0c-11eb-8553-6ff500ef7a15.png)

**On the main homepage - https://github.com/constellation-app** The training section has developer training however there is also Analyst training available. Would be good to change this section to something like User and Developer training.
![image](https://user-images.githubusercontent.com/83679004/123345334-2e64c280-d599-11eb-86de-af7941ee941f.png)

### Steps to Reproduce

1.  Go to https://github.com/constellation-app/constellation-app.github.io and review text

2.  Go to https://github.com/constellation-app/constellation-adaptors and review text

3. Look at the training section on the main page

**Expected behaviour:** No Typos

**Actual behaviour:** Typos, as per the Issue Description

**Reproduces how often:** 100%

**Comment by GammaVel** [comment]
hi @arcturus2 when these typos get fixed it would also be good to change the text for the training section to include the user training. I have added a comment to the issue description.

**Comment by antares1470** [comment]
@GammaVel I've made those changes

**Comment by GammaVel** [comment]
@antares1470  Many thanks for fixing those typos ! Looks great.
