### ISSUE TITLE
Copy Results from Analytic View

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1117]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Currently when you run an analytic in the analytic view, you can't copy the results table out of the view. It would be helpful to do so to be able to save results elsewhere. Comma separated values should suffice.

### Steps to Reproduce

1.  Open a graph with nodes and open the Analytic View
2.  Highlight some nodes and run an analytic
3.  Try copy the resulting table to another application like Notepad or Excel

**Expected behaviour:** Can copy results from result table

**Actual behaviour:** Can't copy results from result table

**Reproduces how often:** 100%

### Additional Information

Nil

**Comment by GammaVel** [comment]
Thank you, this is working like a treat.  I can export both CSV and XLSX, Thanks for adding this extra functionality!
