### ISSUE TITLE
Investigate Exporting as SVG

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1119]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Currently, Export to image exports the graph as a png. This can result in some poor image quality as you zoom in though. I don't know how possible this is but it might be worth exploring whether exporting as a svg is a possibility. If it is, this would be very helpful if you wanted to add a graph to a presentation.

### Steps to Reproduce

1.  Open a graph
2.  File > Export > To Image..

**Expected behaviour:** Resulting image is lower quality png

**Actual behaviour:** Should have an option to export as higher quality image type like svg

**Reproduces how often:** 100%

### Additional Information

Can probably close this ticket if it doesn't appear possible but it would be cool to do if it is

**Comment by HolandCrick** [comment]
Thanks a lot to @capricornunicorn123 , @antares1470, @Delphinus8821 for enhancing the SVG file export feature. The SVG file export is working, but the large graph export taking long time. Would be nice to have performance improvement during export.

![image](https://github.com/constellation-app/constellation/assets/157770877/0d7d0f71-6d75-4822-8980-e126c6ad153e)
