### ISSUE TITLE
Lacking a way to Color-by or Icon-by

### ISSUE THREAD

**Issue by spjspj** [constellation-app/constellation#112]
Two possible new analytic windows would be a 'Color by' window (in which you would be able to color the icons based on the ranges present in data - essentially color by the groups that can be found in Histogram or based on say 'Aa - Ae', 'Af - Al', 'Am - Az' from a field that only has 'A's a the start of the data) and an 'Icon by' in which you could modify the icons on the fly based on some attribute.

**Comment by cygnus-x-1** [comment]
All of this is possible using the Attribute Editor / Scripting View / REST API, however it would also be relatively easy to implement plugins to do this if it was expected to be a common enough operation.

The Analytic View provides its own version of this (color / size by score) for the results of an analytic plugin, perhaps the Histogram could also provide this (ie. color by bin)

**Comment by CrucisGamma** [comment]
Mostly a duplicate of #165!
