### ISSUE TITLE
Include Icons in Graph that aren't part of the default set

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1121]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Constellation provides the option to set a custom icon on a node. If the icon is not part of the default set that comes with Constellation though, it relies on the file path to retrieve the icon. This becomes a problem if you then share that graph with someone else as they then won't be able to see that icon and then they will need to set it themselves.

It would be helpful if any custom icons added are stored in the graph. That way you're able to share graphs with custom icons without then needing the receiver to manually add the icons themselves.

### Steps to Reproduce

1.  Open a new graph and add a node
2.  Set the icon of the node (via Attribute Editor) to some image you have
3.  Save the graph and email it to someone
4. Get the other person to open the graph in Constellation

**Expected behaviour:** Other person sees the custom icon on the node

**Actual behaviour:** Other person sees a question mark icon on the node (same one as for unknown type nodes)

**Reproduces how often:** 100%

### Additional Information

Nil

**Comment by Astroboy2022** [comment]
Thank you @OrionsGuardian for making this change. It is super handy. I have just been sharing a graph with custom icons and it works.
