### ISSUE TITLE
Analytic View results no longer sorted by default

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1122]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

In previous versions of Constellation, the results of running an analytic (or series of analytics) would be presented ordered by highest score to lowest by default. This has changed in v2.3 though to a seemingly random order that doesn't provide any value until after you've applied sorting to table. I think it would be helpful to bring back this old default sorting.

### Steps to Reproduce

1. Open an older version of Constellation (e.g. v2.1)
2. Create a graph and save it
3. Run any analytic on it (e.g. Betweenness Centrality)
4. Open the graph in v2.3 and run the same analytic
5. Compare the resulting table

**Expected behaviour:** Result sets in both versions look the same

**Actual behaviour:** Result sets have different default sort orders making it appear like there are different results being produced

**Reproduces how often:** 100%

### Additional Information

I think there was some work done to get displaying results in the analytic view more efficient so the answers may lie in what was done there

**Comment by aldebaran30701** [comment]
Tested with no issues
