### ISSUE TITLE
Add tags to plugins

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1126]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Some plugins have had tags added to them (e.g. Low Level, Selection) but the vast majority of plugins are missing these. For those plugins, we should look to add tags as tags enable better filtering in views like the Plugin Reporter

### Steps to Reproduce

1.  \[First Step\]

2.  \[Second Step\]

3.  \[and so on…\]

**Expected behaviour:** All plugins are tagged

**Actual behaviour:** Only some plugins are tagged

**Reproduces how often:** 100%

### Additional Information

Any additional information, configuration or data that might be
necessary to reproduce the issue.

**Comment by GammaVel** [comment]
The new tags in the plug in reporter are great. Just wondering if down the track there might be too many to display nicely in the drop down filer (as it expands with more tags) but that is a separate issue.

**Comment by arcturus2** [comment]
@GammaVel the intention would be to limit the amount of tags we have so this shouldn't be a major problem. Thank you for the question though.
