### ISSUE TITLE
Change Quality Category names and colours

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1136]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The current quality categories are Default, Info, Warning, Severe, and Fatal. Some of these make sense as categories but some really don't make sense as to that they mean (e.g. what does it mean for something to flag as 'Default'). The colours assigned to them are also a bit random (White, Blue, Purple, Red, Black respectively).

I'm proposing changing these categories to something that makes a little more sense to read and understand. Something like Ok (if no rules flag), Minor, Medium, Major, Severe, Critical. Colours could then follow something like Green, Blue, Yellow, Orange, Red, Dark Red/Black respectively.

**Expected behaviour:** The meaning of a Quality category is easy to understnad

**Actual behaviour:** Some quality categories (e.g. Default) are confusing to understand

**Reproduces how often:** 40-60% (The number of categories I think that are currently a tad confusing)

### Additional Information

Nil

**Comment by aldebaran30701** [comment]
Just some background, the current categories are based off the netbeans logging system for consistency. The colours were meant to be linear but I agree having orange in the mix is a better representation of getting worse. We'd have to ensure that the colors fit with colorblind users (Yellow background, white text | Yellow category, Orange category), but also worth noting that the categories are also listed in text on the row of the table.

- Default - now OK - Green
- Info - now Minor - Blue
- Warning - now Medium - Yellow/Orange
- Severe - now Major - Light Red
- Fatal - now Critical - Dark Red

When you have many rules which are in the black coloured category, it is hard to tell there is any issue in dark mode - hence the change to dark red.
![image](https://user-images.githubusercontent.com/58677759/125368087-a401c880-e3b8-11eb-994f-de463bfc16f9.png)

I'm also wondering if there is a real need to add and extra category and make it 6 total. I feel that may be enough granularity to tag rules with the 5 current options. From a UX perspective I feel like I'm either concerned about a rule or am not concerned. Let me know if you have a different opinion on adding extra categories.

**Comment by antares1470** [comment]
> I'm also wondering if there is a real need to add and extra category and make it 6 total. I feel that may be enough granularity to tag rules with the 5 current options. From a UX perspective I feel like I'm either concerned about a rule or am not concerned. Let me know if you have a different opinion on adding extra categories.

@aldebaran30701 So the idea I had in mind with adding a 6th category was mainly to distinguish when no rules are flagged on a node. e.g. the Unknown Type rule currently flags as 'Default'. The Quality Category button in the Data Access View though looks the exact same with just that rule flagging as it does if no rule is flagging (i.e. 'Quality Category: N/A').

In my head, the 'Ok' category is mainly for that button when no rule is flagged rather than being able to set a rule to 'Ok' (so potentially that means 'Ok' doesn't need to be a quality category itself). So the mapping I had in mind would be:

* Default -> Minor (Blue)
* Info -> Medium (Yellow)
* Warning -> Major (Orange)
* Severe -> Severe (Red)
* Fatal -> Critical (Dark Red)
* 
The colour of the text could obviously be adjusted to depending on the background colour (e.g. would probably use black text for the yellow background and white text on the dark red)

**Comment by aldebaran30701** [comment]
Good idea - So all vertices would be automatically "OK" until changed.

**Comment by antares1470** [comment]
> Good idea - So all vertices would be automatically "OK" until changed.

Not so much Ok until changed but rather than Ok until it flags a rule

**Comment by Delphinus8821** [comment]
Below I have included images of the changed colours and categories. Are these colours suitable?
Should I create a new category to act as the default or "ok" for when it hasn't flagged a rule yet? @antares1470 

![Minor](https://user-images.githubusercontent.com/73083035/126428502-6754b853-d18b-4802-b8ec-5de5b6d3cfa2.PNG)
![Medium](https://user-images.githubusercontent.com/73083035/126428508-2e725093-8d49-4db3-9726-e646a6f68577.PNG)
![Major](https://user-images.githubusercontent.com/73083035/126428510-fe0d37c0-0138-43fd-8759-41ee261bcee0.PNG)
![Severe](https://user-images.githubusercontent.com/73083035/126428515-4cd461f0-9a44-4781-9d93-62f280251989.PNG)
![Critical](https://user-images.githubusercontent.com/73083035/126428525-6b665d29-a862-4f4b-a7a5-77f24ff8e492.PNG)

**Comment by antares1470** [comment]
> Are these colours suitable?
> Should I create a new category to act as the default or "ok" for when it hasn't flagged a rule yet? @antares1470

@Delphinus8821 I'm liking the colours! What I'll say though is that I envisioned Medium being Yellow and Minor being blue (rather than blue and green respectively). Ok (green) would be a new category and would come up when no rules have been flagged (currently 'Default' and no rules flagged looks exactly the same which I wan to move away from).

As an aside, ideally if we can avoid displaying '<>' in the category, I think that would be good (i.e. explicitly say 'OK' and 'MINOR')

**Comment by GammaVel** [comment]
I really like the new colours, they look great. I noticed that the help guide has not been updated with the new categories and colors. Can this please be updated as part of this ticket? 

![image](https://user-images.githubusercontent.com/83679004/128468833-b54cd16f-c67d-4259-b161-4bccae197a84.png)

**Comment by antares1470** [comment]
@GammaVel I've made that update here: #1215

**Comment by GammaVel** [comment]
Brilliant!!!  Thanks @antares1470 for updating the help guide for the new settings!  Now I know what each of the new categories and colors mean. 
![image](https://user-images.githubusercontent.com/83679004/130384175-566c764a-5bde-4a11-9b7f-5b564439f389.png)
