### ISSUE TITLE
Show when quality control rule has a category which is different from the default

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#1140]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
Currently, the UI that enables the category of the QC rules to be customized does not show when the value is different from the default. This makes it difficult to realize when it has been changed. Ideally, some representation of the default value would be shown, or some extra text on the button to reset default to show "reset to FATAL". 

Another option could be to disable the reset button when the rule is on its default. That way if reset is enabled the user will know that it is a viable option to reset the choice.

Use your best judgement on what could potentially be a viable solution. Feel free to comment below any ideas for this.
\[Description of the issue\]

### Steps to Reproduce

1.  Open Quality Control View

2.  Open Category priorities within the view

![image](https://user-images.githubusercontent.com/58677759/125367038-8af81800-e3b6-11eb-9065-d163f8eed0d5.png)

**Expected behaviour:** Some representation when the current category is not the same as the default

**Actual behaviour:** nothing.

**Reproduces how often:** 100%

### Additional Information

N/A

**Comment by GammaVel** [comment]
Thanks @aldebaran30701  for making these changes and thanks @antares1470 for suggesting them. It is working as intended. I noticed if I change back to the default and then change it again it has "Reset" without the default however I don't think there are any issues with this. As a suggestion, it might be good to update the help information with some more context on the defaults. I will make a new ticket for this.
