### ISSUE TITLE
Auto Notes remain after undo

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1141]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

If you have the Notes View open and you run a plugin (e.g. Create a Node), an auto note is generated. If you undo this though, the note remains and the user could be blissfully unaware that the auto note is no longer relevant. I think if an undo happens, the relevant auto note should either be updated to note that the plugin action was undone, or be removed altogether. I lean towards the latter

### Steps to Reproduce

1. Open a new graph
2. Open Notes View and have the auto notes filter on
3. Add a node
4. Observe the note generated in notes view
5. Undo that add (Ctrl-Z)

**Expected behaviour:** Auto note is either removed or updated to indicate an undo

**Actual behaviour:** Auto note doesn't change and remains

**Reproduces how often:** 100%

**Comment by Auriga2** [comment]
Noticed another issue in the Noes view: 

Undo and Redo actions disappear just when clicking on the Notes view. ( Edit->undo and redo options disables and short keys don't work) 

Apparently because it updates the state after most of the  actions on Notes View. While debugging it disappears at the `graph.setObjectValue(stateAttributeId, 0, newState);` in the `NotesViewController.NotesViewStateWriter `. 

Probably can be handled in a separate bug.

**Comment by GammaVel** [comment]
It is great to see this bit of functionality working as it means the Auto notes will line up with the set of final actions. I have tried this out and it is working really well.  Thanks @Auriga2 !
