### ISSUE TITLE
Caching issue preventing new Tab Names displaying for File delimiter and import from DB

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1149]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The **From File Delimiter** and **From JDBC** tabs have been renamed to be **From File** and **From Database** respectively. The updates did not take into effect until the constellation folder was deleted under D:\Users\gamma\AppData\Roaming\.constellation

Looks like there are some files in the cache for this which need to be cleared up for the tab change to take effect.

### Steps to Reproduce

1.  Download the latest version of Constellation

2.  Click on import from file (either from the main menu or clicking on the icon) -> Check the tab name ->  it still shows as From Delimited File

3. Click on Import for Database -> Check the tab name -> It still shows as From JDBC

4. Close Constellation

5. Go back and clear the constellation folder D:\Users\gamma\AppData\Roaming\.constellation

6. Relaunch Constellation - Repeat the same steps to launch Import from file and import from JDBC > Tabs are now named correctly.  

**Reproduces how often:** 100%
### Additional Information

![image](https://user-images.githubusercontent.com/83679004/127078461-e91e6a99-886f-4304-afdc-761405a3b400.png)

**Comment by Auriga2** [comment]
Welcome page still has the previous captions. Not the same issue, because I see the correct tabs here:
![image](https://user-images.githubusercontent.com/64826928/127618279-f8840239-9e83-4fa9-8f17-50becfc247dd.png)

**Comment by GammaVel** [comment]
Very interesting and good pickup. I have the same old names on the welcome page even though I have cleared the cache.

**Comment by arcturus2** [comment]
Resetting the cache is a way to resolve this and a script has been made available in the root level when you unzip the zip file. See https://github.com/constellation-app/constellation-applications/pull/3 for more details.

**Comment by GammaVel** [comment]
Thanks @arcturus2 for creating the script and thanks @aldebaran30701 for the detailed analysis. It would be great to promote it on the website and help guide, so people know it is there in case they find some functionality is missing.
