### ISSUE TITLE
Allow enabling/disabling of QC Rules

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1151]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

In the Quality Control View, you have the ability to modify the quality category of each of the rules (if you don't like the given defaults). There may be scenarios though when some of the given rules don't seem relevant or important. In such circumstances you may want to then mark the category as Ok (which currently isn't possible), but I think what makes more sense is to be able to turn off rules you're not interested in (because I think it might look a little odd being told by the QC view that a particular node is ok despite it indicating all these rules flagging).

The ability to enable/disable rules will give more power to the user to determine what data quality issues are important to them rather than leaving it the development team to make that determination.

### Steps to Reproduce

1. Open Quality Control View
2. Select Category Priority to open up dialog box

**Expected behaviour:** Users should be able to enable/disable rules if so desired

**Actual behaviour:** A rule can be set to MINOR at the lowest, can't disable a rule at all

**Reproduces how often:** 100%

### Additional Information

By default I think every rule should be enabled (mimicking current behaviour). Choosing to disable a rule is then in the hands of the user

**Comment by GammaVel** [comment]
Thanks @antares1470 for adding the ability to disable the QC rules if they are not required. I tried this out and it worked well. I also tried out the fix for the QC update in the DAV and that was working too (fix mentioned in the MR).
