### ISSUE TITLE
Review existing INFO and FINE logging

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#116]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

This is an investigative task along with implementing recommendations from the finding.

A review of the current logging and INFO and FINE can do with a review and see if any of them should change.

To start with we need to define what the criteria/rules are that determine if a log message should be logged at INFO or FINE.

The 2 high level tasks are:
* [ ] Define and document in [CONTRIBUTING.md](https://github.com/constellation-app/constellation/blob/master/CONTRIBUTING.md) what are the criteria/rules we should use to determine if we log at the INFO or FINE level
* [ ] Implement recommendations from the investigation so that it aligns with the criteria/rules

**Comment by aldebaran30701** [comment]
Are we talking about going through every instance where something is logged to those levels and making sure that the appropriate message is sent, as well as logged at the appropriate level? Sounds like a long, ongoing task. 
Wondering if you have any ideas for a plan of attack - can we just review the existing logs where there is an issue? EG. during test running or application start - logging messages may clutter up the console and may be easy to identify.

**Comment by arcturus2** [comment]
@aldebaran30701 so this was more about defining and documenting what would constitute INFO and other levels. Then it would be to go through them and that part can be more time consuming. There are 611 `LOGGER` calls so I don't think it will take that much time if we divide and conquer.

**Comment by aldebaran30701** [comment]
@arcturus2  Closing this for cleanup.
