### ISSUE TITLE
Notes View - expand the size of the Edit message box

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1176]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Extra functionality has been added to the Notes view so Notes can be added to Nodes or Transactions. Thanks for that. Would it be possible to make the Edit message box wider by default when Edit is first click on as you can't see what the text is on the radio buttons. 

This is a minor issue but would help with UX. I noticed if I drag the Edit pane that it expands to show all the text. Having this size initially would be good.  

### Steps to Reproduce

1.  Launch the notes view

2. Add in a user note

3. Click on Edit to user note

**Expected behaviour:** I can see all of the text on the message box when first lanuched

**Actual behaviour:** I wasn't too sure what the text was and didn't realise that 
**Reproduces how often:**100%

### Additional Information

![image](https://user-images.githubusercontent.com/83679004/128809990-1e6e203d-de61-4ad7-997e-e3031c05f4c7.png)

**Comment by antares1470** [comment]
I'm wondering if the changes made here #1325 (which was addressing #1290) might resolve this issue. Thoughts @GammaVel?

**Comment by GammaVel** [comment]
I agree @antares1470 with the new screen design that this issue is now irrelevant. I'm happy to close this off.
