### ISSUE TITLE
Fix NB11Jdk11 build issues in TravisCI 

### ISSUE THREAD

**Issue by rsabhi** [constellation-app/constellation#12]
### Description

Currently TravisCI build support only Netbeans 8.2 and jdk 8 build. So updated the .travis.yml file, docker file to handle JDK11 Netbeans 11

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behaviour:** [What you expect to happen]

**Actual behaviour:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by aldebaran30701** [comment]
@TheDen Seeming as you have done some work on Travis for this project, what would be the best way to tackle this? Am I on the right path?

I've had a look over the **travis.yml** file and the general consensus is to add a tag for JDK version. It seems to be managing that part correctly to my limited Travis knowledge. 
I looked at the build log and why the branch is failing; 
>The command "docker run -v $(pwd):/workdir/ --workdir /workdir/ constellation-app/netbeans-builder .travis/script.sh" exited with 125.
0.07s$ sonar-scanner
sonar-scanner: command not found
The command "sonar-scanner" exited with 127.

Would the issue be that SonarQube is not connected to the NB11 branch?
I'm interested in giving this a crack if it isn't too far over my head (not knowing much regarding Travis)

**Comment by TheDen** [comment]
Hey @aldebaran30701 the `sonar-scanner` doesn't because we use the [SonarCloud addon on Travis](https://github.com/constellation-app/constellation/blob/master/.travis.yml#L22-L26), so locally it won't have `sonar-scanner`. 

I created a NB11 docker image with zulu jdk (`zulu11.37.17-ca-jdk11.0.6-linux_x64`), but I'm not sure whether we want to replace the existing image now with that one, or have both images available for now?

Which branch is NB11 in? I can add the Dockerfile there, and we can have two Dockefiles (and eventually deprecate the old one?)

**Comment by aldebaran30701** [comment]
Hi @TheDen 
>Which branch is NB11 in?

Its in nb11jdk11migration-master

>I created a NB11 docker image with zulu jdk (zulu11.37.17-ca-jdk11.0.6-linux_x64), but I'm not sure whether we want to replace the existing image now with that one, or have both images available for now?

I'd assume we would be able to have both images available; for testing and analysis of new pull requests. As long as this is the idea @arcturus2 had in mind.

>I can add the Dockerfile there, and we can have two Dockefiles (and eventually deprecate the old one?)

This is what I would be happy with - How would switching of the files be done? Would it be hardcoded within the NB11 branch?
Would both build using TravisCI when pulled from respective branches? [Master | nb11jdk11migration-master]

**Comment by arcturus2** [comment]
> I'd assume we would be able to have both images available; for testing and analysis of new pull requests. As long as this is the idea @arcturus2 had in mind.

Yes please @aldebaran30701 and @TheDen. We will need both for testing until we get the NB11 version ready for release.
