### ISSUE TITLE
Refactor JSON Serialization/De-Serialization

### ISSUE THREAD

**Issue by formalhaunt** [constellation-app/constellation#1202]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Separate out the Jackson serialization/de-serialization from the graph creation logic. Basically each plugin has this IO class in it that has this transformation logic in it describing how to take the fields and values in the JSON and create the objects. Ideally the POJO would be the object that the IO class is creating but it does not seem to translate always.

I feel it would be cleaner to have POJOs describing the JSON and annotated with Jackson annotations. Then use a creational pattern to build the objects you need.

It would remove all this messy complicated (and prone to typo) looping through jsonNode arrays etc. Each POJO could then be serialized and de-serialized in isolation which is not the case at the moment (the write methods seem to expect the jsonGenerator to already be inside an object but the read starts one level down so it can't read what it writes).

### Steps to Reproduce

N/A

**Comment by aldebaran30701** [comment]
Added to Brainstorm ideas:
https://github.com/constellation-app/constellation/wiki/Brainstorm-Ideas
