### ISSUE TITLE
Investigate JUnit5 over TestNG

### ISSUE THREAD

**Issue by formalhaunt** [constellation-app/constellation#1203]
### Prerequisites

- [X ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

JUnit5 has been around for several years now. It has many improvements over JUnit4 and in my opinion TestNG. There seems to be more native support for JUnit5 in 3rd part libraries like Mockito (though there seems to always be 3rd party support see - https://github.com/mockito/mockito-testng).

https://junit.org/junit5/docs/current/user-guide/

There is ANT support as detailed in this example - https://github.com/junit-team/junit5-samples/tree/r5.7.2/junit5-jupiter-starter-ant

As a part of this it may be advantageous to also look at a more advanced assertion library like Hamcrest so that if the decision to change testing frameworks happens at a later stage the majority of assertions are using a third party library and don't need to be modified during the refactor.

### Steps to Reproduce

N/A

**Comment by antares1470** [comment]
Thanks for the suggestion @formalhaunt, just wanted to let you know that for now we have moved this to [Brainstorming Ideas](https://github.com/constellation-app/constellation/wiki/Brainstorming-Ideas)
