### ISSUE TITLE
Constellation Dev Training Guide Updates

### ISSUE THREAD

**Issue by Atlas139mkm** [constellation-app/constellation#1238]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

While going through the developer guide I kept track of some issues I found along the way. I have created a list below of the issues within the PDF.

Changes for PDF

Some of the images within the first 16 pages are outdated compared to the current version of netbeans.

Page 14 (actionPerformed ActionEvent)
- Uses system.out.println however It doesn't print anything to the console
- Would it be better to use Log, or another alternative?

Page 33 ( ConstellationIcon getIcon())
- the function was not working with getIcon
- changing getIcon() to getIconSymbol() fixed this issue

Page 40 (for loop)
- altering the function to accept startTime and endTime caused me issues
- I left my for loop in its basic form of just OutbreakUtilities.getFlights(cityName)
- getDepartureTime in OutbreakUtilities was calling a method that doesn't exist anymore 
- the getDepartureTime function has been changed however the pdf will still need to be altered to match it

Page 41  (edit function)
- CorePluginRegistry.DESELECT_ALL should be VisualGraphPluginRegistry.DESELECT_ALL
- CorePluginRegistry.RESET should be InteractiveGraphPluginRegistry.RESET_VIEW

Page 48 (PluginExecutor,  line 2 of code at the bottom of the page)
- another RESET issue
- corePluginRegistry.RESET = InteractiveGraphPluginRegistry.RESET_VIEW

Page 54 + (bin.key issues)
- error stating key has protected access, causing the code not to be able to use it
- key is actually a public variable
- Maybe make a note saying if this is throwing the protected access error to build coreHistogramView first then retry

**Comment by arcturus2** [comment]
Thank you @Atlas139mkm for this.

**Comment by Delphinus8821** [comment]
More things that would be good to fix in the Developer Guide

 **Bugs:**

- 	Setting Geo.Country to digraph should auto-complete to country 
- 	Duplicate cities in training data are merged, we should add country as a primary key to avoid this

**Documentation:
General:**

- 	Copy/Paste of code blocks also copies new lines, resulting in invalid syntax.
Chapter 2:
- 	2.1.6 > The screenshot of city nodes should be typed 'Location', not 'City'.
Chapter 4:
- 	4.2.2 > make it clearer that OutbreakUtilities.addFlightToRecord(>>>) replaces the entire contents of the for loop in the previous code block.
- 	4.2.3 > document how to display non-percentage progress.
Chapter 5:
- 	Need to better explain GraphReadMethods/ReadableGraph vs GraphWriteMethods/WritableGraph, how they relate to locking and the importance of .release()/.commit().
- 	Need to better explain executeNow vs executeLater.
- 	Recommend making 'Spread Outbreak' a step-by-step tutorial and having students build a selection plugin as an exercise.
Chapter 6:
- 	6.1.2 > We should move all this to the toString() method of Outbreak.
- 	6.2.2 > Add some '...' to represent code not displayed in the code block.
- 	Need more code blocks, as it is easy to lose crucial details in the blocks of text (eg. returning null for valid in 6.2.3).
Chapter 7:
- 	Top component screenshot is of the wrong top component (should not be 'improved').
- 	Improved listening diagram is missing an underscore for the 'REMOVED_AND_ADDED' transition.

**Documentation Additions:**
	Chapter 4: Controller parameter behaviour (PluginParameterControllers)
	Chapter 5: Controlling merging behaviour (GraphElementMerger / GraphAttributeMerger)
	Chapter 8: Security & Proxy management
	Chapter 9: Graph Renderer Framework 
	Chapter 9: Arrangement Framework 

**Other things that could be good to add:**
	Rendering framework 
	layer.xml
	Rest API
	Management of 3rd party libraries 
	Adding application preference options

**Comment by Quasar985** [comment]
This issue continues in https://github.com/constellation-app/constellation/issues/1982

**Comment by HolandCrick** [comment]
Thanks Quasar985 for updating the developer guide. There are few more issue which will continues in #1982.
