### ISSUE TITLE
Add Shortcut to Data Access View on Welcome Page and toolbar

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1239]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Given the Data Access View is one the ways to get data onto a graph, it makes sense to have a shortcut for it on the Welcome Page (like the File and Database Importer) as well as the top toolbar (like Histogram and Timeline)

**Expected behaviour:** A shortcut to the Data Access View from both the Welcome Page and the top toolbar

**Actual behaviour:** No such shortcuts exist

**Reproduces how often:** 100%

**Comment by GammaVel** [comment]
Thanks for adding this handy shortcut to the toolbar and welcome page.  I confirmed both of these are working and launching the view. I'm not a huge fan of the eye icon but understand why it was picked.
