### ISSUE TITLE
Make templates more obvious in Data Access View

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1240]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

One of the lesser known features of the Data Access View is creating templates. The way templates work is that you can create a workflow using steps and plugins and can save that as a template so you don't need to recreate that workflow everytime you load up Constellation. This is a cool feature, but currently it's hidden in an options menu drop-down with "Load" and "Save" not exactly being clear as to what is loading or saving.

What I propose is 2 things:
1) Move this out of the Options menu so that users can see this option from the get go
2) Rename Load/Save to something like Load/Save Template or Load/Save Workflow

### Steps to Reproduce

1. Open up Data Access View
2. Setup a workflow
3. Try and save it

**Expected behaviour:** Option to load/save template can be accessed without digging through any drop-downs

**Actual behaviour:** Option to load/save template is accessed via Options menu

**Reproduces how often:** \[What percentage of the time does it reproduce?\]

### Additional Information

The help pages for Data Access View will probably need to be updated with this change

**Comment by GammaVel** [comment]
Thank you @Atlas139mkm for making these improvements to the Data Access View options. I think it is much clearer now what these are for. I noticed my results are not saving as I would expect however I don't think this is related as I checked the previous version and it is also happening there. I'll do some more digging and raise a new issue if required.
