### ISSUE TITLE
Add Quality Button and Go Button to bottom of Data Access View

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1241]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The current workflow in Data Access View is select all the plugins you want to run (configuring parameters along the way) and then going back to the top of the view and pressing Go. This workflow while not terrible does not against the more common workflow found in applications which would have the Go button at the bottom (i.e. fill in everything top-to-bottom rather than top-to-bottom-to-top). I don't think we need to move the Go button and the Quality button (which is good to check before hitting go) to the bottom of the view but it might help with the user experience to have the option on both the top (current workflow) and the bottom (more common workflow)

**Expected behaviour:** User can press Go and check the quality at the bottom of the view

**Actual behaviour:** Have to go back to the top of the view to do these things

**Reproduces how often:** 100%

**Comment by GammaVel** [comment]
Thanks for all the hard work that went into solving this one @Atlas139mkm. I like the new buttons on the bottom of the pane and they do the same thing as the one on the top. I'll be curious to see which option people like the most.
