### ISSUE TITLE
Allow editing attributes in Attribute Editor by clicking on the field

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1242]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

To edit an attribute in the Attribute Editor, you currently have to click on the Edit button next the field, rather than the field itself. This might go against intuition which may suggest you can edit the field by merely clicking on it. I think it would be good to implement this more intuitive way of editing attributes

### Steps to Reproduce

1.  Open a graph and Attribute Editor
2. Click on the field of one of the attributes
3. Click on the edit button next to the field

**Expected behaviour:** Clicking on the attribute field brings up the interface to edit the value

**Actual behaviour:** Clicking on the attribute field does nothing. Clicking on the Edit button next to it brings up the interface.

**Reproduces how often:** 100%

### Additional Information

If this is successfully implemented, this could remove the need for the Edit button (and so could probably be removed alongside this change)

**Comment by Auriga2** [comment]
Should we open it at a single click or double click? Also removing the edit button will make it less intuitive for some users, at least until they get used to it?

**Comment by GammaVel** [comment]
I like this little nifty change, it is much easier to edit values now. Thank you @Auriga2 for fixing this up. I like the way it works with multiple click combinations; single, double, triple.
