### ISSUE TITLE
Fix inconsistencies with opening files

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1243]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Across Constellation, there are different dialog boxes that are presented when wanting to open a file. Some use the native OS while others use a custom Constellation dialog box. This should be fixed such that it is consistent across the application.

### Steps to Reproduce

1. Open Constellation
2. Go File > Open
3. Observe the dialog box
4. Open the File Importer
5. Click the + button to load a file
6. Observe the dialog box

**Expected behaviour:** Dialog box used should be the same

**Actual behaviour:** One uses a constellation dialog and the other uses the local OS dialog

**Reproduces how often:** 100%
### Additional Information

Given you get the Constellation dialog when going File > Open, I suspect it is a native Netbeans one. I do think it looks slightly nicer either way so I think using that dialog is the way to go

**Comment by sol695510** [comment]
There are 7 instances of the native Netbeans dialog versus 3 of the native OS dialog, which includes the one in the File Importer. Once I have the File Importer one switched I'll change the remaining ones to match.

**Comment by GammaVel** [comment]
Thanks @sol695510 for making this update. It looks great!  Constellation now has the same dialog displaying for open, DB import, save, save as and export and it looks quite smart. Thanks again!
