### ISSUE TITLE
Notes View - Improve screen layout on the Edit note maximised screen

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1246]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

When editing an existing note on the Notes view there is an option to maximise the "Edit Note" to be full screen. When this is done there is a bit of empty screen real estate as  the actual notes section isn't that long. If I type in lots of notes I end up with a scroll bar. As a suggestion it would be really good to make the Note section larger so I can see more of my notes without a scroll bar. I've added a screenshot below. 

### Steps to Reproduce

1.   Navigate to the Nodes View under experimental

2.  Add a user note to the graph

3.  Edit the user note which has been added to the graph
4. On the Edit Note pop up, click the maximise button
5. View the maximised screen ->  it would be great to increase the space available for the user notes so I can see more of my notes at once. Suggest moving the 3 buttons down and save down the screen. 
![image](https://user-images.githubusercontent.com/83679004/129984006-ef842fdf-9d61-4dda-b1b4-cb63f570e528.png)
<!--

### Behaviour

**Reproduces how often:** 100%

### Additional Information
NA

**Comment by antares1470** [comment]
I'm wondering if the changes made here #1325 (which was addressing #1290) might resolve this issue. Thoughts @GammaVel?

**Comment by GammaVel** [comment]
Thanks @antares1470 for the advice. I agree this issue is no longer relevant given the nice new updates which have been made to the nodes view. Happy to close it off.
