### ISSUE TITLE
Notes View - Suggestion to disable "Add" and "Remove" selected elements when note is applied to the whole graph

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1249]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

On the Notes view I can add User notes to an entire graph or an individual selection of Node and Transactions. If I add a note to the entire graph and Click Edit I am presented with three options to Keep, Add or Remove.  As an improvement it would be good if the options to Add or Remove are greyed out or hidden as the Note already applies to the entire graph so you can't really add to the selection. If I do try and remove a node from the selection, the note remains for the entire graph and if I click on "Select on graph" I can see that the node has not been removed from the Note. 

### Steps to Reproduce

1.  From the Notes View add a Note to the entire graph. 
2. Select one of the nodes on the graph
3.  Right click the note and select Remove Selected Elements
4. Navigate back to the note and R mouse click to Select on graph > Expecting node is not included in the selection

**Expected behaviour:** The options to Remove and Add don't get shown for a note that applies to the whole graph so I don't see the issue if I try to remove a node. 

**Actual behaviour:** \The node is still part of the Note as it applies to all of the graph. 

**Reproduces how often:**100%

### Additional Information
![image](https://user-images.githubusercontent.com/83679004/129995371-8d4dff08-1392-49dd-ad90-878b33c554dc.png)
new release: 
![image](https://user-images.githubusercontent.com/83679004/134610803-4a8e3486-df60-4854-8df6-4fd59d6998ab.png)

**Comment by GammaVel** [comment]
Hi Constellation developers!  I updated my screenshot here as I noticed the functionality has changed with the latest build. This is still an issue, I can select to Add or Remove to a note that applies to the whole graph but it doesn't actually do anything. It would be great if this could be fixed.

**Comment by Atlas139mkm** [comment]
Hey @GammaVel just a comment on this one. I could maybe understand removing the "Remove Selected" option when the note is attached to the graph, as there is no graph elements to remove from the note. However you wouldn't want to remove the "Add Selected" option as the user might create a note that is attached to the graph but they then want to associate it various graph elements. This just leaves the option for them to select graph elements and change the notes association. 

Who ever picks up this ticket, I would imagine the solution would be to remove the "Remove Selected" option when the note is associated with the graph.

**Comment by GammaVel** [comment]
Thank you for making this change to the notes that apply to the whole graph. It looks good.
