### ISSUE TITLE
Import from File - Attribute Section unable to be reopened once collapsed on laptop screen

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1255]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

I like to work from a laptop as it's very convenient. The "Source and Destination" and the "Attribute Filter" on the Import from file both have an option to collapse to make the section smaller. If I collapse the "Source and Destination" I can click on the twisty icon to expand it again. If I collapse the Attribute filter there doesn't appear to be a way of expanding it again from my laptop screen. I have to close and reopen Constellation.  It would be great if this could be fixed. 

### Steps to Reproduce

1.  Go to File Import

2. Collapse the "Source and Destination" > it can be expanded again

3. Collapse the Attributes Section > there is no option to expand it. The only work around I have found is to close the File Import, close and reopen constellation. 
![image](https://user-images.githubusercontent.com/83679004/130172733-4b4faaa9-11d3-419c-83f8-22ad6d890feb.png)

**Expected behaviour:**The Attribute section can be expanded once collapsed

**Actual behaviour:** Unable to reopen it

**Reproduces how often:** 100%

**Comment by Atlas139mkm** [comment]
Has this been fixed? I'm a bit confused.
For me I can expand/shrink:  source/destination and Attributes
     - in PR #1355 I have added the ability to expand/shrink the configuration section
     
I don't have a way to collapse attribute filter in the first place. I thought it was just intended to be a label and text box not a collapsible pane.

I did notice if the constellation window is too small you cannot see the attribute drop down as the screen isn't big enough to display it all.

**Comment by GammaVel** [comment]
Thanks @Atlas139mkm. This is still an issue for me. I realised the wording in my screenshot is a bit misleading as I said Attribute filter. Sorry about that. On my laptop display (15inch) I can't get the Attributes back once I collapse it, no matter what I try until close and reopen constellation. I guess it probably doesn't need an icon but a way of getting it back. Not sure if your other fix addresses that but I'm happy to give it a try.

**Comment by GammaVel** [comment]
Thanks @Atlas139mkm  for fixing this issue for people on laptops like myself. I can confirm I can get to the attributes with the vertical scroll bar. I like the way you got rid of some of the blank space too.
