### ISSUE TITLE
Right click menu for buttons down the bottom right

### ISSUE THREAD

**Issue by CrucisGamma** [constellation-app/constellation#1261]
Would be nice to have a right click menu a bit like the following for the Nodes, Links, Edges and Transactions buttons on the bottom right of the screen.  Something like 'Select all' or 'Unselect all' or 'Zoom to Selection' or similar (i.e. no new functionality, just adding a right click option to them with existing operations).

![right_click_menu](https://user-images.githubusercontent.com/62917181/130386138-c7b1c965-c82b-4ce3-b603-02ae132766c5.png)

**Comment by sol695510** [comment]
Tested, changes appear as intended.
