### ISSUE TITLE
Created nodes not visible after fly-through on empty graph

### ISSUE THREAD

**Issue by Atlas139mkm** [constellation-app/constellation#1262]
### Description

After doing a fly-through on an empty graph, then stopping the fly through, trying to add nodes to the graph creates them however they cannot be seen.

### Steps to Reproduce

1.  Create a new empty graph

2.  Experimental/Animations/Fly-Through

3.   Experimental/Animations/Stop Animating

4.  Toggle selection mode to draw mode

5.  click on the graph to add nodes (the node count in the bottom left should increase, however they will not visually appear)

**Expected behaviour:** It would be expected that the graph would continue with its normal behavior after stopping the fly-through

**Actual behaviour:** It doesn't show the nodes visually when creating them after stopping the fly through animation.

**Reproduces how often:** 100%

### Additional Information

If you stop the animation straight after starting it, the issue will not be produced. There is about a 2 second window to stop the animation to maintain the graph working.

**Comment by arcturus2** [comment]
@Atlas139mkm assume this was picked up during testing the latest release candidate?

**Comment by Atlas139mkm** [comment]
Yeah it was

**Comment by arcturus2** [comment]
Thanks @Atlas139mkm for finding this issue. I gave it a test in v2.3 and confirmed it was an issue there also. Therefore I've gone ahead and removed the v2.4.0-rc1 I added as I am going to reserve this tag for issues that only occur in the RC testing. Ideally I would prefer we don't introduce new bugs that were not there from the previous release and this tag will help to catch those.

**Comment by GammaVel** [comment]
I tried this out with the latest release candidate and this fixes the issue. Thanks again @Atlas139mkm for finding and fixing !!
