### ISSUE TITLE
Running Throb Nodes on empty graph causes a crash

### ISSUE THREAD

**Issue by Atlas139mkm** [constellation-app/constellation#1264]
### Description

Running Throb Nodes on an empty graph causes an immediate crash

### Steps to Reproduce

1.  create new graph

2.  Experimental/Animations/Throb Nodes

3.  Crash

**Expected behaviour:** Either a warning be thrown to the user or nothing

**Actual behaviour:** Constellation crashes

**Reproduces how often:** 100%

**Comment by arcturus2** [comment]
@Atlas139mkm assume this was picked up during testing the latest release candidate?

**Comment by Atlas139mkm** [comment]
Yeah it was

**Comment by arcturus2** [comment]
Thanks @Atlas139mkm for finding this issue. I gave it a test in v2.3 and confirmed it was an issue there also. Therefore I've gone ahead and removed the v2.4.0-rc1 I added as I am going to reserve this tag for issues that only occur in the RC testing. Ideally I would prefer we don't introduce new bugs that were not there from the previous release and this tag will help to catch those.

**Comment by GammaVel** [comment]
Thank you @Atlas139mkm for identifying this crash and fixing it !!! Nice work :-)
