### ISSUE TITLE
Freeform Select in the graph

### ISSUE THREAD

**Issue by CrucisGamma** [constellation-app/constellation#1268]
Would like to get a freeform select option that is able to select everything that falls within the drawn shape based on the the current viewport.  Mockup shown in attached image
![freeform_select_constellation](https://user-images.githubusercontent.com/62917181/130398733-45a4313b-8353-46d0-ae7e-55d50fcbc461.png)

**Comment by CrucisGamma** [comment]
Resolved with #1353

**Comment by arcturus2** [comment]
@GammaVel when you get a chance can you give this a test too?

**Comment by GammaVel** [comment]
This is absolutely brilliant work!  It works so well. Thank you @CrucisGamma for adding this great new feature in. @arcturus2 asked me to do some testing and it is working without any issues. I can't wait to read a new blog post on this feature.

**Comment by CrucisGamma** [comment]
Thanks for testing it @GammaVel and glad it works :)  Will write up something about it at some point hopefully ;)
