### ISSUE TITLE
Manage Templates - Clear button is cut off

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1270]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The Clear button is cut off on the Manage Templates Screen. I think this might be because of the other font and header issue for dialog boxes (https://github.com/constellation-app/constellation/issues/1266) however thought I would raise it here in case anyone else spots it.  I have also noticed that the Set Default and Delete buttons are not working as expected. When I click on them nothing happens.

### Steps to Reproduce

1.  From the File Menu click on Manage Templates

2.  Check the buttons on the screen
3. Click on the buttons to delete or set a default

**Expected behaviour:** All three buttons are shown and work. 

**Actual behaviour:** The third clear button is cut off and I can't click on it. I wasn't too sure what the button title was until I checked out version 2.3.
When I click on the buttons nothing happens with the templates. 

**Reproduces how often:**100%

### Additional Information

![image](https://user-images.githubusercontent.com/83679004/130400975-d3825f4a-5b4d-42dd-82da-eaa2aeab192b.png)

**Comment by arcturus2** [comment]
I tested this on v2.4.0-rc2 and its still an issue.

**Comment by arcturus2** [comment]
@GammaVel  please see the screenshot in https://github.com/constellation-app/constellation/pull/1329. It is wider than I want it to be but I was able to find a quick fix for now to help get v2.4 over the line. I tried to reduce the spacing between the buttons but I was unable to figure that out in the small timeframe I allowed myself for this.

**Comment by GammaVel** [comment]
Thanks @arcturus2 for resolving the issue here so quickly. All the buttons are now visible and they are working which is really good. I can manage my templates now (delete, set defaults).
