### ISSUE TITLE
Conversation View ConcurrentMod

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1271]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

If you make a graph selection that will display something in the Conversation view and then change the selection before the Conversation View had a chance to display the previous content, a ConcurrentMod exception is thrown. At that point, no conversations will display in the Conversation View.

```
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at au.gov.asd.tac.constellation.views.conversationview.ConversationBox.highlightRegions(ConversationBox.java:287)
	at au.gov.asd.tac.constellation.views.conversationview.ConversationBox$BubbleCell.updateItem(ConversationBox.java:440)
	at au.gov.asd.tac.constellation.views.conversationview.ConversationBox$BubbleCell.updateItem(ConversationBox.java:389)
```

### Steps to Reproduce

1. Open Conversation View
2. Open Cornell_Movie-Dialogs_Corpus-Enemy_of_the_State.star from Exercise 7 of the analyst training
3. Select the node at the center of the main star shape on the graph (DEAN)
4. Select one of attached transactions/edges/links before the content in the Conversation View has updated

**Expected behaviour:** No exception is thrown, Conversation view is still usable after changing the selection

**Actual behaviour:** Exception is thrown, Conversation view unusable

**Reproduces how often:** 100%

### Additional Information

I couldn't get this to replicate in v2.3 but I observed that the content in Conversation view loaded much faster compared to v2.4rc2. I therefore won't rule out that it might be happening in v2.3 or earlier but certainly something happening in the Conversation view in v2.4rc2 makes it far easier for it to occur

**Comment by GammaVel** [comment]
Thank you @arcturus2 for fixing this.  I tried to break this and can't  - I'm no longer getting the concurrent mod error.
