### ISSUE TITLE
Introduction link in Whats New page is broken

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1274]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

At the top of Whats New Page is a hyperlink that's supposed to go to an introduction. This link no longer works and should be fixed.

### Steps to Reproduce

1. Open Whats New Page
2. Click on 'introduction' hyperlink located at top of page

**Expected behaviour:** Goes to an introduction page

**Actual behaviour:** Nothing

**Reproduces how often:** 100%

### Additional Information

Any additional information, configuration or data that might be
necessary to reproduce the issue.

**Comment by GammaVel** [comment]
Working now!  Thanks for fixing the broken link  :-)
