### ISSUE TITLE
Welcome page - Recent File Icons - improve length if file name or add hover text

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1286]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The Welcome page has a recent section with icons to open files that have been accessed lately. I like to have long file names as it lets me know what my graph is all about. I have noticed that the file names are being cut off at 20 characters on the recent icons. Can this be increased to allow for more or could hover text be added so I can see the full name? I actually have a couple of longer file names that are almost the same name but because the file name is being cut off I can't tell the difference. This would be nice to have functionality. 

### Steps to Reproduce

1.  Open Constellation Welcome page > look at the Recent files section
2.  Access some files that have longer file names and check the Recent files section > not all the file name can be seen. 
3.  Look for some hover text for the full file name > non available. 

**Expected behaviour:** There is hover text so I can see the full file name &/OR more file name characters are allowed OR the size of the file name shrinks so it is all shown on the card. 

**Actual behaviour:** File names are cut off at around 20 characters

**Reproduces how often:** 100%

### Additional Information

![image](https://user-images.githubusercontent.com/83679004/130707392-14bf9d63-39c3-41fc-9fb5-81155855cbe4.png)

**Comment by GammaVel** [comment]
Notice how not all of the tiles have the graph picture shown?   There is another issue for that: https://github.com/constellation-app/constellation/issues/1094

**Comment by Atlas139mkm** [comment]
After looking into this a bit, I have run into a few issues. Setting a tooltip (hover text) onto the buttons throws an illegalArgumentException: type mismatch. The Error points to javafx.controls/javafx.scene.control.Control.loadSkinClass. After extensive googling I cannot find a solution for this issue. If someone has seen this error before or knows how to fix it, please let me know.

potential other solutions I could think of were: 
- wrapping the text of the file name
    - This would allow more of the file name to appear
    - However if there was a screen shot of the graph on the button then it would still get cut off by the size of the button
- Increasing the size of the buttons so that there is more room for the text to appear on the button.
    - Bigger button = more space for graph picture and filename text

**Comment by Atlas139mkm** [comment]
can do, give me a sec

**Comment by GammaVel** [comment]
Thanks @Atlas139mkm for adding the hover text. This really helps me with my graph files that have similar long file names.
