### ISSUE TITLE
Notes view deleting user added notes on specific sequence of events

### ISSUE THREAD

**Issue by Atlas139mkm** [constellation-app/constellation#1287]
### Description

Adding a note to a node then closing notes view, deselecting the node and opening the notes view removes the note from the node it was placed on. 

Gif at the bottom shows a clear demonstration of this.

### Steps to Reproduce

1.  Open notes view (ensure no other views open)

2.  Select a node

3.  input a title and content and add a note to it

4. close notes view

5. deselect currently selected node 

6. open notes view

7. select node the original note was made on

8. there is no note

**Expected behaviour:** The note should stay on the node when it is placed on it, no matter what the user does (other than deleting it)

**Actual behaviour:** The note deletes its self

**Reproduces how often:** 100%

### Additional Information

![Notes View Bug](https://user-images.githubusercontent.com/88649439/130709245-9a585f7a-b3c8-4c19-98a2-08e0fed24e18.gif)

**Comment by sol695510** [comment]
![user note deletion bug](https://user-images.githubusercontent.com/58677774/130730006-3ac927ab-3e15-44f5-9356-9b3210a4de7b.gif)
The bug is not limited to just user notes that are assigned to a node but also for user notes that are assigned to the graph as well.

**Comment by GammaVel** [comment]
Thanks for adding the notes back @sol695510 . Looking great 👍
