### ISSUE TITLE
UX improvement suggestions for notes view

### ISSUE THREAD

**Issue by Atlas139mkm** [constellation-app/constellation#1290]
### Description

While testing the notes view, it felt like it didn't flow too well from a UX perspective. 
- The pop up from the edit button feels a bit strange with the check boxes down the bottom indicating if you want to add or remove the note from specific graph elements.
    - This is also a problem if the user has not already highlighted the graph elements they want to add or remove the note from. If they click back to constellation to alter their selection the popup will disappear behind the constellation window. (gif provided at the bottom)
    - The 'keep original selection' checkbox is also not needed if designed correctly
- below is the current vs my suggested UI 
 
Actual look
![image](https://user-images.githubusercontent.com/88649439/130714039-6edd00ca-4619-4ba2-a783-e15e83518db7.png)

Suggested look
![image](https://user-images.githubusercontent.com/88649439/130714032-838ea2ce-6836-4e66-8ce2-9493378ac399.png)

- Changes
    - Editable text for title and content within the note (re-sizeable based on amount of text)
    - Show the number of graph elements the note is connected too at the bottom of the note, represented in the same manner as constellation has.
    - Add selected button - adds the note to the currently selected graph elements
    - Remove selected button - removes the note from the currently selected graph elements
    - Delete note button - deletes the note

- Reasoning 
    - Removes the need for the pop-up
    - user can still interact with the graph and add or remove the note from graph elements, without needing to worry about the pop up disappearing
    - icons down the bottom convey the same message in a consistent way with constellation, while taking up less space and removing text
    - Easier for user to see all notes functionality
    - should increases overall usability while maintaining all the same functionality

### Additional Information

 - adding a note to all graph elements
 - deciding I want to remove it from Vertex 0 and both transactions
 - however not all graph elements are selected
 - the edit pop up then disappears behind the constellation window when I need to change my selected elements

*Ignore pop up appearing on another window (that my computer putting it on the main window)
![Notes UI flow](https://user-images.githubusercontent.com/88649439/130713272-86ae4269-6ba6-4043-a161-c1cd14823f85.gif)

Note: I'm not sure even sure if this is possible so I'd love feedback and comments on my suggestions

**Comment by arcturus2** [comment]
Love the suggestions @Atlas139mkm

**Comment by GammaVel** [comment]
hi @Atlas139mkm. Just look a quick look at this now and when deleting a note there is a colon that I don't think belongs there after the question mark: 
![image](https://user-images.githubusercontent.com/83679004/133952683-04e0206a-3732-4f40-aad6-f7e7216b9f01.png)

Would it be possible to remove it?  I was also wondering about the two Confirmation text, could one be called Cancel?

**Comment by arcturus2** [comment]
Thank you for the quick fix @Atlas139mkm
@GammaVel this should be ready for you to test in the build tomorrow.

**Comment by GammaVel** [comment]
Thanks @arcturus2 and @Atlas139mkm for making the update to the confirmation box. It looks great now!
![image](https://user-images.githubusercontent.com/83679004/134600902-239eabad-16ec-4894-86ca-e9f043f5817c.png)

**Comment by GammaVel** [comment]
Thanks for adding all the improvements into the notes view, it is looking really snazzy now!  Thanks @Atlas139mkm and @arcturus2.  I have noticed a few things which I will raise new issues for as they are kind of their own tasks. 
Thanks again!
