### ISSUE TITLE
Testing Timeline View - disappearing graph - minor issue 

### ISSUE THREAD

**Issue by papanurgle666** [constellation-app/constellation#1294]
### Description

\[Description of the issue\]

### Steps to Reproduce

1.  open timeline view

2.  select temporal attribute

3.  see existing time graph 
![image](https://user-images.githubusercontent.com/89491484/130729707-7e12a109-a2b1-4812-9f1c-b05b9a66769a.png)

4. select "show selected only" button
![image](https://user-images.githubusercontent.com/89491484/130730164-198d4f91-febd-4462-8d98-c62b30a7bfbb.png)

5.  scroll mouse wheel to return graph
<!--

### Behaviour

**Expected behaviour:**  I expected the circled graph to redraw based on the new selection

**Actual behaviour:**  graph disappeared until mouse scroll wheel was used

**Reproduces how often:**  every time

**Comment by arcturus2** [comment]
I've added the bug label based on what I @papanurgle666 is suggesting here. However I am inclined to think this is as per design. If you keep zooming in you can get into a situation where the deviation is so small that its flat. Thoughts anyone?

**Comment by GammaVel** [comment]
Assign myself to this issue as I would like to see if I can reproduce what is happening.

**Comment by GammaVel** [comment]
This issue has been resolved with improvements that have been made to the Timeline view, see the below gif on how this is currently working. @papanurgle666 if you are still having issues feel free to create a new issue and attach a copy of the star file that has problems. 
![timelineView](https://user-images.githubusercontent.com/83679004/168194373-f954328e-38b6-448f-b72e-f7c50fc62bc0.gif)
