### ISSUE TITLE
Help button on the Plugins dialog box doesn't launch help

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1295]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The Plugins dialog box can be accessed from Setup (main menu)> Plugins. I have noticed that the help button on the bottom right doesn't actually launch the help guide. I know this is a minor issue but this dialog doesn't have much information which is why I wanted to click on help to find out more. 

### Steps to Reproduce

1.  From the main menu click on Setup > Plugins
2.  On the Plugins screen click on Help on the bottom right > help contents are not displayed as expected. 

**Expected behaviour:** The help guide launches with information on how the plugins work and what they are used for OR the help button is not shown as an option here. 

**Actual behaviour:** Nothing happens when the help guide is clicked. 

**Reproduces how often:**100%

### Additional Information

![image](https://user-images.githubusercontent.com/83679004/130731164-ac75b605-50d9-4c25-a75b-2231adf67907.png)

**Comment by sol695510** [comment]
![image](https://user-images.githubusercontent.com/58677774/132776431-ae6d3b51-ea2c-4341-b15d-8710130cc835.png)

![image](https://user-images.githubusercontent.com/58677774/132776564-c1187b24-5bf8-405e-b3ce-c085ac425d96.png)

Searching and looking in the Help Contents seems to show that there isn't a help page for this window. @antares1470 @arcturus2 Would it be preferred if the Help button functionality was removed for now? e.g. the button is disabled (greyed out) temporarily until a help page for the window is created.

**Comment by sol695510** [comment]
![image](https://user-images.githubusercontent.com/58677774/132777702-2e470448-629c-4602-9e4b-4f5400179847.png)

Looking into it I can't seem to find/access the class for this window to modify the button's behaviour, but when the offline/online help ticket gets merged it should cover it.

**Comment by antares1470** [comment]
> Searching and looking in the Help Contents seems to show that there isn't a help page for this window. @antares1470 @arcturus2 Would it be preferred if the Help button functionality was removed for now? e.g. the button is disabled (greyed out) temporarily until a help page for the window is created.

To answer your question, I think it makes sense to remove it for now. If you look at the bottom of the list in #340, there is an intention to eventually create a help page covering the plugin framework so that might be the page to link if we can modify this
