### ISSUE TITLE
Add units for available memory on the Memory screen

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1297]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Constellation tells me how much memory it is using from Help > Memory. The screen doesn't display the units which makes it a bit confusing to know how much memory it is using. Can the units be added in?  Suggest changing display from bytes to MB or GB(?)

### Steps to Reproduce

1.  From the main menu click on Help > Memory
2.  Look at the values that display  

**Expected behaviour:** memory is in MB or GB (?) and units are displayed. 

**Actual behaviour:** I think it is reporting bytes. 

**Reproduces how often:** 100%

### Additional Information
![image](https://user-images.githubusercontent.com/83679004/130737023-236b8105-fac6-4c69-ad6f-debdd545916f.png)

**Comment by arcturus2** [comment]
Good idea thanks @GammaVel

**Comment by GammaVel** [comment]
Thanks @Atlas139mkm for including the units now on the Memory screen. This data is much more meaningful now and I can easily compare it to memory usage in the Task Manager.  Thanks for fixing this so fast!
 
![image](https://user-images.githubusercontent.com/83679004/133954901-66e49aa5-efcc-44d3-a461-03d8bc892750.png)
