### ISSUE TITLE
Implement slack notification from travis

### ISSUE THREAD

**Issue by rsabhi** [constellation-app/constellation#13]
### Description

implement slack notification from travis

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behaviour:** [What you expect to happen]

**Actual behaviour:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by arcturus2** [comment]
When we get busy enough to have a public slack we can look at doing this.
