### ISSUE TITLE
Previous Views strange functionality / only works when called via the search function 

### ISSUE THREAD

**Issue by Atlas139mkm** [constellation-app/constellation#1301]
### Description

Found while doing release v2.4 testing.
This function does 2 strange things. 
- 1 it does not appear to do anything when called from experimental > tools > previous view
- 2 it works on the view it is first called on after an action on a view has occurred (refer to steps to reproduce or the gif at the bottom for an example)

### Steps to Reproduce

1.  open 3 views (for example: notes view, analytic view attribute editor)

2.  Navigate to a view (notes view)

3.  perform some action on that view (create a note)

4. call the previous view function via the search bar

5. swap to analytic view

6. swap to attribute editor 

7. call the previous view function (it will take you back to the notes view, not the attribute editor as you might expect)

**Expected behaviour:** After calling the previous view function, it should take you back to the last view you had open.

**Actual behaviour:** Doesn't work calling it via experimental > tools > previous view and when called via the search bar it takes you back to the last view you had open when calling the previous view function instead of the last view you had open.

**Reproduces how often:** 100%

### Additional Information

- testing the function from experimental > tools > previous view did nothing
- testing via the search function should have returned the attribute editor being the last view selected, however returned notes being the last view that had the previous view function called on it after an action (creating a note)

![strange previous view function 2](https://user-images.githubusercontent.com/88649439/130887382-cf4adf86-ac83-47e8-9734-2d6568de4b88.gif)

**Comment by mimosa2** [comment]
Tested this and found working ok.
