### ISSUE TITLE
Import from file - Enable sections one at a time

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#1307]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

To help improve UX can we investigate disabling all sections of the file importer on load like the "Configruation" and "Attributes" section given none of them can be used until the "Source and Destination" section is filled out? It should help guide new users how to do an import without reading any documentation.

As a quick example see how much clearer it is when only the top section is enabled?

![image](https://user-images.githubusercontent.com/39325530/131076407-fec6f910-50c8-4cef-afb6-0ef85f66baa5.png)

**Comment by Atlas139mkm** [comment]
Looking into this, Thoughts on not disabling it but having it start collapsed. Once a file is present in the files list then it would expand for the user. This would avoid annoyances for any developing of the import pane if users had to import every time they wanted to examine the view.

**Comment by GammaVel** [comment]
I love the changes that have been made and it makes this functionality simpler to use.  Thanks @Atlas139mkm!
