### ISSUE TITLE
Import from File - Move transactions to the middle

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#1308]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

A simple yet effective improvement is moving the transactions attributes block to the middle so that it is a clearer representation of how a destination node hangs at the end of a transaction.

![image](https://user-images.githubusercontent.com/39325530/131076907-674dfc63-c13e-403d-8bbb-01ba81f55f83.png)

**Comment by GammaVel** [comment]
The new layout is great. This makes more sense. Thanks @Atlas139mkm for making this change!!
