### ISSUE TITLE
Import from File - Make menu options more obvious

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#1310]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The "Options" menu and what it has is not always clear to users and given there is not many options there, they could just be buttons on the GUI.

![image](https://user-images.githubusercontent.com/39325530/131077510-58945fda-5393-4c5a-9758-28a5827d756f.png)

**Comment by GammaVel** [comment]
Thanks @Atlas139mkm for making these new menu items more obvious. Nice work :-)
