### ISSUE TITLE
Make menu items more obvious

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#1314]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Can menu items be made more obvious somehow? Some icons on the toolbar are not clear if they are enabled and can be clicked. Could the new flat light or dark themes help resolve this?

![image](https://user-images.githubusercontent.com/39325530/131080598-ad6bf67f-1079-47cb-9cda-4e861eba83e7.png)

**Comment by HolandCrick** [comment]
Reset View and Zoom to Selection (used a grey magnifying class sitting on a grey background). from Display --> Reset View by Axis: x, -x, y, -y, z and -Z are also working fine. From menu --> Expand Graph and Contract graph works as expected.

![image](https://github.com/constellation-app/constellation/assets/157770877/449ef01e-abcf-45e4-9ff2-6c9acd825f5a)

**Comment by HolandCrick** [comment]
Menu works as expected.
