### ISSUE TITLE
Import from DB (JDBC) - add more information to the help guide on Managing Connections

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1324]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Can the help section for the Import from Database please be updated with more information on how to add a driver and manage the connection?  It has lots of information on how to use the rest of the import functionality and it would be really good to have some guidance on where to get the driver, what it is needed for, and an example of a connection string. I really think this would help new people to using this functionality

### Steps to Reproduce

1.  In Constellation open the Import from Database > Click on Help Icon

2.  Read the help information that is available on this screen for advice on adding a driver and managing the connection strings

3.  Only a couple of sentences are available

**Expected behaviour:** I can find out more what needs to be added to the drivers and connection screen in the help guide

**Actual behaviour:** as per description, limited info

**Reproduces how often:** 100%

### Additional Information

![image](https://user-images.githubusercontent.com/83679004/131449593-bcca95cc-845c-4009-8471-157979168aac.png)

**Comment by HolandCrick** [comment]
@GammaVel & @arcturus2- thanks for enhancing the Help Page Text for "Import from JDBC".  Looks good.
