### ISSUE TITLE
Column types are incorrectly inferred in constellation_client.get_dataframe()

### ISSUE THREAD

**Issue by algol60** [constellation-app/constellation#133]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues

### Description

When reading string values that look like numbers, the column types are being incorrectly inferred in `constellation_client.get_dataframe()`.

### Steps to Reproduce

Create a new analytic graph. Manually add three nodes with the following identifiers:
* "1.0"
* "2"
* "12345678901234"

Create a transaction from node "2" to node "12345678901234".

Start the CONSTELLATION REST server using Tools -> Start REST Server.

In a Jupyter session (notebook or console), execute the following code.

```
import constellation_client

cc = constellation_client.Constellation()

df = cc.get_dataframe(attrs=['source.Identifier', 'destination.Identifier'])
print(df.dtypes)
print(df)
```

The result is:

```
source.Identifier           int64
destination.Identifier    float64
dtype: object
   source.Identifier  destination.Identifier
0                  1                     NaN
1                  2            1.234568e+13
```

**Expected behaviour:** The Identifier types should be string (object), not int or float.

**Actual behaviour:** `pandas.read_json()` is inferring ints and floats because the values look like ints and floats.

**Reproduces how often:** 100%

**Comment by arcturus2** [comment]
Thank you @algol60. I've merged your PR so I'll close the issue.
