### ISSUE TITLE
Layers View - bug with adding and deleting layers when graph is not open

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1334]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

In Constellation it is possible to open the Layers view when there is no graph actually open. If I try and add some layers and go to delete them, the deletion process does not remove them from the screen. If I click " Add New Layer" once more I get new layers showing up on the right hand side, adjacent to where they should be.

### Steps to Reproduce

1.  Launch Constellation and DO NOT load a graph. 
2.  Open the layers view from Experimental
3.  Click on Add new layer
4.  Click on Delete > delete does not work
5. Click on Add new layer again > Layers appear to the side.

**Expected behaviour:** I can add and remove layers from the Layers view even when there is no graph open, I can add queries without an error being displayed OR I can't access any of this functionality until I have a graph open. In reality it would be hard to set up layers without viewing a graph first.

**Actual behaviour:** Refer to test steps

**Reproduces how often:** 100%

### Additional Information

![image](https://user-images.githubusercontent.com/83679004/131610482-6af693c5-a3d7-4f77-9e1a-2180abc50c53.png)

**Comment by arcturus2** [comment]
Hmm. Is there any reason we should have the layers view visible when there is no graph? Should everything just be disabled like the Histogram? Interested in your thoughts @aldebaran30701 @serpens24 @antares1470 @GammaVel

**Comment by antares1470** [comment]
> Hmm. Is there any reason we should have the layers view visible when there is no graph? Should everything just be disabled like the Histogram? Interested in your thoughts @aldebaran30701 @serpens24 @antares1470 @GammaVel

Given layers are only saved per graph, I think you're right that it doesn't make sense to have anything in the layers view enabled while there aren't any graphs open

**Comment by aldebaran30701** [comment]
I like the idea, can be replaced with a meaningful message about opening a graph to enable layers.
I'd have to investigate a good way to store the current graph so in the event the person closes all graphs, it keeps consistency. Can be done. 
There are a heap of bugs I've come across and fixed which stem from the fact that no graph is opened. This would reduce those sorts of issues.

**Comment by arcturus2** [comment]
Sounds good @aldebaran30701. Maybe we just focus on getting https://github.com/constellation-app/constellation/issues/339 implemented which should help fix the layers view and others.

**Comment by GammaVel** [comment]
Hi @aldebaran30701, I agree it would be a good idea not to enable the layers when no graph was open as I can't see how someone could set up layers or queries without visualising a graph and it would save you time having to code for these unlikely scenarios. I'll update the expected behaviour in the issue here.

**Comment by Delphinus8821** [comment]
The fix for this works well based on testing in master.
