### ISSUE TITLE
Remove dependency from CoreWebServer to Core Functionality

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#1338]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
Having the dependency means that the CoreWebServer module cannot be used with other modules without the extra level of dependency on CoreFunctionality. This ticket should be the basis for finding what is used from CoreFunctionality within CoreWebServer, and refactoring it so that this dependency does not exist.
\[Description of the issue\]

### Steps to Reproduce

1.  Right click CoreWebServer module and go to properties -> libraries -> module dependencies
Now: Functionality is in the list
After: Functionality can be removed from the list

**Expected behaviour:** \[What you expect to happen\]

**Actual behaviour:** \[What actually happens\]

**Reproduces how often:** \[What percentage of the time does it reproduce?\]

### Additional Information

Any additional information, configuration or data that might be
necessary to reproduce the issue.

**Comment by aldebaran30701** [comment]
I managed to remove the dependency on functionality from the web server - but to do this I had to duplicate some code that launches a browser. this was one plugin that seemed to be the best option other than removing code throughout the whole code base.
I then went to try and remove the duplication from CoreHelp to WebServer and use the WebServer instead of HelpWebServer. This also added a cyclic dependency, but this really made me aware of all the dependencies weaved within the WebServer.

Core Analytic Schema - AddRecordStore uses input streams to pull in a record store. 
CoreArrangementPlugins - uses arrangements after the graph has been imported.
(Cont...)

That's just the start. See the image below for the other dependencies that would need to be removed before it can really be used atomically within the codebase.
![image](https://user-images.githubusercontent.com/58677759/152256342-f3f86f2c-5a0e-49bd-a989-1323e5b9d871.png)


The whole web server acts as a link between Constellation and importing via the rest server - this entwines itself in a heap of modules and really would be a huge task to decouple. 
I haven't got any idea for how to do that - and think it might be more effort than it is worth. the duplication currently is one 100 line class. To me that sounds acceptable when you consider the amount of work necessary for the benefit of removing that duplication.

**Comment by arcturus2** [comment]
Good investigation @aldebaran30701. I think the 100 lines is OK but now curios to know what that is. Can you point me to it?

**Comment by aldebaran30701** [comment]
@arcturus2 Thats the HelpWebServer which uses some lines of code from within CoreWebServer class WebServer.
I think it has some specific things to help, like naming the thread Help Web Server.

**Comment by aldebaran30701** [comment]
Closing this as the impact of the duplication is minor in this instance. Can be reopened if a problem in the future arises.
