### ISSUE TITLE
Select Backbone also selecting nodes only connected by a loop

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1340]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Select Backbone should only select nodes with more than 1 neighbour and transactions that connect 2 backbone nodes. This should exclude nodes only connected by loops. At present though, it appears that nodes with loops (and the loops themselves) are being selected, even though they wouldn't form part of the backbone otherwise. This should be fixed.

### Steps to Reproduce

1.  Construct the graph below but ensure everything is deselected
2.  Select 'Select Backbone'

**Expected behaviour:** Vertex \#0 is selected

**Actual behaviour:** Vertex \#0, Vertex \#2, and Vertex\#3 are selected

**Reproduces how often:** 100%

### Additional Information

This is the graph I used to test it (showing the result after running Select Backbone with nothing selected prior):

![SelectBackboneTest](https://user-images.githubusercontent.com/62311243/131787906-c575d327-46ef-48c2-beb8-06632a83b5e0.png)

**Comment by Atlas139mkm** [comment]
Just gave this a test and looks like its working as intended. Just vertex0 is being selected.
