### ISSUE TITLE
Remove dependency from between Data Access View and Quality Control View

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#1341]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
Using a look up will assist with the effort to decouple these modules, leading to a more flexible codebase.
For this issue to be completed, the modules will not be dependent on eachother.
\[Description of the issue\]

### Steps to Reproduce

N/A

**Expected behaviour:** \[What you expect to happen\]

**Actual behaviour:** \[What actually happens\]

**Reproduces how often:** \[What percentage of the time does it reproduce?\]

### Additional Information

Any additional information, configuration or data that might be
necessary to reproduce the issue.

**Comment by GammaVel** [comment]
This would be super handy to have as it would presumably work vice versa (ie - I could turn off the quality control view if I don't need it with my graph)
