### ISSUE TITLE
AbstractObjectAttributeDescription.getString() returns an incorrect null value

### ISSUE THREAD

**Issue by algol60** [constellation-app/constellation#135]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues

### Description

AbstractObjectAttributeDescription.getString() returns the string "null" instead of the null value when the object's value is null.

### Steps to Reproduce

Create a new analytic graph. Manually create a node. Add a float_or_null attribute such as Geo.Altitude.

Start the CONSTELLATION REST server using Tools -> Start REST Server.

In a Jupyter session (notebook or console), execute the following code.

```
import constellation_client

cc = constellation_client.Constellation()

df = cc.get_dataframe(attrs=['source.Geo.Altitude'])
df
```

**Expected behaviour:** A single-row dataframe containing a None value for Geo.Altitude.

**Actual behaviour:** (Python stack trace elided)
```
HTTPError: 500 Server Error: Server Error for url: http://localhost:1517/v1/recordstore/get?attrs=source.Geo.Altitude
```

**Reproduces how often:** 100%

**Comment by arcturus2** [comment]
Closing this given the PR has been merged and tested. Thank you @algol60
