### ISSUE TITLE
Tools Compare graph - suggest adding output information when graph is compared to itself

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1350]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

In Constellation there is a handy feature to compare graphs from the Tools menu. I have noticed I can compare my own graph to itself as, it is available in the dropdown as a selection item. If I do this, the output window is blank but I do end up with a new graph being created. It would be great if the output window had something like " No differences detected" or "Selected graphs for comparison match". 

### Steps to Reproduce

1.  Open any graph in Constellation
2.  Click on Tools > Compare Graph
3.  Select the same graph that you have open in the **Compare with graph field** 
4.  Look at the outputs from running this comparison > it is blank
5.  Check a new graph has been made from the comparison > it has been made, all nodes and transactions are grey

**Expected behaviour:** The output is not blank as a comparison has been happening, there were no differences. In this case the output console has a message along the lines of "No differences"

**Actual behaviour:** Output is blank

**Reproduces how often:** 100% of the time I compare a graph to itself

### Additional Information

![image](https://user-images.githubusercontent.com/83679004/131956509-5fe2ee27-5c28-48a4-99a9-a8ae999b8f61.png)

**Comment by arcturus2** [comment]
Thank you @GammaVel for this great suggestion.

**Comment by GammaVel** [comment]
I'm getting an error when I go to save the resultant graph. Will try to identify what is causing it.

**Comment by GammaVel** [comment]
I can't replicate this error so happy so it could have been to do with other runtime errors I was seeing at the time. I've repeated with a couple more and it is working. Thanks @aldebaran30701 for working on this.
