### ISSUE TITLE
Import from DB - add check to Test and Add buttons on the Add Connections screen

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1359]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

I can use the import from DB functionality to connect Constellation to a DB for building my graph. After clicking the Manage Connection button I need to set up a new driver and connection.  On the Add Connection screen it would be really good to have a check on the **Test** and **Add** buttons so they tell me when I have not entered in enough information. Similar to a mandatory field check. The missing fields could go red if they don't have data in them. 

This would help me know how to use this screen better. 

### Steps to Reproduce

1.  Go to Import from DB > Manage Connections
2.  Add a driver if you have not done so already
3.  On the Add connections screen enter in a connection name and the driver but don't add the Connection String
4.  Click on Test (see expected result below)
5.  Repeat with the Add button.

**Expected behaviour:** Popup stating that not all fields have been entered

**Actual behaviour:** No result, the Test and Add buttons only tell me information once I have filled in all the fields which makes it harder for me to know what to do on this screen.

**Reproduces how often:** 100%
### Additional Information

![image](https://user-images.githubusercontent.com/83679004/132159188-d4236152-e90c-463f-9643-85e0aeb16cda.png)

**Comment by Auriga2** [comment]
Looks good in v2.5.0-rc1

**Comment by Auriga2** [comment]
But, it would have been great if we could add the same for the `Add Driver` button. I'll create a new ticket to handle that.
