### ISSUE TITLE
Option to save defaults / load defaults for dialogs requiring input

### ISSUE THREAD

**Issue by CrucisGamma** [constellation-app/constellation#1361]
Would really like the option to be able to save the values I've entered into dialogs as defaults and then have the option to repopulate the same dialog with those defaults at a later stage.  Mockup shown.  Have used this technique in another project and it becomes very quick and saves on the tedium of typing in something you wish to repeat later on.  Mockup shown in the image below.
![image](https://user-images.githubusercontent.com/62917181/132269790-0c78b780-3a09-457e-82af-5f79daafb05f.png)

**Comment by arcturus2** [comment]
I like the idea @CrucisGamma and this is doable. An attempt was made to do a similar thing within the Data Access View (#25) but we ran into issues. I think for stand alone plugins like this we could make it work.

**Comment by GammaVel** [comment]
This would be nice to have and it has been added to the brainstorming ideas for consideration in future development work. This issue will be closed for now as it isn't actively being worked on.
