### ISSUE TITLE
Improve handling of HiDPI displays

### ISSUE THREAD

**Issue by bradh** [constellation-app/constellation#137]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

Using Constellation on a Windows HiDPI screen results in strange displays (mix of overly large, normal sized and tiny text). Switching to Nimbus look'n'feel seems better.

### Steps to Reproduce

1. Create a new graph
2. Note dialog
![image](https://user-images.githubusercontent.com/174642/66250648-d8c70180-e788-11e9-8174-586f52901fbd.png)

**Expected behaviour:** [What you expect to happen]

Text is consistent with rest of application.

**Actual behaviour:** [What actually happens]

See above screenshot

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always

### Additional Information

There are other places this happens. Probably needs a more experienced user to work through the activities on a machine where this shows up.

**Comment by arcturus2** [comment]
Hi @bradh thank you for creating this issue. This might be because we are still on Java 8. In Java 9 they introduced native support for HiDPI so I am wondering if you could download [this version](https://drive.google.com/open?id=1H5BcsONkNFGVUB1CMWEvL5NcZutRqmee) and give it a go? This is a very early preview of Constellation using Java 11 and there are several things not working so don't use this for anything else. I'm only interested to know if the "Sphere Graph Builder" looks any different (when you are using the default look at feel).

**Comment by cygnus-x-1** [comment]
+1 on this issue - I get some odd layouts using Constellation on a Surface Book.

**Comment by arcturus2** [comment]
@cygnus-x-1 are you able to give [this version](https://drive.google.com/open?id=1H5BcsONkNFGVUB1CMWEvL5NcZutRqmee) a go which is an early preview of Constellation running Java 11.

**Comment by cygnus-x-1** [comment]
> @cygnus-x-1 are you able to give [this version](https://drive.google.com/open?id=1H5BcsONkNFGVUB1CMWEvL5NcZutRqmee) a go which is an early preview of Constellation running Java 11.

That version did seem to help a lot.

**Comment by cygnus-x-1** [comment]
@arcturus2  - can this be closed give the Java 11 work?

**Comment by arcturus2** [comment]
Let's close it soon @cygnus-x-1 when we get `master-nb11` to `master`. Good point!
