### ISSUE TITLE
OK and Cancel buttons section has different shading on some dialog boxes

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1403]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The OK and Cancel section on some dialog boxes has a different shading compared to the rest of the dialog box. Not sure what is causing this issue, it could be related to stylesheets.  See the below screenshot for the dialog boxes which are on the Manage Templates and the Export to GeoJSON and GeoPackage on the Map View.

### Steps to Reproduce

1.  From the File menu click on Manage templates and review the dialog box that displays

2.  Repeat with the Map view and the Download to Geo... packages

**Expected behaviour:** The same colour applies for all of the dialog box
**Actual behaviour:** slight colour change before the OK and Cancel buttons

**Reproduces how often:** 100% for the dialogs I have looked at 

### Additional Information

![image](https://user-images.githubusercontent.com/83679004/133360598-4284a40c-2781-4cf1-a0e0-cedc428b1975.png)
![image](https://user-images.githubusercontent.com/83679004/133360670-b413091b-e467-4936-9a00-6f8fa21e15b1.png)

**Comment by arcturus2** [comment]
I've tested this and I can confirm the shaded area no longer exists. I confirmed this using a colour picker.
