### ISSUE TITLE
Update the Import from File and Import from Database help sections for the new Attributes screen layout

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1404]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The Import from Database and Import from files screens have been updated to move the transaction attributes to the middle of the Attribute section. The options button has also been removed. I noticed that the help guide screenshot needs updating to reflect the changes. 

### Steps to Reproduce

1.  Launch the Import from DB OR Import from File

2.  Note the new buttons which have replaced the previous options and Scroll down to the attribute section

3.  Launch the help guide and look at the screenshot > this needs updating. 

**Expected behaviour:** Help guide screenshot reflects the new screen layout

**Actual behaviour:** Screenshot based off previous version which is a bit confusing

**Reproduces how often:** 100%

### Additional Information

![image](https://user-images.githubusercontent.com/83679004/133369424-be0e5c0f-45d0-4d28-a63a-578be136dcae.png)

**Comment by GammaVel** [comment]
Also found this text that needs updating in the help guide:
![image](https://user-images.githubusercontent.com/83679004/133374054-94e0c6d2-bfc3-474c-acb7-cbaf3c749735.png)

**Comment by GammaVel** [comment]
HI again !  I also noticed the screenshot in the Import from Database needs updating too as the order has changed there. I'll update the issue details with this information as it would make sense to do both updates  together:
![image](https://user-images.githubusercontent.com/83679004/133968344-dccce575-5a15-4e38-b9f0-1a9e8a215aa8.png)

**Comment by HolandCrick** [comment]
@Quasar985 thanks for your help to address the Import help pages. It's working nicely.
