### ISSUE TITLE
Update the toolbar and welcome page icon for data access view

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1407]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

A new icon has been added on the Welcome page and the Toolbar to access the Data Access view. This is an eye which makes sense but it could be a bit off putting to some people. A specific data icon might be more meaningful.

### Steps to Reproduce

1.  Review the icon for the Data access view on the welcome page and toolbar

**Expected behaviour:** Icon reflects what the view does

**Actual behaviour:** eye could be off putting.... looks like big brother watching. 

**Reproduces how often:** 100%
### Additional Information

Thanks for considering this minor issue. I really like the shortcuts. 
![image](https://user-images.githubusercontent.com/83679004/133388712-5eee3062-4cbe-4d64-a163-2fd463804960.png)

**Comment by GammaVel** [comment]
I really like the Add chart Icon which you can see on google icons here - https://fonts.google.com/icons?selected=Material+Icons+Outlined:folder_open:&icon.query=data   it shows that the graphs can be enriched using this feature.

**Comment by arcturus2** [comment]
^https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Aadd_chart%3A

**Comment by GammaVel** [comment]
Nice work @Atlas139mkm and @arcturus2 ! I definitely think it is better than the eye. It just occurred to me that a key might have been good too as I like to use this view to unlock my data. Maybe next time!
