### ISSUE TITLE
Examples or Video Tutorial Availability

### ISSUE THREAD

**Issue by intelligi123** [constellation-app/constellation#1417]
Hi,

I am new to Constellation and feeling immense need of video tutorial or some walk through examples of sample graphs which I am having a hard time to find. Can someone help please.

Thank you in advance.

**Comment by intelligi123** [comment]
Thank you so much. Are there any video tutorials been made by community to start with?

**Comment by arcturus2** [comment]
@intelligi123 thank you for your feedback and totally agree! There aren't any videos available yet and this is something we have been wanting to do for some time too. It's been a matter of getting time to do them. I think it will be really beneficial to get done along with the development work we are doing.

There are aspirations to do some this month or next and we will see if we can do them.

You mentioned an overview video using some sample graphs. They sound like solid ideas. If you later think of anything else please feel free to comment here and we can consider it.

Thank you.

**Comment by sol695510** [comment]
Keep track of this in #412
