### ISSUE TITLE
Cursor becomes invisible when over nodes that are using the default grey colour.

### ISSUE THREAD

**Issue by sol695510** [constellation-app/constellation#1419]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

When the mouse cursor is moved over nodes that are set to the default colour grey, they become invisible. The cursor inverts its colour based on what it is over onscreen, e.g. white screen = black cursor and vice versa. The default grey is the colour that is assumedly located right in between black and white so its inverse is the same grey colour thus the cursor appears to go invisible when over that colour node.

### Steps to Reproduce

1.  Open a new graph.

2.  Toggle the selection mode to draw and place a node.

3.  Right click the node and select "Open in Attribute Editor".

4.  Press Edit on the "color" attribute and click "Restore Default".

5. Move the mouse over the node and observe the cursor appearing to go invisible as it moves over the node.

**Expected behaviour:** Cursor to remain visible when over the node.

**Actual behaviour:** Cursor goes invisible when over the node.

**Reproduces how often:**100%

### Additional Information

![Cursor invisible on default colour node](https://user-images.githubusercontent.com/58677774/133733761-bd8c32d8-92a5-4059-826d-2a11bcd29c8d.gif)

**Comment by arcturus2** [comment]
Thanks @sol695510 for raising this one. I'm going to close this as a duplicate because we are tracking this issue #675. Cheers.
