### ISSUE TITLE
Specify graphs in the REST API

### ISSUE THREAD

**Issue by algol60** [constellation-app/constellation#142]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The current REST API only allows operations on the current graph. It would be useful to allow different graphs to be specified where relevant.

**Comment by arcturus2** [comment]
The PR from @algol60 have been merged.
