### ISSUE TITLE
Remove the redundant Edit button from the attribute editor

### ISSUE THREAD

**Issue by Auriga2** [constellation-app/constellation#1421]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
As per the notes in the https://github.com/constellation-app/constellation/pull/1397, the `Edit` buttons in the attribute editor are left redundant until the users get familiarized with the new feature there. (To open up the edit interface when clicked on the attribute value.) This ticket is to remove it once sufficient time is given.

### Steps to Reproduce

1.  \[First Step\]

2.  \[Second Step\]

3.  \[and so on…\]

**Expected behaviour:** \[What you expect to happen\]

**Actual behaviour:** \[What actually happens\]

**Reproduces how often:** \[What percentage of the time does it reproduce?\]

### Additional Information
https://github.com/constellation-app/constellation/issues/1242
https://github.com/constellation-app/constellation/pull/1397

**Comment by GammaVel** [comment]
Thank you @capricornunicorn123 for removing the edit buttons. The Attribute editor seems far more streamlined without having the edit buttons shown and it still works well to edit simply by clicking in the fields.
