### ISSUE TITLE
DGraph Connector

### ISSUE THREAD

**Issue by daveaitel** [constellation-app/constellation#1422]
### Requirements

* Hi! Imagine you had a lot of data you were going to view with Constellation - but it was loaded into DGraph, which is a BSD-licensed graph database that can horizontally scale. Ideally you would be able to just connect this to Constellation with a "DQL Query" that got you a subgraph, and then iterate on that query to get interesting information out of it and see patterns and shapes. 
* This is not currently possible as far as I can tell, even though there IS A Java connector in DGraph and that seems like it would  be a very easy fit for Constellation.

### Prerequisites

- [ X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

\[Description of the issue\]

We need a clean way to get data from DGraph to Constellation. This would be a mindblowing demo and both are "free".

### Steps to Reproduce

N/A
1.  \[First Step\]

2.  \[Second Step\]

3.  \[and so on…\]

**Expected behaviour:**  A window where you can input a DGraph DQL query and then populate the Constellation view.

**Actual behaviour:** No such window exists.

**Reproduces how often:** 100% of the time.

### Additional Information

I dave.aitel@cordyceps.systems would be happy to help with sample data, queries, DGraph installation help, etc. I honestly believe this would be a fairly easy thing to do, and also of huge impact for the project!

**Comment by arcturus2** [comment]
@daveaitel for those of us unfamiliar with DGraph, can you provide links to the documentation which talks about the connectors? When this gets worked on then I might ask for more information like how to setup DGraph and sample data etc but right now, some doco about the connectors would be useful thanks.

**Comment by daveaitel** [comment]
https://dgraph.io/docs/clients/java/ is the most basic connector (aka, making queries getting json data back!) 
https://github.com/G-Research/spark-dgraph-connector is a more advanced example.
https://blog.knoldus.com/how-to-use-dgraph-in-your-java-application/ (basic tutorial)

They have a simple docker image that has everything you need to just "run a DGraph instance". :)

**Comment by altair1673** [comment]
Added to brainstorming in the wiki. Would be nice to have in the future

**Comment by daveaitel** [comment]
Honestly, I take it back. A better target would be PostGres AGE
https://age.apache.org/
