### ISSUE TITLE
Add a REST endpoint to get graph, node, transaction attributes

### ISSUE THREAD

**Issue by algol60** [constellation-app/constellation#144]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

It is currently not possible for a REST client to discover what graph, node, and transaction attributes are present on a graph.

**Expected behaviour:** The REST endpoint should return a map of graph, node, and transaction attributes to their types.

**Comment by arcturus2** [comment]
@algol60's PR has been merged.
