### ISSUE TITLE
Disappearing notes...help?!?

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1445]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

I have noticed with the latest master build that some of my notes are disappearing from my graph. I added tons of notes into a graph and then came back later and they were not there when I reopened the graph. I can't reproduce this issue nicely, initially I thought it might of had something to do with using Control S to save instead of the menu however that doesn't appear to be it. It could be time related as I had left my graph idle for some time.  This also happened to one of my graphs from a previous release, all of the user notes disappeared and I can't get then back. 

### Steps to Reproduce

1.  Open graph and Add notes to the notes view, either to the  whole graph or sub items on a graph

2.  Save graph and reopen > on some occasions the notes are not there that were just added

3.  Sorry I can't reproduce this better!

**Expected behaviour:** My user notes are always there

**Actual behaviour:** Somehow they disappeared

**Reproduces how often:**not sure how to reproduce this one. 
### Additional Information

NA

**Comment by aldebaran30701** [comment]
I don't seem to be finding any disappearing notes. I usually replicate #1526 during testing of the reproducer.
