### ISSUE TITLE
Update colour/color for new graph attribute labels

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1447]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Colour is spelt differently on the Attribute screen for the new Graph node and transaction labels:
node_bottom_labels_colours
node_top_labels_colours
transaction_labels_colour

It has the Australian spelling as opposed to the American spelling that is on the other attributes. It might be a good idea to make them all the same for consistency. 
![image](https://user-images.githubusercontent.com/83679004/134627518-bf2c8935-254e-4ec9-ba9a-954e3d2809c2.png)

### Steps to Reproduce

1.  Go to the Attribute Editor
2.  Check the spelling of colour > observe the differences

**Expected behaviour:** new label updates have color instead of colour to match the existing ones
**Actual behaviour:** see above screenshot

**Reproduces how often:** 100%
### Additional Information

NA

**Comment by serpens24** [comment]
Can we confirm that we want the spelling to be **color** - ie American. If so, this isssue probably becomes aglobal search to look for all occurences.

**Comment by GammaVel** [comment]
Thank you for making the spelling consistent now. This looks good, this is under the graph attributes.
![image](https://user-images.githubusercontent.com/83679004/185826037-4fbfc9a8-1a0a-4838-bf29-636694df0d0e.png)
