### ISSUE TITLE
Add ability for 'solid' images as a graph option

### ISSUE THREAD

**Issue by CrucisGamma** [constellation-app/constellation#1464]
Would like the option to be able to present a solid image (maybe by using a GL_TRIANGLE_FAN with Z component for opengl 3.3 in some fashion)  I had a go at doing this and didn't get as far as I would have liked :( 

Something like the following image that was generated by not-me in matlab.
![1qTlXOkiYpmT-jaKsdXuh9Ywe0740JqpauVdI-Cz8pFrYZTTuraZ15TUr3IBwPY5e-qHw_KzTek3zcN64uTz_q0qMfEo0rPBbVTlJk-6](https://user-images.githubusercontent.com/62917181/135545115-c05cc26f-f795-45b5-afbd-2c6bfd3d521a.gif)

**Comment by GammaVel** [comment]
This is a really great suggestion and I have added to the list of brainstorming ideas as an future enhancement. This ticket will be closed for now. @CrucisGamma please keep those great ideas coming!
