### ISSUE TITLE
Allow the user to be able to shrink the size of the histogram bins

### ISSUE THREAD

**Issue by CrucisGamma** [constellation-app/constellation#1477]
At the moment, there's a lot of scrolling involved with the histogram tool where it would be nice to get a feel for the distribution of the data (at the user's discretion) if the bin's height was lessened.

Something a bit like this:
![image](https://user-images.githubusercontent.com/62917181/136294363-3ea948e4-a016-4fef-9af6-8318cf9eb89b.png)

verses this:
![image](https://user-images.githubusercontent.com/62917181/136294399-59e73218-70e4-4cbf-a858-c47986b6e055.png)

**Comment by arcturus2** [comment]
Gotcha. Another idea I had was (but for the Histogram re-write in the JavaFX probably) would be to collapse the options section to maximise the histogram bins section if you know what I mean.

**Comment by arcturus2** [comment]
This feature works well based on testing and I wasn't able to break any of the other features in the histogram etc.
