### ISSUE TITLE
Save the jython script (if modified) into a .star file

### ISSUE THREAD

**Issue by CrucisGamma** [constellation-app/constellation#1485]
Would be nice to have whatever script was last present in the script view for a given graph to be saved with the .star for later loading.  Histogram settings seem to be graph specific (not sure if this is actually the case - will investigate further - but they change when I open up a saved .star file).

**Comment by GammaVel** [comment]
This idea makes sense however it is not recommended to store any scripts in Constellation. Instead, it is preferable to keep these in a separate developer IDE where there will be source control. This ticket will be closed.
