### ISSUE TITLE
Exception while loading Test Parameters preferences 

### ISSUE THREAD

**Issue by mimosa2** [constellation-app/constellation#1488]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Exception while loading Test Parameters preferences 

### Steps to Reproduce

1.  Open data access view and select few parameters from Test parameters plugin

2.  Select Workflow Options -> Save Templates and save the file

3.  Right click and  Select Deactivate all plugins to clear the selections. 

4.  Select Workflow Options -> Load Templates and open the file in step 2

### Behaviour

**Expected behaviour:**  The selected parameters should be loaded w/o exception

**Actual behaviour:**  The exception thrown. But the parameters are loaded except Graph Element Type.

This is from current master
![Testparameters_error2](https://user-images.githubusercontent.com/54261086/137048100-00af4b62-a904-4450-8a1b-649833b549e7.PNG)
This is from Version 2.4
![Testparameters_error](https://user-images.githubusercontent.com/54261086/137048221-e210f1ee-204f-4e4e-9b25-0bfc1c466701.PNG)

**Reproduces how often:** 100%

### Additional Information
![Testparameters_error](https://user-images.githubusercontent.com/54261086/137049330-cda530ed-b012-4bc2-aaca-084368eddd76.PNG)
![Testparameters_error2](https://user-images.githubusercontent.com/54261086/137049373-2e556b4e-be2b-4b84-a868-9926c8fb9289.PNG)

**Comment by sol695510** [comment]
Tested by following the steps to reproduce and received the expected behaviour, with no exceptions, with 2 different selections for templates.
