### ISSUE TITLE
Welcome Page Recent Graph Screenshots Issue

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1499]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Presently the screenshots used on the welcome page for recent graphs are named according to file name. It seems like this would make sense but the problem here is that a file name is not unique. This means that if you have multiple files with the same name (with different file paths), they are going to use the same screenshot (with the most recent one overriding the previous one since all screenshots are located in the same directory).

### Steps to Reproduce

1. Create a new graph
2. Add a few nodes and save the graph
3. Create a new graph
4. Create a sphere graph (or something else, so long as the graph is different to the first one)
5. Save the graph in a different location but with the same name as the previous graph
6. Close and open Constellation

**Expected behaviour:** Screenshots for each graph with the same name should match the graph it is opening
**Actual behaviour:** Screenshots for each graph with the same name match the graph of that name that was last saved

**Reproduces how often:** 100%

### Additional Information

You won't actually see this in master currently due to some other issues with the welcome page recent files (namely being determined by file name rather than path so only one file of a particular name shows up) but that issue is resolved in #1465 so you'll be able to see the issue if you test on that branch or wait for it to be merged into master

While file names aren't unique, file paths should be so I think the file path needs to be used in some way. It may not be the best option to use the path as the file name itself though due to how long file paths can be

**Comment by GammaVel** [comment]
Hi, just letting you know my welcome page screenshots on my version of Constellation are looking like this currently: 
![image](https://user-images.githubusercontent.com/83679004/179664682-d98bc9ac-8e8b-482a-a184-8ba8bdedcf1b.png)

They don't have the constellation logo. This is happening with the latest nightly build version.

**Comment by GammaVel** [comment]
Thanks @arcturus2 for this bug fix. This is working for me from the Welcome page - graphs with the same name in different locations can be opened. 

I still sometimes have the Constellation logo but maybe that is where the screenshot didn't save?  Seems ok. I only have no screenshots shown when I go back to the older version. Again, this is reasonable. 

![image](https://user-images.githubusercontent.com/83679004/187354460-29c4916d-dc61-4c2a-b7e4-80e3529d0b6a.png)
