### ISSUE TITLE
Missing icons in drop down menus

### ISSUE THREAD

**Issue by CrucisGamma** [constellation-app/constellation#1506]
May just be the system menus (only ones I've found missing at this stage) but will continue looking for more.
![image](https://user-images.githubusercontent.com/62917181/137856887-c8df5c97-bff1-4dd4-9b51-5bc4a3ff2bd3.png)

**Comment by antares1470** [comment]
Thanks for the suggestion @CrucisGamma. Sadly some of these icons could only be resolved in netbeans as the icons need to be applied to action class and in some cases, Constellation doesn't have control over the action class or access to the required icon. Going to close for now but if there ends up being a way to figure some of these other ones out, happy to re-open at a later stage
