### ISSUE TITLE
Improve screenshot quality

### ISSUE THREAD

**Issue by constellationuser** [constellation-app/constellation#151]
### Description

Often I want to share a picture of a graph I've created in CONSTELLATION. I'm doing this with file -> export -> To Image. However, this simply takes a screenshot at my current resolution, so if I'm mapping out a lot of e.g. infrastructure with small text including country flags and IP addresses I can't see any of this detail due to the zoom level.

i2 Analyst Notebook handles this better by choosing an appropriate zoom resolution and width/height of the image to create. Please can you look into improving this functionality. Maybe creating an e.g. SVG rather than an image with fixed pixel values may help?

**Comment by arcturus2** [comment]
As you've highlighted @constellationuser, the export to image feature literally takes a screenshot of the current resolution. With i2 providing the ability to change the resolution of the exported image feels like something we might be able to do as a first step; so you don't need to have a 4K screen to have an amazing looking image 😄 

The ability to export to SVG is a great idea but will take a lot longer to implement I suspect.
