### ISSUE TITLE
Use higher quality images for country flags

### ISSUE THREAD

**Issue by constellationuser** [constellation-app/constellation#152]
Please can you switch to higher quality country flag images? E.g. the USA flag has a single star which makes it hard to tell it's USA, and the flags with the Union Jack don't have the diagonal red lines aligned to the left/right within their bounding white lines.

**Comment by arcturus2** [comment]
Thank you for the valuable feedback @constellationuser. We've had trouble trying to find a good quality icon set for all of the country flags but will have another look.

If someone can point me to a good set then we can work to bring that into Constellation.

**Comment by cygnus-x-1** [comment]
The current set of country flag icons are stylised to be more recognisable at low resolution (which seemed appropriate for use as icons on a graph). If we were to change them, the biggest challenge will be finding an icon set that we don't need to pay for, and that has representation for all countries in ISO 3166.

**Comment by Caldwell-20** [comment]
At first glance, this set seems to have all of the flags needed and under a  Creative Commons (Attribution 3.0 Unported) license. Based on the comments, it might be missing the Netherlands, but if that is the case, it can be created by rearanging the Russian flag.

[https://www.iconfinder.com/iconsets/ensign-11](https://www.iconfinder.com/iconsets/ensign-11?utm_source=sharing-feature&utm_medium=social&utm_campaign=sharing-feature&utm_content=link)

**Comment by arcturus2** [comment]
> https://www.flaticon.com/packs/international-flags

I like the icons from the flaticon pack @Caldwell-20 has found. Do you think this will work @cygnus-x-1?

@serpens24 and @sol695510, given you've also looked into this, did you find one you wanted to use.

**Comment by cygnus-x-1** [comment]
They look fine to me - just need to double check there's an icon for all supported countries (as per the Country class).

**Comment by sol695510** [comment]
[https://github.com/gosquared/flags]

@arcturus2 This pack covers the current 218 flags present in Constellation with higher quality and detail, as well as smaller sizes if needed.

**Comment by arcturus2** [comment]
nice @sol695510 lets go with this then.

**Comment by cygnus-x-1** [comment]
This icon set only seems to have images up to 64x64 resolution, whereas Constellation icons by default are 256x256. There would be no issue using these, except Constellation will upscale them and they will likely look just as pixelated as the current flag icons.

**Comment by sol695510** [comment]
@cygnus-x-1 That's a good point, I can use the alternate set suggested by @Caldwell-20. An account is required to download the set but you mentioned the site it comes from has been used before, does that mean someone on this project has an account registered?
