### ISSUE TITLE
Object.finalize() deprecated

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#1521]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
A few classes in Constellation have implementations of the old finalize() methods.
A solution will need to be reviewed that suits the needs in context of the current usage.

`au.gov.asd.tac.constellation.utilities.visual.VisualManager` L111 & L115
`au.gov.asd.tac.constellation.graph.StoreGraph` L214 & L218
`au.gov.asd.tac.constellation.graph.locking.DualGraph` L153 & L157
`au.gov.asd.tac.constellation.graph.node.GraphNode` L172 & L176
`au.gov.asd.tac.constellation.graph.node.gui.SimpleGraphTopComponent` L152 & L156

**Comment by HolandCrick** [comment]
@Quasar985 thanks for adding another enhancement for Visual Memory Management. I've tested in old version and new version of the code and Visual memory management improved.
