### ISSUE TITLE
Desktop shortcuts which point nowhere cause many error messages

### ISSUE THREAD

**Issue by constellationuser** [constellation-app/constellation#153]
I had some shortcuts on my Windows desktop where the file or folder they pointed to had moved. When I went to open a file (File -> Open) in CONSTELLATION I kept getting warning messages about this, which re-appeared every time I browsed into or out of a folder in the GUI, so opening a single CONSTELLATION file could cause the error message to pop-up 5 or 6 times depending on how nested my folder structure was.

Interestingly these warning messages didn't appear when when I went Import -> From Delimited FIle -> Green plus button, likely as this used a more modern WIndows GUI for browsing files (and not one that looks like Windows 98)

**Comment by cygnus-x-1** [comment]
The Delimited File Importer uses JavaFX for file selection, as oppose to Netbeans default Swing file chooser. I'm curious what the behaviour of the JavaFX file chooser was when selecting a broken shortcut, as I'd fully expect to see an error occur here.

**Comment by aldebaran30701** [comment]
I have tried twice, to replicate the error messages using dead shortcuts on the desktop to files and folders. 
I have not received any error messages from either:
 - Selecting the file shortcut
 - Selecting the folder shortcut
 - Selecting another folder on the desktop
 - Various folder navigation strategies (up one level etc.). 
They do not appear to cause an error message in either menu.

Would the proposed solution be to look into the file picker menus and standardize them to use the JavaFX style?

Any further thoughts on how to replicate this would be much appreciated in the effort to resolve the errors.

**Comment by arcturus2** [comment]
I'm going to close this given we don't have a decent reproducer. If this issue comes up again and we get more information then let's revisit it.
