### ISSUE TITLE
Show full filepath when hovering over recent files on welcome screen

### ISSUE THREAD

**Issue by serpens24** [constellation-app/constellation#1537]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

When hovering over recent files in the File->Open Recent menu option, the full filename/path is displayed in the bottom status bar. The same does NOT happen when hovering over recent files as displayed on the Welcome screen. It would be great if the same behaviour existed in both cases.

### Steps to Reproduce

1.  Start Constellation

2.  Hover mouse over a recent file in the Recent files part of the welcome screen. Observe no file information displayed in bottom status bar

3.  Select File->Open Recent and hover over same filename, observe file information IS displayed in the status bar.

### Behaviour

**Expected behaviour:** File path is displayed in the status bar in both cases

**Actual behaviour:** File path is NOt displayed when hovering over welcome screen file  preview

**Reproduces how often:** 100%

### Additional Information

See images below, showing what is shown from the File->Open Recent menu, and what hovering over a Recent file on welcome screen looks like.

![image](https://user-images.githubusercontent.com/58677108/139788970-bfce4509-2565-4b6d-9c83-8e5baa6725d5.png)

![image](https://user-images.githubusercontent.com/58677108/139789003-ab0e8f44-9f8f-400b-938a-70ea06b50a6e.png)

**Comment by GammaVel** [comment]
Thank you again @aldebaran30701 for making this new feature. It is a great idea.
I took a look and found the hover text started flashing for the tiles on the right of the screen, where the file path was long. It is ok for the tiles on the left of the screen. I think this could be to do with the text exceeding the bounds of the application. 

Next, for some reason the last 3 tiles are not getting updated with a mini screenshot so I only end up with 7 and not 10 screenshots.

Here is a screenshot of the above two issues:
![image](https://user-images.githubusercontent.com/83679004/152249761-58cf6a46-a8ea-42bc-94a3-fbbd3cf60e31.png).

Can i please get your advice on this couple of issues?  Many thanks, Gamma.

**Comment by GammaVel** [comment]
I looked at the hover text flashing and I don't think it is a big issue as you need to have a small screen and a long file name path for it to show up.  Seeing it is not very noticeable it can be closed. I'll create a new issue for the missing tiles for the recent files, not sure what is causing that to happen. It can be seen in Release 2.5 too.
