### ISSUE TITLE
Button to vertically or horizontally align nodes

### ISSUE THREAD

**Issue by constellationuser** [constellation-app/constellation#155]
Often when I'm mapping out infrastructure there are different levels to the infra which have different purposes. To map this I often place nodes in the same level in a vertical or horizontal line. Currently I'm doing this manually - is there a way to align them so their x or y co-ordinate is all the same? Maybe I'm missing an obvious option or button somewhere.

Thanks

**Comment by arcturus2** [comment]
I don't we have a way to do this yet so this is another good suggestion. Constellation has the grid arrangement so we should be able to implement the new arrangements you've asked for leveraging some of the existing capability perhaps.

**Comment by cygnus-x-1** [comment]
There is a hierarchical arrangement (which needs improving honestly) that might get you some of the way there. There are also plugins to arrange by attribute values (eg. group by type), however the 'inner' arrangement (the way each group is laid out) here is grid by default. Perhaps we could create a 'line' inner arrangement and allow the arrange by attribute layout to use that?

**Comment by serpens24** [comment]
The code that triggers the Grid arrangement (as found in CoreArrangementPlugins\src\au\gov\asd\tac\constellation\plugins\arrangements\grid\ArrangeInGridAction.java) makes use of the ArrangeInGridComponentsPlugin plugin (strangely identiifed as GRID_COMPOSITE in CoreArrangementPlugins\src\au\gov\asd\tac\constellation\plugins\arrangements\ArrangementPluginRegistry.java).

The ArrangeInGridComponentsPlugin is triggered and uses GridChoiceParameters.getDefaultParameters() which sets the default GridChoice value to SQUARE. 

The GridChoice enum has a heap of options: Square, Horizontal/Vertical lines, Two/Three/Four rows, Two/Three/Four Columns. I hacked the code so set the default arrangement to Vertical Line and re-ran constellation and found that selecting  Arrange-Grid then arranges the vertexes in a Vertical Line ... so all the underlying code is there ... 


As an aside for further thought, Gather Nodes also arranges elements in Grids but does it its own way (twice) so there seems to be a heap of duplication and redundancu here ... perhaps GatherNodesInGraphPlugin and GatherNodesPlugin should be reviewed to see if they can make use of GridArranger.

**Comment by serpens24** [comment]
@arcturus2 - using the above approach, the arrange menu looks like the follwing:
![image](https://user-images.githubusercontent.com/58677108/81353099-5b40e680-9107-11ea-8b23-1e853782390b.png)

If we use this approach, then the ArrangeInGridComponentsPlugin would appear to be redundant ....would it still be required in the source set @algol60  ?

**Comment by arcturus2** [comment]
@serpens24 that's a great job and u've added shortcuts too - please PR this when you get a chance to have a play.

**Comment by serpens24** [comment]
> @serpens24 that's a great job and u've added shortcuts too - please PR this when you get a chance to have a play.

Will do. I'll submit it over the weekend as I get a chance.
