### ISSUE TITLE
Exceptions in Map View

### ISSUE THREAD

**Issue by Auriga2** [constellation-app/constellation#1572]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
In the Map View, the `OK` button in the pop up windows is enabled by default when there's no graph opened as well.  
E.g.

-  `Zoom -> `Zoom to Location`, 
- All windows popped up by ` Export From the Map view` drop down menu

![image](https://user-images.githubusercontent.com/64826928/143187811-80341877-6333-44c4-be30-1175de253149.png)

If the user clicks the `OK` button, this exception is thrown:
![image](https://user-images.githubusercontent.com/64826928/143381810-3a232135-da82-4b17-85c8-d25fea7ba08a.png)

If a graph is opened and the user clicks on the `OK` button with empty fields, this exception is thrown:
![image](https://user-images.githubusercontent.com/64826928/143184019-a3f5b8ca-e3c8-49de-863f-d0aa0a8edf4a.png)

![image](https://user-images.githubusercontent.com/64826928/143383238-0113a0c7-63d7-47ea-a876-6983f5d0383b.png)

Also any validation error is thrown as an exception, E.g.: Invalid location coordinate entered in the `Zoom to Location` pop up window:
![image](https://user-images.githubusercontent.com/64826928/143177388-5e99a3c8-6201-4172-ac8b-2ca423020776.png)

I tried to save a graph analysed with map view and when saving it got this exception:
![image](https://user-images.githubusercontent.com/64826928/143326415-c5328c19-85e7-4d78-b4dd-aef0ed34cebd.png)

No errors are thrown if the `Cancel` button is clicked or the top right corner `Close` button is clicked.

### Steps to Reproduce

1.  Open Map View and follow the steps above

**Expected behaviour:** \[What you expect to happen\]
 Ideally the `OK` button should only be enabled when a valid  graph is opened and all required fields are entered in the pop up window.
**Actual behaviour:** \[What actually happens\]
The `OK` button is enabled by default and exceptions are thrown if the user clicks it in above scenarios.
**Reproduces how often:** \[What percentage of the time does it reproduce?\]
100%

**Comment by aldebaran30701** [comment]
#1609 is up for PR to address the majority of these issues, I feel like the last issue with saving the graph should be made into another ticket. It seems like there might be a recent change that introduced a bug with the screenshots of the graph.

**Comment by GammaVel** [comment]
Thanks @aldebaran30701 for resolving these issues, I did notice runtime exception when the file name is not specified in the export options, I created a new issue for this. https://github.com/constellation-app/constellation/issues/1646
