### ISSUE TITLE
Table View Exports not working

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1574]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Currently in master, the table view isn't exporting anything for any of the options. It brings up the dialog box when prompted but after that, nothing is actually saved.

### Steps to Reproduce

1. Open table view and a non-empty graph
2. Select an export option from the table view (any of them)
3. Follow the prompts to save
4. Open the directory where you saved the file

**Expected behaviour:** The correct kind of file is saved in the desired location

**Actual behaviour:** Either nothing is saved, or a file with a blank file type is created

**Reproduces how often:** 100%

### Additional Information

A quick dig suggests the issue is related to the table view refactor

**Comment by GammaVel** [comment]
Thank you for fixing up this issue @antares1470. I checked it out and it is working a real treat now for both csv and xlsx. I did notice a couple of really minor issues with this functionality which I suspect might have been there for a while. Still it would be great to fix them up  - see #1623 and #1624
