### ISSUE TITLE
Inconsistencies in Database Importer

### ISSUE THREAD

**Issue by Auriga2** [constellation-app/constellation#1577]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

1) The same error message added in #1359 when there are empty mandatory fields in the `Add Connections` window, can be added in the `Add Drivers` window for consistency, although there's only one field which is of course mandatory. 

2) Some brief description in `PromptText` similar to  `Add Connections` window would be nice, again for consistency:

![image](https://user-images.githubusercontent.com/64826928/143987861-20ade5f0-3a5f-4bef-a7b1-60e82a81e891.png)

![image](https://user-images.githubusercontent.com/64826928/143988447-f0d5aadf-bc07-4c83-90e9-1e14f2a5d694.png)

3) Noticed an issue with the import status message when there is a filter applied. I guess it should only display the number of rows that are actually drawn on the graph. This looks more like a bug if the filter doesn't select any rows, as it doesn't draw anything on the graph but the message says it has imported some rows.
![image](https://user-images.githubusercontent.com/64826928/144000629-ab9fa70c-9d36-4ad4-8a72-f6094d997d25.png)

### Steps to Reproduce

1.  Open constellation and open `Import From Database` window and try above

**Expected behaviour:** Be consistent

**Actual behaviour:** Not consistent

**Reproduces how often:** 100%

**Comment by Auriga2** [comment]
Another issue in the `Add Driver` window: User can type in the `Driver` field but it doesn't respond and doesn't work even for a valid path. Once a jar is added and the `Name` is populated, the user can manually edit the path but that doesn't populate the correct Name. ->Either disable editing on `Driver` or respond to user editing.

**Comment by Auriga2** [comment]
More issues in the Row filter of the `File Importer` if two or more files contain different headers:

1. On the same Run pane, different files would display the same filter text but subsequent files would not filter and mark the rows, of course because the column headers do not match. But if we import, any matching rows (of the corresponding column location- it matches the column location rather than the column header) from those files are also imported which is incorrect.

2. If a new file is added after the filter text is entered, and if there are matching rows, they are marked, but the filter is marked in red until cut and pasted!:
![image](https://user-images.githubusercontent.com/64826928/145940702-8a909762-08ad-4928-b21d-8cdbcca4a3b1.png)

**Comment by Auriga2** [comment]
5.  Currently it only imports from the highlighted file and any matching fields in the other file on the same column location. In the code a single run pane only supports a single table structure because once we drag and drop attributes or change their column, that change applies across all the files. The filter also relies on that. For this reason I guess it doesn't make sense to import if a different column contains the header in the filter, because we'll possibly be importing different columns. I guess the scope of this is vague, so I'll create a different bug ticket to handle this later with further discussions.

Possible solutions:

- Only allow adding of files with same column structure Or
- Add different `Definitions` per file, and avoid importing of rows of other files with different column headers in the same location but import the rows of other files if there's a column exists in any location with the same name, irrespective of the column name the attributes are mapped to.

6. To recreate: open a CSV file and add a filter text with a changed column name. It should mark the filter in red. Now remove that file and edit that file to contain the changed header text and open to import again. This marks the filtered row but the filter is still marked in red until the text is entered again.

**Comment by antares1470** [comment]
> 5. Currently it only imports from the highlighted file and any matching fields in the other file on the same column location. In the code a single run pane only supports a single table structure because once we drag and drop attributes or change their column, that change applies across all the files. The filter also relies on that. For this reason I guess it doesn't make sense to import if a different column contains the header in the filter, because we'll possibly be importing different columns. I guess the scope of this is vague, so I'll create a different bug ticket to handle this later with further discussions.
> 
> 
> Possible solutions:
> 
>     * Only allow adding of files with same column structure Or
> 
>     * Add different `Definitions` per file, and avoid importing of rows of other files with different column headers in the same location but import the rows of other files if there's a column exists in any location with the same name, irrespective of the column name the attributes are mapped to.
> 
> 
>     6. To recreate: open a CSV file and add a filter text with a changed column name. It should mark the filter in red. Now remove that file and edit that file to contain the changed header text and open to import again. This marks the filtered row but the filter is still marked in red until the text is entered again.

I think some of issues mentioned here are also mentioned or related to issues mentioned here: #1102

**Comment by Auriga2** [comment]
Yes it should handle this issue. Thanks Antares, I was about to create a new ticket for this. Arcturus has suggested the 1st solution there, which makes sense and less confusing to users.
