### ISSUE TITLE
Adaptors Data Access Plugin help pages missing from Help menu

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1579]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Some of the data access plugins found in the adaptors module have a help page and these are accessible from the data access view. These help pages on the other hand appear to be missing from the help table of contents (or at least aren't found under the data access view section as you would expect

### Steps to Reproduce

1. Open 2.5-rc1
2. Open Data Access View
3. Click on blue help button next to Import from GraphML (which is a plugin in adaptors)
4. Confirm the help page opens
5. Search for it in the menu on the side

**Expected behaviour:** Help page found in Data Access Viewsection of table of contents

**Actual behaviour:** Help page can't be found in table of contents

**Reproduces how often:** 100%

### Additional Information

Any additional information, configuration or data that might be
necessary to reproduce the issue.

**Comment by antares1470** [comment]
The issue here may related to this comment made during the initial work on the new help system: https://github.com/constellation-app/constellation/pull/1462#discussion_r736989398

**Comment by GammaVel** [comment]
HI @aldebaran30701. I took a look at this issue with the new online help and it is still occurring for me, under the DAV the relevant help page is launching, however it doesn't appear under the help tree structure as you would expect. This is with the online version of help:
![image](https://user-images.githubusercontent.com/83679004/152245220-574f5c02-4746-4cf8-891b-02f07d3597ed.png)
The offline version has the tree structure I would expect:
![image](https://user-images.githubusercontent.com/83679004/152245467-5be65a70-08b3-47bd-81f7-d5c60f02bcb5.png).
I'll move this back into In Progress to discuss further

**Comment by aldebaran30701** [comment]
Closing this and will document information towards a larger solution in another ticket.
