### ISSUE TITLE
Data Access View - Green button greyed out without graph open

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#158]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

When I open the Data Access View, I can check some plugins to run but I am not able to click on Go. It took some time to figure out that a new graph has to be opened first.

This is not intuitive so some thought to improve the UX is required.

### Steps to Reproduce

1. Open the Data Access View
2. Select a plugin

**Expected behaviour:** The Go button should be green

**Actual behaviour:** The Go button is disabled because there is no open graph.

**Reproduces how often:** 100%

### Additional Information

Some suggestions:
* Can the Go button be enabled and if there is no graph opened then can the default graph be opened before the Data Access Plugin runs?

**Comment by aldebaran30701** [comment]
To enact this enhancement, I suggest creating a new blank graph (utilizing the default schema) whenever the following preconditions are met:
- Data Access View is open
- Plugin is selected (Checked)
- Plugin parameters are valid
- No graph is present

This can be achieved by adding the below code block to the following section of the 
[code](https://github.com/constellation-app/constellation/blob/e2fde449f8d80d89be456842d3c938f5b999ab6c/CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/DataAccessPane.java#L786]|https://github.com/constellation-app/constellation/blob/e2fde449f8d80d89be456842d3c938f5b999ab6c/CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/DataAccessPane.java#L786).
`// When there is not a graph, and a plugin selected with valid parameters, create a new graph
if(!graphPresent && pluginSelected && selectedPluginsValid){`
        `NewDefaultSchemaGraphAction graphAction = new NewDefaultSchemaGraphAction();`
        `graphAction.actionPerformed(null);`
`}`

Please let me know if this will be a fitting enhancement of the code, and I can submit a pull request with the implementation.

**Comment by arcturus2** [comment]
Hey @aldebaran30701, this is pretty much perfect I reckon. 

I say this because it means that we do it for the user rather than:
* Throwing an error and get the user to manually do it (like they have to now)
* Open a graph by default when Constellation opens which will slow down the load time further, plus sometimes users would just want to open an existing graph.

**Comment by cygnus-x-1** [comment]
The plugin framework works on the assumption that a graph is present. I think a better solution would be to have views convey to the user when their requirements are not met (no graph, incorrect attributes present, etc) rather than filling in the blanks for the user, as this could lead to them not understanding when there is a problem. I have previously experimented with this concept by having a translucent warning appear atop the the Map View when required geospatial attributes were not available on the current graph. Compare this to the alternate solution, where I automatically added the attributes on the users behalf to ensure everything worked - the user would likely still see no data, but not understand why. This concept could be expanded to all views, and built into the views framework.

**Comment by arcturus2** [comment]
That's a fair point @cygnus-x-1. If we can solve this problem in a consistent way that all views adhere to then that would be ideal. The idea of presenting a translucent overlay with a warning letting the user know they need to open a graph before they can use the data access view can be applied to pretty much all of the views.

This issue keeps tripping up new users and is a great UX case study to get fixed properly.

@cygnus-x-1 can you share the code for translucent overlay? Also, would you like to create an issue describing how you would like this translucent layer to work?

Depending on how long it takes to get that working, I'm wondering if we can use the solution @aldebaran30701 described to start with and then solve this problem by using the solution @cygnus-x-1 has described.

If we go down this route of a quick fix initially then @aldebaran30701 can you please add a comment in the code to say that the if block should be removed once we get the solution @cygnus-x-1 has suggested in (and quote the issue number)?

Thoughts?

**Comment by aldebaran30701** [comment]
I can see how that implementation will benefit the application as a whole, moving forward. A few error messages could be done away with using the technique @cygnus-x-1 describes. 
I am preparing a pull request with the complete code and should be able to get it out today.
