### ISSUE TITLE
Hidden Conversation Bubble Text

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1580]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Sometimes not all the content of a conversation bubble is visible straight away and you have you to click on the bubble in order for all the content to display.

### Steps to Reproduce

1. Open (or create) a graph with content in the transactions
2. Open Conversation View, ensure content is displayed in view

**Expected behaviour:** All text in a bubble is visible from the outset

**Actual behaviour:** Sometimes you have to click on a bubble in order to see all the text

**Reproduces how often:** Sometimes

### Additional Information

Having tested in a few versions, this seems to be an issue in 2.5-rc1 and 2.4, but not 2.3

See this gif demonstrating the issue below. Note that it doesn't seem to happen for all the bubbles that have more than one line of text. Also note that the same transaction has the issue if you capture the view from the other side of the conversation (i.e. "sender" becomes "recipient" and vice-versa)
![conversationBubbleIssue](https://user-images.githubusercontent.com/62311243/144322598-2f9fa261-bd2d-414a-a211-5ed0944bace8.gif)

**Comment by Auriga2** [comment]
@spica198 Is this fixed? I cannot find any PR.

**Comment by GammaVel** [comment]
I've been looking at the conversation view in the latest nightly build and have gotten some mixed results:

- In a new graph that I created with conversations I am still seeing the last couple of lines being cut off and it is not until I click on the bubble that I see the full text.  Here is a gif of the issue:

![text cutOff](https://user-images.githubusercontent.com/83679004/185509523-6fd99661-4363-4c32-b925-b829b5360a3c.gif)

- In one of the training  graphs (Cornell_Movie-Dialogs_Corpus)  which has conversation text and 6000 nodes, it is cutting the text off midway through the line of some of the conversation bubbles but it is random where it is happening. Here is a screenshot: 

![image](https://user-images.githubusercontent.com/83679004/185522578-6b6f99f1-f5e3-4d4e-9448-42c6a3ae7ad4.png)

If I click it shows the rest of the text.
Here is a gif of the issue:
![conversationTextCutOff](https://user-images.githubusercontent.com/83679004/185522939-4bf66ded-aa6d-49ee-9f98-c39d6a07a1a5.gif)

I will move this back into in progress for some more review.

**Comment by GammaVel** [comment]
Thank you @altair1673 for getting this one resolved! It looks great now and I can see all of the conversation text which is fatastic!  Here is one long example of it working for me:
![image](https://user-images.githubusercontent.com/83679004/223898108-829baef2-1ce1-45a5-bf27-018fd983a6ef.png)
