### ISSUE TITLE
Layers View Help Button Missing

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1581]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

When you open the layers view, the help button previously seen is no longer there. This is only the case when a graph is open. When a graph isn't open, the default view shows the help button

### Steps to Reproduce

1. Open Layers Views with no graph open
2. Verify the help button can be seen
3. Open a graph

**Expected behaviour:** Help button should be located next to the Deselect All Layers button
**Actual behaviour:** Help button no where to be seen

**Reproduces how often:** 100%

### Additional Information

Not an issue in v2.4, only in v2.5-rc1. The code seems to suggest the help button should be there

**Comment by GammaVel** [comment]
Thanks Constellation team for adding the help guide button back to the layers view! I confirmed it is working as expected.
