### ISSUE TITLE
Clash in different ways to create a layer

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1582]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

There are 2 ways to create a layer: via query and via the right-click context menu. At the moment though you can also do both in the same layer and this has presented a bug. If you have a query of a particular graph element type and then use the context menu to add the same kinds of graph elements to the layer, a union is done of the query and context menu elements. If on the other hand you have a query of a particular graph element and different graph elements added via context menu, the context menu elements only appear if there also exists a query of the same type of graph elements.

This is probably the best way to demonstrate it (also see gif below):
- Nodes added via context menu -> context menu nodes show up in layer
- Nodes added via context menu and vertex query added -> context menu nodes show up in layer
- Nodes added via context menu and vertex and transaction queries added -> context menu nodes show up in layer
- Nodes added via context menu and transaction query added -> context menu nodes DO NOT show up in layer

### Steps to Reproduce

1.  Follow steps of gif below (note context menu elements already added to the layer

**Expected behaviour:** Either graph elements added via context menu are visible even if only a query of the other graph element type is added, or it should be impossible for a layer to be generated using both a query and via context menu

**Actual behaviour:** Graph elements added via context menu not visible if only a query of the other graph element type is added

**Reproduces how often:** 100%

### Additional Information

This gif demonstates the issue. Note that Vertex 1 was already added via the right-click context menu and is not a part of the result set of the vertex query.
![layersIssue](https://user-images.githubusercontent.com/62311243/144338410-0f4d9612-0c88-46bf-9f12-3ada864fa6b5.gif)

**Comment by HolandCrick** [comment]
@OrionsGuardian thanks for fixing the Layers View bug. The Union and Intersection are standard functions are functioning  between data sets without error.
