### ISSUE TITLE
Notes View throwing exception after being closed

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1583]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

It appears that the notes view is trying to create a note even after the view has been closed and this is causing a null pointer to be thrown:
```
java.lang.NullPointerException
	at au.gov.asd.tac.constellation.views.notes.NotesViewPane.createNote(NotesViewPane.java:610)
	at au.gov.asd.tac.constellation.views.notes.NotesViewPane.lambda$updateNotesUI$13(NotesViewPane.java:510)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at au.gov.asd.tac.constellation.views.notes.NotesViewPane.lambda$updateNotesUI$14(NotesViewPane.java:510)
```

### Steps to Reproduce

1. Open Notes View
2. Open a new graph
3. Create a sphere graph
4. Do a few other actions
5. Close the Notes View
6. Do a few more actions of the graph
6. Run the sphere graph builder again

**Expected behaviour:** No exception thrown relating to notes view

**Actual behaviour:** Exception thrown

**Reproduces how often:** Sometimes (is definitely happening with graph builders though)

### Additional Information

Found this issue in v2.5-rc1. Wasn't an issue in v2.4

**Comment by GammaVel** [comment]
Thank you @antares1470 for fixing up the exception here. It is looking really good and I can't trigger the error anymore. Thanks :-)
