### ISSUE TITLE
Layer By Time UX improvement

### ISSUE THREAD

**Issue by Auriga2** [constellation-app/constellation#1585]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
In the `Arrange`->`Layer by Time ` window, if the user doesn't select `Date-time attribute` and proceed by clicking `OK`, an error message is displayed but it also closes the window. It'd be nice if we could still keep the window open so that the user doesn't have to open it and re-enter other parameters again. 

Maybe we can default it to the first value, similar to other drop downs `Layer date-times by` and `Unit`, and/or disable the `OK` button until `Date-time attribute` is entered.

![image](https://user-images.githubusercontent.com/64826928/144521953-33ff6800-b2f0-4a8f-93c3-4af6ae653543.png)

### Steps to Reproduce

1.  Open a graph and open `Arrange`->`Layer by Time ` 

2.  `OK` button is enabled, so click it with the default values

**Expected behaviour:** 'OK' button is disabled until `Layer date-times by` is entered or it is auto populated by default.

**Actual behaviour:** Error message pops up, closing the window.

**Reproduces how often:** 100%

**Comment by antares1470** [comment]
The work done in #1674 included setting the Date-time attribute to the first option if one exists so this might actually already be done

**Comment by GammaVel** [comment]
Thanks @antares1470. I agree the Date-time attribute is being set automatically now which is good. 
![image](https://user-images.githubusercontent.com/83679004/178169260-3876445a-7bf0-4ab9-8038-4a7046c38afa.png). Now if the user clicks OK there is no warning message.

There is a lot of empty space shown on this dialog box which could be improved, I will make a new ticket for that.
