### ISSUE TITLE
Add count for Total Bins Selected in Histogram

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1601]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

A small but helpful feature that could be added is an indicator in the histogram view showing how many bins are currently selected. An indicator of the total bin count was added previously so this possibly be extended to include the selected count. 

Currently to do this you need to first filter on selection, get the total count from there, and then reset filters if you want to go back to the rest of the data so this would save those unnecessary steps

**Comment by GammaVel** [comment]
love it!  This is a very handy new feature that I have been trying out. Thank you @aldebaran30701 for merging this in. Looks great.
