### ISSUE TITLE
Incorrect button label in Script View's Getting Started text

### ISSUE THREAD

**Issue by mimosa2** [constellation-app/constellation#1607]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Incorrect button label in Script View's Getting Started text.

### Steps to Reproduce

Step 1. Open the Script View and search the Getting Started Text for the words  #Clicking on "Actions".  This should be changed to 
#Clicking on "Options" to match the button label on the bottom left.

Step 2. Open the Help Pages within the Help menu and select Scripting View. The help content has an image of the Script View which
contains the incorrect words #Clicking on "Actions". The image needs to be replaced after the change in Step 1.   
 

**Expected behaviour:** Correct text to be displayed.

**Actual behaviour:**  Incorrect text displayed.

**Reproduces how often:** 100%

### Additional Information

Any additional information, configuration or data that might be
necessary to reproduce the issue.

**Comment by GammaVel** [comment]
The information text has been updated, thanks @mimosa2 for this.  I have noticed the help guide text needs updating.
Here is a screenshot of it:
![image](https://user-images.githubusercontent.com/83679004/177251175-7b47ea6d-ec76-488a-87a4-5c6b27cdef5e.png)

Moving this one back to in progress for now.

**Comment by mimosa2** [comment]
Thanks @GammaVel. I have checked ( master branch) this morning and  found that  it is updated correctly. Please see below; 
![ScriptingView](https://user-images.githubusercontent.com/54261086/177902716-d94b302b-9204-49a5-bb1e-5a055e57787b.PNG)

**Comment by GammaVel** [comment]
Thanks @mimosa2 . I have worked out this is a difference between offline and online help. The offline help has been updated, the online help has not.

![image](https://user-images.githubusercontent.com/83679004/178163501-a19f03cb-ba43-44a5-9c80-b5593d2ca575.png)

**Comment by mimosa2** [comment]
Thanks @GammaVel for identifying the issue. I checked this with @Delphinus8821 and found that the location for the online help documents are in a different folder below.  
https://github.com/constellation-app/constellation-app.github.io/blob/master/docs/help/constellation/CoreScriptingView/src/au/gov/asd/tac/constellation/views/scripting/docs/resources/ScriptingView.png
This image is still the old one. I will find out from @antares1470 when this is to be updated.

**Comment by arcturus2** [comment]
@mimosa2 @GammaVel this should be fixed now.

**Comment by mimosa2** [comment]
This is fixed. Thanks.

**Comment by GammaVel** [comment]
Awesome!  Thank you @mimosa2 for updating the online help guide. I am glad we figured it out and both versions of the help guide are now consistent.  Here is a screenshot of the updated online version.  I'm looking forward to trying out the scripting view out some more soon. 
![image](https://user-images.githubusercontent.com/83679004/182969722-66538f31-076b-4879-965a-510dcfb0079b.png)
