### ISSUE TITLE
Fastest Box Blur exception

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1616]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

While writing unit tests for the `GaussianBlur` class, I encountered an ArrayOutOfBounds exception happening with the `gaussianBlurBox` function with the Blur Box type set to `FASTEST`. The issue appears to lie in the `boxBlurFFH` function call (may also happen in the `boxBlurFFT` function called afterwards). In that function, it is accessing an index in the source channel that is partially determined by the value of the radius (the variable `ri`)`. Problem here though is that there doesn't appear to be any restriction on the value of the radius and the source channel size is not determined in any way by the radius which allows the exception to occur.

### Steps to Reproduce

1.  Call the `gaussianBlurBox` function with the type = FASTEST, width = 2, height = 3, radius = 2

**Expected behaviour:** No exception thrown

**Actual behaviour:** `ArrayOutofBounds`

**Reproduces how often:** 100%

### Additional Information

Chatted to cygnus-x-1 who is listed as the author of the class and apparently they got the algorithms from this blog: http://blog.ivank.net/fastest-gaussian-blur.html. Could be a useful reference point for whoever picks up this ticket

**Comment by HolandCrick** [comment]
@Quasar985 - thanks for resolving the Heatmap bug. 
The Fastest Box Blur **Exception Error** is not throwing in V11 nightly build 04/03/2024 which was in earlier v9/v10. At the same time, from map view -> enable the option Heatmap (Standard) is working which was not working in earlier versions. Good work folks.

Although, the Map View option is not taking/showing the map location where most of the nodes are. Is it possible to enhance that feature?
