### ISSUE TITLE
Online help - menu buttons are appearing blue on blue text on hover which can't easily be read

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1621]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

In the new online help for Constellation the menu side buttons are appearing as blue on blue text when you hover over them. This makes the buttons hard to read. This is not happening with the offline help, there the buttons turn grey on hover.

### Steps to Reproduce

1.  Navigate to the Constellation home page> Documentation: https://www.constellation-app.com/help/constellation/CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/docs/about-constellation.html
2.  Hover (mouse over) the left side menu items
3.  Observe the colour of the button change to Blue and the existing blue text doesn't change > becomes hard to read

**Expected behaviour:** Button text remains easy to read. 

**Actual behaviour:** 
![image](https://user-images.githubusercontent.com/83679004/152261497-f3cdefcd-fa14-4f5e-94dc-c831f6dd8d44.png)

**Reproduces how often:** 100%

### Additional Information

Styling on the website is overriding the styling on the help.

**Comment by arcturus2** [comment]
The changes have been merged in but I note that when testing this you will need to either clear the browser cache or hold shift when you refresh the page.

**Comment by GammaVel** [comment]
Thanks you @Delphinus8821 for making this update!  The online help is looking very snazzy now!!
![image](https://user-images.githubusercontent.com/83679004/173482431-e6320d6b-9606-4829-b4ae-1fab592715dd.png)
