### ISSUE TITLE
Welcome screen and File Open Recent - not all recent files are showing up

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1622]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The welcome screen shows tiles with a screenshot of the graph which is very handy. I have noticed in Release 2.5 and the nightly builds that the tiles are blank for the last three ones, even when I have been working with over 10 graphs. Can this be looked at as it wasn't an issue with previous versions. I have seen an error (see below) when saving one of the graphs a couple of times but I don't think it is causing the issue. 

### Steps to Reproduce

1.  Open the latest version of Constellation with the Welcome page

2.  Look at the tiles which are shown there - notice the last three are blank.

3.  Open and save some other graphs, enough to make the 10 tiles be populated
4. Open and close Constellation and check the welcome page, there are still a few blank tiles
5. Repeat again
6. Check the File Open recent and notice all of the files are not there too. 

**Expected behaviour:** If I have worked on 10+ graphs recently, all of the tiles are populated on the Welcome page and File Open recent

**Actual behaviour:** 3 blank tiles:
![image](https://user-images.githubusercontent.com/83679004/152264260-6b9f5e73-8fad-451e-a978-f98b06a7c468.png)

**Reproduces how often:** Missing tiles - 100%, runtime error is not easily reproducible. 

### Additional Information

Observed this run time error when saving a couple of my graphs but it isn't reproducible:
![image](https://user-images.githubusercontent.com/83679004/152264403-15d3a52d-be7a-459a-ab99-0ebdc5bae058.png)

**Comment by Auriga2** [comment]
When testing v2.6, I  noticed that this number of blank previews is changing time to time. For me, once all of them loaded, then changed to one blank preview. However I didn't observe the exception above. 

But the image was the default image when existing files are opened and just closed. Looks like it's saving a screenshot only when saving a file. To fix this, would it be possible to generate a screenshot when closing a file as well?

**Comment by Delphinus8821** [comment]
When testing v2.8 now only 5 of the most recent graphs show up in both the File -> Open Recent, and the recent graphs shown in the Welcome Page. Can confirm that graphs that are just opened and not saved have the default image on the Welcome Page instead of an image of the graph.

**Comment by Astroboy2022** [comment]
During testing I have found that the tiles are populating for me. I have tried this three times and the tiles/open recent are all remaining populated 

![image](https://user-images.githubusercontent.com/108911408/201238115-5eaab2c5-de5f-4d69-97a3-fa93b90d64fe.png)

**Comment by Astroboy2022** [comment]
Version information for the above test is below: 
![image](https://user-images.githubusercontent.com/108911408/201239732-48a4b3d3-70c0-4283-ac12-1936cc810cb5.png)

**Comment by GammaVel** [comment]
Thanks @Astroboy2022 for checking this out, it was interesting that you only had the Constellation logo and not the graph in the screenshots, not sure if that had something to do them all being sample graphs. Would be good good to keep an eye on this in case something there has broken.
