### ISSUE TITLE
Table Export - remove the file path from the File name when setting File Types to All Files

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1624]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

From the Table view it is possible to export data to CSV or excel. In the file export dialog you can change the file type to be all files. If you make this change and navigate up a folder level and into another folder, the File name is getting populated with the full file path. This information isn't actually needed as it makes it slightly harder to add your new file name. If I don't change the file name or add to it, the file doesn't actually save.
![image](https://user-images.githubusercontent.com/83679004/152435557-58dc86b3-eefb-4f97-bf1a-d3d34068084b.png)

### Steps to Reproduce

1.  Open a graph and the table view. 
2.  Click export to excel or csv
3.  In the export dialog change the file type to be All files
4.  Go up a folder level
5.  Go into another file > Observe how the file path is automatically being added to the file name
6.  Don't change the file name and save > Navigate to the saved location and the file is not actually there
7.  Repeat the above steps this time removing the file path > the file is saved.

**Expected behaviour:** The file path does not automatically get added

**Actual behaviour:** The file path is being added, when I change the file extension to all files and I move through the folder structure

**Reproduces how often:** 100%
### Additional Information

Not a major issue, might be good to look at with #1624 . Thanks !!

**Comment by Auriga2** [comment]
This seems to be a limitation with the `FileChooserBuilder` used. Same behavior in other places it's used, such as Scripting View, Export To Image,  Export To JSON, DAV Save results. Should we try to use JavaFX.FileChooser or swing JFileChooser instead?

**Comment by Auriga2** [comment]
Yes this is an issue with the `FileChooserBuilder` which by default displays the file/folder path in the File name field. Explicitly setting ` .setFilesOnly(true)` fixes the problem.

Also noticed that the` Export To Image` and `Export To JSON` doesn't show the existing files of the relevant type (including previously saved), but only shows the folders. Fixed that also in the below PR.

**Comment by Auriga2** [comment]
Reverted the change for DAV Save results, which expects a folder to be chosen. (Looks like it doesn't seem to work, if so a separate bug will be logged)

**Comment by GammaVel** [comment]
Thanks @Auriga2 for making this fix. This is working beautifully now when I go to export my graph from the table view.
