### ISSUE TITLE
Import from Database - add in a clear option

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1628]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

On the Import from Database screen it would be super handy to have a Clear option, in case I have queried the wrong data and I need to redo my query and load some more. It is possible to clear this by closing the run but it wasn't immediately obvious to me. A clear button would be super awesome if possible. 

### Steps to Reproduce

1.  As per above description, set up a new DB connection and configure, import data
2.  The data I wanted isn't quite right - look for a clear option, none is shown
3.  Clear the data by closing the run. This means when I query I need to click on the plus which took me a little bit to work out
4.  I also tried closing the Import from DB as a workaround,  but when I reopened it the data was still there. 

**Expected behaviour:** As an enhancement add a clear button. **Update - add this at the query level so it will also clear the query and the query results.

**Actual behaviour:** It is not really obvious on how to clear the data

**Reproduces how often:** 100%

### Additional Information
--original clear button placement screenshot removed (it wasn't the best idea to have it here, sorry)
--new suggested placement:
![image](https://user-images.githubusercontent.com/83679004/180333839-c7ab8b04-e37d-433b-b995-f4828a31dfb4.png)

This would help with the user experience.

**Comment by antares1470** [comment]
Would it make more sense to add a Clear option to the query field itself (i.e. in the Source and Destination Panel)? Worth noting that clearing the config panel won't actually clear the query as you can just add a new run which would have the query results

**Comment by GammaVel** [comment]
Thanks @antares1470 for pointing that out. Initially I thought the clear should be at the results level but this would also be present on the import from file screen. If I clicked it there, I would not be able to get import results back easily as there is no import button. That would be a bit confusing.

Can this be added at the query level?  I will update the issue description with a new screenshot too.
![image](https://user-images.githubusercontent.com/83679004/180332812-03721769-40d3-46fd-a411-7c5f94055f63.png)

**Comment by GammaVel** [comment]
Thanks @altair1673 for adding the clear button!  I really love it!  I have been using it to clear out my queries results and it is so much easier now to keep running the queries until I get the results I need. 

Thank you for picking up my suggestion and implementing it!

Here is a screenshot for "Before and After" (AFTER)
![image](https://user-images.githubusercontent.com/83679004/182991471-8292705b-280b-4ca0-82af-715e9e826794.png)
