### ISSUE TITLE
Graph renderer doesn't support different language fonts

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#163]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Constellation had great support for different languages because it relied on the [Arial Unicode MS Font](https://en.wikipedia.org/wiki/Arial_Unicode_MS) however MS Office 2016 dropped support for the font due to licensing costs I think, Constellation needs to find a font we can use to support different languages again.

A work around was to default to the `Malgun Glothic` which does a good job with Chinese characters but fails with Arabic, Hindi etc  (i.e any character not supported by `Malgun Glothic`.).

The attribute editor or table view seems to figure out which font to use and render it but on the graph, OpenGL doesn't have that fallback logic and displays blanks.

### Steps to Reproduce

1. Open a new graph
2. Change to draw mode
3. Click on the graph to create a new node
4. Change to select mode
5. Select the node
6. Bring up the attribute editor by going to Views -> Attribute Editor or Ctrl + Shift + E
7. Click on the `Edit` button besides the `Identifier` attribute
8. Paste some Arabic text
9. Click OK
10. Press F5

**Expected behaviour:** The text should be displayed on the graph

**Actual behaviour:** The label of the node is blank

**Reproduces how often:** 100%

### Additional Information

The `Malgun Glothic` font is currently hard coded so as a start, we need to make it visible as a preferences option in Constellation so that a user can select which font they want to use.

**Comment by aldebaran30701** [comment]
Currently looking at this for a fix:
Idea is to handle a font family picker similar to that held in Options -> Miscellaneous -> Output. 
![image](https://user-images.githubusercontent.com/58677759/71148848-b8cdb700-227c-11ea-84a5-5569b3e0cde7.png)
This picker would be implemented in a cut - down way and held in Constellation -> Graph as a way to pick the default font family, size colour etc. for nodes.
It would store preferences very similarly to the graph blaze size. 

I have one issue. I cannot seem to change the font to anything else!
I search the project and only find one font hardcoded for the graph.
https://github.com/constellation-app/constellation/blob/6d3e363526a5a53457fcfb68dc7f9b6593a479cb/CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/utilities/SharedDrawable.java#L76
I changed it to multiple different values in the wild chance I selected one that was not supported in Windows 10. 

Any thoughts on this solution, and or help with further expertise on the matter are welcomed.

**Comment by arcturus2** [comment]
Hi @aldebaran30701 thank you for looking at this.

Some background information for you...

The Setup -> Options -> Misc is provided by the NetBeans framework which out of the box is designed to set the font for the Output window which in NetBeans is Window -> Output and in Constellation it is Help -> Show Logs.

We took the option of not creating our own preferences for the font family and size and tried to hook into the values provided by this Miscellaneous window which is stored in `org/netbeans/core/output2`.

https://github.com/constellation-app/constellation/blob/a07d37e07e15ef5ff33af6827cb09c87c3aeb12e/CorePreferences/src/au/gov/asd/tac/constellation/preferences/ApplicationPreferenceKeys.java#L159-L163

There are issues with this, one mainly being that this output window only supports Swing fonts which means we can't use it for the JavaFX views like the DAV, Quality Control View etc. I'm actually not sure exactly how the fonts are assigned to the JavaFX views but it seems to have a nice fall back approach and is able to render text from different languages, unlike the graph renderer because we've hard coded the only font it can use.

I think your suggestion of creating our own font picker is the way to go and that should be used across everything in the application perhaps like the menus, views (Swing/JavaFX) and the OpenGL renderer. Note that there is also `FontUtilities.java` which doesn't check whether the Swing based font is also compatible with JavaFX and will need updating.

@algol60 is working on a solution to have the renderer support a list of fonts and fall back to the next font if the particular character can't be drawn by the preferred font. His work is available in this [glyphs app](https://github.com/constellation-app/miscellaneous/tree/master/Glyphs) and I think he will need some help to neatly hook this up to Constellation preferences.

Perhaps we can do away with this Miscellaneous window if things work out.

I'm not sure if I've answered your questions so let me know if you need anything clarified. It would be great for you to collaborate with @algol60 when his gotten the fallback logic working.

**Comment by aldebaran30701** [comment]
Yes and no, It may be just something I have overlooked in terms of other locations to set the main font. 
No problems, The fallback of single characters is a nice way to draw all characters no matter the language. I can push the current progress of the storage of preferences to [my fork](https://github.com/aldebaran30701/constellation/tree/DifferentFont-%23163), and if need be I can assist in hooking everything up. I am happy to sit on this issue, and have a look at FontUtilities for a way to verify compatibility with JavaFX.

**Comment by arcturus2** [comment]
>...if need be I can assist in hooking everything up. I am happy to sit on this issue, and have a look at FontUtilities for a way to verify compatibility with JavaFX.

Thank you.
