### ISSUE TITLE
Data Access View - runtime error when opening

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1638]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

A runtime error is being displayed when the Data Access View is being opened for the first time in a new Constellation session. It is opening over the graph area. This is happening with the latest nightly build and Release 2.5. If I close the DAV and reopen it in the same session I don't have the error however if I completely close and reopen constellation and open the DAV it is displayed.

### Steps to Reproduce

1.  Open a new graph in Constellation
2.  Open the Data Access View (DAV)
3.  Observe runtime error
4.  Close DAV
5.  Reopen > this time there is no error displayed
6.  Close and reopen Constellation and open the DAV > Error again

**Expected behaviour:**No errors when launching the DAV

**Actual behaviour:** Runtime error, as per the screenshot

**Reproduces how often:** 100%

### Additional Information
![image](https://user-images.githubusercontent.com/83679004/153127017-b7285113-07a0-49b0-ac3b-ea518fa7e31f.png).
![image](https://user-images.githubusercontent.com/83679004/153127391-96d3c1d6-3e35-459d-b647-850e1c951890.png)

**Comment by Delphinus8821** [comment]
This can be fixed by running the reset.bat script that is included with each release version of Constellation.

**Comment by GammaVel** [comment]
Thanks @Delphinus8821, this has now been added to the list of [known issues](https://github.com/constellation-app/constellation/wiki/Known-Issues) and can be closed.
