### ISSUE TITLE
Compare graph possible improvements

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#1647]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
Come from the discussion in the PR of #1350

There may be a better solution and that may be to actually just not allow the user to compare graph when only one graph is present.
Open to discussion on this ticket as the solution still needs to be fleshed out.

\[Description of the issue\]

### Steps to Reproduce

open compare graph with one graph - user may be unsure why only one graph exists to compare against.

### Behaviour

* Try to include measurable metrics that can be aimed for (if applicable to the issue),
e.g. if it's a time issue then "should take 5 seconds or less to finish"
or if it's a workflow issue "should be accomplished in 2 or less clicks".

-->

**Comment by aldebaran30701** [comment]
I've just completed a quick Pr for something that may solve this issue. Check out the PR linked to this ticket once it is up.

**Comment by GammaVel** [comment]
Thanks @aldebaran30701 for making this improvement. Looks great!  Thanks for making all the improvements to the Compare Grpah Functionality.
