### ISSUE TITLE
Add support for dynamic icons

### ISSUE THREAD

**Issue by cygnus-x-1** [constellation-app/constellation#165]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Constellation provides good support for static icons built from byte data, images, or even algorithms (such as the pie chart icons). It would be great if this could be extended to support dynamic icons, that is icons which listen to and update with attribute values. For example, you could generate a pie chart icon based on an Attribute which represents a percentage value, or a bar chart icon based on an Attribute which represents bin values, or even simply a number icon based on an integer attribute value. I would imagine these icons would be pre-configured to listen to a particular attribute (or set of attributes) or this attribute could be specified later through the user interface.

### Steps to Reproduce

1. Set the icon of a node to be a dynamic icon.
2. Change the value of the attribute it is listening to.

**Expected behaviour:** [What you expect to happen]
The icon is updated immediately to reflect the new attribute value.

**Actual behaviour:** [What actually happens]
Nothing happens to the icon.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Additional Information

Issue #112 has a similar request and it will be worth resolving both together.

**Comment by spjspj** [comment]
Do you see something like #112 being similar to this arcturus?

**Comment by arcturus2** [comment]
Thanks @spjspj, I do think they are similar and likely to have a similar implementation. Good triaging.

**Comment by CrucisGamma** [comment]
I think this still has value for assigning icons to data based on automatic data ranges in a given field.

**Comment by GammaVel** [comment]
Excellent idea which has been added to brainstorming for now. Closing issue.
