### ISSUE TITLE
Favourites option in Data access view is not working

### ISSUE THREAD

**Issue by mimosa2** [constellation-app/constellation#1650]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Favourites in Data access view is not working

### Steps to Reproduce

1. Open DAV select few plugins and click the star (Favourites)  

2. Select add or remove to choose the list of favourites 

3. Close and open the application 

**Expected behaviour:** Favourites should appear as a DA category with selected plugins

**Actual behaviour:** Favourites doesn't appear

**Reproduces how often:** 100%

### Additional Information

Any additional information, configuration or data that might be
necessary to reproduce the issue.

**Comment by GammaVel** [comment]
Working great. Thank you @mimosa2.
