### ISSUE TITLE
Database Importer - broken Templates

### ISSUE THREAD

**Issue by Auriga2** [constellation-app/constellation#1654]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
Clicking on `Load Template` or `Save Template` buttons does not dot anything or pop up any message/exception. Same behaviour in V2.5 as well.
### Steps to Reproduce

Load `Import From Database` window and click `Load Template` or `Save Template` buttons. You can pull some data from a database and then click on `Load Template` or `Save Template` buttons as well, but nothing happens.

**Expected behaviour:**  Does not load and save templates

**Actual behaviour:** Load and save templates

**Reproduces how often:** 100%

**Comment by Auriga2** [comment]
@antares1470 @arcturus2 
This (JDBC Importer templates) doesn't seem to have ever worked, at least since the code refactoring. 

Database Importer Templates were supposed to be stored in a folder called `ImportJDBC`. There is another folder called `JDBCImport` in the same location, which stores driver details. so it's confusing with the `ImportJDBC`, hence renamed that and the delimited templates file folder as below.

`ImportJDBC`->`DatabaseImporterTemplates`
`ImportDelimited`->`FileImporterTemplates`

`FileImporterTemplates` worked before, so we need to move existing templates into the new folder. Is there a way to do that and delete the unwanted folder by a script or something? Otherwise should I keep `ImportDelimited` folder as it is?

**Comment by Auriga2** [comment]
For now I left the `ImportDelimited` as it is. The PR is only for Database importer anyway.

**Comment by GammaVel** [comment]
Thanks for fixing the issues with the templates on the Import from database @Auriga2 !  I'm able to use the templates with my imported SQLite data and they are working really well.
