### ISSUE TITLE
String parameter values not saving

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1662]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

String parameters come with a drop-down list of recent values which is handy should you need to use a value more than once. What should happen is that when you run a plugin, any string parameter values are saved and can then accessed via the drop-down list next to the parameter. Currently though, this no longer happens

### Steps to Reproduce

1. Open a graph with a node
2. Run the split nodes plugins, ensuring there is a value entered for the Split characters parameter

**Expected behaviour:** After pressing go, the drop-down for the Split characters plugin should contain the value just used

**Actual behaviour:** List remains empty

**Reproduces how often:** 100%

### Additional Information

I tested this on a version where this wasn't an issue (2.1) and the most recent version (2.6). I observed after running on 2.1and then 2.6 that the values loaded into the drop-down list fine so the issue appears to only be with the saving of the values

**Comment by GammaVel** [comment]
Thanks for fixing this issue up @Delphinus8821. I have tried this out with the Spilt note plug in similar to your testing but also some others and they were working too. I closed and reopened Constellation and the values were retained between sessions. 
It is great to see this working!!
