### ISSUE TITLE
Add Excel DateTime parsing option

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1663]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Given Constellation is able to import excel files through the File Importer, it would be helpful to be able to add the native excel datetime as an option for parsing into Constellation as currently that is not an option (you have to convert to Epoch or similar).

For reference, the native format for Excel is days after 1/1/1900. e.g. 1/1/2020 12pm would be 43831.5

### Steps to Reproduce

1. Create an excel spreadsheet with a column with datetimes represented as a numeric value
2. Open File Importer in Constellation and load file in
3. Try to parse the intended column as a datetime

**Expected behaviour:** Option to parse excel datetime

**Actual behaviour:** Can't parse as a datetime field, have to create a seperate column in the spreadsheet which converts to Epoch or similar

**Reproduces how often:** 100%

**Comment by GammaVel** [comment]
This is working a real treat now. Thanks @Auriga2  for all your efforts with setting this up. It is so handy to be able to import from excel now.
