### ISSUE TITLE
Update README after new help implementation

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#1676]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

If I understand correctly, we should be able to remove the below steps in the readme as we are not using the java help module.
![image](https://user-images.githubusercontent.com/58677759/163065918-c3a190f7-24a3-4937-8905-47a1de121abf.png)

\[Description of the issue\]

### Steps to Reproduce

1.  \[First Step\]

2.  \[Second Step\]

3.  \[and so on…\]

**Expected behaviour:** \[What you expect to happen\]

**Actual behaviour:** \[What actually happens\]

**Reproduces how often:** \[What percentage of the time does it reproduce?\]

### Additional Information

Any additional information, configuration or data that might be
necessary to reproduce the issue.

**Comment by GammaVel** [comment]
Thanks for removing the unneeded text @arcturus2.
