### ISSUE TITLE
Data Access View Help guide section - add information about configuring categories

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1681]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The Data Access view now has an option to configure what categories are displayed. This means if I don't like a category I can hide it. The help guide section for the data access view does not contain any information on this handy feature. It would be great if it did, similar to the workflow options section in the Data Access View Help. 

### Steps to Reproduce

1. Open the Data Access View and click the help guide link
2. Check for information on the new display configuration options > none found
3. Go to the Options help information and check if there is anything there > none found

**Expected behaviour:** The help guide contains information about configuring the visible categories in the Data Access View configuration options

**Actual behaviour:** no information available in help on this
**Reproduces how often:** 100%

### Additional Information
![image](https://user-images.githubusercontent.com/83679004/163903112-ca23493c-0b2d-471a-9d06-55c43d8cbce0.png)

**Comment by GammaVel** [comment]
Thanks very much @mimosa2 for making the changes here. When I checked offline help for the preferences I don't actually have an image shown:
![image](https://user-images.githubusercontent.com/83679004/197096266-2db7b7cb-2891-47dc-8a98-f88fcefaab93.png)
Do you know why this might be the case?

Separately, when I checked online help the changes where not there compared to offline. Has online help been updated yet?
Here is a screenshot showing the difference between offline and online:
![image](https://user-images.githubusercontent.com/83679004/197096842-b380aa74-0f11-4050-8120-44ead3e39c1b.png)

**Comment by Delphinus8821** [comment]
@GammaVel That image path being broken I am fixing in my PR #1774 as I need to edit the help page there anyway. Online help has not yet been updated with the new pages

**Comment by mimosa2** [comment]
@Delphinus8821 Thanks for updating the image path.

**Comment by GammaVel** [comment]
I'm still seeing an error when I click on Preferences in the Data Access View in the offline help.

**Comment by Astroboy2022** [comment]
I have taken a look at this today (25 November) and it appears that there is still no link there when checking the offline help for the preferences 

![image](https://user-images.githubusercontent.com/108911408/203905585-bcdfa141-0a24-47bf-b1ac-15617557091a.png)

**Comment by GammaVel** [comment]
Thanks @Delphinus8821 for fixing this up for us. Looks good now, the image is present:
![image](https://user-images.githubusercontent.com/83679004/211243939-bdda25c3-d760-4c03-88b7-738c520c3dca.png)
