### ISSUE TITLE
Bug with Selection in the new Advanced find

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1694]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

There is an issue with the new Advanced Find (under Experimental) which can be seen when there 2 search criteria and one of them is for selection and the Current Selection has been set to IGNORE. For example:
![image](https://user-images.githubusercontent.com/83679004/166849528-2ee9f876-b2ed-4d2b-a01c-edf89133ed99.png)
When selected is set to true the logic is in reverse - i.e - it doesn't find the item. When it is set to false it finds the item in the selection. 
### Steps to Reproduce

1.  Open up the Experimental find > Advanced
2.  Set the criteria to be Look for Node, Match criteria ALL, Current Selection IGNORE
3. Add criteria where you know there will be a match on the graph
4. Add another criteria for selected and set it to TRUE. 
5. Highlight an area on the graph which has the Node with the match
6. Click on Find > The node is not found
7. Compare to the current Find. In this case the node is found. 

**Expected behaviour:** When Selected = True and my match node meets the criteria, the node/s are found. I am not sure if this has something to do with IGNORE being set

**Actual behaviour:**see test steps above

**Reproduces how often:** 100%

### Additional Information

Here is a gif of the issue:
![selected option](https://user-images.githubusercontent.com/83679004/165230532-c837b016-3c43-479d-b161-208596a248ac.gif)

**Comment by GammaVel** [comment]
This is looking great now, thanks @altair1673 for getting to the bottom of what was causing my issue here. It is now working as I expect it to and makes more sense logically.

**Comment by Delphinus8821** [comment]
Currently testing the find view and noticed something happening with the selection in the advanced find. When the Current Selection is set to 'Ignore', then clicking Find Next will add each found node to the selection. When the Current Selection is set to 'Add To', clicking Find Next will only highlight that found node. This appears to be backwards to how I would expect it to work.
What are your thoughts on this @antares1470 @GammaVel @altair1673 ?

See below for an example

![find_view_selection](https://user-images.githubusercontent.com/73083035/186312935-38830dac-29e1-4fba-8325-173ae2c240b7.gif)

**Comment by antares1470** [comment]
> Currently testing the find view on 2.8.0-rc1 and noticed something happening with the selection in the advanced find. When the Current Selection is set to 'Ignore', then clicking Find Next will add each found node to the selection. When the Current Selection is set to 'Add To', clicking Find Next will only highlight that found node. This appears to be backwards to how I would expect it to work. What are your thoughts on this @antares1470 @GammaVel @altair1673 ?

@Delphinus8821 I would tend to agree with your analysis. Given it's a separate issue to the one here (albeit very similar), could be worth a separate ticket

**Comment by Delphinus8821** [comment]
> > Currently testing the find view on 2.8.0-rc1 and noticed something happening with the selection in the advanced find. When the Current Selection is set to 'Ignore', then clicking Find Next will add each found node to the selection. When the Current Selection is set to 'Add To', clicking Find Next will only highlight that found node. This appears to be backwards to how I would expect it to work. What are your thoughts on this @antares1470 @GammaVel @altair1673 ?
> 
> @Delphinus8821 I would tend to agree with your analysis. Given it's a separate issue to the one here (albeit very similar), could be worth a separate ticket

@antares1470 I believe this was caused by the fix for this ticket as it works as I would expect it to in v2.7.0
