### ISSUE TITLE
Minor EPOCH formatter improvement

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1699]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The Epoch datetime formatter used in Constellation is the Unix epoch. I think it might be good to explicitly state this in the formatter so that people on the off chance don't confuse it for another epoch.

**Expected behaviour:** Formatter states EPOCH (Unix)
**Actual behaviour:** Formatter states EPOCH

**Reproduces how often:** 100%

### Additional Information

Any additional information, configuration or data that might be
necessary to reproduce the issue.

**Comment by GammaVel** [comment]
Thanks for making this nifty change @altair1673. Looks good, I saw this update when I was importing some CSV and XLSX files with EPOCH date times.
