### ISSUE TITLE
Revert back label attribute names

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1706]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Previously the graph attributes for labels were called "node_labels_top", "node_labels_bottom", and "transaction_labels". It wasn't clear though that these attributes were also where you edited label colours as well (since there was no mention of the colour in the display value). This was then changed so that the display value included colour but also the attribute names themselves were changed to "node_top_labels_colours", "node_bottom_labels_colours", and "transaction_labels_colours". What I think may have happened now is that it isn't necessarily clear that these attributes are where you edit the labels themselves (just the colours) and so this change may have been a slight over-correction.

I think including the colour in the display value should be sufficient for making clear that the colour gets edited there and for that reason I'm proposing keeping the display value as it is currently but reverting back to the old attribute names ("node_labels_top", "node_labels_bottom", "transaction_label")

**Expected behaviour:** Attributes describe label but value contains an indication that colour can be edited

**Actual behaviour:** Attributes describe label colour, not clear that the labels themselves (aside from colour) are edited there

**Reproduces how often:** 100%

### Additional Information

Any additional information, configuration or data that might be
necessary to reproduce the issue.

**Comment by GammaVel** [comment]
Thanks for making this update @Delphinus8821. It is clearer now that you can change the value of the label and the colour. This is a nifty improvement!

Here is a screenshot of the update:
![image](https://user-images.githubusercontent.com/83679004/185828090-6ed4b45b-a621-42a3-9f7e-8bcb1817a82b.png)
