### ISSUE TITLE
Export from the map view - Node options are not shown as expected

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1720]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

From the map view it is possible to export to different file types such as GeoJason, GeoPackage, KML etc. After clicking on the export button and selecting one of the file options, the "Export" dialog is displayed.  This has options for Node and Transactions for the graph. It is not possible to select any node Attributes, as the drop down in not enabled. If you switch to Transactions and back to Nodes it does become enabled. 

### Steps to Reproduce

1.  Open a graph which has location information
2.  Open the Map view
3.  Click on Export and pick one of the options
4.  Observe Node is shown by default but the Attribute drop down can't be selected:
![image](https://user-images.githubusercontent.com/83679004/178164898-0040f703-19e6-4264-95f8-357969ba8cc8.png)
5. Change Element type to be Transaction and back again to Node > you can now see the Node Attributes:
![image](https://user-images.githubusercontent.com/83679004/178164931-e70c876e-537b-40ed-aff2-49d5def90e0e.png)

**Expected behaviour:**  The node attributes are shown immediately without having to change to Transactions and back again.
**Actual behaviour:** See above screenshots and Repro steps

**Reproduces how often:**100% for all the different file types

### Additional Information

NA

**Comment by antares1470** [comment]
This may be because the attribute value was set before the controller for it was defined. Setting the value after the controller definition should resolve the issue (if that is indeed the issue here)

**Comment by GammaVel** [comment]
Thank you @antares1470  for resolving this issue. I have tried this out and it looks really good now, I don't need to go to the transactions option and back again to see the attributes that I am interested in. Thanks! All of the export options look good.
