### ISSUE TITLE
Export from the Map View - last save location is not being retained

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1721]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

From the Map view it is possible to export to 4 different file types.  After selecting a file type and performing a save, the last save location is not being retained when next using this option in the same session of Constellation.  I checked my Constellation options (under Set up > Options >Application > Open Save location) and this is set to remember the last save location. 
This is a small issue but would be great to have consistent with the rest of the app that does remember the last save location. 

### Steps to Reproduce

1.  Open a graph with location information
2.  Click on Export and pick one of the file types
3.  User save to select a file location
4. Complete save
5. Decide to export again, repeat the above steps > notice the save location is the original one that was first displayed

**Expected behaviour:**
The last save location is stored and displayed to save some mouse clicks and make it consistent with the rest of the app

**Actual behaviour:**
Last save location not recorded

**Reproduces how often:** 100% for all the different options

**Additional Information**

Not a huge issue but worth mentioning.

**Comment by Auriga2** [comment]
Probably should wait till https://github.com/constellation-app/constellation/issues/1746 and https://github.com/constellation-app/constellation/issues/1825 are done.

**Comment by HolandCrick** [comment]
Thank you @capricornunicorn123 for resolving the Map View issue. Looks good.
