### ISSUE TITLE
Importing from file - java.lang.NumberFormatException: For input string: "ERRO" when header row is included in the data

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1731]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

This is a small edge case to do with importing from a CSV file which has date/time field mapping set and the header row included in the loaded data.

A runtime error is being displayed during the import from file process, if you have not selected the "File has headers" and the header row is included on the first line of the import and the date mapping has been applied to the column.  

When the date time field is applied to the column, the header row contents are being shown as ERROR. 
It is still possible to select the import button. When this is done a runtime error is displayed : java.lang.NumberFormatException: For input string: "ERRO" (full details below) 

### Steps to Reproduce

1.  Select a sample CSV file which includes a date/time field and has a header row which is the column titles
2.  Choose Destination - Analytic graph - do not select the "File has headers" option
3.  Observe in the preview that the column headings are present as the first line
4.  Apply the date/time to the date time column
5. Observe the column heading for the date/time has ERROR as expected
![image](https://user-images.githubusercontent.com/83679004/179640327-e9734a65-c0a2-4424-9097-3c94a10eae8c.png)

6. Complete the rest of the file mapping and select import > Run time error is displayed > 
7.  Repeat with another file to make sure this is repeatable > it is

**Expected behaviour:** The error field is ignored and the import completes with a message saying how many error rows were ignored

**Actual behaviour:** Run time error > I need to manually correct this error by turning on the option for file has headers (hence this is not a big issue)
**Reproduces how often:** 100%

### Additional Information

![image](https://user-images.githubusercontent.com/83679004/179639738-422ad07e-41bf-4ab4-9ef9-f859e4b7350e.png)

**Comment by Auriga2** [comment]
I now get `java.lang.IllegalArgumentException` exception when recreating this. Can you please check @spica198 
![image](https://github.com/constellation-app/constellation/assets/64826928/c13364b7-cd11-47dd-b34b-b922680ca124)

**Comment by Auriga2** [comment]
After getting this exception, user cannot proceed importing, it displays the successful message but doesn't draw any nodes, until constellation is closed and reopened.

**Comment by GammaVel** [comment]
Thank you @spica198 and @Auriga2 for figuring this one out.  I can confirm that my original issue has been addressed now, if I forget to tick : "File has headers" and add the date time mapping, the column heading is correctly reporting that it has been skippe, and I can view my graph. Thanks!
