### ISSUE TITLE
Layers Right-click Context Menu

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1750]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

When you use the right-click context menu on the graph. There is a menu option called "Layers" which can be used manually add and remove graph elements from layers. At the moment though, there is something wrong with the structure of that Layers option as rather than there being simply Add and Remove options, Remove is instead embedded in an additional Layers menu

![LayersContextMenu](https://user-images.githubusercontent.com/62311243/183335230-8f9b1f5e-8623-4ec9-80eb-01c80d245a77.png)

### Steps to Reproduce

1. Open a new Graph
2. Add a node to the graph
3. Right-click on the Node
4. Hover over the Layers option

**Expected behaviour:** Sub-menu includes "Add Selection to Layer" and "Remove Selection from Layer"

**Actual behaviour:** Sub-menu includes "Add Selection to Layer" and another "Layers" and that sub-menu includes "Remove Selection from Layer"

**Reproduces how often:** 100%

### Additional Information

Has apparently been an issue since v2.5

**Comment by Auriga2** [comment]
This looks like a bug in the `ContextMenuProvider` interface, if multiple items are returned in the `getMenuPath`. The below part seems broken.

![image](https://user-images.githubusercontent.com/64826928/229411547-f1f36dc4-2705-4d8f-a2e2-24463cd17cf3.png)


E.g. If the add and remove layers are added under "Blazes" which is already existing, the new items are added with 2 more "Blazes" under the existing "Blazes" item.
![image](https://user-images.githubusercontent.com/64826928/229410736-0795b178-d8cb-410e-9f61-e75b571f5df9.png)

**Comment by GammaVel** [comment]
Looking good, thanks @Auriga2  for the update, looking good now.
![image](https://user-images.githubusercontent.com/83679004/237015961-c0d38159-3f1b-4589-aafb-3b77701adc75.png)

Blazes are also looking good too.
