### ISSUE TITLE
Add HTML or Markdown support to notes in Notes View

### ISSUE THREAD

**Issue by sol695510** [constellation-app/constellation#1754]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Add support for HTML or Markdown to user generated notes in Notes View for more expressiveness.

### Additional Information

Example of the New Issue editor in GitHub, which has support for styling with Markdown:

![image](https://user-images.githubusercontent.com/58677774/184806062-3bda4459-94ef-4208-a906-db3bf9de4c7b.png)
![image](https://user-images.githubusercontent.com/58677774/184806159-6d06b2ee-f5f5-4695-9787-ea9c9718dee7.png)

**Comment by GammaVel** [comment]
Hi @altair1673, I was very keen to try this new functionality out. I have a graph that I made in a previous version of Constellation, when I option this in the latest nightly build I am getting a runtime error fairly consistently when I open the graph or I click on any of the buttons on the notes view. Here is what the run time error states:

![image](https://github.com/constellation-app/constellation/assets/83679004/48b03538-aef9-4c16-902b-7096bfe577cb)

It would be great if you could please take a look into this. Thanks!

**Comment by GammaVel** [comment]
Hi @altair1673, the previous error that I was seeing was to do with a graph made with one of the latest nightly builds, it is not happening with the released versions which is good. I am keen to get your thoughts on the below issues if possible please.

**Different font/size text between system notes and user notes**
I took another look at the mark down and the user notes have a different font and size compared to the system generated notes. Can you please look into this as it might be good if they were more consistent. Here is an example:
![image](https://github.com/constellation-app/constellation/assets/83679004/22eaf775-b453-40bc-aaab-98d6e083a0b5)

**Help**
If people don't know the mark down syntax it is going to be hard to know how it gets applied. It would be good if help could be updated to include information on how the markdown works in Constellation. 

Thanks!!

**Comment by GammaVel** [comment]
Hi @altair1673!  
Thanks very much for adding in the new help information. The is one issue, the escape characters have made it into the help and if you use the escape characters they don't actually work. Is there a way of ensuring these are not in the help as unless you know markdown, you will think these need to be included. 

![image](https://github.com/constellation-app/constellation/assets/83679004/29602c6d-9c1e-4b91-94f3-04532416d1da)

**Comment by GammaVel** [comment]
Thank you @altair1673 for making the changes!  It looks great now.
![image](https://github.com/constellation-app/constellation/assets/83679004/b3cffd1f-5c66-4463-b37b-1da53c9361ee)
