### ISSUE TITLE
Concurrent modification runtime error observed with RC 2.8 when saving a graph following data import

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1757]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The following concurrent modification runtime error has been observed with RC 2.8 when saving a new graph after it had been imported:
![image](https://user-images.githubusercontent.com/83679004/187350867-b4b82f5d-b581-476e-8af2-21595871e28a.png)

I went back to release 2.7 to see if the same thing happens there and it did not show up. 

### Steps to Reproduce

1. Download and run the latest release candidate 2.8
2. Perform normal graph operations, opening a few graphs
3. Perform a file import and save the graph - error observed

### Behaviour

* Try to include measurable metrics that can be aimed for (if applicable to the issue),
e.g. if it's a time issue then "should take 5 seconds or less to finish"
or if it's a workflow issue "should be accomplished in 2 or less clicks".

-->

**Expected behaviour:** No concurrent mod error

**Actual behaviour:**Random error that is not clearly reproducible

**Reproduces how often:** Unsure, random, doesn't appear to be very often

**Comment by GammaVel** [comment]
I saw this error again just now and this time I got the full error details when I took the snippet.

I got this after I had done a CSV import and then switched to XLS and did an import. I used Save as to save my new graph and I got the error. 

![image](https://user-images.githubusercontent.com/83679004/188041894-9855637a-f664-49d4-bacc-d59f35715df2.png)

**Comment by antares1470** [comment]
I've done an investigation on this and from what I can tell, the issue seems to be around the introduction of `RecentFiles.getUniqueRecentFiles()`. If I'm correct on that, this issue will have been around likely since v2.5

**Comment by GammaVel** [comment]
Thanks @antares1470 for that information and working out what the source of the error is.

**Comment by GammaVel** [comment]
Thanks @antares1470 for resolving this issue. I have tried this out with the latest nightly build and I am no longer seeing the error. Thank you :-)
