### ISSUE TITLE
Add a time-based filter for notes in Notes View

### ISSUE THREAD

**Issue by sol695510** [constellation-app/constellation#1761]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Add a filter to the filter dropdown in Notes View that allows the user to select a date time range and filter the available notes, showing only notes created within that range.

### Additional Information

N/A

**Comment by GammaVel** [comment]
Hello!  Thanks for adding in this handy filter. Would it be possible to make it the same as the date picker on the data access view?  Would be good to be consistent.
![image](https://user-images.githubusercontent.com/83679004/231335235-e79fe4d8-f8bd-4865-bdd8-137d1cc453ba.png)


Also, would it be possible for the help to be updated with this new filter information?

![image](https://user-images.githubusercontent.com/83679004/231335577-5fa7e8b4-b5f2-4a59-b56b-cb6518117e3b.png)

**Comment by Auriga2** [comment]
Just had a quick look and wondering whether we can have a common date time picker utility instead of adding the same functionality in multiple places, like DAV, Find view, and now notes view?

**Comment by GammaVel** [comment]
Thanks for making these changes @altair1673. They look great to me and it is especially good to see you the help also got the extra information added. Thanks!
