### ISSUE TITLE
Optimise notes display in Notes View

### ISSUE THREAD

**Issue by sol695510** [constellation-app/constellation#1762]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Changes to be implemented better display notes in the Notes View:

- Move ‘new note’ UI to a pop-up to free space to view more notes.

- Move ‘edit’ and ‘remove’ buttons of each note to the top as depending on the size of the note, having them centred vertically can be difficult for usability.

- Add a 'show more / show less' toggle when the information on a note exceeds a defined limit to reduce how information on notes are displayed, as to reduce size of notes and increase number of notes viewable.

### Additional Information

N/A

**Comment by GammaVel** [comment]
Thank you @altair1673 for improving the notes view here, this looks great. I like how the Show More and Show less is working.
