### ISSUE TITLE
Wrong graph can have it's view reset (zoom level changed) upon plugin completion.

### ISSUE THREAD

**Issue by OrionsGuardian** [constellation-app/constellation#1764]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Issue with long running plugins where the user can potentially switch to a different graph while the plugin is running, then when the plugin completes, the currently active graph is suddenly zoomed (has it's view reset) instead of the graph for which the plugin was running.

**Expected behaviour:** \[What you expect to happen\]

When a plugin completes, the currently active graph should only have it's view reset if its the graph for which the plugin was running.

**Actual behaviour:** \[What actually happens\]

The currently active graph has it's view reset to a level which would be appropriate on the graph for which the plugin was running.

**Reproduces how often:** \[What percentage of the time does it reproduce?\]

Requires a long running plugin where there is time for the user to select a different graph while the plugin is running.
In such cases it is 100% reproduceable.

### Additional Information

The issue applies to any plugin which has a final step of resetting the view, but does not provide a link to the related graph for which the plugin is running. In such cases, if there is time while the plugin is running for the user to select a different graph, then the currently active graph will be the one that has it's view reset.

**Comment by Astroboy2022** [comment]
I have taken a look at this, making use of the scripting view. I noticed that the behaviour matches the expected behaviour now. Thank you @OrionsGuardian
