### ISSUE TITLE
Using Jupyter notebooks to import data - improve case sensitivity

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1767]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Currently if you use Using Jupyter notebooks to import data you need to have the entities in exactly the right case or they will not get recognised. For example - person has to be "Person" and not "person" or "PERSON". If it is in uppercase it won't be recognised.  The issue arises if you are using another program to create the data it could create it as PERSON which would then need to be manually updated before importing.  

### Steps to Reproduce

1.  Refer to description above for details on what is happening here

**Expected behaviour:** When using Juypter notebooks Constellation automatically recognises entity keywords regardless of what casing the letters have. Mixed case, lower case, uppercase should all be recognised. 

**Actual behaviour:**When creating the data for import you need to set it up to match Upperletter followed by lower letters. 

**Reproduces how often:** 100%
### Additional Information

NA

**Comment by HolandCrick** [comment]
Thanks to Guilty-Spark-343; altair1673 and antares1470 for raising and resolving the importing case sensitive data using Juypiter Note Book. It works well now as expected. 

![image](https://github.com/constellation-app/constellation/assets/157770877/7f738f25-38b7-41db-8286-4635a4763a16)
![image](https://github.com/constellation-app/constellation/assets/157770877/736342e2-3267-46c1-8639-dcad29dc8c34)
![image](https://github.com/constellation-app/constellation/assets/157770877/1839750b-97a4-4e22-979d-61952015e10e)
![image](https://github.com/constellation-app/constellation/assets/157770877/225d18ff-fffe-470f-803b-5122bcfbb6d7)
