### ISSUE TITLE
Attribute Editor not Updating when in a Minimized Window Group

### ISSUE THREAD

**Issue by altair1673** [constellation-app/constellation#1773]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

When the Attribute editor is minimized, re-opened and not docked (minimized window group), any new attributes are not added in when adding from the "+" options menu.

The attribute editor doesn't reflect what is currently selected on the graph when the editor is in this minimized window group. However if you close the attribute editor and re-open it docked then any added attributes appear.

Right-clicking a graph element and selecting "show in attribute editor" opens editor in the minimized window group and the element is not selected.

### Steps to Reproduce

1.  Select element on graph

2.  Open attribute editor in a minimized window group

3.  Add new attribute to graph through the "+" menu.

4.  See that editor is not updated and option to add attribute has disappeared.

5.  Completely close the attribute editor and re-open it docked to see the new attributes.

**Expected behaviour:** The attribute editor works the same as if it was docked.

**Actual behaviour:** The attribute editor has no working functionality when in a minimized window group.

**Reproduces how often:** 100%

### Additional Information

Any additional information, configuration or data that might be
necessary to reproduce the issue.

**Comment by Delphinus8821** [comment]
As shown below the attribute editor does not function when in a minimized window group. 
Trying to add a new attribute:
![attribute_not_adding](https://user-images.githubusercontent.com/73083035/196330730-d1a93603-39d0-430d-a4f4-82a9de8bcaf2.gif)

Right-click 'Show in Attribute Editor' not working:
![attribute_not_showing](https://user-images.githubusercontent.com/73083035/196330748-cdf180a7-c0eb-40dd-9e91-0123896994b4.gif)

**Comment by GammaVel** [comment]
Thank you @spica198 for resolving this issue.  I tried this out and it looked great.  Good to see this one fixed.
