### ISSUE TITLE
Null Pointer Exception while using new Advanced Find functionality

### ISSUE THREAD

**Issue by OrionsGuardian** [constellation-app/constellation#1786]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Null pointer being reported while using the new Advanced Find functionality.

### Steps to Reproduce

Create at least 3 separate graphs with at least 3 nodes in each graph.
Open the new Find dialog (Ctrl-B)
Go to the Advanced Find tab.
Set up a search for Identifiers containing "1".
Tick the box to "Search all open graphs"
Click on Find Next and cycle through the results once.
Change the search to find Labels containing "2".
Click on Find Next and cycle through the results once.
Change the search back to finding Identifiers containing "1".
Click on Find Next and cycle through the results.

At some point while repeating these steps, a null pointer exception may occur:

> java.lang.NullPointerException
>  	at au.gov.asd.tac.constellation.views.attributeeditor.AttributeReader.populateValues(AttributeReader.java:271)
>  	at au.gov.asd.tac.constellation.views.attributeeditor.AttributeReader.refreshAttributes(AttributeReader.java:131)
>  	at au.gov.asd.tac.constellation.views.attributeeditor.AttributeReader.refreshAttributes(AttributeReader.java:90)
>  	at au.gov.asd.tac.constellation.views.attributeeditor.AttributeEditorTopComponent.lambda$new$0(AttributeEditorTopComponent.java:133)
>  [catch] at java.base/java.lang.Thread.run(Thread.java:829)
> 

**Expected behaviour:** \[What you expect to happen\]

Null pointers should be caught and handled cleanly.

**Actual behaviour:** \[What actually happens\]

Null pointer is being reported to user.

**Reproduces how often:** \[What percentage of the time does it reproduce?\]

Not often. Happens inconsistently.

**Comment by GammaVel** [comment]
Thank you @spica198 for resolving this issue. This was an interesting edge case. I have tried the steps out that are listed in the scenario and I have not seen the run time error. Looks good!
