### ISSUE TITLE
The Date and DateTime format in the Attribute fields

### ISSUE THREAD

**Issue by StoltHD** [constellation-app/constellation#179]
Is it somehow possible to change the Date format and/or the DateTime format in Constellation?

I really want to use the ISO standard format of YYYY-MM-DD, but can't seem to find any place to change from the default DD.MM.YYYY

This is on a Windows PC and I assume it use the system Date format, but it would be great if there was a way to change it in the software...?

**Comment by arcturus2** [comment]
Hey @StoltHD can I double check whether you are referring to importing from a delimited file or something else?

If you're referring to the delimited importer then you can right click on the attribute and set a date formatter like so:

![image](https://user-images.githubusercontent.com/39325530/71216054-76a08600-230d-11ea-819a-bb46533de815.png)

**Comment by cygnus-x-1** [comment]
Both 'date' and 'datetime' attribute types in Constellation store underlying data as longs, and represent it through UIs in the ISO standard format. If you're not seeing this somewhere in the application (other than importers, as @arcturus2 is talking about above) then that is a bug and we'd like to know exactly how to reproduce it.

**Comment by StoltHD** [comment]
Its not in the importer, but when I add a Custom attrbute on i.e. a Node.
When I set that field as a Date Type and then try to write the date in
YYYY-MM-DD format it doesn't take that and set the todays date in the short
format of my computers input short date format as DD.MM.YYYY...

I always use the YYYY-MM-DD format in application field and file name, both
because of the sort order in Windows, but also because of the easier way of
reading it in a list og table... while in Windows and day to day calendars
I would like to use the DD MM YYYY format...

EDIT:
I did some more testing    just now, and its not in the field it selaf the
problem is, that field do actually show the format, but it is in the
calender picker/edit dialog field the problem is...

If I enter the date 1875-12-19 and click save, it will not take the format
in the "picker" and return todays date in the written format i.e.
2019-12-20. But if I type in the same date 19.12.1875 in the
calender/picker dialog and I earlier had a date in the YY-MM-DD format in
the attribute field, it will give me the correct input date in the
YYYY-MM-DD format... if I then open the Edit dialog again, the format there
is shown as DD.MM.YYYY

So I think it is a bug in the date edit dialog (where you get the
calendar)...

Sorry that I didn't tripple check this before I posted...

It's easy to reproduce...
1. Add a Custom Atrribute to Nodes with type Date
2. Create a Node, select the Node and click on the Edit button for the Date
field
3. Then type in a date other than "todays date" in the date field in the
format YYY-MM-DD, click OK, It should now show "Todays date" in the format
YYYY-MM-DD.
4. Click Edit again and you should see the date in the format DD.MM.YYYY,
change the Year in the Edit dialog to i.e. 1875 and click ok, you should
now find that the date in the attribute field has changed to 1875-MM-DD.

Best regards and happy Holidays

fre. 20. des. 2019 kl. 04:00 skrev cygnus-x-1 <notifications@github.com>:

**Comment by arcturus2** [comment]
Thank you for the details and reproducer. Happy holidays to you too!

**Comment by cygnus-x-1** [comment]
It looks like the default behaviour of the JavaFX _DatePicker_ is to accept strings in the format DD/MM/YYYY. This appears to be customisable and so the behaviour could be changed. 

Perhaps a more pressing issue is that the DatePicker has no validation in place. This means that I can enter a date in ISO format (using the Attribute Editor) and hit okay and everything looks fine, except that the attribute value will either not change from its previous value or be set to today's date if its previous value was null.

**Comment by StoltHD** [comment]
cygnus-x-1,

Yes, that's part of the same problem... bettet explained...

fre. 20. des. 2019 kl. 23:54 skrev cygnus-x-1 <notifications@github.com>:
