### ISSUE TITLE
CSV File import - Runtime error if there is an error with the Date and "Skip Invalid rows" is not ticked

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1795]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Constellation has the option now to "Skip Invalid Rows" when importing a file that contains errors. If I don't tick this option and the CSV file contains an error with the date field, a runtime error message is displayed (shown in the screenshot section). This is 100% reproducible. It would be good if a more user friendly error message was presented instead of the Runtime error message to help me know how to resolve this issue.  

I can select "Skip Invalid Rows" to get around this error but it wasn't immediately apparent to me to do this. 
This is more of an issue when the error is outside of the 100 preview rows as I do not know there is an error present until I do the import. 

### Steps to Reproduce

1.  Set up a file that has an error on a date field that is outside of the first 100 rows
2.  Use the Import from file functionality and select file
3. Perform the field mapping, including the date field
4. Click import > the run time error is shown
5. Click ignore invalid rows > the runtime error is not shown, and the import completes as expected

### Behaviour

**Expected behaviour:** A message displays saying "Unable to complete import due to error with data. The file can be imported if you select Ignore invalid rows "

**Actual behaviour:** Run time error:
![image](https://user-images.githubusercontent.com/83679004/211699113-03fff940-1d23-403a-8c6d-6230b402156f.png)

**Reproduces how often:** 100%

### Additional Information

This issue relates to https://github.com/constellation-app/constellation/issues/1449

**Comment by Auriga2** [comment]
It'd be nice to word the message to `.........if you select the Ignore invalid rows checkbox next to the Import button` or similar, specially for new users to locate this check box. I initially checked the options at the top.

**Comment by GammaVel** [comment]
Thanks @Auriga2 and @spica198 for looking into this issue. I tried this out again and there is no run time exception being shown which is perfect. I noticed a small typo that would be good to fix, so I made a new issue for that.
