### ISSUE TITLE
Minor wording update suggested to File Import message for rows being skipped

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1796]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

After importing a file a message pops up to let you know how many rows were imported. This is super useful. The message currently has "Skipped rows <0/a number> due to import error. 
At the moment it looks like this could be referring to the row number that was skipped or the number of rows skipped.
![image](https://user-images.githubusercontent.com/83679004/211700947-22385e04-c4df-48e7-886a-3e464807085d.png)

As an enhancement it would be better if this was: 
Skipped <0/a number> rows due to import error. 

OR
Skipped rows: <0/a number> due to import error.  (with a colon)

OR 
Rows skipped: <0/a number> due to import error.  (with a colon and reorder of wording)

### Steps to Reproduce

1.  Import a file that contains an error in the date column, but most of the dates are in correct format
2. Click "Skip invalid rows"
3. Import > Observe message that is displayed

**Expected behaviour:** Small wording change suggested

**Actual behaviour:** NA

**Reproduces how often:** 100%
### Additional Information

![image](https://user-images.githubusercontent.com/83679004/211701133-935e92f2-b465-4e09-968d-965d28b6f319.png)

**Comment by Auriga2** [comment]
It'd be nice if we could word `row or rows` instead of `row(s)`  similar to `file or files` in the error message, as that's a simple check in the code.

![image](https://github.com/constellation-app/constellation/assets/64826928/22efb455-0d72-4c4a-a3df-f2dda6bed0bd)

![image](https://github.com/constellation-app/constellation/assets/64826928/b7ddf62c-783c-40b1-8d87-a8b5bb9f21ae)

**Comment by GammaVel** [comment]
Thanks for fixing the wording here, looks great!

Here is the new text:
![image](https://github.com/constellation-app/constellation/assets/83679004/9919ec15-3962-4dcf-9740-25581d352ed0)

The wording also looks really good when there is 1 row with an error;
![image](https://github.com/constellation-app/constellation/assets/83679004/23af033c-b742-4d50-996d-aa77155bfc44)

or 0 rows:
![image](https://github.com/constellation-app/constellation/assets/83679004/3da21dff-ddb2-4c52-be3c-0bd6a6b3f747)
