### ISSUE TITLE
Prevent repeated Exception Dialog windows from being displayed.

### ISSUE THREAD

**Issue by OrionsGuardian** [constellation-app/constellation#1806]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

If an Exception occurs and it is repeated multiple times, then there will be a popup for each and every repeated occurrence.

![image](https://user-images.githubusercontent.com/104604488/219194781-8c2908be-d794-45ba-857f-ba753499745d.png)

In the above screenshot, a Null Pointer Exception was thrown, and a popup is shown to the user. 
Click cancel, and the same popup is shown again to the user. 
Click cancel again, and the same popup shows up again. 
Look at the log file and see that the same exception has occurred 1971 times, and it appears that each one will have a popup shown.

This is a terrible user experience.

There are a few ways we can address this issue.
1. We could create a side panel to record exceptions, instead of popping them up and requiring user interaction.
2. The popup dialog could include another button/check box to suppress any more exceptions containing the same message.
     (note: this would lose information on how many exceptions actually happened)

Probably a combination of both would be best.
Display a popup on the first exception and record it in the side panel.
Then prevent any more popups with the same error, and only record them in the side panel (incrementing a counter of occurrences for a repeated message)
 

### Steps to Reproduce

Any process which can generate repeated errors/exceptions.
In the screenshot above, it was running Analytics on a large graph.
Generally, any plugin that can generate errors while iterating through all nodes of the graph can lead to the same issue.

**Expected behaviour:** \[What you expect to happen\]
One dialog box to inform the user that an exception occurred.

**Actual behaviour:** \[What actually happens\]
Thousands of dialog boxes can be displayed to inform the user of the same error that occurred multiple times.

**Reproduces how often:** \[What percentage of the time does it reproduce?\]

Whenever a process runs over multiple graph nodes and the same error occurs while processing each node.

### Additional Information

This issue has surfaced when the threshold level for displaying exceptions was changed to make it more obvious to the user that an exception occurred.
Ref: #50

**Comment by GammaVel** [comment]
Thank you @OrionsGuardian for making this improvement, and thanks for including a link to your testing script that you used to trigger the exceptions. It is very handing that Constellation comes with a scripting view and it is also handy that you included a way of triggering the exceptions.
