### ISSUE TITLE
constellation_client.py pandas read_json data type error

### ISSUE THREAD

**Issue by rozie1337** [constellation-app/constellation#1816]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Hello, FYI constellation_client.py `Constellation.get_dataframe` encounters an error (_Expected file path name or file-like object, got type ''_) on the call to `pd.read_json`, due to the 'data' argument having a type of <class 'bytes'> instead of being <class 'str'>.

This may be related to a change in newer versions of Python requests or Pandas.

This same issue also exists in the `Constellation.get_graph_attributes -> pd.read_json` call.

### Steps to Reproduce

1. Environment: Python 3.10.5, pandas 1.5.3, requests 2.28.1

2.  Follow 'Constellaton-Training (Analyst training) Exercise 10 - Network Analysis With Python' to Part 2 (Getting Data from CONSTELLATION) -> https://github.com/constellation-app/constellation-training/blob/master/Analyst%20Training/Exercise%2010%20-%20Network%20Analysis%20With%20Python/notebooks_and_constellation.ipynb

3.  Running `df = cc.get_dataframe()` will hit the error. 

**Expected behaviour:** Pandas correctly parsing the data variable into a dataframe.

**Actual behaviour:** Pandas throws an error due to the 'data' variable being the wrong type.

**Reproduces how often:** 100%

### Additional Information
Can be fixed by calling something like `<variable>.decode("utf-8")` before the call to `pd.read_json` if it is type `bytes`, or by updating the requests call to ensure it returns a string.

**Comment by HolandCrick** [comment]
Hello @Guilty-Spark-343 for addressing the _Json data type error. It works for .get_dataframe but still need to address the  .get_graph_attributes(). The graph attribute section through the error:

![image](https://github.com/constellation-app/constellation/assets/157770877/f6333e6c-dcdb-467b-8fe9-610b669d18b7)

new ticket #2004
