### ISSUE TITLE
Arithmetic Exception in Conversation View

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1824]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Arithmetic Exception occurring in the Conversation View

```
java.lang.ArithmeticException: / by zero
at au.gov.asd.tac.constellation.views.conversationview.ConversationBox.lambda$new$9(ConversationBox.java:249)
```

### Steps to Reproduce

1. Open up a graph with content viewable in the Conversation View
2. In the Conversation View, write a search term with no results
3. Press Enter

**Expected behaviour:** No exception

**Actual behaviour:** Exception

**Reproduces how often:** 100%

### Additional Information

Issue appears to be due to the calculation `% foundCount`  with no prior check for the value of `foundCount` (which if 0 will throw the exception)

**Comment by GammaVel** [comment]
Thanks for fixing up this error @Auriga2. It is working great now!
