### ISSUE TITLE
`Remember Open/Save Location` constellation preference use

### ISSUE THREAD

**Issue by Auriga2** [constellation-app/constellation#1825]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
Looks like the previous implementation of the `Remember Open/Save Location` preference is changed with recent changes.

In the v2.9 the preference has no effect. (Specially when the option is unset, which is supposed to open the user's home directory.) But the last saved location and open location are remembered separately, but only within the same file chooser.
E.g.: if a graph is opened from the welcome page that location is not remembered when ctrl+O opening. 

Need to discuss which behavior is required here.

In any case can we remove the Constellation preference, as we can't think of a user case for this preference unchecked?

### Steps to Reproduce

As described above
  

**Expected behaviour:** need to discuss

**Actual behaviour:** As described above

**Reproduces how often:** 100%

### Additional Information
Applies to https://github.com/constellation-app/constellation/issues/1721 as well
Probably can be applied in other file choosers such as `Add Driver` in `Import from Database` -> `Manage connections`

**Comment by GammaVel** [comment]
Thanks for investigating this issue and applying a fix. It is great that the file location is being retained consistently. A couple of small UI things observed, will raise new issues for these. One bug also noticed with copying and pasting #1956.
