### ISSUE TITLE
Plugins are being auto-selected in the Data Access View

### ISSUE THREAD

**Issue by OrionsGuardian** [constellation-app/constellation#1829]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The following 2 plugins in the Data Access View are being auto-selected when a graph is either opened or closed:
* Extract Words From Text
* Split Nodes based on Identifier

Note: this only occurs once the plugins have been expanded in the Data Access View

\[Description of the issue\]

### Steps to Reproduce

1.  Open the Data Access View and **expand** the two plugins: 
    * Extract Words From Text 
    * Split Nodes based on Identifier

2.  Open a New graph and notice that those two plugins become selected.

3. De-select the plugins, then close the graph. Notice the plugins are selected again.

**Expected behaviour:** \[What you expect to happen\]
Plugins should not be automatically selected when graphs are opened or closed.

**Actual behaviour:** \[What actually happens\]
Specific plugins are being selected on open/close of graphs.

**Reproduces how often:** \[What percentage of the time does it reproduce?\]
100% for the identified plugins.

**Comment by GammaVel** [comment]
Thanks @OrionsGuardian for fixing this bug that crept in. I saw this happening with v2.9 and it has been fixed with the latest nightly build for v2.10. Thanks again!
