### ISSUE TITLE
Inline changes made to notes aren't recognised as changes to be saved

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1835]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Once a note has been created in the Notes View, you have the option to edit the note (text, colour, etc). When you make these edits though, these aren't recognised as changes to the file and so you can't save the change to the note and when you close the graph and open it again, the note will be back to the version you had when the graph was last saved.

The only way you can save the edit is by either making a change on the graph to trigger having unsaved changes, or by adding a new note.

### Steps to Reproduce

1. Open a graph with at least one user note (alternatively create a graph, add a note and then save the graph)
2. With the Notes View open, edit one of the user notes in some way (change the text, change the colour) and press ok
3. Note that the graph doesn't highlight as having unsaved changes so Ctrl-S won't do anything
4. Close the graph and re-open it

**Expected behaviour:** Changes made to note should be visible

**Actual behaviour:** Changes made to note are lost

**Reproduces how often:** 100%

**Comment by GammaVel** [comment]
Thank you @altair1673 for completing these changes, they are working extremely well. When I edit a note and then save it the graph is showing up as unsaved and warns me when I go to close it. Works with notes for the graph and notes for a selection.
