### ISSUE TITLE
Remove Old Find View

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1836]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

I think the new Find View (currently sitting in Experimental) is sitting in a good enough space that it can finally replace the old one. Doing this will require doing the following:
1) Deleting the code relating specifically to the old Find View (there may be classes or packages used by both the old and new, in which case we want to keep those parts)
2) Changing the shortcut of the new Find View to match what the old one use to be (Magnifying class icon, Ctrl-F, label is "Find...")
3) Migrate the code sitting in "find2", to simply "find" (as there is no reason for it to be find2 any longer)

### Additional Information

In doing this, we're likely to encounter a similar thing to what happened with Table View and Data Access View whereby trying to open the view will throw an exception being unable to find the top component (which happens if you are using an instance where you have opened the old find previously). Luckily though, we now have the Reset script that comes with all the version downloads which can be used to clear the cache and remove the issue.

**Comment by GammaVel** [comment]
It is great to see the updated Find view included in the normal menu now. Thanks @antares1470 and @capricornunicorn123 . I actually found I did not need to use the reset script at all, and it just worked.
