### ISSUE TITLE
Recent screenshots are not consistently displaying on the Welcome page

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1838]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

I have been using the latest nightly build for Release 2.9 and I have noticed that the Recent graphs are not consistently displaying. I went back to Release 2.8 and there were no issues there, I had all of my recent graphs. 

### Steps to Reproduce

1.  Download the latest nightly build for Windows, available under Actions
2.  Unzip and run the constellation64.bat
3.  Observe that none of my recent files are present
4. Check Recent Files under the Files option > my recent files are being shown there

### Behaviour

**Expected behaviour:** 
The Welcome page shows the recent file screenshots

**Actual behaviour:** I don't see my recent file screenshots

**Reproduces how often:** I have seen this inconsistent behaviour before but seems to be more noticeable now

### Additional Information

Not sure if this is relevant - but when I opened a recent graph and saved it, closed Constellation and reopened it, all of the screenshots were present.  When I opened another graph without saving it, and closed Constellation again, all of the recent screenshots were missing

**Comment by GammaVel** [comment]
### Steps to Reproduce

1.  Download the latest nightly build for Windows, available under Actions
2.  Unzip and run the constellation64.bat
3.  Observe that none of my recent files are present
4. Check Recent Files under the Files option > my recent files are being shown there
<!--

### Behaviour

![image](https://github.com/constellation-app/constellation/assets/83679004/6f4db136-eac9-448b-b6e7-51c220ed8b6e)

**Expected behaviour:** 
The Welcome page shows the recent file screenshots

**Actual behaviour:** I don't see my recent file screenshots

**Reproduces how often:** I have seen this inconsistent behaviour before but seems to be more noticeable now

### Additional Information

Not sure if this is relevant - but when I opened a recent graph and saved it, closed Constellation and reopened it, all of the screenshots were present.  When I opened another graph without saving it, and closed Constellation again, all of the recent screenshots were missing

**Comment by OrionsGuardian** [comment]
I've managed to replicate this in my dev environment with lots of trace statements to see the program flow.
It only occurs roughly once every 20 relaunches of constellation, but that can easily vary between systems.
The problem is a timing issue where the WelcomeViewPane tries to read the Recent Files list before the RecentFiles class has been initialised.
```
WelcomeViewPane.recentGraphsSetup()
    final List<HistoryItem> fileDetails = RecentFiles.getUniqueRecentFiles();
```

The `fileDetails` variable will be empty if it is set before the `RecentFiles.init()` function has completed.

**Comment by GammaVel** [comment]
Thank you @OrionsGuardian for figuring this one out. This has always been a bit problematic and it is working well with the latest nightly build (v2.10.0). Thanks for figuring this out.

**Comment by GammaVel** [comment]
Actually!  I just tried again opening and closing Constellation a few more times and the issue came back!  It looks like it has improved but there still might be a problem. I will reopen this issue if it becomes more of a problem as it has definitely improved.

**Comment by OrionsGuardian** [comment]
The changes were merged in this morning, so last night's build won't
actually have the new code.
From tonight's build onwards it should have the new code in place.
