### ISSUE TITLE
Workflow Plugins throwing exceptions

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1844]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

A recent change was made to create a global thread pool and a number of processes were changed to use this thread pool instead of creating their own. Workflow Query Plugins are one such place which was moved to using the global thread pool. The problem here though is that in their current implementation, workflow query plugins shutdown the thread pool after it has finished using it (previously it had its own thread pool it was creating and shutting down). This means after a workflow query plugin is run, any subsequent process attempting to execute on that thread pool is throwing a `java.util.concurrent.RejectedExecutionException`

### Steps to Reproduce

1. Open a graph
2. Open Data Access View and select Test Parameters (Batched)
3. Run the plugin
4. Run it again

**Expected behaviour:** Plugin runs the 2nd time as intended

**Actual behaviour:** `RejectedExecutionException` thrown

**Reproduces how often:** 100%

### Additional Information

There are other processes that you could run after running Test Parameters (Batched) the first time but simply running the plugin again a 2nd time is the easiest one to try for reproducing purposes

**Comment by GammaVel** [comment]
Hi @antares1470, thank you for resolving this issue. I tried this out and I don't get any errors when running the Test Parameters (Bacthed) multiple times. I also tried out the Test Parameters and that looked good too.  Thanks!
