### ISSUE TITLE
Notes View - Changes lost if editing a note when an Autosave occurs on the graph.

### ISSUE THREAD

**Issue by OrionsGuardian** [constellation-app/constellation#1848]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

While editing a Note, an Autosave occurred on the graph and all changes were lost.
The screen refreshed with the data reverted back to how it was before editing.

The same issue also occurs when switching between two graphs when there is a note in edit mode on one graph ... all changes are lost.

**Expected behaviour:** 
When an Autosave occurs, it should not reload/recreate the Notes view screen.

**Actual behaviour:**
When an Autosave occurs, it is currently recreating the Notes View panel with the data reverted to the point prior to editing.

**Reproduces how often:**
100%

**Comment by antares1470** [comment]
can confirm this is also occurring on v2.9

**Comment by GammaVel** [comment]
Thank you @altair1673, this is looking really good now. I didn't see any of my notes disappearing on autosave.
