### ISSUE TITLE
Notes View tags filter (Select tag(s)) not working

### ISSUE THREAD

**Issue by Auriga2** [constellation-app/constellation#1854]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
Notes of a plugin that doesn't have any of the selected tags should be filtered out. It's not filtering properly as in the example gif attached.
![notes view tags filter2](https://github.com/constellation-app/constellation/assets/64826928/a20c1fef-6ee4-475c-ba3a-7da298466b38)

### Steps to Reproduce

1. Open a graph and Notes View. Perform some activities on the graph such as select a node, delete it 

2. Select Auto notes filter and see notes appear for those activities

3.  Select/Deselect tags under the `Select tag(s)` filter and see it is not always displaying the notes with matching tags and also it's not hiding the matching notes when tags are unchecked.

**Expected behaviour:** Tags filter should only display the notes related to the checked tags.

**Actual behaviour:** Tags filter is not always displaying the matching notes when tags are checked. And it's not hiding the matching notes when tags are unchecked.

**Reproduces how often:** 100%

**Comment by GammaVel** [comment]
Thank you @Auriga2 for detecting this issue and getting this working once more. It is working very well now on the graphs that I have tried this with.
