### ISSUE TITLE
Ensure all Data Access Plugins report results

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1858]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

After executing and viewing Data Access plugins in the Plugin Reporter, some plugins display the results of the plugin (e.g. Remove Nodes will highlight how many nodes were removed). Some plugins though merely state that they ran successfully (e.g. Split Nodes). It would be good if all the Data Access Plugins in the latter category could have their results displayed to help users better understand what actually happened when the plugin ran:
- how many nodes were split into how many other nodes?
- how many nodes were imported?
- how many attributes were removed?
- etc

![pluginReporterCompletionStatus](https://github.com/constellation-app/constellation/assets/62311243/68b99bc6-230e-40f9-976f-1ed69e75897c)

### Steps to Reproduce

1. Create a graph or open an existing graph
2. Run Split Nodes on the graph
3. Run Remove Nodes on the graph
4. Look at the Plugin Reporter

**Expected behaviour:** Data Access Plugin should all provide detail on the result of the execution (e.g. like Remove Nodes)

**Actual behaviour:** Some plugins merely state that they're finished (e.g. Split Nodes)

**Reproduces how often:** 100% (for plugins that don't have it)

### Additional Information

This is achieved in the code through the the `PluginInteraction` object, namely the `interaction.setProgress()` function. This should be added in all data access plugins

**Comment by antares1470** [comment]
Probably just requires work done for plugins in constellation-adaptors

**Comment by GammaVel** [comment]
Hi @capricornunicorn123 , the improvements you have made here are fantastic!  They work really well and it greatly enhances the value of the plugin reporter. I have been trying these out on a whole range of different graphs and with various plugins and it is working really well.  I had a good read of your MR request and was impressed with the level of detail and the code refactoring that you provided. Maybe a blog post about these would be good in the new release?

Here are some of the improvements that I really liked, the new progress bar:
![image](https://github.com/constellation-app/constellation/assets/83679004/9ccf2292-62db-4a25-b7f9-64c447b5e504)

The extra detail on the spilt nodes:
![image](https://github.com/constellation-app/constellation/assets/83679004/de300714-47bb-4a8f-bc83-b2fc9f452c24)
