### ISSUE TITLE
Opening items from recent searches will fail after closing and re opening constellation

### ISSUE THREAD

**Issue by formalhaut69** [constellation-app/constellation#186]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
Opening an item from recent searches will fail after re opening constellation. 

### Steps to Reproduce

1. Search for something in the search bar (that isn't already in the recent searches) and open it. 
2. Close and then re open constellation
3. Search for and then re open the item from the recent searches section 

**Expected behaviour:** 
The item should load and function correctly 

**Actual behaviour:** 
A window appears stating the Recent Quick Search Item was not found and the item does not load.

**Reproduces how often:** 
100%

### Additional Information

The window that appears:
![image](https://user-images.githubusercontent.com/58677762/71796638-e1d2b200-309a-11ea-8949-ee8000dfe629.png)

**Comment by formalhaut69** [comment]
It seems that this issue doesn't occur if the item was already open when constellation is re opened, even if the item is first closed before selecting it in the recent searches. The issue doesn't seem to occur if you leave constellation open for some time.

**Comment by arcturus2** [comment]
Tested this in v2 and confirmed this is still an issue.

**Comment by formalhaut69** [comment]
I remember spending a bit of time looking into this issue a while back. The issue appears to be right on the border of our implementation and Netbeans' quick search libraries. So not sure if its an issue with their libraries being slow to load our content or a bug with our implementation.

**Comment by GammaVel** [comment]
Confirmed this issue still happening in v2.3. This was tested by searching for an item on help (e.g. histogram) and Whats New and viewing the content, checking the item was shown in the recent searches and then closing Constellation. When Constellation was reopened and I clicked on the item from quick search, the same message was displayed (Recent Quick Search Item not found).

**Comment by GammaVel** [comment]
It is great to see this working!  I have tried this out and the recent search item can be found now after closing and reopening Constellation. Thanks @OrionsGuardian as this was a tricky problem reading back though the history.
