### ISSUE TITLE
Rename star graphs from client

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1860]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

It would be nice to be able to specify or change Constellation graph title names within scripts using the client to improve efficiency when using something Jupyter Notebooks to generate multiple Constellation graphs

### Steps to Reproduce

1.  \[First Step\]

2.  \[Second Step\]

3.  \[and so on…\]

**Expected behaviour:** Be able to rename from script

**Actual behaviour:** Have to rename afterwards via normal means (e.g. File explorer)

**Reproduces how often:** 100%

**Comment by Auriga2** [comment]
@antares1470 Jupyter notebook uses new_graph end point to create a new graph. We can add an optional parameter to specify the graph name there when creating the graph. In absence of that, it'll be the current behavior- generate the graph with the default name `analytic graph1` etc.

Other than that do we need a separate endpoint to rename a graph? If so which parameters would the user specify :

- graph ID? 
- The fully qualified path of the .star file? 
- graph name/The default name `analytic graph1` etc.? 
- Use the current active graph?

**Comment by HolandCrick** [comment]
@Auriga2 Thanks for adding the enhancement to change Constellation graph title names within using Jupyter scripts. It works as expected. 

![image](https://github.com/constellation-app/constellation/assets/157770877/632221a8-aa05-470b-ba4d-a48424c18928)
