### ISSUE TITLE
Selecting Cluster within the Hierarchical Clusters Tool with an empty graph causes an exception

### ISSUE THREAD

**Issue by formalhaut69** [constellation-app/constellation#187]
### Prerequisites
[SupportPackage-klewis47-2020-01-07-09-14-05.zip](https://github.com/constellation-app/constellation/files/4028099/SupportPackage-klewis47-2020-01-07-09-14-05.zip)
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
Clicking on the cluster button in the Hierarchical Clusters tool will raise an Arithmetic Exception. 

### Steps to Reproduce

1. Make a new graph
2. Click Tools -> Clusters -> Hierarchical
3. Click on Cluster

**Expected behaviour:** 

**Actual behaviour:** 
An Arithmetic Exception is raised.

**Reproduces how often:**
100%

### Additional Information
![image](https://user-images.githubusercontent.com/58677762/71854323-a92fe880-312d-11ea-8246-636c2cc19f4d.png)

**Comment by aldebaran30701** [comment]
As shown, the error points to  Line 89 This divides by 0. https://github.com/constellation-app/constellation/blob/c968184e866a76049d50df69b27b6304f7b739b5/CoreAlgorithms/src/au/gov/asd/tac/constellation/algorithms/clustering/hierarchical/NestedHierarchicalDisplayPanel.java#L83-L84
Shown below is the portion of code that evaluates to 0. 
https://github.com/constellation-app/constellation/blob/c968184e866a76049d50df69b27b6304f7b739b5/CoreAlgorithms/src/au/gov/asd/tac/constellation/algorithms/clustering/hierarchical/NestedHierarchicalDisplayPanel.java#L66-L69
Line 69 upon execution has state.steps = -1. Which evaluates to the else condition. This results in stepLimit being set to 0.
The divide by 0 exception is then raised.

Full code below:
https://github.com/constellation-app/constellation/blob/c968184e866a76049d50df69b27b6304f7b739b5/CoreAlgorithms/src/au/gov/asd/tac/constellation/algorithms/clustering/hierarchical/NestedHierarchicalDisplayPanel.java#L66-L93

I have not dug deep into the issue to provide a fix, let alone wrapping my head around what the code controls.
Feel free to suggest any ideas
