### ISSUE TITLE
NullPointerException for editing Multiple node attributes with varying boolean values

### ISSUE THREAD

**Issue by capricornunicorn123** [constellation-app/constellation#1879]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Null Pointer exception is thrown when trying to edit a boolean attribute of multiple nodes at the same time where some attributes selected have true whilst others have false.

### Steps to Reproduce
**Step 1**
- Open a graph and place two nodes.

**Step 2**
- Open the attribute editor and set the Node attribute "pinned" to true for one of the nodes and false for the other.
![image 1](https://github.com/constellation-app/constellation/assets/139201011/9ddf7b2b-5388-4f97-bfc0-a9973352e116)

**Step 3**
- Select both nodes and attempt to modify the value of the Node attribute "pinned".

**Expected behaviour:** 
Should provide the user with a pop-up window prompting the user to edit the value. 

Currently the pop-up window Boolean value only displays on check box for true.

- Perhaps a true check box and a false check box where only one can be selected could be implemented. In group selections none are selected to indicate the fact that multiple nodes have different values.

- Perhaps instead of tick and untick, the check box can display a third "filled" option to symbolize multiple values. 

- Perhaps implementing a switch button with one side being true, one side being false and the center symbolizing multiple values. 

**Actual behaviour:**
A null pointer exception is thrown:
![Error](https://github.com/constellation-app/constellation/assets/139201011/91255ac9-ef39-4f09-85dc-aa7a2e2b419e)

**Reproduces how often:** 
Occurs every time that an attribute is edited when multiple nodes are selected and their attribute has varying Boolean values. 

Does not occur if all nodes have the modified attribute of the same boolean value. 

### Additional Information

N/A

**Comment by antares1470** [comment]
I think ideally it would be good to keep check box as is (though I'm not entirely against switching to something like true and false radio buttons).

It's probably worth taking a look at other attribute types and how they handle editing multiple values. The answer for a lot of them is...they don't really. They all seem to try and set to null when they encounter multiple values (at least it appears that way testing it out). This is fine for attribute types where null is a valid value but less so for ones where null isn't. Types like float get away with it because it simply populates the dialog box with the text 'null' (and you simply won't be able to hit enter until you change it to a valid float), types like boolean on the other hand don't seem to be able to handle null quite as well (hence the exception). An alternate idea to address this is perhaps setting to a default value that is appropriate for the given type. Attribute descriptions already have a default value, perhaps that is the one worth using (so for boolean, that would be false).

**Comment by serpens24** [comment]
@antares1470 - my initial thought is if you want to edit multiple values that ALL would be set to the entered vaue. IE in the case described in the steps to repeat, all values would be set to the same boolean value. This is similar to pasting an excel cell value into multiple other cells.

I will now look at the context of how the null is being used and how the functionality currently works.

**Comment by serpens24** [comment]
Have managed to make a null boolean get treated as false with the following change:
            checkBox.setSelected((value != null) && value);
                      
Now looking to see what happends for other data types I could find in Attribute error:

**WORKING**
**DateTime**: value is set to "current" date time. This seems to make sense as its not replicating any single value of the multi, and the control needs to have some values. 
**String**: show an empty text box
**Enum** (ie type): show an empty value
**Icons**:  an empty icon selection screen is shown
**Color**: an defaulted color picker is shown (white is the default)


**ISSUES**
layer_mask: there are issues here - when the edit dialog is opened an error is shown:
![image](https://github.com/constellation-app/constellation/assets/58677108/02ec91c4-5527-4a0b-b402-e4a7f2fbf562)
**layer_visibility**: there are issues here - when the edit dialog is opened an error is shown:
![image](https://github.com/constellation-app/constellation/assets/58677108/9761060f-e8f2-46bc-8b91-38bd5e918f83)

**Comment by GammaVel** [comment]
Thanks for fixing the issue @serpens24 and finding the issues with the custom attributes, this looks really good now, I can confirm the run time exception is no longer being displayed that was originally.
