### ISSUE TITLE
Make Default Table Column Ordering Configurable

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1882]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Presently, Constellation by default displays the key attributes in the Table View if no other column ordering is specified. There also exists a default column order (ironically not set by default) which gets all attributes that start with a capital letter.

In a number of other places in Core, Constellation makes use of lookups in order to make Constellation extensible. Core would then have some default implementation and then any developers extending could then easily extend or override with their own implementations if so desired. 

I believe the default column ordering in the table view would be a good place to make use of lookups. While you are already able to specify a custom table ordering via table preferences, some developers may prefer a certain order be set by default rather than having to load that order in every session. So Core can set a default ordering (e.g. key attributes) and developers can choose to override that if so desired.

**Expected behaviour:** Default column order is configurable

**Actual behaviour:** Default column order is set in Core

### Additional Information

Currently if no order is specified, the table view fires off the 'Show Key Columns' menu item code rather than 'Show Default Columns' code. I think as part of this, that should change to fire off the latter by default and then possibly changing the default default ordering to key columns (as I don't think that all the attributes starting with capital letters is all that useful as a display)

**Comment by HolandCrick** [comment]
@andromeda-224  Thanks for adding the enhancement on Table View Default Column Ordering Configurable. It works now as expected.

![Image](https://github.com/user-attachments/assets/36981667-c1ab-4648-99b2-01b24608a51e)
