### ISSUE TITLE
Allow clicking in the Attribute editor field to untick the no value automatically

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1888]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

I needed to add some more attribute values to nodes on my graph using the Attribute Editor. It is very easy to click in the attribute field and the box displays for the field to be edited. I tried to start typing in the field however it didn't work. It wasn't until I realised the No value field was set, and I needed to untick it. 

### Steps to Reproduce

1.  Open any graph and the Attribute editor
2.  Select a node on the graph and observe the attribute editor is populated with values
3. Click on one of the fields to Edit them
4. Immediately think I can start editing the value > I can not > you first need to untick the field for no value. 
>>> To avoid a mouse click, is it possible to automatically untick the no value field so that if a user starts typing it gets turned off.
>>> Alternatively, is this field needed ? The text box field could have no value until the user started typing. 

**Reproduces how often:** 100%

### Additional Information

![image](https://github.com/constellation-app/constellation/assets/83679004/df544cec-4e30-4b47-b8c5-495f8584a290)

**Comment by GammaVel** [comment]
Hi @altair1673, it is fantastic to see how quickly my feedback has been addressed, thanks for making this change!  It is much easier to use. 
There might be an issue with the Reset to Default option.  In version 2.10 when this was ticked, this would grey out the text and automatically select the No value option. This isn't happening with the latest nightly build.  It resets it back to nothing but it doesn't automatically grey out the text and select the No value option.

Here are some screenshots to explain more for the above:
![image](https://github.com/constellation-app/constellation/assets/83679004/505eb8ff-4219-4065-b21d-0e18260f78fe)



It is working as expected when I click on the No value checkbox, no issues with that one. Can you please check with is happening with the Restore default?  
Thanks!

**Comment by HolandCrick** [comment]
@altair1673 @sol695510 thanks for identifying and fixing the Attribute Editor Field "No Value" Tick Box.  It is now allowing immediate editing in editor fields and "No Value Tick Box " moved to the middle.

![image](https://github.com/constellation-app/constellation/assets/157770877/ca4c4834-9cd8-4333-b6d3-c6288b481474)
