### ISSUE TITLE
Hide null fields in the Attribute Editor 

### ISSUE THREAD

**Issue by Delphinus8821** [constellation-app/constellation#1893]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

When viewing the results of a selection in the Attribute Editor, fields that display "No Value" (i.e. null) distract from the populated values and increase the amount of scrolling required. The default behaviour should be to filter such fields out of the Attribute Editor view and update whenever the selection changes.

**Comment by GammaVel** [comment]
Looks great at @serpens24. I found this very handy to hide the attribute fields that did not have any data present in them.

Here is an example of this working on my graph. 
![image](https://github.com/constellation-app/constellation/assets/83679004/fc7d56c6-6f46-4230-80c8-84245af4e1d9)

**Comment by GammaVel** [comment]
Closing issue
