### ISSUE TITLE
Quick Search function is not working.

### ISSUE THREAD

**Issue by OrionsGuardian** [constellation-app/constellation#1899]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

![image](https://github.com/constellation-app/constellation/assets/104604488/2e5cfa54-2e00-4b31-8548-e178f84e796a)

It appears that when the new Find functionality was introduced, the Quick Search functionality was removed.
It should be reinstated or adapted to work with the new Find functionality.

### Behaviour

**Expected behaviour:**
Users are familiar with entering text into the quick search box to conveniently locate and select graph elements.

**Actual behaviour:**
Entering text into the Quick Seach box does not currently look at any of the graph data, which means it no longer provides quick access to nodes/transactions in the graph.

**Reproduces how often:**
100%

**Comment by GammaVel** [comment]
Thank you very much @OrionsGuardian for fixing up the quick search and getting that working once more. Looks great!
One small thing, after performing a few quick searches, the list of recent quick searches builds up. If I select my search item from here it doesn't actually locate the item, even though if I select it from the node section it will.

Here is a screenshot of what I mean:
![image](https://github.com/constellation-app/constellation/assets/83679004/69c729bb-be9c-4bab-8c49-3ee7340541d7)

Curious to know if you get the same behaviour here. 
Thanks!

**Comment by GammaVel** [comment]
Turns out there is an existing long standing issue for the quick search not working - see https://github.com/constellation-app/constellation/issues/186

**Comment by GammaVel** [comment]
Thanks @OrionsGuardian for getting this working again, that is really good. There was already an issue for the recent search not working #186 so I have moved that into In progress and I will close this one off as it is looking great. Thanks again!
