### ISSUE TITLE
Creating a custom (node) attribute of type time_zone results in graph throwing exception on load

### ISSUE THREAD

**Issue by serpens24** [constellation-app/constellation#1907]
### Description

After adding a custom attribute to a graphs Node attribute list and saving the graph, the graph can no longer be pened with an exception thrown:
![image](https://github.com/constellation-app/constellation/assets/58677108/737e209b-35f1-4baf-8be1-017c95e5ed41)

------------------------------------
java.lang.IllegalStateException: Error creating data type for new Node attribute 'AAA-timezone'

au.gov.asd.tac.constellation.graph.StoreGraph.addAttribute(StoreGraph.java:1596)
au.gov.asd.tac.constellation.graph.file.io.GraphJsonReader.parseElement(GraphJsonReader.java:598)
au.gov.asd.tac.constellation.graph.file.io.GraphJsonReader.readGraph(GraphJsonReader.java:419)
au.gov.asd.tac.constellation.graph.file.io.GraphJsonReader.readGraphZip(GraphJsonReader.java:177)
au.gov.asd.tac.constellation.graph.file.io.GraphJsonReader.readGraphZip(GraphJsonReader.java:106)
au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphOpener$GraphFileOpener.doInBackground(VisualGraphOpener.java:205)
au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphOpener$GraphFileOpener.doInBackground(VisualGraphOpener.java:174)
java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
java.base/java.lang.Thread.run(Thread.java:834)

The graph opens but is shown empty

### Steps to Reproduce

1. Create a new graph and draw a new node on it
2. Open the attribute editor and click the **+** icon for the list of Node attributes
3. Select Custom, provide an attribute name, ie "AAA-timezone" and select Attribute-type to be time_zone. Press the OK button to add the attribute
4. Save and close the graph
5. Attempt to re-open the graph

### Behaviour

An error dialog is shown as per the image above containing the stack trace shown
The graph opens but is empty

**Expected behaviour:**

The graph opens successfully with all data

**Actual behaviour:** 

The graph opens but is empty

**Reproduces how often:**

100%

### Additional Information

nil

**Comment by HolandCrick** [comment]
Thanks to Quasar985 for fixing the custom node attribute bug. The new Node attribute change works and the graph opens successfully with all data. 

![image](https://github.com/constellation-app/constellation/assets/157770877/e3316a1d-051a-45f5-afa1-649584267653)
