### ISSUE TITLE
Find button to zoom to results 

### ISSUE THREAD

**Issue by Delphinus8821** [constellation-app/constellation#1912]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
When I am using the "find and replace" basic find functionality to try and locate nodes on my graph, I have to also hit the "zoom to results" button after I hit find. I would love if there was another button that did both functionalities at the same time. 

### Behaviour

**Expected behaviour:**  Zoom to results after the find button is pressed. 

**Actual behaviour:**  Results are selected on the find action but then have to manually zoom to selection. 

**Reproduces how often:**  100%

**Comment by HolandCrick** [comment]
@Guilty-Spark-343 - Thanks for enhancing the search feature. It's good edition.
