### ISSUE TITLE
Data Access Categories Don't Display in v2.11-rc1 if preference used in previous version

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1918]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

in v.211-rc1, Data Access View doesn't display any plugins if the categories preference has been used in a previous version. If I then go into the Data Access View Preferences, the list is displayed as it was in the previous version and if you save any changes there it then finally displays the categories in whatever order you set. Using the Reset script fixed the issue as well but in reality they should never have disappeared to start with
![DataAccessNoCategories](https://github.com/constellation-app/constellation/assets/62311243/22540a5c-bccf-4fda-b975-39205e9dbb64)
![DataAccessCategories](https://github.com/constellation-app/constellation/assets/62311243/bb94a015-6c2b-4128-ab76-3c38bb2e7b13)

### Steps to Reproduce

1. Run Reset script (to ensure blank state)
2. Open Constellation v2.10
3. Open Data Access View preferences, move a category to the Hidden list
4. Restart Constellation
5. Go back to preferences, move that category back to Visible list (this step may not be necessary but it was what I did when I found the issue)
6. Restart Constellation v2.10 and verify the categories are all displayed in Data Access View
7. Close Constellation v2.10 and open v2.11-rc1

**Expected behaviour:** Data Access Plugins should display in Data Access View

**Actual behaviour:** No plugins visible

**Reproduces how often:** 100%

### Additional Information

Given re-ordering wasn't possible before 2.11-rc1, I would say it would be ideal that the first open in v2.11-rc1 has all the categories listed as visible displayed in the default order (given the default order of the list in the preferences prior to then wasn't in the correct default order but up until now didn't matter), but I understand if that may be too difficult to determine.

**Comment by HolandCrick** [comment]
antares1470 and sol695510 for raising the issue and resolving. The Fixed Data Access Categories is displaying new as expected.
