### ISSUE TITLE
Reset Data Access Category Preference Lists

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1919]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Being able to choose which Data Access Plugin Categories to display and in which order is helpful but I think it might be helpful to have an option to reset everything if desired (i.e. all the categories in the visible list in the default order). Currently if I want to do that, I either have to do a bunch of playing around trying to get everything into that order (which could get tedious), or I need to use the Reset script (which requires Constellation closed and will reset other things as well)

**Expected behaviour:** Some sort of Reset to Default button that will put all the categories back in the default position

**Actual behaviour:** Doing this manually or outside the application itself

**Comment by HolandCrick** [comment]
Thanks to @Guilty-Spark-343 for adding the "Reset Data Access Category". It is useful feature and works very well. 
![image](https://github.com/constellation-app/constellation/assets/157770877/4812fb17-eb7c-4303-b3e4-04dde35fcda4)
