### ISSUE TITLE
`PluginParametersSwingDialog` buttons are not customizable

### ISSUE THREAD

**Issue by capricornunicorn123** [constellation-app/constellation#1924]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
`DialogDisplayer`s (Specifically `PluginParametersSwingDialog`s) have default button values of "OK and "Cancel". Although generally fitting with all use cases, it would be better if these button labels were suited to the specific use case of the `DialogDisplayer`. 

### Steps to Reproduce
1.  Open new graph
2.  Build Sphere graph (note the "OK", "Cancel" buttons)
3.  Select OK.
4.  Right Click on the graph tab and select rename (note the "OK", "Cancel" buttons)

**Expected behaviour:** 
Build Graph "OK" button would be better served as "Build"
Rename Graph "OK button would be better served as "Rename"

**Actual behaviour:**
All acceptance buttons default to "OK"

**verification process:**
Execute Plugins interactively and note the label of the acceptance button.
Some known examples:
  Experimental > Build > Build Spere graph.
  File > Export> To Screenshot.

**Reproduces how often:** 
100%

### Additional Information

Any additional information, configuration or data that might be
necessary to reproduce the issue.

**Comment by HolandCrick** [comment]
The Export Action button text is right in all types except a) Screenshot and b) JSON file type.

![image](https://github.com/constellation-app/constellation/assets/157770877/6ca5d42b-d35e-49c0-975c-b7991292c488)

**Comment by capricornunicorn123** [comment]
The dialog windows in the screenshot a) and screenshot b) are FileChoserDialog windows and are not PluginParameterSwingDialog windows. As a result these acceptance options are not customizable for screenshot a) and b). 

The comment is still valid but would be out of scope for this ticket and should be captured in a separate issue. Keeping in mind that the current implementation of FileChooserDialogs would not be able to support this feature, the ticket will likely go stale until a new FileChoserDialog implementation is created.

**Comment by HolandCrick** [comment]
@capricornunicorn123 - 
![image](https://github.com/constellation-app/constellation/assets/157770877/c1630837-8ca8-468c-a4ce-85cb22613a19)
