### ISSUE TITLE
File Name no longer preserved when saving first time

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1943]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Constellation allows you to rename graphs via right-clicking the graph tab and selecting Rename. For a new graph, when you do this and try to save though, this new name doesn't come up by default in the file name section in the Save As dialog. This use to be the case but at some stage this was removed. Bringing this back would be helpful particularly if you have several new graphs open as it makes it easier to know which graph is being saved.

### Steps to Reproduce

1. Open a new graph, add a node
2. Right-click the graph tab and navigate to Rename, give your graph a name
3. Save the graph

**Expected behaviour:** File Name field of Save As dialog is pre-populated with graph name by default

**Actual behaviour:** File name field is blank by default

**Reproduces how often:** 100%

### Additional Information

Having done some quick digging, it seems the File name field is blank by default when using Save As regardless of whether the graph has been renamed or not (probably just not as notable an issue when your graph has a default name like 'analytic graph 1')

**Comment by HolandCrick** [comment]
@antares1470 - Thanks for resolving the Fine Name Retaining option bug during Save As - It's working now as expected and the  File Name field of Save As dialog is pre-populated with graph name by default.

![image](https://github.com/constellation-app/constellation/assets/157770877/21fcd9da-2cd4-4b8d-9dcc-90973cba0634)
