### ISSUE TITLE
Unit Test creates a new CSV file in the user directory

### ISSUE THREAD

**Issue by Delphinus8821** [constellation-app/constellation#1948]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Every time the unit test class `SaveResultsFileWriterNGTest` in `CoreUtilities` is run it creates a CSV file in your user directory.

![image](https://github.com/constellation-app/constellation/assets/73083035/34f5fe4d-7bca-45ba-a9fc-8404da45d0c6)

### Steps to Reproduce

1.  Run the unit test class `SaveResultsFileWriterNGTest` in `CoreUtilities` 

2.  Observe a new CSV file is created in the user directory 

**Expected behaviour:**  File is created and then deleted once the test is finished

**Actual behaviour:** File is created and never deleted

**Reproduces how often:**  100%

**Comment by HolandCrick** [comment]
@Quasar985 Thanks for fixing the isuse.
