### ISSUE TITLE
`DataAccessView` `ContextMenu` is not showing in `DataAccessTabPane`

### ISSUE THREAD

**Issue by capricornunicorn123** [constellation-app/constellation#1949]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
The behavior of `DataAccessView` `Tab` `ContextMenu` was changed in #51 whereby the `Tab` `ContextMenu` only appears on the `Tab` heading and not in the body of the `Tab` (the `Pane`). The desired outcome is for the `Tab` `ContextMenu` to appear when right clicking on the entire `Pane`. This functionality was removed due to the triggering of two `ContextMenus` when clicking on the `MultiChoiceInputField`.

### Steps to Reproduce

1. Open DAV

2.  Right Click on Tab, note the context menu

3.  Right Click on Pane, note the absence of the tab context menu

<!--

### Behavior
N/A

### Additional Information
N/A

**Comment by HolandCrick** [comment]
@capricornunicorn123 Thanks for resolving the Context Menu in Data Access View. Now the presence on context menu is presence in heading and body of the tab.
