### ISSUE TITLE
It seems the GDELT API doesn't work

### ISSUE THREAD

**Issue by NETfrix** [constellation-app/constellation#1952]
### Prerequisites

- [X ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

It seems the GDELT API doesn't work. 

### Steps to Reproduce

1. Import

2.  import from GDELT knowledge graph

3.  entity option: person (limit result - 1000)
4. GO
![GDELT API](https://github.com/constellation-app/constellation/assets/91426407/ed027e8e-630c-4f87-8fa8-be1eaa921850)

**Expected behaviour:** I'l get a GDELT graph
**Actual behaviour:** \file read error
**Reproduces how often:** \[all the time

### Additional Information

Any additional information, configuration or data that might be
necessary to reproduce the issue.

**Comment by HolandCrick** [comment]
@Delphinus8821 Thanks for fixing the GDETL bug. Looks like the "File Not Found...." error is not appearing. 

![image](https://github.com/constellation-app/constellation/assets/157770877/dd7f8d92-f9dd-414c-94d8-f7677f2af1e6)
