### ISSUE TITLE
Notes View issues - buttons are overlapping with multiple lines of notes and unable to resize notes edit box

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1954]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

In the latest nightly build (09/02) Notes the buttons for the notes that have multiple lines of text are overlapping with the content of the note. When you edit the note you can't resize the box, so you are not able to click save. This was not an issue in version 2.11 official release. 

### Steps to Reproduce

1.  Open the latest nightly build
2.  Open an existing graph that has some longer notes
3. Go to the Notes view
4. Observe that the buttons are overlapping with the text
5. Click on Edit > Observe that the edit box can't be resized so I can't save the changes to my note
6. Go back and check v2.10 > this does not have these issues, it was working
7. Go back and check v2.11  prod release > this also has the issue with the overlapping text but the edit box can be resized without any issues  

**Actual behaviour:**  see above

**Reproduces how often:** 100%
### Additional Information
![image](https://github.com/constellation-app/constellation/assets/83679004/5e9f605b-08a8-4ade-b48a-a4b274b7765c)

**Comment by HolandCrick** [comment]
Thanks Quasar985 for fixing the text overlapping the Note View Buttons. It's working now as expected.

![image](https://github.com/constellation-app/constellation/assets/157770877/8c6e4faa-ecce-4a1e-8748-d6b163ff636c)
