### ISSUE TITLE
Add Keyboard Shortcut for Camera zoom

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1955]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Keyboard shortcuts exist for panning but not zooming on the graph. This makes it difficult to navigate the graph view without a mouse with a mouse wheel (e.g. trackball) as it means you have to use a careful use of Reset View and Zoom To Selection which is far more tedious than it needs to be

**Expected behaviour:** Keyboard shortcut for Camera zoom exists

**Actual behaviour:** Such behaviour does not exist

**Reproduces how often:** 100%

### Additional Information

As part of this, you could also look into making zoom compatible with a trackball mouse but the keyboard shortcut at a minimum should be sufficient

**Comment by HolandCrick** [comment]
Thanks to Quasar985 for adding a useful enhancement Zoom In/Out. It works as expected.
Scroll mouse wheel to conveniently zoom in and out of the graph view or   Ctrl+Alt+Up Arrow and Ctrl+Alt+Down Arrow or just use the menu option. 

![image](https://github.com/constellation-app/constellation/assets/157770877/c9b5cc6a-f988-4ed9-ad82-d41496ad5365)
