### ISSUE TITLE
Null pointer exception when copying and pasting nodes and transactions onto a new graph 

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1956]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

In the latest nightly build 09/02 I am getting a Null Pointer exception for a few different graphs when I select some nodes and copy and paste them onto a new graph. This does not happen for the same graphs in v2.11 (prod release) so it looks like something has changed to cause this to happen.

### Steps to Reproduce

1. Open up attached graph which is one of my data science graphs
2. Select some of the nodes on the graph
3. Use Control C to copy
4. Paste into a blank graph > run time error observed
5. Repeat with another graph that has a sphere builder component added > same error
6. Repeat with a third graph that comes from training > no error
7. Go back to v2.11 prod release > the same error doesn't appear
8. Repeat with the Edit menu to copy > there is no error using this option

**Expected behaviour:** no issues with copying and pasting

**Actual behaviour:** Error but not for all graphs

**Reproduces how often:** 100% on the graphs where it is an issue

### Additional Information
Use the sphere graph builder to get a reproducer here.

**Comment by antares1470** [comment]
This appears to be similar to #1967 which has been resolved

**Comment by HolandCrick** [comment]
@Auriga2 Thanks for your help to fix the Null Pointer Exception Bug during copying and pasting.  No more issues with copying and pasting.

**Comment by Auriga2** [comment]
Thanks @Quasar985
