### ISSUE TITLE
File Importer Formatter Dialogs have not been updated with Dark/Light Mode

### ISSUE THREAD

**Issue by Delphinus8821** [constellation-app/constellation#1958]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
The dialogs that pop up when setting a formatter or the default value for an attribute in the file importer have not been updated to the new dark and light mode look and feels. 
The new attribute pop up has also not been updated.

### Steps to Reproduce

1.  Open the File Importer and add a file to import

2.  Right click on an attribute field and select one of the formatters, set default value or click the plus to add a new attribute 

3.  Observe dialog box not updated with the new dark/light mode look and feel 

**Expected behaviour:** Dialogs to match the dark or light mode look and feel 

**Actual behaviour:** Dialogs look like the old styling 

**Reproduces how often:** 100%

### Additional Information
Date time formatter 
![image](https://github.com/constellation-app/constellation/assets/73083035/c61e99db-cd1a-4025-977c-abebc4b89f24)

Set default value dialog 
![image](https://github.com/constellation-app/constellation/assets/73083035/4645e389-9a89-488e-be05-ff77e8bc50b9)

New attribute 
![image](https://github.com/constellation-app/constellation/assets/73083035/a9c5fc33-17ed-4591-b70b-fbabbc55dbc9)

**Comment by HolandCrick** [comment]
@Quasar985 thanks for updating the Importer Formatter Dialogs to match Dark/Light Mode. The look and feel matches with mode.

![image](https://github.com/constellation-app/constellation/assets/157770877/e1db7cbe-ccde-4b29-8821-7257c541ae48)
