### ISSUE TITLE
Advanced find > run time exception when using a List to search and clicking on Find All

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1962]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

There is a bug in v2.11 with the List search option available under the Advanced Find. After adding in some list values to search for a runtime error is being displayed. This does not happen with the old find view in version 2.10.

### Steps to Reproduce

1. Open up an existing Constellation graph that has some values for the nodes (Identifiers or labels)
2. Go to Edit > Find
3. Copy the value for one of the Identifiers and check it can be found on the graph (this simply establishes that general find is working)
4. Go to Advanced Find
5. Change the Match Criteria to be Any
6. Click on the "Use List" checkbox
7. Paste in the previous Search term that was copied
8. Click on Find all > Runtime error is seen
9. Repeat tests with v2.10 > this is not an issue > it works here with the old find view

**Expected behaviour:** The node is selected on the graph automatically

**Reproduces how often:** \[What percentage of the time does it reproduce?\]

### Additional Information

![image](https://github.com/constellation-app/constellation/assets/83679004/666df546-dee7-4cf9-8ecb-20fe91759438)

**Comment by HolandCrick** [comment]
Thanks GammaVel to raise the advance find issue and Auriga2 for resolving. Looks like the Advance Find is working as expected.

![image](https://github.com/constellation-app/constellation/assets/157770877/20d9e691-a92e-4706-9421-07f214093852)
