### ISSUE TITLE
Advanced Find criteria is hard to read on light Look and Feel displays (black text on gray background)

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1963]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Advanced Find has the option to add criteria in after clicking the plus icon. On the light look and feel displays such as Windows, Windows classic and Flatlaf Light, the criteria section that displays has black text on a gray background which is really difficult to read. 

### Steps to Reproduce

1. In Constellation change the display to be Windows, Windows classic and Flatlaf Light
2. Open a graph
3. Go to Find
4. Go to Advanced Find
5. Click the plus icon to enter in a criteria > notice the display is hard to read

**Reproduces how often:** 100% for the light themes
### Additional Information

![image](https://github.com/constellation-app/constellation/assets/83679004/42fe0e75-9ec5-40bf-b90f-42eb49ddf487)

**Comment by HolandCrick** [comment]
Thanks to Quasar985 for fixing the Advanced Find criteria black text on gray background issue. It's working well now. 

![image](https://github.com/constellation-app/constellation/assets/157770877/71399608-9f9e-4957-b847-11161cf3a471)
