### ISSUE TITLE
Update FlagIconProvider to align more with Country enum

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1968]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The `FlagIconProvider` provides us with a nice way of being able to display country flags as decorators. Currently, all the icons listed have an alias determined by the digraph listed in its equivalent value in the `Country` enum but I think it would be nice to be able to expand this further to include additional aliases which we can identify from the country enum i.e. trigraph and alternate names. There already is a function in there called `addAliases` and so this shouldn't be too difficult to add. 

The name for the icon itself should probably also use the country display name instead (e.g, `Country.AUSTRALIA.getDisplayName()` rather than `"Australia"`)

**Expected behaviour:** Naming Digraph, trigraph, display name, or alternate names in Geo.Country should display flag icon

**Actual behaviour:** Only digraph and equiv to display name display icon

**Reproduces how often:** 100%

### Additional Information

Any additional information, configuration or data that might be
necessary to reproduce the issue.

**Comment by HolandCrick** [comment]
Hello @Quasar985 - thanks for enhancing the FlagIconProvider provides. Working nicely.

![image](https://github.com/constellation-app/constellation/assets/157770877/8180bb3a-77e4-4a80-a9d7-52a509ed6172)

![image](https://github.com/constellation-app/constellation/assets/157770877/5850efdb-6fee-465c-98bb-da6dbd1d6bfe)
