### ISSUE TITLE
Update Country enum with new values

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1969]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

It's been a while since the Country enum has been updated but some countries around the world have had some name changes and so this should probably also be reflected in our code. Some examples that come to mind:

Czech Republic -> Czechia
Netherlands -> The Netherlands
Turkey -> Turkiye
Macedonia -> North Macedonia

We could add these new names as alternate names to the existing entries although perhaps the more correct way to do it would be make the new names the display names and move the old names to being alternates

**Expected behaviour:** New country names reflected in code

**Actual behaviour:** New country names not recognised yet

**Reproduces how often:** 100%

### Additional Information

This work could be paired with #1968

**Comment by HolandCrick** [comment]
Hello @Quasar985 - thanks for updating the country names. 

![image](https://github.com/constellation-app/constellation/assets/157770877/3ab65c15-fdcf-4629-b343-9d53b403e686)
