### ISSUE TITLE
The Analytic View "Options" button doesn't do anything

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#197]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The "Options" Button on the Analytic View menu does nothing.
Unsure if it has a function but is broken, or it has no function and is still visible/enabled.

### Steps to Reproduce

1. Open Analytic View
2. Select "Options"

**Expected behaviour:**
Menu to appear

**Actual behaviour:** 
Nothing

**Reproduces how often:** 100%

### Additional Information

UX is not intuitive if the button is not meant to perform any action.

**Comment by cygnus-x-1** [comment]
The options menu should currently be hidden. If you look at the code creating the Options menu in _AnalyticViewPane_, you'll see there are some future features which have not yet been implemented.

**Comment by aldebaran30701** [comment]
Ah yes, I'm happy for us to close this issue or keep it open to implement the features necessary in the future. 
Moving forward, would there be a need to create an issue for things that will need development in the future? Ie. if we note some TODO: statements in the code that do not have issues relating to them, should we make an issue to keep track of future development? or only create tickets for bugs.

**Comment by arcturus2** [comment]
@aldebaran30701 my first preference will be to create a ticket because it is the best way to track work and plan future work. If there is a lack of motivation/too busy/not expecting it to be looked at for years then a TODO statement will be fine.

One fine day when we get on top of the bugs, I would really like to go through all of the TODO's and make tickets for them.

**Comment by aldebaran30701** [comment]
Action for this ticket is to remove the specific options menu - create a PR and then close this issue. Future work will create the options dialog when the need exists.
