### ISSUE TITLE
Jupyter notebook issues - automatically copy the constellation_client.py file  Jupyter Notebook directorywhen starting the REST server.

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1974]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

I have been trying to get a Juypter notebook up and running as I saw this is a powerful way of importing data to a graph using python. It has taken a bit to get it working. The first thing I had to do was to update my PATH variable to include the location of python. Following this I had to copy the constellation_client.py to the same location that my notebook was. Once I did this everything worked.

We should copy the constellation_client.py file to the Jupyter Notebook directory (if specified), when starting the REST server. That should make things easier for users, and ensure they've got the current version of the file.

### Steps to Reproduce

1. Try running the notebook without the constellation_client.py at the same location as the notebook > this does not work
2. Copy the client to the location > now the notebook works

**Expected behaviour:** If I don't need to do this the help should tell me what is preferred

**Actual behaviour:** Extra steps required, which while they were simple, these are not in the current help and it is a bit confusing. 

**Reproduces how often:** 100%

**Comment by HolandCrick** [comment]
@Quasar985 thanks for your attention, the Jupyter Notebooks Script showing HTTP Error during New graph creation.

Created New Ticket #2067
![image](https://github.com/constellation-app/constellation/assets/157770877/7df1f2b4-2e7b-493c-85f8-a5896e8e70c5)
