### ISSUE TITLE
Analytic & Conversation Views Closing Bug

### ISSUE THREAD

**Issue by Delphinus8821** [constellation-app/constellation#1975]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
Sometimes closing the Analytic View can cause Constellation to completely freeze up and become unresponsive. This occurs when there are at least 2 graphs open and the Conversation View open. This also happens when the Conversation View is replaced with the Layers View.

### Steps to Reproduce

1.  Open or create 2 graphs

2.  Open the Conversation View and the Analytic View

3.  Close the Analytic View

4. Observe that Constellation is unresponsive

5. Also occurs when the Conversation View is replaced with the Layers View.

**Expected behaviour:** Constellation to continue being responsive

**Actual behaviour:** Constellation is unresponsive

**Reproduces how often:** 100%

### Additional Information
Both views can be empty for this to occur. Graphs do not need to have conversation data and the Analytic View does not need to run an analytic.

**Comment by HolandCrick** [comment]
@Delphinus8821 -thanks for your help to fix the closing the Analytic View caused Constellation to completely freeze up and become unresponsive. 

It's working fine now.
![image](https://github.com/user-attachments/assets/3fce7335-f6f9-42a7-8a3a-7266056562a6)
