### ISSUE TITLE
Constellation Client assumes you haven't changed the user directory

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1977]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Constellation allows users to change the user directory that Constellation uses via preferences. When the rest client is started, this user directory is where is the rest.json file is created.

In the client, the instantiation of the client looks for this file in OS user home. This is the default value for the user directory in preferences but if you change this, that is no longer the case. The result of that is that the client doesn't obtain all the information it needs from that file (because its looking in the wrong place) and subsequently any function calls on the client fail (e.g. it can't find the secret) 

If possible, this should be changed to instead pull from user directory as defined in Constellation preferences

### Steps to Reproduce

1. Change your user directory via Setup -> Options -> Constellation -> Application
2. Go Tools -> Start Jupyter Notebook (assuming you can already open up Jupyter notebooks)
3. Run the notebooks_and_constellation jupyter notebook (available from Constellation scripts repostitory)

**Expected behaviour:** Notebook should run without error

**Actual behaviour:** Error thrown being unable to find Constellation secret

**Reproduces how often:** 100%

**Comment by HolandCrick** [comment]
@Quasar985 thanks for addressing the user directory issue. User can now run Jupyter notebooks from any chosen folder, as it's not reliant on the "user directory" anymore.
