### ISSUE TITLE
Export to SVG Enhancements 

### ISSUE THREAD

**Issue by capricornunicorn123** [constellation-app/constellation#1980]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The Export to SVG plugin could use some enhancements to increase efficiency and reduce some issues in edge cases. This issue will highlight any known weaknesses in need of enhancement. 

Export Duration
The current plugin takes a long time to export large graphs. the time to export increases linearly with graph size and can take more than 3 minuets on graphs with more than 5000 elements. 

Element Repositioning. 
There appears to be a visual anomaly where by exporting a graph from a non Z perspective causes all elements in the graph to move 1 unit in the z direction. this results in graph elements being misaligned on the output image. 

### Additional Information

**Some suggested improvements.** 

- Make the plugin thread-able with node and connection generation able to be split across multiple threads. 
- Make an option for output file structure selection. Writing as a single-file svg takes time as the file must be written too linearly. Whilst a external referencing SVG can have elements written to their own file with a single main svg file referencing these external files. both modes have their own benefits and will empower the user if able to choose tween the two.

**Comment by HolandCrick** [comment]
@capricornunicorn123 many thanks for your help to fix the SVG export performance bug. My test result looks like this:
20k graph using 4 core - Linked took 1m 3 sec
20k graph using 4 core - Embedded took 1m 7 sec
50k graph using 4 core - Linked took 3m 2 sec
50k graph using 4 core - Embedded took 4m 3 sec
70k graph using 4 core - Linked took 4m 9 sec **(application was frizzed)**
70k graph using 4 core - Embedded took 12m 55sec  **(application was frizzed)**

Performance gets worst when graph size over 20K and select 2core, hope this could be extended in future.

**_the File name has been overwritten without warning!_**  This need a warning that you are replacing your existing file.

**Comment by capricornunicorn123** [comment]
Performance will decease somewhat linearly with increasing graph size, and with decreasing processors available, so further enhancements to the performance of the SVG Export plugin would have to come from increasing the efficiency of the inner workings of the SVGExportPlugin and are likely to only produce negligable improvements. 

Note, the original implementation would take more than 3 minuets on graphs with 5000 nodes so based on your 20k graph, 4 core, Linked export numbers above, this new version is running 12x faster. 

Regarding the missing file override warning above, this is likely an existing issue stemming from the FileInputPane, I have noted this specific scenario on [issue 2082](https://github.com/constellation-app/constellation/issues/2082) so it will be addressed along with that ticket.

Would that be enough to satisfy this ticket as closed?

**Comment by capricornunicorn123** [comment]
Also, [issue 2115](https://github.com/constellation-app/constellation/issues/2115) has been created to address application responsiveness when exporting to SVG.

**Comment by HolandCrick** [comment]
@capricornunicorn123 - thanks for explaining the performance issue and file overwriting issue. Yes can be close now.
