### ISSUE TITLE
Add word wrapping to Table View

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1983]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Table View currently doesn't have word wrapping meaning if you have an entry in your table that is really long, the only way you can see it all in the table is to make the column it sits in really wide which could get very impractical

### Steps to Reproduce

1. Create a node, make the identifier a really long name
2. Open Table View, switch to node view
(could equally do this with any attribute on node or transaction)

**Expected behaviour:** Text word wraps allowing for a better sized column

**Actual behaviour:** Either a really long column to view the all of the content, or the content is cut off in some way

**Reproduces how often:** 100%

### Additional Information

Maybe a first step would be to able to expand cells vertically as well (not just horizontally as it currently stands)

**Comment by HolandCrick** [comment]
@andromeda-224  - Thank you for fixing the word wrapping bug for long text as name in identifier or node or transaction. In Table View - Text word wraps make the column auto adjusted. 
![Image](https://github.com/user-attachments/assets/cb265d35-cea9-4436-af1c-a69691c06a50)
