### ISSUE TITLE
Conversation view unresponsive bug 

### ISSUE THREAD

**Issue by Delphinus8821** [constellation-app/constellation#1988]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
When the Conversation View tries to load too much content at once, it will cause Constellation to become unresponsive and throw continuous Unexpected Exceptions. 

### Steps to Reproduce

1.  Create a new graph. Build a sphere graph with 50 nodes and 50000 transactions.

2.  Select all transactions. Add the attributes Content and Content.Translated in the Attribute Editor. Give both of these attributes values (make sure all transactions have values).

3.  Deselect everything on the graph. Open the Conversation View.

4. Select a node on the graph. If bug does not happen immediately, then select a different node with a lot of transactions.

**Expected behaviour:** Conversation view displays all conversation data and translations 

**Actual behaviour:** Constellation becomes unresponsive and continuously throws an Unexpected Exception.

**Reproduces how often:** \[What percentage of the time does it reproduce?\]

### Additional Information
Stack trace from the logs
![image](https://github.com/constellation-app/constellation/assets/73083035/f0a1ad7d-5b25-48c2-b75f-dce8379f7b42)

Empty Exception window
![image](https://github.com/constellation-app/constellation/assets/73083035/62d625c9-e12a-4b02-9852-3df7b5c55e5e)

**Comment by HolandCrick** [comment]
@Delphinus8821 thanks for addressing the unresponsive issue and Unexpected Exception in Large Conversation View. It's working fine now.

![image](https://github.com/constellation-app/constellation/assets/157770877/804bb40e-8856-47e8-801e-b8004a7c98d2)
