### ISSUE TITLE
Start REST Server not creating the required files 

### ISSUE THREAD

**Issue by nchristensen44** [constellation-app/constellation#1993]
### Prerequisites

X

### Description

When creating a REST server the two files required:

 $HOME/.ipython/Constellation_client.py - this is a Python module that provides a convenient interface to the REST API. In general, it does not change from day to day.
$HOME/.CONSTELLATION/rest.json - this file contains a secret that the client must use when communicating with the server. This stops another client on the same system from hijacking the server.

aren't appearing. The server is being created and the local host 1517 has been established but no sign of the other two files. I have found the .py file on the Constellation Github but no sign of rest.json.

I am new to constellation so I may be following the wrong procedure.

### Steps to Reproduce

On the constellation app use the tools drop down and select the 'start REST Server'

**Comment by HolandCrick** [comment]
@Quasar985 - thanks a lot for fixing the REST Server issue. Now after running REST Server - the jason file appear in both the ".CONSTELLATION" and ".ipython" folders in the user directory. 

![image](https://github.com/constellation-app/constellation/assets/157770877/6e7b3880-d9e9-4951-bc8e-b7d8f50edb64)
