### ISSUE TITLE
Datetime Range widget wrap time components

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#2014]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The DAV Datetime Range global parameter has an embedded widget for the From and To time components under the absolute range. It would be great if the up and down arrows for Hours, Minutes, and Seconds, wrapped around the max and min values.

For instance, if the hour is set to 23 and I press the up arrow once, it should change to 0, or if the Minute is set to 0 and I press the down arrow once, it should change to 59

### Steps to Reproduce

1. Open Data Access View
2. Expand Absolute Range in Datetime range global parameter
3. Set the Hour to 23 and the Minute to 0
4. Press the up arrow once for Hour and down arrow once for Minute

**Expected behaviour:** Hour changes to 0, Minute changes to 59 (i.e. datetime wraps around)

**Actual behaviour:** Hour stays at 23, Minute stays at 0

**Reproduces how often:** 100%

**Comment by HolandCrick** [comment]
@Quasar985 thanks for enhancing the date/time feature. It works as expected.

![image](https://github.com/constellation-app/constellation/assets/157770877/b31898fa-e4e7-4542-9d02-857ade5abfcd)
