### ISSUE TITLE
Light Mode issues.

### ISSUE THREAD

**Issue by OrionsGuardian** [constellation-app/constellation#2016]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

\[Description of the issue\]
There are a number of screens that have not been fully adapted to a light mode Look and Feel.
There are cases where we have black text on dark background.
Light text on a white background.
White icon images on a white background.
Mix of white text and black text in a component.
Some icons being hard to distinguish on the new blue background.
Some inconsistencies in the colour palette between different views.

### Steps to Reproduce

Attribute Editor example:
![image](https://github.com/constellation-app/constellation/assets/104604488/999b9c9f-12a6-49cf-b5ed-f578d4c697ab)

Data Access View example:
![image](https://github.com/constellation-app/constellation/assets/104604488/f25c9366-39c1-44eb-b3ae-7e590f3de931)

Notes View example:
![image](https://github.com/constellation-app/constellation/assets/104604488/c9a905e1-915b-4386-ad0a-a74afdbe8112)

Error Report example:
![image](https://github.com/constellation-app/constellation/assets/104604488/23d8e6d0-2a1a-42f7-b1d2-add48d23d7ec)

(Plus there are issues with the colour palette choices in the Table View and the Conversation view.)

**Expected behaviour:**
Consistent colour scheme throughout the product for each mode, Light or Dark.

**Actual behaviour:**
Some screens are not consistent with the Light mode colour scheme.

**Reproduces how often:**
100%

### Additional Information

There are also some lingering Dark mode issues that should be addressed at the same time.

**Comment by HolandCrick** [comment]
@OrionsGuardian - thanks a lot for fixing the light mode Look and Feel bug. Looks like it's much better than before.

![image](https://github.com/constellation-app/constellation/assets/157770877/21b8eb82-5163-466e-aed0-724a67af0b99)

![image](https://github.com/constellation-app/constellation/assets/157770877/566e8b9e-79cf-4dc3-8152-62020d870a3f)

![image](https://github.com/constellation-app/constellation/assets/157770877/777ac58a-2888-46e4-a04a-79b2e868c1b5)
