### ISSUE TITLE
Sonar Cleanup

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#2022]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

It's been a bit since there was some effort put in the cleanup some of the issues being flagged by Sonarcloud but it would be good to get some of the numbers down.

### Additional Information

If you're contributing to this, please comment what rule(s) you are looking at so that there isn't any duplication of effort

**Comment by antares1470** [comment]
(Java) Private mutable members should not be stored or returned directly

**Comment by Delphinus8821** [comment]
(Java) Redundant casts should not be used
(Java) Simple class names should be used

**Comment by capricornunicorn123** [comment]
(Java) Unused "private" fields should be removed

**Comment by Delphinus8821** [comment]
(Java) Literal suffixes should be upper case
(Java) Lambdas should be replaced with method references

**Comment by Quasar985** [comment]
(Java) Math operands should be cast before assignment
(Java) Tests should use fixed data instead of randomized data
(XML) Sections of code should not be commented out

**Comment by Quasar985** [comment]
(Java) Empty statements should be removed
(Java) Enum values should be compared with "=="
(Java) Lazy initialization of "static" fields should be "synchronized"

**Comment by Quasar985** [comment]
(Java) Accessing an array element should not trigger an ArrayIndexOutOfBoundsException
(Java) Arrays and lists should not be copied using loops
(Java) Comparators should be "Serializable"

**Comment by Quasar985** [comment]
(Java) The names of methods with boolean return values should start with "is" or "has"
(Java) Unused "private" methods should be removed
(Java) "collect" should be used with "Streams" instead of "list::add"

**Comment by Delphinus8821** [comment]
(Java) Private fields only used as local variables in methods should become local variables

**Comment by capricornunicorn123** [comment]
(Java) Arrays should not be created for varargs parameters

**Comment by Quasar985** [comment]
(CSS) CSS properties should be valid
(Java) "switch" statements and expressions should not be nested
(Java) Constructors of an "abstract" class should not be declared "public"

(Java) Encryption algorithms should be used with secure mode and padding scheme
(Java) Non-primitive fields should not be "volatile"
(Java) XML parsers should not be vulnerable to XXE attacks

**Comment by Quasar985** [comment]
(Java) Execution of the Garbage Collector should be triggered only by the JVM
(Java) Regular expressions should not overflow the stack
(Java) Standard outputs should not be used directly to log anything

**Comment by OrionsGuardian** [comment]
(Java) Raw types should not be used

**Comment by capricornunicorn123** [comment]
(Java) Method names should comply with a naming convention

**Comment by Quasar985** [comment]
(Java) Method names should comply with a naming convention

**Comment by Quasar985** [comment]
(Java) Unused assignments should be removed

**Comment by OrionsGuardian** [comment]
(Java) Generic wildcard types should not be used in return types
(Java) Avoid using boxed "Boolean" types directly in boolean expressions

**Comment by Quasar985** [comment]
(Java) "Preconditions" and logging arguments should not require evaluation

**Comment by Quasar985** [comment]
(Java) "Exception" should not be caught when not required by called methods

**Comment by Quasar985** [comment]
(Java) "NullPointerException" should not be explicitly thrown

**Comment by Quasar985** [comment]
(Java) Jump statements should not be redundant

**Comment by Quasar985** [comment]
(Java) Fields in non-serializable classes should not be "transient"

**Comment by antares1470** [comment]
(Java) Constant names should comply with a naming convention
(Java) "clone" should not be overriden
(Java) String literals should not be duplicated
(Java) "switch" statements should have "default" clauses
(Java) Methods should not be empty
