### ISSUE TITLE
Cant find correct value to use for colour in CSV file import

### ISSUE THREAD

**Issue by mrwoodo** [constellation-app/constellation#2045]
### Prerequisites

- [X ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

I cannot find in the help / tutorials what the colour attribute requires, during CSV file import. I've tried using named Colours (eg Red), and RGB hex codes both with and without a hash symbol (e.g. #FF0000, FF0000).

### Steps to Reproduce

1.  As above

**Expected behaviour:** 

Colour attribute to update

**Actual behaviour:** 

No effect. In the Table View, the transaction.color column appears as `<No Value>`

### Additional Information

N/A

**Comment by Quasar985** [comment]
Hi!
Both named colours and hex values should work. When importing, did you make sure to drag the "color" attribute for Transactions to the correct column of your CSV in the configuration section?
![image](https://github.com/constellation-app/constellation/assets/159855864/1267773e-e2d1-4a8c-aaf1-61bd529c658f)
<br />
<br />

Also in the table view, you'll need click the "Column Visibilty" button then "Show All Columns" to see the color columns (at least on the versions I'm using).
![image](https://github.com/constellation-app/constellation/assets/159855864/e31322de-e210-4d94-bb5e-1ab881e0df06)

<br />
<br />
If that still doesn't work, which version of Constellation are you using? I've tested out importing from CSV on a few different versions and couldn't seem to replicate the problem.

**Comment by Quasar985** [comment]
Also, exercise 2 in the analyst training has some guides for importing from CSV if you ever needed to brush up. Training can be found [here](https://github.com/constellation-app/constellation-training).

**Comment by mrwoodo** [comment]
> Both named colours and hex values should work.

Hi Quasar, I figured it out! My csv file had spaces between the preceding comma and the colour e.g.  `Attrib1,Attrib2, Green` which was being ignored. Stripping out the spaces resolves it.

Silly mistake, thank you for your time in helping debug this!
