### ISSUE TITLE
Overriding open graph files

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#2048]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Right now, it is possible to save override a graph while it is still open. This really shouldn't be possible and causes a bunch of errors when trying to save the original graph.

### Steps to Reproduce

1. Open a new graph and save with a new name. Keep that graph open
2. Open another new graph and when prompted choose the previously saved graph to trigger override (this is the problematic step)
3. Go back to first graph, make a change and then attempt to save
4. Exception thrown as it can't find the data object (due to step 2 being allowed to happen)

**Expected behaviour:** Constellation should not allow graphs to be overwritten while in use

**Actual behaviour:** Constellation allows overwriting graphs in use, causing errors down the line

**Reproduces how often:** 100%

**Comment by HolandCrick** [comment]
@Quasar985 thanks for fixing the Overriding open graph issue. After triggering override on an open graph, went back to 1st graph, edited the graph and saved successfully  without error. Working as expected.

![image](https://github.com/constellation-app/constellation/assets/157770877/c4c5c239-db99-40f0-ae18-541d840a8a01)
