### ISSUE TITLE
DataAccessView Option Category Changes

### ISSUE THREAD

**Issue by capricornunicorn123** [constellation-app/constellation#2055]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

When adjusting the visible categories in the Data Access View using the options panel, changes to the visible categories are not reflected in the Data Access View until an application restart occurs. Adjusting the option does not however prompt the user to restart the application. 

On restarting the application, if there are no categories in the visible column, an error is thrown.

### Behaviour
**Expected behaviour:** update instantly with no errors
**Actual behaviour:** errors thrown or no update

**Comment by HolandCrick** [comment]
@Quasar985 thanks for fixing the DataAccessView Option Catagory issue. Looks like it is working really well. No more errors and very responsive.
- Did not Prompt the user to restart the application.
- On restarting the application, if there are no categories in the visible column, an error is thrown.

![image](https://github.com/constellation-app/constellation/assets/157770877/3b5103ce-0664-4175-be80-f9c205adc699)
