### ISSUE TITLE
Timeline View error ... ConcurrentModificationException

### ISSUE THREAD

**Issue by OrionsGuardian** [constellation-app/constellation#2058]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Testing in V3 dev build:
Create a simple graph with a few nodes in sequence and link each node to the next node with a single transaction, so you have, for example, 5 nodes and 4 transactions.
Set the datetime field on the transactions in sequence so that they occur one hour after the previous transaction.

Open the Timeline View.
It should show the 4 transactions with 1 hour spacing between them.

Try to select an area in the Timeline View which encompasses 2 or more of the transactions.
Exception occurs:

![image](https://github.com/constellation-app/constellation/assets/104604488/a08cd00e-9c9f-40f7-8f23-806244237aa8)

**Expected behaviour:**

The entries selected in the Timeline View will be selected in the Graph.

**Actual behaviour:**

ConcurrentModificationException

**Reproduces how often:**

100%

### Additional Information

Following the same steps in V2.11 works correctly.

**Comment by HolandCrick** [comment]
@OrionsGuardian - thanks for your time to fix the Timeline View Error. It's working nicely now.

![image](https://github.com/constellation-app/constellation/assets/157770877/6d0cdb0b-44b3-4e41-bff4-4c3bd2608cb3)
