### ISSUE TITLE
Dev Guide: Update Exercise 8.2 Help

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#2061]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Exercise 8.2 of the dev guide is no longer correct and needs to be updated. The exercise was designed for the old help system but this is no longer relevant with the new help system having been in place for a while now. The exercise should be updated to create a help page within the new help system.

### Additional Information

This will require updating both the content in the guide, and the files used to do the exercise

**Comment by HolandCrick** [comment]
@antares1470  - Thanks for updating the Dev Guide.   The exercise section is updated to create a help page within the new help system.
