### ISSUE TITLE
Update Data Access View icon in Welcome Page

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#2063]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

When the icons were recently updated, one icon which was missed was the Data Access View icon on the Welcome page. This should be updated to match the new icon for the Data Access View

**Expected behaviour:** Icon for Data Access View on Welcome Page matches icon found in Views Menu

**Actual behaviour:** Icon for Data Access View on Welcome Page is the old icon

**Reproduces how often:** 100%

**Comment by HolandCrick** [comment]
@andromeda-224 - thanks for updating the icon. 
![image](https://github.com/user-attachments/assets/8c1399d9-4205-4eed-aac1-6143ea79c219)
