### ISSUE TITLE
Add Select Nodes and Select Transactions

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#2064]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Constellation has easy ways to Select and Deselect all but no easy way of only selecting nodes or only selecting transactions. Given Deselect Nodes and Deselect Transactions exists, it only makes sense for their counterparts to also exist

### Steps to Reproduce

1.  \[First Step\]

2.  \[Second Step\]

3.  \[and so on…\]

**Expected behaviour:** Action exists to select all nodes, and select all transactions

**Actual behaviour:** No such action exists

**Reproduces how often:** 100%

**Comment by HolandCrick** [comment]
@Quasar985 - thanks a lot for enhancing the select/deselect Nodes and Transactions. Looks good but can we make the deselect option gray when nothing is selected? 

![image](https://github.com/constellation-app/constellation/assets/157770877/c29d8e39-27d5-455d-873d-12ff8ea09e46)
