### ISSUE TITLE
Update Build scripts to use v4 of upload-artifact

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#2066]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

v3 of actions/upload-artifact will no longer be able to be used from November 30 2024. The nightly build, and release build scripts will need to be updated to use v4 before then.

https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/ 

### Additional Information

The blog attached has links to documentation on migrating workflows to v4 as it sounds like it may not be as simple as changing the number from 3 to 4

**Comment by HolandCrick** [comment]
Re-Tested 24/10/2024:
I am still having issue in Hierarchical Arrangement Functionality. Can you please look into these issues:
a) Shortest Path button - missing tool-tip; Help button need some additional explanation in help page for the Shortest Path button.
b) Large Graph still hang when apply Hierarchical Toggle Enabled.
c) Clusters left / right arrows or Cluster Graph - one of them should change. Either the hierarchy should be flipped somehow, or the buttons should be changed to up/down (and moved next to each other).
