### ISSUE TITLE
Jupyter notebook issues - The Jupyter Notebook script is showing error while creating new Graph

### ISSUE THREAD

**Issue by HolandCrick** [constellation-app/constellation#2067]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
I have been trying to get a Juypter notebook up and running, as a powerful way of importing data to a graph using python. The Notebook script is failing with HTTP error when creating new Constellation Graph. 

![image](https://github.com/constellation-app/constellation/assets/157770877/756efbb4-c523-4ee8-967b-9ecb5f8e4a61)

### Steps to Reproduce

1. Go Tools -> Start Jupyter Notebook (assuming you can already open up Jupyter notebooks)
3. Run the the notebook Script 
4. Script runs several steps but failed in creating new Constellation with HTTP Error

**Expected behaviour:**  It should create new graph

**Actual behaviour:** Showing HTTP Error

**Reproduces how often:** 100%

### Additional Information

Related ticket #1974

**Comment by Quasar985** [comment]
Extra context: In my testing of this issue, this only happens if a graph (even a blank one) is not already open in consty. Running the notebook code to make a graph a second time succeeds.

**Comment by HolandCrick** [comment]
Running the notebook script for new Graph creation is working but it takes over 15-20 second to create new graph. No more timeout or HTTP500 error
