### ISSUE TITLE
 Deprecated python code warning

### ISSUE THREAD

**Issue by Quasar985** [constellation-app/constellation#2073]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Warning is thrown in constellation_client regarding the read_json function:
```FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.```

### Steps to Reproduce

1.  Open graph

2. Start Jupyter Server

3.  Run the following code:

```
import io
import os
import pandas as pd
import PIL.Image, PIL.ImageDraw, PIL.ImageFilter, PIL.ImageFont

# Also import some of the notebook display methods so we can display nice things.
#
from IPython.display import display, HTML, Image

# This is a convenient Python interface to the REST API.
#
import constellation_client

cc = constellation_client.Constellation()

df = cc.get_dataframe()
df.head()
```

**Expected behaviour:** No warnings are thrown.

**Actual behaviour:**Warning is thrown, regarding deprecated code

**Reproduces how often:** Always

**Comment by HolandCrick** [comment]
@Quasar985 Thanks to addressing the deprecated python code issue. Need bit more work on it. Pls see the error:

![image](https://github.com/constellation-app/constellation/assets/157770877/f8795680-cb43-47c6-99dd-11a886a564c7)

**Comment by HolandCrick** [comment]
@Quasar985 - a big thanks to you for fixing the Jupyter bug. It's working now end to end.
