### ISSUE TITLE
Dark Mode Issue in Analytic View

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#2077]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

In the Analytic View, running in dark mode, the float and integer parameters for analytics appear to have a light mode colour scheme applied to the spinners. These should be modified to be dark (similar to parameters in data access view plugins). Confirmed that in light mode, the spinners appear to be an appropriate colour so the issue is only in dark mode

![analyticViewDarkModeNumberParameters](https://github.com/constellation-app/constellation/assets/62311243/e638a70f-708d-472c-8804-672eb62f1f2a)

### Steps to Reproduce

1. Open Constellation in Dark mode
2. Open Analytic View
3. Click HITS Centrality Analytic from list of analytics (Categories > Centrality), or any other analytic with numerical parameters, to display parameters

**Expected behaviour:** Numeric parameters have a dark colour scheme applied to spinner

**Actual behaviour:** Numeric parameters have a light colour scheme applied to spinner

**Reproduces how often:** 100%

**Comment by HolandCrick** [comment]
@Delphinus8821 thanks for addressing the dark mode issue in Analytic View. It looks good to me now.

![image](https://github.com/constellation-app/constellation/assets/157770877/a945c75e-0b79-4537-90b3-bf12345fcae1)
