### ISSUE TITLE
Duplicate copies of help page opened

### ISSUE THREAD

**Issue by Quasar985** [constellation-app/constellation#2084]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Searching "export-from-constellation" displays multiple copies of the same help page and opening one of them will instead open 64 copies of the help page.

### Steps to Reproduce

1. Open Constellation
2. In the search bar, type export-from-constellation.
3. Observe multiple copies of the export-from-constellation page.
4. Click any one of the export-from-constellation pages.
5. Observe 64 copies of export-from-constellation being opened.

**Expected behaviour:** One copy appears in search and one copy to be opened.

**Actual behaviour:**  Multiple copies appear in search and 64 copies opened in browser.

**Reproduces how often:** Always

### Additional Information
N/A

**Comment by HolandCrick** [comment]
@Quasar985 thanks for fixing the search functionality. Looks working fine now. 

Extra copies of a help page are no longer opened.
