### ISSUE TITLE
Help page search doesn't work if help page has spaces in name

### ISSUE THREAD

**Issue by Quasar985** [constellation-app/constellation#2104]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

If a help page has spaces in its name, searching for that page won't work if the full name is typed out.
For example, the page "import from database". If the user searches for ```import from database```, the search results will be empty. But if a user searches ```import-from-database```, then the page will appear.

### Steps to Reproduce

1.  In the search bar type: ```import from database```

**Expected behaviour:** The page for "import from database" appears in search

**Actual behaviour:** The page for "import from database" does not appear.

**Reproduces how often:** Always

**Comment by HolandCrick** [comment]
Many Search for help does not open in "Help Page/File" in Browser and show exception error i.e.:
        Import Graph File
	Gaffer Simple Query Options
	Simple Graph
	DNA Graph Builder
	
![image](https://github.com/constellation-app/constellation/assets/157770877/bcd79ae3-be58-4cc7-b089-9a2215898d24)

**Comment by Quasar985** [comment]
> Many Search for help does not open in "Help Page/File" in Browser and show exception error i.e.: Import Graph File Gaffer Simple Query Options Simple Graph DNA Graph Builder

Actions and plugins will also appear in search, which might be the help pages don't open as you might've clicked the action instead. Help pages will have (H) next to the search result. Also

**Comment by HolandCrick** [comment]
@Quasar985 thanks for addressing the issue. It's working now as expected.
