### ISSUE TITLE
java.lang.NullPointerException - Error when delete any Template

### ISSUE THREAD

**Issue by HolandCrick** [constellation-app/constellation#2107]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

java.lang.NullPointerException - Error when delete any template. 

### Steps to Reproduce

1.  File Menu -> Select Manage Template

2.  Select any saved template from the dropdown box

3.  Click Delete

**Expected behaviour:** Delete Should perform with a confirmation warning. 

**Actual behaviour:** \[java.lang.NullPointerException - Exception Error appears
![image](https://github.com/constellation-app/constellation/assets/157770877/615c6ea3-d3cd-4b8f-851d-26b9532c0c1e)

**Reproduces how often:** 100%

### Additional Information

Any additional information, configuration or data that might be
necessary to reproduce the issue.

**Comment by Auriga2** [comment]
Present in v2.11 too.

**Comment by Auriga2** [comment]
The exception is thrown in v2.11 but the template gets deleted. In v3 they don't get deleted after the exception, so has to be fixed.

**Comment by HolandCrick** [comment]
@Auriga2 thanks for fixing the bug when delete any Template. It's working nicely now.
