### ISSUE TITLE
Add "Select Nodes" and "Select Transactions" to right-click selection menu

### ISSUE THREAD

**Issue by Quasar985** [constellation-app/constellation#2108]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

It would be handy if the new "Select Nodes" and "Select Transactions" were added to the right-click selection menu.

### Steps to Reproduce

1.  Open graph in consty

2. Right click on empty part of graph

3. Hover over selection menu

4. Observe other selection/deselection options are present, but not "Select Nodes" and "Select Transactions"

**Expected behaviour:** "Select Nodes" and "Select Transactions" should be present in right-click selection menu

**Actual behaviour:** They are not present

**Reproduces how often:** Always

**Comment by HolandCrick** [comment]
@Quasar985 thanks for enhancement of the select nodes and transactions. It's very helpful.

![image](https://github.com/constellation-app/constellation/assets/157770877/89bbd98d-5d1f-453f-a87f-1c40680a526b)
