### ISSUE TITLE
Override warning shown when opening file in word cloud

### ISSUE THREAD

**Issue by Quasar985** [constellation-app/constellation#2111]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Warning is shown to user when opening file, claiming the selected file will be overridden. This does not make sense for opening a file.

### Steps to Reproduce

1.  Open Consty

2. Open world cloud view

3.  Open file in "background File" parameter

4. Observe that override warning is shown when opening file.

**Expected behaviour:**  File is opened with no override warning.

**Actual behaviour:** Consty warns that selected file will be overriden.

**Reproduces how often:**  Always

**Comment by HolandCrick** [comment]
@Quasar985 thanks for fixing the bug. Word Cloud View is not giving any warning when opening file in "background File" parameter. Well done.
