### ISSUE TITLE
Add help buttons to other features

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#2117]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

A number of plugin/feature panels and dialog boxes have been updated recently to add a help button which takes the user to the relevant help. From testing v3-rc1, I've found a couple of other places where a help button could be added:

- K-Truss panel
- Merge Nodes (Tools, not Data Access View) dialog 

### Steps to Reproduce

1. Open new graph and add 2 nodes (have both nodes selected). Alternatively open existing graph and ensure >=2 nodes selected
2. Navigate to Tools > K-Truss and observe resulting panel
3. Navigate to Tools > Merge Nodes and observe resulting dialog

**Expected behaviour:** Each should have a help button which when clicked, opens up the help page for that feature
**Actual behaviour:** No help page buttons

**Reproduces how often:** 100%

### Additional Information
N/A

**Comment by HolandCrick** [comment]
@Delphinus8821 - thanks for enhancing the help feature in K-Truss and Marge Nodes. It's working nicely.

![image](https://github.com/constellation-app/constellation/assets/157770877/cb983a5e-c76b-4250-a226-f8d7f2d2f84e)
