### ISSUE TITLE
Search All Graphs Getting Stuck on One Graph

### ISSUE THREAD

**Issue by Delphinus8821** [constellation-app/constellation#2118]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
In the Find View, if the user tries to search for a term in all open graphs that only appears multiple times in some but not all of the graphs, then the Find Next and Find Previous buttons will appear to get stuck on one node. This only occurs if one of the open graphs does not have a result for that search term.

### Steps to Reproduce

1.  Open at least 2 graphs with a different number of nodes (e.g. one Sphere Graph with 100 nodes and one graph with only 4 nodes)
2.  Open the Find View, change the Search In dropdown to All Open Graphs and search for a value that only appears on one of the graphs but will find multiple results (e.g. '5' in the Basic Find)
3. Click Find Next or Find Previous multiple times 
4. Observe that the same node continues to be highlighted instead of going between all results

**Expected behaviour:**  Continue to go between results on Find Next/Find Previous

**Actual behaviour:**  Stays on the same result

**Reproduces how often:**  100%

**Comment by HolandCrick** [comment]
@Auriga2 - Thanks for fixing the search functionality. It works in all active graphs. Continue to go between results on Find Next/Find Previous.


![Image](https://github.com/user-attachments/assets/8823f11a-5860-42b0-86e5-49ddb62e1636)
