### ISSUE TITLE
Info Map options dialog look and feel should be consistent with the rest of the application

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#2119]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The Info Map clustering can be run a couple of different ways, one of which brings up a dialog box to allow you to tinker with the parameters before running the algorithm. Looking closer at the dialog though, it seems that the way its been created is slightly different to other plugins, and so the look and feel of the dialog also feels different. The most notable thing is that it is using radio buttons which should actually be check boxes given you can select more than one at a time in each group.

This should be altered to ensure a more consistent look and feel across the application

### Steps to Reproduce

1. Open new graph
2. Tools -> Cluster -> Info Map...

**Expected behaviour:** Resulting dialog should have a look and feel that is consistent with other dialogs across the application

**Actual behaviour:** Dialog is uniquely created and stands out as much

**Reproduces how often:** 100%

### Additional Information

At the minimum, the radio boxes should become checkboxes.

Given Info Map is a plugin though, there's an argument that this should be refactored to be able to use `PluginParametersSwingDialog` rather than having a custom dialog. This though will require some refactoring of the plugin itself to make some of the options in the dialog parameters themselves (currently the only parameter for the plugin is a config which consists of those parameters found in the dialog

**Comment by HolandCrick** [comment]
@Quasar985 Thanks for re-arranging the Info Map Dialog from radio buttons to drop-down.  The Info Map Dialog is stands out now.
