### ISSUE TITLE
Hierarchical Clustering Issues

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#2120]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Having given the Hierarchical clustering a test recently, I encountered a few issues which might need to be fixed:

1) When choosing how to view Excluded elements, choosing dimmed will dim any transactions between clusters, but choosing hidden will not hide any transactions between clusters
![hierarchicalClusteringIssue](https://github.com/constellation-app/constellation/assets/62311243/392c7667-6106-4a86-93c8-0cf77d1fbb03)

2) The left and right arrows either side of "x clusters" label seem counter-intuitive as clicking left increases the number of clusters and clicking right decreases the number of clusters. I can see when I click either one that the bar on the hierarchy moves in the same direction as the arrow I clicked but it still feel like something should change. Either the hierarchy should be flipped somehow, or the buttons should maybe be changed to up/down (and moved next to each other)

3) The Shortest Path button was confusing for me as it didn't seem clear what it was going to do upon first glance. Hovering over the button to reveal the tooltip helped somewhat but maybe some additional explanation on the help page could be good

### Steps to Reproduce

1. Open new graph
2. Experimental -> Build Graph -> Small World Graph Builder (I changed the number of nodes to 50 but left other parameters as default)
3. Tools -> Cluster -> Hierarchical, play around with the panel

**Expected behaviour:** Transactions between clusters are hidden when hidden is selected, other features feel intuitive to use

**Actual behaviour:** Transactions between clusters are visible when hidden is selected, other features either feel unintuitive or counterintuitive

**Reproduces how often:** 100%

**Comment by HolandCrick** [comment]
**Re-Tested 24/10/2024:**
I am still having issue in Hierarchical Arrangement Functionality. Can you please look into these issues:
a) Shortest Path button - missing tool-tip; Help button need some additional explanation in help page for the Shortest Path button.
b) Large Graph still hang when apply Hierarchical Toggle Enabled.
c) Clusters left / right arrows or Cluster Graph -  one of them should change. Either the hierarchy should be flipped somehow, or the buttons should maybe be changed to up/down (and moved next to each other).

**Comment by HolandCrick** [comment]
@Quasar985 thanks for fixing the Hierarchical Clustering Issue. It's working now as expected. Now Transactions between clusters are hidden when hidden is selected

![Image](https://github.com/user-attachments/assets/534d212a-f9a4-4062-bc33-9012a5fe9d49)
