### ISSUE TITLE
DateTime attribute date picker does not work

### ISSUE THREAD

**Issue by Delphinus8821** [constellation-app/constellation#2127]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The Date picker in DateTime attribute in the Attribute Editor cannot be changed. 
This occurs in both v2.11 and v3.0-rc1.

![dateTimePicker](https://github.com/constellation-app/constellation/assets/73083035/c7d1996d-0c22-41b9-b7e9-9e80ed07049f)

### Steps to Reproduce

1.  Open a graph with at least one transaction and select the transaction

2.  Open the Attribute Editor and attempt to change Date on the DateTime attribute under Transaction attributes

3.  Observe the Date stays the same after being changed

**Expected behaviour:** Date to update to the new date chosen 

**Actual behaviour:** Date stays the same

**Reproduces how often:** 100%

**Comment by HolandCrick** [comment]
@Quasar985 - Thanks for trying to fix the date update in Attribute Editor (Transaction). Date to update to the new date chosen from Calendar not working, but works when type using keyboard. Time setup works using mouse.
Selected 14/07/20224 bust still 25/07/2024 current date.
![image](https://github.com/user-attachments/assets/6468ee51-1092-4a9e-b20d-c4667aeea722)

**Comment by HolandCrick** [comment]
@Quasar985 - thank you for fixing the date bug. It's working nicely now.
