### ISSUE TITLE
Word Cloud view- Unexpected Exception when no graphs are open

### ISSUE THREAD

**Issue by Auriga2** [constellation-app/constellation#2130]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

 An unexpected Exception is thrown when Generate button is clicked while no graphs are open. An edge case but nice to handle it.
![image](https://github.com/constellation-app/constellation/assets/64826928/6bc38e01-52f0-4c2a-b5da-ee8f4b512f02)

### Steps to Reproduce

1.  Open Word Cloud view
2. Make sure no graph is open

3.  Click on the Generate button

**Expected behaviour:**  No Exception is thrown 

**Actual behaviour:**  An unexpected Exception is thrown 

**Reproduces how often:** 100%

**Comment by HolandCrick** [comment]
@Auriga2 - Thanks for fixing the WordCloud View issue. It's working now and no exception.

![image](https://github.com/user-attachments/assets/6f160297-f73c-4407-be80-83534a865cda)
