### ISSUE TITLE
Duplicate FlatLAF Dark Option

### ISSUE THREAD

**Issue by capricornunicorn123** [constellation-app/constellation#2134]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Currently the act of setting FlatLAF Dark as the default LAF appears to be causing a duplicate LAF option. This issue only appears when opening the application after a fresh clean and build and I am unsure if it is an issue in the releases. I'm assuming that if the user does not have a preferred option the application sets the default to FlatLAF Dark and in doing so, unintentionally ads FlatLAF Dark to the list of options.

![image](https://github.com/constellation-app/constellation/assets/139201011/0a1af69c-c444-42b7-abbe-f30ec13e7f47)

### Steps to Reproduce

1.  Do a full Update, clean and build.
2.  Open the appearance options
3.  Note the duplicated FlatLAF Dark option
4.  Select a new LAF option
5.  Restart the application 
6.  Open the appearance options.
7.  Note the duplicated FlatLAF Dark option has disappeared.

**Expected behaviour:** No duplicate options

**Actual behaviour:**  FlatLAF Dark is duplicated on first open

**Reproduces how often:** Whenever the application is opened for the first time

**Comment by HolandCrick** [comment]
@Quasar985 - Thanks for resolving the bug. It's working now, no duplicate FlatLAF Dark option.
