### ISSUE TITLE
Offline Help Images not Loading if File Path contains a Space

### ISSUE THREAD

**Issue by Delphinus8821** [constellation-app/constellation#2135]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
If a release version of Constellation is put into a folder with spaces, then the help images on offline help do not load.
![image](https://github.com/constellation-app/constellation/assets/73083035/329f0637-25f4-46e6-a973-0cf857263883)

### Steps to Reproduce

1.  Download a release version of Constellation and unzip it into a folder with a space in the folder name

2.  Run Constellation and open offline help

3.  Note that images do not load correctly 

**Expected behaviour:** Images to load

**Actual behaviour:** Images do not load

**Reproduces how often:** 100%

**Comment by HolandCrick** [comment]
@Quasar985 - Thanks for fixing the Image not loading if file path contains a Space.

![image](https://github.com/user-attachments/assets/1f23b165-2b3f-4915-9b3e-8826c4502fed)
