### ISSUE TITLE
Test Notifications OK button throws exception

### ISSUE THREAD

**Issue by andromeda-224** [constellation-app/constellation#2139]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

An Unexpected exception is thrown on Test Notifications when OK clicked:
![image](https://github.com/user-attachments/assets/787a6c5a-b25d-45e8-8a3e-54313f437507)

### Steps to Reproduce

1.  Create a new Graph.

2.  Select menu item Experimental -> Developer -> Test Notifications

3.  Click OK. An Unexpected Exception is thrown.

**Expected behaviour:** Expected a series of notification dialogs. This can be seen if you click Cancel instead of OK.

**Actual behaviour:** 

- An exception is thrown. 
- Also, in Display Large Alert dialogs, the "Show Details" and "Hide Details" is difficult to see in FlatLaf Dark Mode. Probably related to https://github.com/constellation-app/constellation/issues/2137.
- If app is not on primary monitor, the some of the dialogs will show up on a different screen.

**Reproduces how often:** 100%

### Additional Information

Happening on v.3.0.0 - rc1.  No exception thrown in v02.11.0.

**Comment by HolandCrick** [comment]
problem is not only with  ok button but also in  cancel and X all three giving error.

**Comment by andromeda-224** [comment]
The notification dialogs (plain, warning, info, error) displayed are expected. The exception on the Ok button click is not expected and should be fixed.

**Comment by andromeda-224** [comment]
The issue with "Show Details" and "Hide Details" being difficult to see in FlatLaf Dark Mode. is not related to https://github.com/constellation-app/constellation/issues/2137. This is fixed with stylesheet. New ticket created for Display alert dialogs appearing on different screen #2159.

**Comment by HolandCrick** [comment]
@andromeda-224 Thanks for addressing the bug. It's generating 13 Notifications without exception error.

![image](https://github.com/user-attachments/assets/6f7adf14-42c4-489d-868c-6565877bed58)
