### ISSUE TITLE
Date time picker: Hard to change to a far apart year when disabled

### ISSUE THREAD

**Issue by Auriga2** [constellation-app/constellation#2142]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
The date time picker in the Layer by time Arrangement has `1970-01-01` in the `From` date  by default, and cannot be changed by typing on the field. User has to click the next arrow button on the year many times, one by one from 1970, if a recent year is required. 

'To' date is also locked, requiring more clicks if an year that's far apart is required. Similarly both dates are disabled in DAV. (Possibly there are other places)

![image](https://github.com/user-attachments/assets/16ea46f2-2d59-4a0a-b4b8-a5ec230953aa)

### Steps to Reproduce

1.  Click Arrange->Layer by time -> date range -> Absolute Range 

2. Click on `From` date and try to change Year to a recent year

**Expected behaviour:** It should be easier to change the year, possibly a drop down?

**Actual behaviour:** Change to an year that's far apart could require many clicks on arrows, one by one from the default year.

**Reproduces how often:** 100%

**Comment by HolandCrick** [comment]
Users can now type in dates. No longer having to click many times to drastically change year.
