### ISSUE TITLE
Schema View Null Pointer Exception

### ISSUE THREAD

**Issue by Delphinus8821** [constellation-app/constellation#2144]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
Sometimes if you open and close the Schema View a lot, a null pointer exception can be thrown.
This occurs in both v3.0-rc1 and v2.11

![image](https://github.com/user-attachments/assets/c3aaba37-ffe4-4f39-a211-24d3dd5a77f2)

### Steps to Reproduce

1.  Open Constellation and a graph

2.  Open and close the Schema View repeatedly until an exception is thrown

**Expected behaviour:** No exceptions

**Actual behaviour:** An exception is thrown

**Reproduces how often:** 20%

### Additional Information

This issue was found while testing #2143 #2145

**Comment by HolandCrick** [comment]
@Quasar985 Thanks for fixing the bug in Schema View. I have opened/Closed the Schima View over 50 time while several new graphs open and few existing graph open too. Did not face any exception error.
