### ISSUE TITLE
Experimental tool Add Hashmod - nothing happens (infinite waiting), no help page

### ISSUE THREAD

**Issue by andromeda-224** [constellation-app/constellation#2147]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Add Hashmod does not work with sample file (as ascertained from original PR).
[country_lat_lon.csv](https://github.com/user-attachments/files/16257947/country_lat_lon.csv)

### Steps to Reproduce

1.  Select Experimental -> Tools -> Add Hashmod

2.  Click on "Single" button and select sample .csv file. Click Open.

3.  Select options Create new Vertexes for non matching keys.

**Expected behaviour:** 
New nodes from csv file should be added to graph and visible.

**Actual behaviour:** 
Add Hashmod progress seems to be in infinite loop.

**Reproduces how often:** 100%

### Additional Information

Logic in code needs updating. ie. run() method in HashmodAction.java

**Comment by HolandCrick** [comment]
Cancel and Ok Buttons both giving Exception

**Comment by andromeda-224** [comment]
> Cancel and Ok Buttons both giving Exception also the Key attribute fields are read only. Need to allow user input.

Fix for exception is in PR #2151. The key attribute fields are meant to be read only as they are populated after the file has been loaded (for information only). The Import File is probably a more developed tool that is similar.

**Comment by HolandCrick** [comment]
@andromeda-224 - Thanks for working on Experimental-> tool-> Add Hashmod. It's giving Null Pointer Exception. 
![image](https://github.com/user-attachments/assets/6c3d9ad6-a856-46a2-900b-8ad173d0b9db)

**Comment by HolandCrick** [comment]
@andromeda-224 thanks for fixing the bug. It's working now.

![image](https://github.com/user-attachments/assets/473754ce-f3e1-4a77-8dc5-823992c27c2b)
