### ISSUE TITLE
Conversation View showing results from a different graph

### ISSUE THREAD

**Issue by OrionsGuardian** [constellation-app/constellation#2149]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

It appears that the Conversation data that is used in one graph will be re-used in the next graph that is activated when that graph does not contain conversation data of its own.

![image](https://github.com/user-attachments/assets/07912e9f-8a2d-492f-8b99-f212a7f2ea51)

The Conversation data should be cleared when a new graph becomes active.

**Comment by Auriga2** [comment]
Not present in V 2.11, so need fixed in v3

**Comment by HolandCrick** [comment]
@Auriga2 thanks a lot for fixing the bug. It's working now; does not need to select a different node to see any Conversation data again. All good now.
![image](https://github.com/user-attachments/assets/a9b40762-5b95-42a4-8c83-6227530dc2d3)
