### ISSUE TITLE
Testable Graph Builder  gives Exception 

### ISSUE THREAD

**Issue by HolandCrick** [constellation-app/constellation#2150]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Experimental ->Developer ->Testable Graph Builder 
make sure you are on existing any graph, not on a new graph.

### Steps to Reproduce

1.  Open Consty
2.  Open any graph or create a new graph
3.  Select Experimental ->Developer ->Testable Graph Builder 

**Expected behaviour:**No error

**Actual behaviour:** Give exception
Give Exception:
![image](https://github.com/user-attachments/assets/003a1bc1-2343-43c6-a5d4-2e7711c3b142)

**Reproduces how often:** 100%

### Additional Information

Any additional information, configuration or data that might be
necessary to reproduce the issue.

**Comment by Auriga2** [comment]
The code expects a blank graph to add the Testable graph. (So it works if run on an empty graph.) Should we enable it to add the testable graph on an existing graph or should we just handle the exception and show a warning message if clicked on a non empty graph? Not really sure of the use case of the Testable graph builder action.

**Comment by Delphinus8821** [comment]
@Auriga2 The Testable Graph builder was made for developers to have a consistent graph to test their work on, so it always creates the exact same graph. 

I think it would make sense to have a warning message if the action is run on a non empty graph.

**Comment by HolandCrick** [comment]
@arcturus2 thanks for fixing the bug. It's working now without error.
