### ISSUE TITLE
Test Notifications - some dialogs appearing on different screen/monitor

### ISSUE THREAD

**Issue by andromeda-224** [constellation-app/constellation#2159]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

If Constellation app is not on primary monitor, some of the Test Notification alert dialogs will appear on a different screen.

### Steps to Reproduce

1.  Create a new Graph.

2.  Select menu item Experimental -> Developer -> Test Notifications

3.  Click OK. 

**Expected behaviour:** All notification dialogs to appear on the same screen where the app is. 

**Actual behaviour:** Some dialogs (noticeably NotifyDisplayer.displayAlert) will appear on a different screen.

**Reproduces how often:**  100%

### Additional Information

Happens in v.3.0 and v2.11

**Comment by HolandCrick** [comment]
@andromeda-224  - Thanks for fixing the Test Notifications. All notification dialogs to appear on the same screen where the app is.
