### ISSUE TITLE
Analytic Graph Vertex Label sizing issue

### ISSUE THREAD

**Issue by DataQub3** [constellation-app/constellation#216]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Vertex labels in Constellation appear very large.  When I manually set them to 0.1 size, the size is correct, but the labels are offset from the corresponding vertex.

### Steps to Reproduce

1. In Constellation click on "File", "New Analytic Graph"
2. Click on menu items "Experimental", "Build Graph", "Sphere Graph builder" and accept the default values.

**Expected behaviour:** Vertex labels should be sized appropriately for viewing

**Actual behaviour:** The vertex labels are huge compared to the vertex icons

**Reproduces how often:** 100%

### Additional Information

Operating System: Ubuntu 18.04
Video Card: [AMD/ATI] Caicos XTX [Radeon HD 8490 / R5 235X OEM]

[SupportPackage-null-2020-01-28-14-51-37.zip](https://github.com/constellation-app/constellation/files/4120651/SupportPackage-null-2020-01-28-14-51-37.zip)

![analytic_graph_sphere](https://user-images.githubusercontent.com/7069058/73236057-f52bf580-41e0-11ea-8f0a-f4443e7dc6b8.png)

**Comment by DataQub3** [comment]
The output of Help->JOGL version is:

OpenGL version: 3.3 (Core Profile) Mesa 19.2.1
Vendor: X.Org
Renderer: AMD CAICOS (DRM 2.50.0 / 5.3.0-26-generic, LLVM 9.0.0)
Shading language version: 3.30

JOGL Attributes
Ant-Version: Apache Ant 1.9.4
Application-Library-Allowable-Codebase: *
Application-Name: Java Bindings for OpenGL
Codebase: *.jogamp.org
Created-By: 1.8.0_60-b27 (Oracle Corporation)
Extension-Name: com.jogamp.opengl
Implementation-Branch: origin/master
Implementation-Build: 2.3-b1469-20151010
Implementation-Commit: e794fc40ba723f2fca4ac892e873975fb393e007
Implementation-Title: Java Bindings for OpenGL Runtime Environment
Implementation-URL: http://jogamp.org/
Implementation-Vendor-Id: com.jogamp
Implementation-Vendor: JogAmp Community
Implementation-Version: 2.3.2
Manifest-Version: 1.0
Permissions: all-permissions
Specification-Title: Java Bindings for OpenGL API Specification
Specification-Vendor: JogAmp Community
Specification-Version: 2.3
Trusted-Library: true

GL Strings
Swap Interval  1
GL Profile     GLProfile[GL3/GL3.hw]
GL Version     3.3 (Core profile, arb, compat[ES2, ES3, ES31, ES32], FBO, hardware) - 3.3 (Core Profile) Mesa 19.2.1 [GL 3.3.0, vendor 19.2.1 ((Core Profile) Mesa 19.2.1)]
Quirks         []
Impl. class    jogamp.opengl.gl4.GL4bcImpl
GL_VENDOR      X.Org
GL_RENDERER    AMD CAICOS (DRM 2.50.0 / 5.3.0-26-generic, LLVM 9.0.0)
GL_VERSION     3.3 (Core Profile) Mesa 19.2.1
GLSL           true, has-compiler-func: true, version: 3.30 / 3.30.0
GL FBO: basic true, full true
GL_EXTENSIONS  190
               GL_AMD_conservative_depth GL_AMD_depth_clamp_separate GL_AMD_draw_buffers_blend GL_AMD_multi_draw_indirect GL_AMD_performance_monitor GL_AMD_pinned_memory GL_AMD_query_buffer_object GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_stencil_export GL_AMD_shader_trinary_minmax GL_AMD_texture_texture4 GL_AMD_vertex_shader_layer GL_AMD_vertex_shader_viewport_index GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_ES2_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_2_compatibility GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_compressed_texture_pixel_storage GL_ARB_compute_shader GL_ARB_conditional_render_inverted GL_ARB_conservative_depth GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_draw_indirect GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_shader GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gpu_shader5 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_occlusion_query2 GL_ARB_parallel_shader_compile GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_sprite GL_ARB_polygon_offset_clamp GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_bit_encoding GL_ARB_shader_clock GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_stencil_export GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_barrier GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map_array GL_ARB_texture_filter_anisotropic GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ATI_blend_equation_separate GL_ATI_meminfo GL_ATI_texture_float GL_ATI_texture_mirror_once GL_EXT_abgr GL_EXT_blend_equation_separate GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_polygon_offset_clamp GL_EXT_provoking_vertex GL_EXT_shader_integer_mix GL_EXT_texture_array GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_mirror_clamp GL_EXT_texture_sRGB GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_decode GL_EXT_texture_shared_exponent GL_EXT_texture_snorm GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array_bgra GL_IBM_multimode_draw_arrays GL_KHR_context_flush_control GL_KHR_debug GL_KHR_no_error GL_KHR_parallel_shader_compile GL_KHR_robust_buffer_access_behavior GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_sliced_3d GL_MESA_pack_invert GL_MESA_shader_integer_functions GL_MESA_texture_signed_rgba GL_NVX_gpu_memory_info GL_NV_conditional_render GL_NV_depth_clamp GL_NV_packed_depth_stencil GL_NV_texture_barrier GL_NV_vdpau_interop GL_OES_EGL_image GL_S3_s3tc
GLX_EXTENSIONS 34
               GLX_ARB_context_flush_control GLX_ARB_create_context GLX_ARB_create_context_no_error GLX_ARB_create_context_profile GLX_ARB_create_context_robustness GLX_ARB_fbconfig_float GLX_ARB_framebuffer_sRGB GLX_ARB_get_proc_address GLX_ARB_multisample GLX_EXT_buffer_age GLX_EXT_create_context_es2_profile GLX_EXT_create_context_es_profile GLX_EXT_fbconfig_packed_float GLX_EXT_framebuffer_sRGB GLX_EXT_import_context GLX_EXT_texture_from_pixmap GLX_EXT_visual_info GLX_EXT_visual_rating GLX_INTEL_swap_event GLX_MESA_copy_sub_buffer GLX_MESA_multithread_makecurrent GLX_MESA_query_renderer GLX_MESA_swap_control GLX_OML_swap_method GLX_OML_sync_control GLX_SGIS_multisample GLX_SGIX_fbconfig GLX_SGIX_pbuffer GLX_SGIX_visual_select_group GLX_SGI_make_current_read GLX_SGI_swap_control GLX_SGI_video_sync GLX_EXT_libglvnd GLX_EXT_no_config_context
-----------------------------------------------------------------------------------------------------

**Comment by cygnus-x-1** [comment]
Wow, this is bizarre.

**Comment by DataQub3** [comment]
This is no longer a bug in the current Constellation source.
Since submitting this bug, Constellation source has been updated.  Using source code from today, Java 11 and Netbeans 11.3, the labels are now displayed properly on the same OS/hardware.
![updated](https://user-images.githubusercontent.com/7069058/78529779-8773f980-7821-11ea-8bee-5e4a715be5e9.png)

**Comment by arcturus2** [comment]
Thanks @DataQub3 I had wanted to get back to you to see if you could test this out after our framework upgrade. You bet me to it - glad its working; you made my day!
