### ISSUE TITLE
Zoom In and Zoom Out keyboard shortcuts not working in Linux.

### ISSUE THREAD

**Issue by OrionsGuardian** [constellation-app/constellation#2165]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The recently added shortcuts to Zoom In (Ctrl-Alt-Up) and to Zoom Out (Ctrl-Alt-Down)
are not working in the Linux version of the V3 Release candidate 

**Expected behaviour:** Keyboard shortcuts should work the same in all environments.

**Actual behaviour:** Zoom In and Zoom Out shortcuts are only working in Windows version.

**Reproduces how often:** 100%

**Comment by HolandCrick** [comment]
@Quasar985 thanks for fixing the Linus bug. Both issues (#2176 and #2165) are working correctly now on the Linux Box.
