### ISSUE TITLE
Conversation View in Linux - Content Bubble is split into two parts

### ISSUE THREAD

**Issue by OrionsGuardian** [constellation-app/constellation#2166]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Conversation Bubbles that appear in the Right Hand column do not have their segments connected.
The main content bubble is displayed on the left, and the speech source marker is displayed on the right.

### Steps to Reproduce

Create 2 nodes with 2 transactions between them, one in each direction.
Add/activate the Content attribute on the transactions in the Attribute Editor and put in some text in that Content attribute for each transaction (and put a date on those transactions as well.)

Open the Conversation View.
Select one of the Nodes in the graph.
There should be 2 speech bubbles (1 from the source, and 1 from the destination)
In Linux, the speech bubble in the right side of the Conversation Screen is split into 2 parts:
![image](https://github.com/user-attachments/assets/e3a80fcf-3569-47d1-bea7-24f1000ca78d)
The triangular speech indicator is not connected to the main content bubble.

**Expected behaviour:** Each conversation bubble should be fully connected.
**Actual behaviour:** Content bubbles in the right column have been split.

**Reproduces how often:** 100%

### Additional Information

It appears to be caused by the size of the font being used to show the Date beneath the Content message.

**Comment by HolandCrick** [comment]
@OrionsGuardian thanks a lot for aggressing the Conversation View in Linux.
Tested the nightly build on Linux and this issue is now resolved.
