### ISSUE TITLE
Layer View masking is not working as expected

### ISSUE THREAD

**Issue by andromeda-224** [constellation-app/constellation#2170]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
When selecting multiple layers on the Layers View, all the corresponding elements on the selected layers are not displayed.

### Steps to Reproduce

1.  Add a node to layer 1.

2.  Add 3 new layers (will refer to them as layer 2, layer 3 and layer 4).

3. Select layer 2 only in Layers View. Add a new node to layer 3.

4.  Select layer 3 only in Layers View. Add a new node to layer 3.

5.  Select layer 4 only in Layers View. Add a new node to layer 4.

6. Deselect Layers. All nodes show up on Layer 0 (the complete graph).

7. Select layer 1, layer 2 and layer 3. Only layer 1 node shows on the graph.

**Expected behaviour:** Expect all elements from all selected layers to be displayed on the graph.

**Actual behaviour:** Only elements from the lowest numbered selected layer is displayed when all layers are selected. Or select layers 2 & 4, all layer 2 & 4 elements show up.  With layers 1 & 3 selected, those elements show up. With layers 1 & 4, those elements show up.  It's to do with masking logic.

**Reproduces how often:** 100%

### Additional Information

Occurs in v2.11.0 and v3.0.0 - rc1

**Comment by HolandCrick** [comment]
@OrionsGuardian - thanks for fixing the bug. All elements from all selected layers to be displayed on the graph.
