### ISSUE TITLE
Welcome page allows multiple copies of the same graph to open, throwing exceptions

### ISSUE THREAD

**Issue by Auriga2** [constellation-app/constellation#2172]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
Recent graphs in the Welcome page can be clicked multiple times, which opens the same graph in multiple tabs. 

![image](https://github.com/user-attachments/assets/b816d602-9452-42fb-a2ce-3cb0fa1ed442)

If you do this on a larger graph, constellation can run out of memory and stuck. 

![image](https://github.com/user-attachments/assets/ca8da986-13c7-488c-8aed-dd3b331618db)

Clicking on these graphs/tabs while partially loading throws this exception.

![image](https://github.com/user-attachments/assets/9a76ae04-25e7-427b-8542-9496140ea65a)

### Steps to Reproduce

1.  Open constellation, open a larger graph and close the app which will add it in the `Recent` section in the Welcome page.

2.  Open constellation and double click on the graph above in the Welcome page

3.  Observe it creating 2 graphs. 
4. Clicking on the graph above in the Welcome page multiple times can cause the 1st exception 
5. Clicking on the graph above in the Welcome page a few times and clicking on these graphs/tabs that are partially loading can cause the 1st exception 

**Expected behaviour:** Welcome page not allowing to open multiples of the same graph and no exceptions thrown

**Actual behaviour:** Welcome page allows to open multiples of the same graph and exceptions are thrown

**Reproduces how often:** 90% with a larger graph

### Additional Information
Observed in v3.0.0.-rc1
Same behavior in v2.11

**Comment by HolandCrick** [comment]
@Quasar985 thanks for fixing the - Welcome page allows multiple copies of the same graph to open, throwing exceptions. It not throwing exception anymore. Working as expected.
