### ISSUE TITLE
constellation_client in the nightly build is not compatible with older versions of Python

### ISSUE THREAD

**Issue by OrionsGuardian** [constellation-app/constellation#2176]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Trying to run Jupyter Notebook with the Linux nightly build has shown this problem.

![image](https://github.com/user-attachments/assets/3da8367e-a98a-462c-911c-f7a4655f342f)

This is from testing on a Centos 7 Linux box where the latest release of Python was version 3.6.8.
The new code apparently requires Python 3.9 or later.

I would suggest changing the code to remain compatible with older versions of Python (3.6 onwards)

### Behaviour

**Expected behaviour:** 
Expect to be able to continue using Centos 7 Linux with Python 3.6.8 to run Jupyter Notebooks connecting to Constellation.

**Actual behaviour:**
Fails to import the constellation_client.py due to new code requiring a later release of Python.

**Reproduces how often:**
100%

**Comment by HolandCrick** [comment]
@Quasar985 thanks for your help to fix the code. Both issues (#2176 and #2165) are working correctly now on the Linux Box.
