### ISSUE TITLE
Notes view warning message has no styling

### ISSUE THREAD

**Issue by Quasar985** [constellation-app/constellation#2188]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Warning message for notes view does not have any styling applied to it.

### Steps to Reproduce

1. Create new graph
2. Open notes view
3. Click "Create note", don't fill in any details, then click "Add Note"
4. Observe warning message is not styled

**Expected behaviour:** Warning popup should be styled according to chosen theme

**Actual behaviour:** Warning message has no styling

**Reproduces how often:** Always

### Additional Information
N/A

**Comment by HolandCrick** [comment]
@Quasar985 - thanks for fixing the Create Note enhancement. It looks great now.

![image](https://github.com/user-attachments/assets/7fe29e24-1b5f-420a-9e9d-93da197f5ca7)
