### ISSUE TITLE
Basic support for Intel graphics cards

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#22]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

Provide basic support for Intel based graphics cards. Constellation currently does not run/isn't usable on a laptop that uses the Intel on board graphics card.

### Steps to Reproduce

1. Unzip Constellation on a machine that has an Intel on-board graphics card
2. Run Constellation

**Expected behaviour:** Constellation should render a new graph correctly

**Actual behaviour:** Constellation fails to open a graph due to unsupported OpenGL versions

**Reproduces how often:** 70%

**Comment by alistaircohen** [comment]
I have been able to get Constellation to run with ~10000 nodes on a Lenovo T480s, with a Intel UHD 620 graphics card and OpenGL 4.5. 
![10000nodes on a Lenovo T480s Intel UHD 620](https://user-images.githubusercontent.com/1286331/63557534-7b864080-c58c-11e9-8e84-cd20ba7a48e2.PNG)

**Comment by arcturus2** [comment]
Thanks @alistaircohen. I've also had feedback on it working on a Microsoft Surface Pro 3 and HP Spector so I'm going to put a wiki page to document this and change the wording on the website.

**Comment by arcturus2** [comment]
I created [Supported Graphics Cards](https://github.com/constellation-app/constellation/wiki/Supported-Graphics-Cards) and added your machine's spec to it. It looks as though Constellation does work on newer models of the Intel onboard card and if so this issue could be closed. I want to wait and see a bit more before deciding.
