### ISSUE TITLE
Password Obfuscator/Deobfuscator throwing error

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#2205]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

In recent times, a change was made in `PasswordUtilities` to change the algorithm spec from AES/CBC/PKCS5Padding to AES/GCM/NoPadding. This has inadvertently broken the obfuscate algorithm of `PasswordObfuscator` and deobfuscate algorithm of `PasswordDeobfuscator`. It throws the following exception when calling the init function of the Cipher object:
```
java.security.InvalidAlgorithmParameterException: AlgorithmParameterSpec not of GCMParameterSpec
```
It turns that when we changed the algorithm spec to what it is currently, we should have also changed the obfuscate and deobfuscate functions to create a `GCMParameterSpec` object instead of an `IvParameterSpec` (as it is currently doing)

### Steps to Reproduce

Note this will only be possible to fix in the local instance of Constellation (run in Netbeans)

1. Create an action which you can easily access that calls one of `PasswordObfuscator.obfuscate` or `PasswordDeobfuscator.deobfuscate`
2. Compile and launch Constellation
3. Run this action

**Expected behaviour:** No exception thrown

**Actual behaviour:** Exception thrown

**Reproduces how often:** 100%

### Additional Information

Any additional information, configuration or data that might be
necessary to reproduce the issue.

**Comment by HolandCrick** [comment]
@Quasar985 Thanks for fixing this bug. Looks like it's working now.
