### ISSUE TITLE
Add Help to the Documentation Pane in the Analytic View 

### ISSUE THREAD

**Issue by Delphinus8821** [constellation-app/constellation#2222]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

In the Analytic View, the documentation pane shows the help page for the analytic which is currently selected. The documentation page currently does not show anything if a question is selected. As help pages exist for the questions, it would be good to show the help in the documentation page.

### Steps to Reproduce

1.  Open the Analytic View and select the Documentation Pane.

2.  Select a question from the Analytic View

3.  See that no help is shown in the Documentation pane 

### Behaviour

**Expected behaviour:** Help documentation is shown

**Actual behaviour:** No help is shown

**Reproduces how often:** 100%

**Comment by HolandCrick** [comment]
@Delphinus8821  Thanks for adding the enhancement. It's very helpful tips.
![Image](https://github.com/user-attachments/assets/2960acb9-bb68-447b-a3ba-a35a97be85c4)
