### ISSUE TITLE
Layers View

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#223]
This is a new view that can work similar to other applications like Adobe Photoshop, Gimp or Visio.

The idea would be to allow a user to slide a graph into layers so that analysis can be done in context of the graph with the ability to dim/hide layers and show others. The current method is to select the part of the graph you are interested in and then open that in a new graph (Ctrl +U). This could be avoided by allowing the user to stay in context of the entire graph but focus on answering one question.

This ticket has a large scope and not everything needs to be done to start with. Based on what is left over, new issues can be created to track them.

Features are:
 * ability to name layers
 * ability to show/hide layers
 * ability to add a selection to a layer
 * nodes and transactions can be part of multiple layers
 * automatically generate layers based on an attributes (e.g transaction types)

**Comment by aldebaran30701** [comment]
Some documentation about Layers View usage. 

**Functionality:**
Add and remove elements of a graph to a layer.
Add via manual selection, or by entry of a query to allow dynamic addition of an element.

**Usage:**
Layers view functionality is accessible from two locations;
 - Right click context menu on an element
 - Experimental -> Views-> Layers View (Main UI View)

The right click context menu allows selected elements to be added or removed from a specified layer.
To do so, have an element selected and right click -> Add to layer -> enter in value from 2-32. Layer 1 is the default show all graph.
![Add to layer](https://user-images.githubusercontent.com/58677759/79290800-309aae00-7f0c-11ea-93bf-380419d80ff3.gif)


The Layers View lists all layers stored on the graph. 
The checkbox marks the visibility of that layer. 
The query input is for entering a query to dynamically show a layer based on element attributes.
The description input can be used to describe the output of the query.
![Toggle Layers](https://user-images.githubusercontent.com/58677759/79291049-c59da700-7f0c-11ea-9f02-9b288d3d215c.gif)

The query will be structured as below

**String comparison:**
Label == Vertex #0<Unknown>
Label != Vertex #0<Unknown>

**Float comparison:**
visibility == 0.0
visibility != 0.0
visibility > 0.0
visibility < 1.0

**Boolean comparison:**
dim == false
dim != true

With conjunction and disjunction of queries, ( ) must surround each query.
Separated by only the boolean operators || or && ie. (Query1)||(Query2)

**Disjunction**
(Label == Vertex #0<Unknown>)||(dim != false)

**Conjunction**
(Label == Vertex #0<Unknown>)&&(dim != false)

NOTE: Below does not currently function 100% correct. 
(Query1)||((Query2)&&(Query3)) - format
(Label == Vertex #0<Unknown>)||((Label != Vertex #2<Unknown>)&&(color == #760a06))

**Attributes:**
VertexAttributes and TransactionAttributes are accessible via their name.
The following attribute names are usable for querying against.
 - color - Hex value of vertex/transaction color
 - dim - Boolean state of the vertex or transaction
 - Identifier - String identifier
 - Label - String label
 - lradius (vertex only) - Float value of label radius
 - nradius (vertex only) - Float value of vertex radius
 - overlay_color - Hex value of vertex/transaction overlay color 
 - selected - Boolean state if selected of vertex/transaction
 - visibility - float value of vertex/transaction visibility 1.0 = visible
 - x (vertex only) - float location
 - x2 (vertex only) - alternative float location
 - y (vertex only) - float location
 - y2 (vertex only) - alternative float location
 - z (vertex only) - float location
 - z2 (vertex only) - alternative float location
 - directed (transaction only) - Boolean is the transaction directed
 - width (transaction only) - Float value of the transaction width

Elements added through a dynamic query will remain added to that layer even after the query has been removed.
To remove them, use the right click context menu -> remove.
An element deleted will be removed from every layer.

Below is an example of adding many elements to a layer.
![Add many to layer](https://user-images.githubusercontent.com/58677759/79291271-62604480-7f0d-11ea-8b52-169166807779.gif)

**Known issues and future implementation ideas:**
 - Layers View labels are misaligned with text inputs
 - Fully nested dynamic queries not correctly functional
 - Some queries incorrectly update the layer mask
 - Visibility of the element is 1.0 (shown) but graph still shows element as visibility 0.0 (not shown)
 - Numeric comparison > and < not implemented completely.
 - No state to keep queries specific to a graph
 - No entry in .star file to save state to graph

**Comment by cygnus-x-1** [comment]
The first time I opened the Layers (after using Constellation for a while), it locked up the entire applications. Other than that, no major bugs were encountered. Some usability thoughts:
- Adding and removing to a layer (i was using the right-click context menu) does not immediately update the visualisation (you've got to turn the layer on and off again to force an update) which made me question if it worked.
- When a layer enabled (and anything outside the layer is hidden), hidden elements can still be selected/interacted with. This is an issue given the intended usage is to limit your analysis to only the current layers.
- There are some useful keyboard shortcuts for deselecting all layers (ctrl+alt+d) and toggling layers (ctrl+alt+<number>) - these need to be more obvious. There could also be a shortcut for creating layers (ctrl+shift+<number>?).
- The query language is a little obtuse. My first query (transactions - Identifier startswith 2) caused a hash error popup as i'd not surrounded a number in quotation marks. There were also queries i just couldn't get to work (dim == 'true' gave me "ExpressionException: Unable to find implementation of operator: EQUALS"). There should be validation applied before attempting to execute the query, and the result of that should be visible to the UI (a red box to say my query is broken).
- It would also be helpful to be able to delete layers.

**Comment by aldebaran30701** [comment]
Closing this as it has been implemented. Any outstanding work or future issues will be created in separate tickets to track progress.
