### ISSUE TITLE
Move Word Cloud View out of Experimental

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#2232]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Word Cloud View has been available in Experimental since the beginning of v3. Given there haven't been any glaring issues discovered since the release, I think it's just about at a point where it can be moved out of Experimental.

**Expected behaviour:** Word Cloud accessible from View menu

**Actual behaviour:** Word Cloud accessible from Experimental View menu

**Reproduces how often:** 100%

### Additional Information

Any additional information, configuration or data that might be
necessary to reproduce the issue.

**Comment by HolandCrick** [comment]
@Quasar985 Thank you for enhancing View Menu.  Word Cloud accessible from View menu and not form Experimental View menu. Working as expected from new location..
