### ISSUE TITLE
Too many levels of error messages

### ISSUE THREAD

**Issue by formalhaut69** [constellation-app/constellation#229]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

When running either the Merge Nodes, Merge Transactions, or Select Top N plugins when not all the information required for the plugin has been entered, you will receive error messages and a plugin exception. 
![image](https://user-images.githubusercontent.com/58677762/73794099-945f7700-47f7-11ea-9a84-f8c9e6a6439a.png)
Perhaps only the 3rd error window should appear or maybe a more meaningful window so that the user can understand what information they didn't enter properly. 

### Steps to Reproduce

1. Select one of the listed plugins
2. Click the "Go" button

**Expected behaviour:** A window should appear explaining what information the user didn't enter

**Actual behaviour:** 2 error windows and an exception appear

**Reproduces how often:** 100%

**Comment by arcturus2** [comment]
Thank you for raising this and agreed that it should be just the last dialog box that appears. Constellation has its own `PluginException` and when there is an error, that should show a dialog box and prevent the build in NetBeans error dialog boxes from appearing. We did investigate this and fix it at one point.

**Comment by arcturus2** [comment]
A `PluginException` thrown in the edit method of a `SimpleEditPlugin` seems to be caught and displayed in the `SimpleEditPlugin` itself, then rethrown, caught and displayed in `DefaultPluginEnvironment`, and occasionally rethrown again until the NetBeans framework catches displays it.

In all instances, `PluginExceptions` should be caught, reported and displayed in one place and not rethrown. Whether this is `SimpleEditPlugin` or `DefaultPlugiEnvironment` is a design decision.

Currently the number of ties and manner in which these exceptions are reported and rethrown is also dependant on the manner in which the plugin executed through the `DefaultPlugiEnvirnnment` (e.g. `executePluginNow` vs `executePluginLater`, although it is not merely this simple).

**Comment by arcturus2** [comment]
@formalhaut69 so I had this issue tracked in my internal issues list so I've just added to yours and updated the title...hope your ok with that 😄.

**Comment by serpens24** [comment]
I have reproduced this problem in the debugger to identify where/when these dialogs and exceptions are being thrown.
They are:
1) Within the exception handler of SimpleQueryPlugin.run() with a call to interaction.notify, this displays the longer of the two 'Select Top N' error dialog. (lines 173-179):
```
                    } catch (Exception e) {
                        final String msg = Bundle.MSG_Query_Failed(graph, getName());
                        interaction.notify(PluginNotificationLevel.ERROR, msg + "\n" + e.getMessage());
                        cancelled = true;
                        LOGGER.log(Level.WARNING, msg, e);
                        throw e;
                    }
```

2) Within the exception handler of DefaultPluginEnvironment.executePluginLater(), this is actually a result of the 'throw e' propagating the exception up from SimpleQueryPlugin.run(), above. This results in the shorter of the two 'Select Top N' error dialogs.
```
            } catch (PluginException ex) {
                auditPluginError(plugin, ex);
                interaction.notify(ex.getNotificationLevel(), ex.getMessage());
                ex.printStackTrace();
                if (currentReport != null) {
                    currentReport.setError(ex);
                }
            }
```

3) The bottom exception showing a stack trace is actually throwing inadvertantly as a result of the **LOGGER.log(Level.WARNING, msg, e);** call within the first code example above. Clearly this isn't the desired outcome. I found that by removing the exception (e) as a final parameter still results in the LOGGER correctly logging the error to the error log, but without the exception being thrown. As the code currently exists, the following log extract is what is produced by the LOGGER call:
--------------------------------------------------------------------------------------------------------
FINE [au.gov.asd.tac.constellation.plugins.PluginExecution]: Select Top N
INFO [au.gov.asd.tac.constellation.views.dataaccess.panes.DataAccessPane]: Plugins run.
Select Top N: Action failed: au.gov.asd.tac.constellation.graph.locking.DualGraph@757edcf4; Select Top N
Select a type category
WARNING [au.gov.asd.tac.constellation.plugins.templates.SimpleQueryPlugin]: Action failed: au.gov.asd.tac.constellation.graph.locking.DualGraph@757edcf4; Select Top N
au.gov.asd.tac.constellation.plugins.PluginException: Select a type category
	at au.gov.asd.tac.constellation.views.dataaccess.plugins.utility.SelectTopNPlugin.edit(SelectTopNPlugin.java:206)
	at au.gov.asd.tac.constellation.plugins.templates.SimpleQueryPlugin.describedEdit(SimpleQueryPlugin.java:265)
[catch] at au.gov.asd.tac.constellation.plugins.templates.SimpleQueryPlugin.run(SimpleQueryPlugin.java:165)
	at au.gov.asd.tac.constellation.graph.node.plugins.DefaultPluginEnvironment.lambda$executePluginLater$0(DefaultPluginEnvironment.java:123)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
SEVERE [au.gov.asd.tac.constellation.graph.node.plugins.DefaultPluginInteraction]: Select Top N: Select a type category
au.gov.asd.tac.constellation.plugins.PluginException: Select a type category
	at au.gov.asd.tac.constellation.views.dataaccess.plugins.utility.SelectTopNPlugin.edit(SelectTopNPlugin.java:206)
	at au.gov.asd.tac.constellation.plugins.templates.SimpleQueryPlugin.describedEdit(SimpleQueryPlugin.java:265)
	at au.gov.asd.tac.constellation.plugins.templates.SimpleQueryPlugin.run(SimpleQueryPlugin.java:165)
	at au.gov.asd.tac.constellation.graph.node.plugins.DefaultPluginEnvironment.lambda$executePluginLater$0(DefaultPluginEnvironment.java:123)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
--------------------------------------------------------------------------------------------------------

By removing the 'e' from the call the following is what is produced by the LOGGER call:
--------------------------------------------------------------------------------------------------------
INFO [au.gov.asd.tac.constellation.views.dataaccess.panes.DataAccessPane]: Plugins run.
Select Top N: Action failed: au.gov.asd.tac.constellation.graph.locking.DualGraph@d837407; Select Top N
Select a type category
WARNING [au.gov.asd.tac.constellation.plugins.templates.SimpleQueryPlugin]: Action failed: au.gov.asd.tac.constellation.graph.locking.DualGraph@d837407; Select Top N
SEVERE [au.gov.asd.tac.constellation.graph.node.plugins.DefaultPluginInteraction]: Select Top N: Select a type category
au.gov.asd.tac.constellation.plugins.PluginException: Select a type category
	at au.gov.asd.tac.constellation.views.dataaccess.plugins.utility.SelectTopNPlugin.edit(SelectTopNPlugin.java:206)
	at au.gov.asd.tac.constellation.plugins.templates.SimpleQueryPlugin.describedEdit(SimpleQueryPlugin.java:265)
	at au.gov.asd.tac.constellation.plugins.templates.SimpleQueryPlugin.run(SimpleQueryPlugin.java:165)
	at au.gov.asd.tac.constellation.graph.node.plugins.DefaultPluginEnvironment.lambda$executePluginLater$0(DefaultPluginEnvironment.java:123)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
--------------------------------------------------------------------------------------------------------

**Comment by serpens24** [comment]
As per above comment the LOGGER call should be updated to not throw its own exception, this can be done by not iuncluding the e parameter in the call.

Finally, it seems a decision needs to be made where to ultimately catch and report the error, @arcturus2 calls out SimpleEditPlugin or DefaultPluginEnvironment as options and these line up with my analysis above. I'm leaning towards using DefaultPluginEnvironment to ultimately report the erro, but will confirm this works now.

**Comment by serpens24** [comment]
So the above apporach works, however rather than deleting the line:
`interaction.notify(PluginNotificationLevel.INFO, msg + "\n" + e.getMessage());
`
Changing it to the following allows the error to be logged, but not thrown as as dialog.
`interaction.notify(PluginNotificationLevel.INFO, msg + "\n" + e.getMessage());
`
