### ISSUE TITLE
New graph button sometimes disappears

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#23]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

This happens randomly. I think it is a race condition type of issue which should be investigated and fixed.

`
INFO [org.openide.loaders.FolderInstance.Toolbars]: Cannot create org.openide.loaders.FolderInstance$HoldInstance@276bd96d[Toolbars/File]
java.io.IOException: Cyclic reference. Somebody is trying to get value from FolderInstance (org.openide.awt.Toolbar$Folder) from the same thread that is processing the instance
    at org.openide.loaders.FolderInstance.instanceCreate(FolderInstance.java:299)
    at org.openide.loaders.FolderInstance.instanceForCookie(FolderInstance.java:580)
    at org.openide.loaders.FolderInstance$HoldInstance.instanceCreate(FolderInstance.java:1153)
[catch] at org.openide.loaders.FolderInstance$1R.instances(FolderInstance.java:700)
    at org.openide.loaders.FolderInstance$1R.run(FolderInstance.java:721)
    at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
    at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
`

### Steps to Reproduce

1. Open Constellation

**Expected behaviour:** The new graph icon should be visible as the first toolbar icon

**Actual behaviour:** The new graph icon is missing

**Reproduces how often:** 5%

**Comment by aldebaran30701** [comment]
This seems to be a common bug. A similar scenario has been reported about the NetBeans environment.
https://netbeans.org/bugzilla/show_bug.cgi?id=232389
Their scenario was with a toolbar item, but others have reported similar issues with different buttons.

The development team also find great difficulty in reproducing this issue. 
I initially launched over 40 manual applications in an attempt to replicate this. No Cigar.
The forum post mentioned 

> _"...It's difficult to debug, and fixing it would be probably quite risky.
I would prefer to have much more time for testing changes in this area."_

**Comment by arcturus2** [comment]
Thanks for the dedication testing this one @aldebaran30701. Opening it 40 times sounds like a ton of patience.

This has happened often when I had a slower computer but I can;'t remember the last time this happened to me after getting an upgraded computer.

I'll keep this open for some more time and review it when we upgrade to NetBeans 11. I'll take it off the Kanban board too.

**Comment by arcturus2** [comment]
This hasn't occurred for a long time since this was raised. It will be worth seeing if this comes up in v2. If not let's close it.
