### ISSUE TITLE
Import from delimited feedback on success

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#232]
The import from delimited does not provide any feedback to whether the import completed succesfully or of there was a failure. Perhaps something like "123 records imported successfully" would be useful.

Given the importer is a floating dialog box, if you click import and the dialog is on top of the graph, you can sit there waiting for it to tell you that the import finished.

**Comment by aldebaran30701** [comment]
@arcturus2 Happy to close this now?
