### ISSUE TITLE
Unable to remove queries in the Data Access View

### ISSUE THREAD

**Issue by formalhaut69** [constellation-app/constellation#235]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Within the data access view, I've noticed that there doesn't appear to be a way to delete saved queries. I think users should be able to to do this so that the list of saved queries doesn't fill up too much and become difficult to navigate

### Steps to Reproduce

1. Select Views -> Data Access View -> Options -> Load

**Expected behaviour:** An option to remove a saved query

**Actual behaviour:** Currently no way to remove saved queries

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information
Within the load query menu dialog, perhaps the remove button could be placed between the "OK" and "Cancel" button and would delete whatever query was currently highlighted.
![image](https://user-images.githubusercontent.com/58677762/73896046-867e2480-48d1-11ea-928f-a66fc602a3be.png)

**Comment by mimosa2** [comment]
It seems this enhancement already done . ( See below). I have tested this and looks fine to me.  I can update the help text to reflect the changes.

![DA_option_load](https://user-images.githubusercontent.com/54261086/79524849-dc770180-80a4-11ea-8edb-65d1adca5587.PNG)

**Comment by arcturus2** [comment]
>  I can update the help text to reflect the changes.
OK please do @mimosa2

**Comment by mimosa2** [comment]
Confirming that formalhaut69 and serpens24 completed this task earlier. As mentioned before I will only update the help text to reflect the changes.
