### ISSUE TITLE
Test v1.3.0

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#247]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Can we test [v1.3.0](https://github.com/constellation-app/constellation/releases/tag/v1.20200225.104006) and make sure it works without issues?

I need help testing on Windows, Linux and Mac. Mac will just be the Linux version.

**Comment by aldebaran30701** [comment]
I have a query regarding the Named Selections behaviour. When creating a selection and dimming any node that isn't selected, then deleting that selection from the Named Selection view - the nodes do not un-dim. A workaround is to create a new selection and reset the selection via inverting the dim. Is this behaviour sufficient for use within the community? or does it need a ticket?

**Comment by arcturus2** [comment]
@aldebaran30701 that is a good question. I think the way it works now is fine. If you dim and then delete the named selection, it can stay dimmed. There are also options to select the dimmed nodes and undim them from the Selections menu.

The KTrus and Hierachical Clustering had an interactive mode which could be toggled so they were the main use case for it to make sure things got reverted back when you came out of interactive mode.

**Comment by arcturus2** [comment]
I've added the new logo, map providers and the experimental jdbc connector and bumped this to v1.3.0.

Can I get some help to please test this out before we get @arc0 to publish this on the Constellation website?

**Comment by StoltHD** [comment]
On Windows 10 build 19546 (insider version), The OpenStreetView map are just black, all the others are showing maps and seems snappy and without any noticable delays or lags...

I Do not know for what reason...

**Comment by arcturus2** [comment]
Thanks for the feedback @StoltHD. I noticed this also during testing. If you click on Help -> Show Logs then you can see the url's it's trying to reach to download the different tiles. They all work when I paste them in the browser but they fail to work from Constellation.

@cygnus-x-1 if you have any ideas then please let me know.

**Comment by arcturus2** [comment]
Released v1.3.1.
