### ISSUE TITLE
Setting a choice in updateParameters causes the DAV plugin to be enabled

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#26]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

Setting a choice in `updateParameters` in a Data Access View (DAV) plugin will fire an event and cause the plugin to be enable. For example refer to `ExtractFromContent` or `SplitNodesPlugin` which have this issue and so for now, the `setChoice` logic has been commented out.

### Steps to Reproduce

1. Open the Data Access View
2. Open a graph

**Expected behaviour:** No plugin is active

**Actual behaviour:** The Extract from Content plugin or Split Nodes plugin is enabled in the DAV

**Reproduces how often:** 90%

### Additional Information

The issue currently does not occur because the relevant code is commented.

**Comment by aldebaran30701** [comment]
Does this issue relate to the following state?

1. Open Constellation
2. Open Data Access View
3. Open a graph
4. Edit a parameter from within any plugin
The above leads to the plugin becoming selected. My question is, is this the behaviour described from the issue?

Uncommenting the relevant code and testing reveals that no odd behaviour occurs following the steps to reduce listed in the issue.
If they are the same issue, it seems that all plugins have this behaviour by default; not just the ones listed within the issue.

**Comment by arcturus2** [comment]
Hey @aldebaran30701, the plugin being enabled when changing a parameter is the expected behaviour.

The issue was that with the mentioned lines uncommented, when you open a new graph, the plugin is enabled. Can you try uncommenting the lines in the SplitNodesPlugin and try to see if the issue occurs?

https://github.com/constellation-app/constellation/blob/7286c5bfa6685cd6cb5e1fdcdf8dafb13c4a5501/CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/SplitNodesPlugin.java#L125-L128

In theory what would happen is the split nodes plugin becomes enabled when you open a new graph.

**Comment by aldebaran30701** [comment]
I did manage to get this event to occur, and as a side note, it did not seem to occur often.
A possible fix which seems to prove viable in initial testing is the following:
As the SplitNodesPlugin uses it's updateParameters() method to check graph type for correlations, the initial checking of the graph and assigning of the transaction type makes the plugin become enabled on launch.   [UpdateParameters code](https://github.com/constellation-app/constellation/blob/7286c5bfa6685cd6cb5e1fdcdf8dafb13c4a5501/CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/SplitNodesPlugin.java#L124)
I propose an overloaded setChoice method which takes the following form.
![image](https://user-images.githubusercontent.com/58677759/71047635-4d0c2100-218c-11ea-9698-0bdd2dc67c1a.png)
This enables the values which are set at graph open, to be still set correctly, but to not trigger a change event. This should be safe as it is only utilised on values which are not changed via entry from the user (ie. dropdown menu)

Another alternate implementation could be to change the signature of setChoice(...), but it would require refactoring of other code.
I have not been able to replicate the issue thus far with the code above implemented.

**Comment by aldebaran30701** [comment]
Recreation of this issue from my experience is from doing the following:
1. open constellation
2. open DAV
3. open new analytic graph
4. expand split nodes plugin
    a. select "correlation"
    b. uncheck split nodes plugin
5. close graph
6. open new analytic graph

These steps seem to reproduce the issue 100% of the time thus far. "split node plugin" and "extract from .. plugin" seem interchangeable with these steps and produce the same result.

**NOTE**: The issue is still persistent even with the code commented out. the current release will produce the issue when following the steps above.

**Comment by arcturus2** [comment]
@aldebaran30701 nice work on the reproducer. I didn't realise this was happening with that code commented out. Are you still ok to look into this when you can?

If so and say you need to make a change that requires updates to the 2 existing plugins, that is fine too. I'm relying on other developers reading `CHANGELOG.md` as the primary way to communicate to them that they need to be aware of changes that could affect them in their modules dependant off Constellation ("Core").
