### ISSUE TITLE
Cancel running plugins via the API

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#262]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

It would be useful to be able to pragmatically cancel (i.e Interrupt) running plugins via the Rest API. In order to cancel plugins, you probably need to have a Restful endpoint to list all of the running plugins too.

**Comment by Auriga2** [comment]
Hi @arcturus2 I had a look at this, and tried to see how the API works first. I cannot see the plugins I run through the API updated in the Plugin Reporter. Is that the intended behaviour? If I try to run the same in constellation afterwards, sometimes it seems to hang in the 'Waiting' state (See below image).

In this issue, do you want to list all the plugins that are listed as 'waiting' in the Plugin Reporter, for a specified graph? 

![image](https://user-images.githubusercontent.com/64826928/83843014-4aee4c80-a743-11ea-8eb9-05f6abaea3df.png)

Also we cannot see a way to cancel a plugin in the constellation other than cancelling processes from the status bar at the bottom. Do you mean to mimic this behaviour through API?

**Comment by arcturus2** [comment]
Hi @Auriga2 

> I cannot see the plugins I run through the API updated in the Plugin Reporter. Is that the intended behaviour? 

You should be able to so something may have gone wrong here. Just to double check we are talking about the same thing are you referring to the built in Rest API? You start this from Tools -> Start Rest Server.

 > If I try to run the same in constellation afterwards, sometimes it seems to hang in the 'Waiting' state...

Though this isn't good, it is happening because the DAV Save State plugin has a long running write lock to the graph so your other plugins are also waiting to write to the graph but cannot because of the existing open write lock.

Can you please create a ticket with a reproducer for this issue? This could help expose a possible deeper issue going on.

> In this issue, do you want to list all the plugins that are listed as 'waiting' in the Plugin Reporter, for a specified graph?

Essentially any plugin that is running, not just the waiting state.

> Also we cannot see a way to cancel a plugin in the constellation other than cancelling processes from the status bar at the bottom. Do you mean to mimic this behaviour through API?

Yeah pretty much. So sending an "interrupt" to the thread running the plugin would be sufficient.

**Comment by Auriga2** [comment]
Hi @arcturus2, Yes I meant the built in Rest API. May be I am using it incorrectly, as I didn't specify any parameters but it didn't throw any error.  I tried REMOVEUNUSEDATTRIBUTES which doesn't need any parameters but still the same response and it doesn't update in the Plugin Reporter. I'll try to debug and see where it fails.
![image](https://user-images.githubusercontent.com/64826928/84099306-72e1f680-aa48-11ea-9272-e183e9775154.png)

**Comment by Auriga2** [comment]
I found the reason- they do not work if you specify `The id of a graph to run the plugin on (optional).`
I entered the graph name there!

**Comment by Auriga2** [comment]
Hi @arcturus, looks like the PluginEnvironment.executePluginLater is the only place a new thread is created per plugin. executePluginNow, executeEditPluginNow and executeReadPluginNow run on the current thread. We cannot interrupt the thread if  plugins run on the same thread. What do you think?

Assuming plugins are running in separate threads, we thought of keeping a list of threads but executePluginLater seem to create all threads in the thread pool with the same name `Default Plugin Environment`

Would it be a good idea to rename these to contain a reference to the graph and plugin (may be `(graph.toString() + ":" + plugin.getName())`), and use this list through the API to list and interrupt relevant thread/s?

![image](https://user-images.githubusercontent.com/64826928/84350639-db6fd580-abf8-11ea-8367-2761c5e0dece.png)

**Comment by arcturus2** [comment]
> I entered the graph name there! In the code it's like `ad062f78-20a8-481e-a7d2-cc997082947e` Not sure how a user would find this ID. Anyway a valid error instead of 200 should be thrown

@Auriga2 So you have to use the graph endpoint to get a list of the graph id's.

Can you create an issue for the return 200 problem when it should return 422?

**Comment by Auriga2** [comment]
@arcturus2  Cool! Thanks. 
Logged #577

**Comment by arcturus2** [comment]
Thanks @Auriga2. I've also been thinking about the thread suggestion but not ready to respond with a suggestion. I've been doing a bit of reading and will need a bit more time.

**Comment by arcturus2** [comment]
Just updating my thoughts on this @Auriga2, the thread naming convention suggested feels a bit hacky to me so I wanted to see if there was a way to keep a list of references to the thread id's and interrupt them that way but I don't know if that will work.

For now let's park this until we get some more ideas.

**Comment by arcturus2** [comment]
Given we have access to the GUI, plugins can be cancelled from the GUI.
