### ISSUE TITLE
Question: - Map View - Zoom level

### ISSUE THREAD

**Issue by StoltHD** [constellation-app/constellation#264]
Is it possible without compiling from source to add more levels of the Map Zoom...?

I am going test out Constellation for a humanities research project and would like to show places on  "house and address" level...

**Comment by arcturus2** [comment]
Hi @StoltHD so we have got some connectors to different map services that will allow you to do that. I need to compile a new version with those modules included. It will be a pre release but i can do that within the next couple of days if you are interested?

**Comment by StoltHD** [comment]
That would be great,
Great work and a great software
________________________________

**Comment by cygnus-x-1** [comment]
The zoom levels are matched to the map provider, as in more adding more zoom levels will result in no tiles being returned. This is not a customisable option, it is predetermined by the map provider.

**Comment by arcturus2** [comment]
Just letting you know the pre-release with the map adaptors is available [here](https://github.com/constellation-app/constellation/releases/tag/v1.20200225.104006).

**Comment by StoltHD** [comment]
Great :-)

I will try it out, if I find anything not working I will let yoou know...
