### ISSUE TITLE
Working through SonarQube Warnings

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#280]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

This issue has been created to communicate work being done on fixing SonarQube warnings. If you would like to help out with fixing these warnings then please add a comment to this issue of which "rule" you are going to work on so we don't double up.

Please PR a change which works on 1 rule at a time so that it can be reviewed and tested easily.

**Comment by cygnus-x-1** [comment]
This might be a dumb question - but how do we access SonarQube?

**Comment by sol695510** [comment]
https://sonarcloud.io/dashboard?id=constellation-app_constellation @cygnus-x-1

**Comment by sol695510** [comment]
**RULE** (Java) Unnecessary imports should be removed

**Comment by sol695510** [comment]
> **RULE** (Java) Unnecessary imports should be removed

![SonarQube - Unecessary Imports](https://user-images.githubusercontent.com/58677774/76393941-8687ad80-63c4-11ea-99f7-481f47d64ce2.PNG)
![AbstractGeoExportPlugin java - Static Imports](https://user-images.githubusercontent.com/58677774/76393957-91dad900-63c4-11ea-9ce7-8f1bdc5683f1.PNG)
![NewLineRenderable java - Static Imports](https://user-images.githubusercontent.com/58677774/76393964-956e6000-63c4-11ea-828b-684608c139a9.PNG)

SonarQube points these out as unnecessary imports but checking the classes they're in, they have been used. Noted the difference between these and the other marked unnecessary imports is that they are static.

**Comment by arcturus2** [comment]
Hi @sol695510 so this is a tricky one. Taking ```import static au.gov.asd.tac.constellation.importexport.geospatial.AbstractGeoExportPlugin.ELEMENT_TYPE_PARAMETER_ID;``` as an example the import isn't used from what I can tell because a constant with the same name created at this line:

https://github.com/constellation-app/constellation/blob/8ca39ffc184302bc1b5e0d4fb9726766358c3caf/CoreImportExport/src/au/gov/asd/tac/constellation/importexport/geospatial/AbstractGeoExportPlugin.java#L72

You should be OK to remove the import.

**Comment by sol695510** [comment]
(Java) Constant names should comply with a naming convention

**Comment by sol695510** [comment]
**RULE** (Java) Empty arrays and collections should be returned instead of null

**Comment by formalhaut69** [comment]
**RULE** (Java) Arrays should not be copied using loops 10

**Comment by antares1470** [comment]
**RULE** (Java) "InterruptedException" should not be ignored

**Comment by antares1470** [comment]
**RULE** (HTML) "html" element should have a language attribute

**Comment by antares1470** [comment]
RULE (Java) Printf-style format string should not lead to unexpected behaviour

**Comment by antares1470** [comment]
**RULE** (Java) "Random" objects should be reused
**RULE** (Java) Math operands should be cast before use
**RULE** (Java) "Iterator.next()" methods should throw "NoSuchElementException"

**Comment by antares1470** [comment]
**RULE** (Java) Throwable.printStackTrace(...) should not be called

**Comment by antares1470** [comment]
**RULE** (Java) "public static" should be constant

**Comment by antares1470** [comment]
**RULE** (Java) Anonymous inner classes containing only one method should become lambdas
**RULE** (Java) Lambdas should be replaced with method references

**Comment by antares1470** [comment]
**RULE** (Java) "switch" statements should have "default" cases

**Comment by antares1470** [comment]
**RULE** (Java) Printf-style format strings should be used correctly

**Comment by antares1470** [comment]
**RULE** (Java) Collapsible "if" statements should be merged

**Comment by antares1470** [comment]
**RULE** (Java) Multiple variables should not be declared on same line

**Comment by antares1470** [comment]
**RULE** (Java) Parentheses should be removed from a single lambda input parameter when its type is inferred

**Comment by antares1470** [comment]
**RULE** (Java) Redundant casts should not be used

**Comment by antares1470** [comment]
**RULE** (Java) Local variables should not be declared and then immediately returned or thrown

**Comment by formalhaut69** [comment]
**RULE** (Java) Math operands should be cast before assignment

**Comment by formalhaut69** [comment]
RULE (Java) Unused local variables should be removed

**Comment by antares1470** [comment]
**RULE** (Java) Boolean literals should not be redundant

**Comment by formalhaut69** [comment]
RULE (Java) Unused local variables should be removed
noticed an odd issue that sonarQube picked up; apparently variable leaf isn't being used. I'm going to leave it the way it is unless someone else has a better suggestion that will make sonarQube happy.
```
for (PQNode leaf : leaves[currentNumber - 1]) {
//            if (leaf.virtualNum == currentNumber) {
            leaf.pertinentLeafCount = 1;
            if (leaf.parent != null) {
                leaf.parent.pertinentChildCount += 1;
                nodesToBubble.addLast(leaf.parent);
            }
            nodesToProcess.addLast(leaf);
//            }
        }
```

**Comment by arcturus2** [comment]
> nodesToProcess.addLast(leaf);

I'd say this is a false positive because it is being added to a a queue and used later on.

**Comment by antares1470** [comment]
**RULE** (Java) "throws" declarations should not be superfluous
**RULE** (Java) Null checks should not be used with "instanceof"
**RULE** (Java) Empty statements should be removed

**Comment by antares1470** [comment]
**RULE** (Java) Nested code blocks should not be used
**RULE** (Java) Overriding methods should do more than simply call the same method in the super class
**RULE** (Java) Strings should not be concatenated using '+' in a loop

**Comment by formalhaut69** [comment]
**RULE** (Java) Asserts should not be used to check the parameters of a public method

**Comment by antares1470** [comment]
**RULE** (Java) "entrySet()" should be iterated when both the key and value are needed

**Comment by antares1470** [comment]
**RULE** (Java) Class variable fields should not have public accessibility

**Comment by formalhaut69** [comment]
**RULE** (Java) Assignments should not be made from within sub-expressions

**Comment by formalhaut69** [comment]
**RULE** - Java "@Override" should be used on overriding and implementing methods

**Comment by formalhaut69** [comment]
**RULE** - Java Return values from functions without side effects should not be ignored

**Comment by antares1470** [comment]
**RULE** (Java) "static" base class members should not be accessed via derived types

**Comment by formalhaut69** [comment]
**RULE** (Java) Anonymous inner classes containing only one method should become lambdas
(There's a few issues with this one, I've explained them on the gitter, I don't believe its solvable so I'm just assigning it to myself here so no one else wastes time on it)

**Comment by arcturus2** [comment]
Thank you @antares1470 @formalhaut69 and @sol695510 for helping with these SonarQube warnings. With an effort to time box this work we've agreed to focus on the following and then have this issue closed:

- Resolve all Blocker and Critical warnings
- Resolve all Bugs and Vulnerabilities

**Comment by antares1470** [comment]
> 
> 
> Thank you @antares1470 @formalhaut69 and @sol695510 for helping with these SonarQube warnings. With an effort to time box this work we've agreed to focus on the following and then have this issue closed:
> 
>     * Resolve all Blocker and Critical warnings
> 
>     * Resolve all Bugs and Vulnerabilities

No Worries. I'm going to do one sweep of everything and knock out false positives/won't fixes and then get to focusing on that

**Comment by sol695510** [comment]
**RULE** (Java) Identical expressions should not be used on both sides of a binary operator

**Comment by formalhaut69** [comment]
**RULE** (Java) Methods and field names should not be the same or differ only by capitalization

**Comment by antares1470** [comment]
**RULE** (HTML) "table" tags should have a description
**RULE** (HTML) Tables should have headers
**RULE** (HTML) "th" tags should have "id" or "scope" attributes
**RULE** (HTML) "title" should be present in all pages
**RULE** (HTML) "html" element should have a language attribute

**Comment by formalhaut69** [comment]
**RULE** (Java) Switch cases should end with an unconditional "break" statement

**Comment by formalhaut69** [comment]
**RULE** (Java) Methods should not be empty

**Comment by antares1470** [comment]
**RULE** (Java) Return values should not be ignored when they contain the operation status code
**RULE** (Java) "enum" fields should not be publicly mutable

**Comment by antares1470** [comment]
**RULE** (Java) Using pseudorandom number generators (PRNGs) is security-sensitive

**Comment by antares1470** [comment]
**RULE** (JavaScript) Variables should be declared explicitly
**RULE** (Java) String literals should not be duplicated

**Comment by antares1470** [comment]
**RULE** (CSS) Shorthand properties that override related longhand properties should be avoided

**Comment by antares1470** [comment]
**RULE** (Java) Identical expressions should not be used on both sides of a binary operator
**RULE** (Java) Loops with at most one loop should be refactored
**RULE** (Java) InputStream.read() implementation should not return a signed byte
**RULE** (Java) Methods should not be named "tostring", "hashcode" or "equal"

**Comment by sol695510** [comment]
> **RULE** (Java) Identical expressions should not be used on both sides of a binary operator
> **RULE** (Java) Loops with at most one loop should be refactored
> **RULE** (Java) InputStream.read() implementation should not return a signed byte
> **RULE** (Java) Methods should not be named "tostring", "hashcode" or "equal"

https://github.com/constellation-app/constellation/issues/280#issuecomment-607542350

I was looking at the first RULE on your list but I've shifted to looking at testing Constellation v2 and/or looking at other rules.

**Comment by antares1470** [comment]
> 
> 
> > **RULE** (Java) Identical expressions should not be used on both sides of a binary operator
> > **RULE** (Java) Loops with at most one loop should be refactored
> > **RULE** (Java) InputStream.read() implementation should not return a signed byte
> > **RULE** (Java) Methods should not be named "tostring", "hashcode" or "equal"
> 
> [#280 (comment)](https://github.com/constellation-app/constellation/issues/280#issuecomment-607542350)
> 
> I was looking at the first RULE on your list but I've shifted to looking at testing Constellation v2 and/or looking at other rules.

My apologies I missed that. I'll remove it from my list then

**Comment by sol695510** [comment]
> > > **RULE** (Java) Identical expressions should not be used on both sides of a binary operator
> > > **RULE** (Java) Loops with at most one loop should be refactored
> > > **RULE** (Java) InputStream.read() implementation should not return a signed byte
> > > **RULE** (Java) Methods should not be named "tostring", "hashcode" or "equal"
> > 
> > 
> > [#280 (comment)](https://github.com/constellation-app/constellation/issues/280#issuecomment-607542350)
> > I was looking at the first RULE on your list but I've shifted to looking at testing Constellation v2 and/or looking at other rules.
> 
> My apologies I missed that. I'll remove it from my list then



> > > **RULE** (Java) Identical expressions should not be used on both sides of a binary operator
> > > **RULE** (Java) Loops with at most one loop should be refactored
> > > **RULE** (Java) InputStream.read() implementation should not return a signed byte
> > > **RULE** (Java) Methods should not be named "tostring", "hashcode" or "equal"
> > 
> > 
> > [#280 (comment)](https://github.com/constellation-app/constellation/issues/280#issuecomment-607542350)
> > I was looking at the first RULE on your list but I've shifted to looking at testing Constellation v2 and/or looking at other rules.
> 
> My apologies I missed that. I'll remove it from my list then (if you intend to revisit it at some point in the future)

I've had some trouble understanding how to resolve that rule last week so do you mind having a look at it? If you resolve it could you explain how you did it too?

**Comment by antares1470** [comment]
> I've had some trouble understanding how to resolve that rule last week so do you mind having a look at it? If you resolve it could you explain how you did it too?

So the hit for '&&' was actually a typo. One side should be drawOriginY rather than both being drawOriginX.

The '<<' hits don't entirely makes sense me. The rule states results are predictable when both sides of the operator are the same but I'm not sure that's the case for this operator. In any case, I've just solved them (to simplify) and noted in a comment what the number equates to

**Comment by sol695510** [comment]
**RULE** (Java) Loops should not be infinite

**Comment by antares1470** [comment]
**RULE** (HTML) Elements deprecated in HTML5 should not be used
**RULE** (Java) Class variable fields should not have public accessibility

**Comment by antares1470** [comment]
**RULE** (Java) Method parameters, caught exceptions and foreach variables' initial values should not be ignored

**Comment by antares1470** [comment]
**RULE** (Java) Optional value should only be accessed after calling isPresent()

**Comment by antares1470** [comment]
**RULE** (Java) Cognitive Complexity of methods should not be too high

**Comment by sol695510** [comment]
**RULE** (Java) Null should not be returned from a "Boolean" method

**Comment by antares1470** [comment]
**RULE** (Java) Constants should not be defined in interfaces

**Comment by arcturus2** [comment]
Again thank you @antares1470 @sol695510 @formalhaut69 for all of the work you have done on the SQ rules. The overall states are looking really good and just know that your hard work is being highlighted to our seniors.

**Comment by arcturus2** [comment]
@arcturus2  @sol695510  @formalhaut69  please note that the SQ rules we are running on the project is a fork of the "Sonar Way" rules set because it has the complexity score set to 60 instead of 15 (the default). As a result, when Sonar Cloud update the "Sonar Way" rules, our rules deviate from the baseline. Sonar Cloud have deprecated some rules and added some since I made the change back in February.

A change log of what has changed is available https://sonarcloud.io/organizations/constellation-app/quality_profiles/changelog?language=java&name=Sonar+way+%28less+strict%29
