### ISSUE TITLE
Performance testing

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#29]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

 * create a unit test to open and close graphs and check memory usage
 * add performance testing to the build
   * this will help identify when a particular commit causes a performance bug
 * do graph performance testing
 * memory leak testing / fixing
   * how much memory do all of the views take?

Note that NetBeans has built in memory usage testing libraries that we should probably use. They are part of the testing "harness" module. 

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behaviour:** [What you expect to happen]

**Actual behaviour:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by aldebaran30701** [comment]
@arcturus2 Just closing this for clean up.
