### ISSUE TITLE
Kali Linux Run issue 

### ISSUE THREAD

**Issue by 5l1v3r1** [constellation-app/constellation#292]
sh constellation gives an error of 
: not foundon: 2: 
: not foundon: 40: 
: not foundon: 44: 
: not foundon: 46: 
constellation: 67: Syntax error: word unexpected (expecting "in")

bash: ./constellation: /bin/sh^M error

**Comment by arcturus2** [comment]
@5l1v3r1 is this the v1.3.0 release?

**Comment by arcturus2** [comment]
@5l1v3r1 can you try the Linux download in https://github.com/constellation-app/constellation/releases/tag/v1.3.1 ?

**Comment by 5l1v3r1** [comment]
alright 1.3.1 is working great. Thank you for your solution and your great work on this project.
