### ISSUE TITLE
Moving nodes on Graph doesn't update associated attributes in Attribute Editor

### ISSUE THREAD

**Issue by serpens24** [constellation-app/constellation#296]
## Description
NOTE: This issue was seen on NB11 version of the application, but is known to also occure on NB8 version.

Currently if the Attribute Editor is open along with a graph, and certain attributes on the graph change, these changes are not refelcted in the Attribute Editor.

The most obvious example is moving s node around on the graph... its positional values do not update in the Attribute Editor unless you click off it, then back onto it.

### Steps to Reproduce

1. Open a graph
2. Open the Attribute Editor an expand the Node block
3. Select a Node on the graph and note its X/Y position in the Attribute Editor
4. Move this node and observe its X?Y position do not change
5. Click off the node (onto another node) and back onto it and note the nodes X/Y values have now updated

**Expected behaviour:**
Node atributes uopdate in real time as its postion changed

**Actual behaviour:**
Atributes are not updated

**Reproduces how often:**
100%

### Additional Information

1. Acturus beleives this was working prior to some recent Attribute Editor changes.

2. I had a quick look at AttributeEditorTopComponent.java and put a breakpoint in graphChanged. I noted that when moving the node this breakpoint was hit, but code always falls into the "event.getEditor() == null" block and returns. 
For a quick test I commented out this if block and found that moving the node and releasing it instantly updates the associated X/Y attributes. A git blame suggests that graphChanged has not been modified for at least 8 months, so perhaps getEditor is returning null in error ?
Looking into this, th ecall stack suggests GraphChangedEvent() at line 49 is being called so set th editor. This might be a clue as to what is going on.

** NOTE ** I was able to replicate this issue in release 1.2.1 which is significantly earlier than was thought that the issue existed, so I'm confirming that my steps are in fact demonstrating the issue that was discussed with @arcturus2  before we look to proceed.

**Comment by arcturus2** [comment]
@serpens24 for some reason I thought this was a recent bug but based on your investigation it must have been earlier last year. The reproducer is correct.

**Comment by serpens24** [comment]
Thanks @arcturus2.

Subsequent to our chat earlier today I investigated if editor is ever assigned a non-null value within 
LockingManager.LockingEdit and it does appear it can occur, ot with DoalGraph. As such I have elected to not pursue checking its use any further as its clear it's not alway going to be set to null.

So the change which resolves the issue in question relates to lines 227-232 of AttributeEditorTopComponent.java. These lines are as per below extract:

`
        /*event.getEditor() is null whenever this event is invoked due to an action 
        which is not relevent to this class e.g. zoom in/out, therefore return 
        from this method without any further execution */
        if (event.getEditor() == null) {
            return;
        }
`

Note the comment prior to the actual code getting implemented indicates the original intent was to not update attributes after zoom and other actions, perhaps this inadvertantly included node moves.
I don't have access to the original source history to see why this check was added - was it addressing a specific issue or not .. perhaps you have visibility of this ? What I will do is confirm that zoom in/out as well as stuff like graph pan doesn't show up any odd behaviour before committing.

**Comment by serpens24** [comment]
OK, so I looked at graph actions such as zoom, pan/move, androtate and found that these actions also don't update the Camera attribute on the graph. Removing the lines in question shows that the Camera attribute now updates (although zoom has no impact, but this seems to be expected given the details shown).

As such I'll proceed with removing the offending lines. @arcturus2  if you do dig up anything in old history logs that suggests these lines were required let me know .

**Comment by arcturus2** [comment]
Thank you @serpens24 for the usual detailed analysis and for your time! If I find out anything I will let you know. Happy to test out a PR when you are ready.
