### ISSUE TITLE
Tidy up the JavaFX stylesheets

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#308]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

A few things worth investigating:
* How do ControlsFX manage CSS files and should be use them?
* How does [GLUON](https://gluonhq.com/products/javafx/) manage JavaFX styling and should we use GLUON?
* What other JavaFX libraries are out there?

A few things I'd like to see implemented:

* bring back the equvilent JavaFX skins for the Quality Control View

```css
-fx-skin: "com.sun.javafx.scene.control.skin.TableViewSkin";
-fx-skin: "com.sun.javafx.scene.control.skin.TableRowSkin"
-fx-skin: "com.sun.javafx.scene.control.skin.TableCellSkin";
-fx-skin: "com.sun.javafx.scene.control.skin.ButtonSkin";
```

* There is more than one `Style-Caspian.css` file in the project. If this is the main css file then it should be hosted in one package
* Review the custom `.css` files and if there are any duplicates then merge them into a common `.css` file
* Break out the colours into their own `'.css` file so we can have light and dark flavours and make it easier to switch between the two.

**Comment by capricornunicorn123** [comment]
Already implemented in PR #1131
