### ISSUE TITLE
Improve Constellation load time

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#31]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

At times, Constellation takes too long to open. I've noticed that the Tutorial page takes a while to load and the Data Access View. There has been some performance improvements done to both of these components already but it might be worth a revisit.

Before working on this, profile Constellation so one can measure the improvements.

Following on from the workshop discussion is was agreed that this is a lower priority task. We also need to set a measurable baseline before we work on this ticket.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behaviour:** [What you expect to happen]

**Actual behaviour:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by arcturus2** [comment]
Is this an issue people have? What is a reasonable amount of time to wait for an application to load? Discussions on this can get deep because it depends on whether you want to wait a bit longer upfront to then have a snappy experience once everything is loaded vs faster load times and then wait for bits of functionality to load as you use them?

**Comment by antares1470** [comment]
Do a profile of load times and close this if we deem them acceptable

**Comment by aldebaran30701** [comment]
As there is no current issue with the load times of Constellation, I am going to close this issue.
To keep the tickets meaningful, they may be raised in the future when the need arises to implement or fix something. ie. Analytic view is slow to use
