### ISSUE TITLE
Investigate views to not listen to events when they are docked

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#32]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

As a developer
I want docked windows to not listen to graph updates
so that I dont waste computational resources updating views that are not visible.

The idea with this was to reduce the computational load by not having views do work when they are not visible.

To see more debug information of listening events enable the following lines in `project.properties`:

`
run.args.extra=-J-Dau.gov.asd.tac.constellation.functionality.views.ListeningTopComponent.level=FINE \
-J-Dau.gov.asd.tac.constellation.graph.node.pluginframework.FrameworkGraphManager.level=FINE
`

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behaviour:** [What you expect to happen]

**Actual behaviour:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by antares1470** [comment]
@aldebaran30701 Can this ticket be closed or is there something else that needs to be done for it?

**Comment by aldebaran30701** [comment]
I forgot to update this ticket. The below views are not implemented in this ticket for the following reasons.
- Find view - Not currently on Generic TopComponent Framework
- Histogram - Not currently on Generic TopComponent Framework
- Timeline - Not currently on Generic TopComponent Framework
- NamedSelection - Utilises an odd listening framework for graph listening and could not implement without bugs

I feel like we can close it, and I can link the tickets to the relevant tickets that will need to be updated when the views are converted.

**Comment by arcturus2** [comment]
Let's close it given the above points @aldebaran30701 mentioned.
