### ISSUE TITLE
The Plugin Reporter does not display messages from child plugins

### ISSUE THREAD

**Issue by canis-majoris-42** [constellation-app/constellation#323]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

An example is running a batched workflow plugin which will spawn child plugins. If we return a message at the end of each plugin, none of them will appear when you look at the Plugin Reporter.

As it stands, if a plugin spawns another plugin on the same thread, the plugin reporter will place the report for the child plugin inside the report for the parent plugin. This is not the case if the child plugin is run on another thread. To fix this, I think plugins should optionally be able to nominate another plugin thread as their parent, and the plugin reporter should look for this and merge reports as appropriate.

Currently all plugins that use the WorkflowQueryPlugin template will produce many (rather than one) plugin report. The issue also occurs with Analytic View plugins.

In addition, the use case I have in mind here is that if a plugin creates a child plugin, and that child plugin fails, then the plugin should be able to lookup the report of the child plugin in order to itself report why it failed.

### Steps to Reproduce

1. Occurs on startup once a new graph is loaded.

**Expected behaviour:** Child plugin reports should appear in the Plugin Reporter.

**Actual behaviour:** Child plugin reports do not appear in the Plugin Reporter.

**Reproduces how often:** 100%

### Additional Information

N/A

**Comment by GammaVel** [comment]
Thank you @OrionsGuardian for making these updates which will be very useful. I am experiencing a Constellation crash with some of my existing graphs which might be related.  The app is freezing and I need to use Task manager to kill it. Not quite sure what is going on behind the scenes but would be great if you could take a look.

**Comment by GammaVel** [comment]
Thanks @OrionsGuardian, the analytic view is working well now without the crashes I  had before. Nice to see this working!
