### ISSUE TITLE
The VisualTopComponent doesn't present a GL canvas when switching between two similar graphs

### ISSUE THREAD

**Issue by canis-majoris-42** [constellation-app/constellation#325]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

This issue seems specific to windows, and I suspect its something to do with the way the netbeans windowing system is interacting with the Open GL canvas. It existed both prior to and after the recent changes to the visual framework (January 2017). The curious thing is that the if the two graphs are structurally different, or have different selections, then the bug does not occur (but other visual differences such as camera/dimming/color/x,y,z do not prevent the bug). It is still unclear how the framework responsible for making the open GL canvas valid knows anything about the similarity between graphs, especially since the same behaviour is present both before and after the recent visual framework overhaul. 

### Steps to Reproduce
    
1. Open a graph. 
2. Make a copy (control+U) of the entire graph.
3. Ensure that both graphs have the same selection.
4. Make sure that all views and the tutorial page are closed.
5. Switch backwards and forwards between the two graphs.
6. One of them should appear entirely black, and interacting with the canvas will do nothing (impossible to add vertices in add mode etc.).

**Expected behaviour:** VisualTopComponent presents a GL canvas when switching between two similar graphs

**Actual behaviour:** VisualTopComponent doesn't present a GL canvas when switching between two similar graphs

**Reproduces how often:** 100%

### Additional Information

N/A

**Comment by Nova-2119** [comment]
@canis-majoris-42 are you able to confirm that this behaviour still occurs? I tried to replicate this issue as described but was unable to.
Immediately after switching there was a blank canvas, but then the canvas was presented after a small amount of time (about a second).

**Comment by canis-majoris-42** [comment]
I give it a go, but this is one of the tickets transferred from our advocates. I never experienced the problem personally.

**Comment by Nova-2119** [comment]
@canis-majoris-42 can you walk me through recreating this? I can get the black canvas but the graph always appears after waiting, with the wait time proportional to the size of the graph.

**Comment by antares1470** [comment]
> @canis-majoris-42 can you walk me through recreating this? I can get the black canvas but the graph always appears after waiting, with the wait time proportional to the size of the graph.

@Nova-2119 it seems what you are seeing is addressed in #59. Possibly these tickets are related?

**Comment by antares1470** [comment]
After some testing, it appears that #59 is the real issue happening so I'm going to close this ticket
