### ISSUE TITLE
Closing a view does not remove the memory it has used

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#33]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

When a view is closed, all objects it created should be released.

An attempt was made by adding `createContent` and `destroyContent` to the `AbstractTopComponent` class, and implementing them in the `JavaFxTopComponent` and `SwingTopComponent` classes.

The first issue was that content needed to be created on the appropriate GUI thread, which caused all sorts of threading issues. This was resolved by using a semaphore to block during creation/destruction to ensure only one operation happens at a time.

The second issue was that destroying the content (by setting it to null) didn't remove it from memory as the outer panes (scrollpane/scene/container) still had reference to the content. This was resolved by changing `destroyContent` to destroy all of these objects and `createContent` to recreate everything.

The third issue was that top components could no longer refer to their content/scrollpane/etc directly as you could never be sure when objects were being destroyed/recreated. This was resolved by adding a `getContent` method which retrieved the current content by digging down through the the top component and adding null checks anywhere this method was used.

The fourth issue was that even after all this, the content was still not properly destroyed as both JavaFX (through its Scene's dirtyNodes system) and Netbeans (through its quicksearch and top component systems) held references. This meant that very little memory was actually saved as the panes could not be garbage collected.

Requires more investigation to progress these issues.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behaviour:** [What you expect to happen]

**Actual behaviour:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by antares1470** [comment]
Do one more evaluation with the move to nb12 and close if it's the same issues

**Comment by antares1470** [comment]
We've done as much as we can for this ticket. Closing
