### ISSUE TITLE
Convert undo and redo to plugins

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#334]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
 At the moment, undo and redo are not plugins. Wrapping these functions around a plugin would allow it to be seen from the Plugin Reporter. 

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behaviour:** Undo and Redo both available as plugins

**Actual behaviour:** Neither Undo nor Redo are available as plugins

**Reproduces how often:** 100%
### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by antares1470** [comment]
@arcturus2 and I realised there probably isn't a use case for programmatically calling undo or redo and so decided this isn't necessary

**Comment by arcturus2** [comment]
This has been moved to [Brainstorm Ideas](https://github.com/constellation-app/constellation/wiki/Brainstorm-Ideas) in case there are some other use cases that come up in the future. The only reason to actually do this would be to follow the idea of making everything into plugins.
