### ISSUE TITLE
Schemas should have unit testing

### ISSUE THREAD

**Issue by serpens24** [constellation-app/constellation#337]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Schemas are critical to ensuring CONSTELLATION functions correctly... they are also highly volitile. This could be partially alleviated by writing some comprehensive unit tests for them. 

### Steps to Reproduce

N/A request for tests

**Expected behaviour:**

N/A request for tests

**Actual behaviour:**

N/A request for tests

**Reproduces how often:** 

N/A request for tests

### Additional Information

N/A

**Comment by antares1470** [comment]
Closing as the effort for this issue is encased in #413
