### ISSUE TITLE
Formally define schemas and inheritance

### ISSUE THREAD

**Issue by serpens24** [constellation-app/constellation#338]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Currently the definition of schemas and the way they work with inheritance is loose and sometimes problematic in terms of real world functionality.
The structure of the schemas are changed more often than they should be as a result. Furthermore, we have an issue with changes to one level of schemas breaking schemas that inherit from them. Inheritance should be formally defined so that this no longer happens, and the concept should probably be unified with inheritance of types that are registered with schemas at different levels in the hierarchy. 

### Steps to Reproduce

N/A

**Expected behaviour:**

Changes to one level of schemas cann break schemas that inherit from them.

**Actual behaviour:** 

Changes to one level of schemas cannot break schemas that inherit from them.

**Reproduces how often:** 

Unable to quantify.

### Additional Information

N/A

**Comment by antares1470** [comment]
Added to Brainstorm ideas and closing
