### ISSUE TITLE
New Starter Pack

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#35]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

We have a growing list of customers and we need to think about stream lining the process on how we introduce and provide ongoing support to new starters.

The place this information can be stored is on the Constellation-app webpage. Consolidating all information suitable for new starters will reduce the learning curve of the tool.

The idea I had was that we provide a pack that has:
* powerpoint slides which introduces Constellation, show casing what it can do and the goal of constellation with accompanied transcript
* a video presentation of how an analyst uses Constellation
  * has an accompanied powerpoint pack (a few slides is fine to give context)
* provide a training pack and transcript that could act as a "Constellation for Basics" training course. This would consist of a word document, powerpoint slides and sample graphs for the exercises.
* provide a "How to write a plugin guide" which is currently in progress but needs to be fleshed out more.
* provide a "How to write a new schema guide".
* provide a "How to create an update centre guide".
* provide an some documentation which talks about the coding standards, development approaches, contributing code back to Core
* provide some case studies of Constellation

**Comment by antares1470** [comment]
@arcturus2 reckons for the update centre guide we can possibly redirect people to an existing Netbeans page for this kind of thing: https://netbeans.org/community/guidelines/au-management.html though that page isn't the best one
