### ISSUE TITLE
Constellation with sample Data Access Plugins

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#353]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Presently the version of Constellation available on GitHub does not have any database connectors so it is difficult to demonstrate the scenario of running queries on entities and observing a graph representation of relational data.

Many have requested for the ability to "play" with a same data set that does not involve them having to import a CSV file. This has also been requested by UX developers to better understand how Constellation could be used.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behaviour:** [What you expect to happen]

**Actual behaviour:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by cygnus-x-1** [comment]
Could I suggest adding some plugins to the Constellation Adaptors which access open source data?

**Comment by canis-majoris-42** [comment]
Added a Pajek Importer and Hopper

**Comment by canis-majoris-42** [comment]
Next I'll have a look at the format of SNAP datasets

**Comment by canis-majoris-42** [comment]
Out of curiosity, what is the done condition for this ticket?

**Comment by canis-majoris-42** [comment]
I've just added a GrasphML Importer and Hopper

**Comment by arcturus2** [comment]
> Out of curiosity, what is the done condition for this ticket?

Presently there were no plugin to run queries so these plugins get to that point. I'd say we are done. Let me move this over to testing once the PR is merged and get some users I have in mind to test.

Again thank you for the very quick turn around time.
