### ISSUE TITLE
Multi-Modal Graphs

### ISSUE THREAD

**Issue by cygnus-x-1** [constellation-app/constellation#354]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Constellation currently models data as a graph by storing the data in _attributes_ and strictly managing those attributes through _schemas_. This means you must write a new schema whenever you want to visualise the attributes in a new way.

This could be improved by rewriting Constellation's graph framework to enable the graph's nodes and transactions to be dynamically defined by any subset of attributes present in the underlying data. This would likely require having an underlying data structure which represents a graph of attributes connected to their values, and a mechanism for collapsing this graph by specifying key attributes which should represent nodes and transactions. 

This system would require a full rewrite of the core graph framework, and most of the views in order to work, but would allow for infinite flexibility in data visualisation, and the ability to switch between types of analysis on-the-fly.

**Comment by arcturus2** [comment]
Moving this one to [Brainstorm Ideas](https://github.com/constellation-app/constellation/wiki/Brainstorm-Ideas)
