### ISSUE TITLE
Attribute Types Composed of Collections of Primitives

### ISSUE THREAD

**Issue by cygnus-x-1** [constellation-app/constellation#355]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Rather than have opaque attribute types which allow the storage of arbitrary objects, attributes could instead be comprised entirely of collections (lists, sets and maps) of primitives (or Strings). This would allow the creation of new types (and their related descriptions, interactions and io) to be streamlined and abstracted. It would also allow multi-valued attributes and the associated attribute merging to be implemented in a clearly defined and consistent manner.

This would likely require changing the graph framework and hence involve a large amount of testing to avoid stability issues.

**Comment by arcturus2** [comment]
I've moved this to [Brainstorm Ideas](https://github.com/constellation-app/constellation/wiki/Brainstorm-Ideas) and closing this issue for now.
