### ISSUE TITLE
Analytic View parameter pane layout jumps around

### ISSUE THREAD

**Issue by serpens24** [constellation-app/constellation#363]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

 The parameter pane in the Analytic View is not laid out correctly when created - on initial interaction it will often resize itself. 

### Steps to Reproduce

1. Open Analytic view and inspect size and position of the paramter pane
2. TODO
(Note - I have not been able to replicate this issue as yet. ... I am running with NB11)

**Expected behaviour:**

Analytic views parameter pane is initialised at the correct size.

**Actual behaviour:** 

On some occasions the initial size is incorrect meaning when user interacts with it it changes dimensions.

**Reproduces how often:** 

I have not yet seen it happen on NB11, unable to confirm %. 

### Additional Information

This issue was requested to be raised. Without information on how often it occurs or the exact steps to reproduce some time may need to initially e invested verifying it still does happen.

**Comment by cygnus-x-1** [comment]
Duplicated by https://github.com/constellation-app/constellation/issues/455.
