### ISSUE TITLE
Importing large Dataframes crashes Constellation

### ISSUE THREAD

**Issue by serpens24** [constellation-app/constellation#369]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Putting a large dataframe from jupyter notebooks into CONSTELLATION causes a crash. the primary suspect is the new renderer, as this seems to be a relatively new issue.

As he said, "It seems that the display is updated as soon as the graph is added (which causes the crash because when of the nodes are at the default (0,0,0)), then updated again after the arrangement is done." The fix would probably be to do the arrangement in the REST server before adding the graph to the renderer. 

### Steps to Reproduce

1. TODO ... get information 

**Expected behaviour:** 
CONSTELLATION does not crash

**Actual behaviour:**
CONSTELLATION crashes

**Reproduces how often:** 
unknown, but assume 100%

### Additional Information

Nil

**Comment by aldebaran30701** [comment]
I've spent some time working on trying to replicate this, the biggest issue I see is the time it takes to render the elements. It did not crash during the tests I performed. I tried increasing no. of elements up to 500, 000 vertices. It seemed to take 4-5 minutes to render the elements. 
I did notice this block of comments near the code that executes during importing:
```
// Do the optional arrangement inside this anonymous "addRecordStoreToGraph" plugin.
// This way, any extra nodes are added and arranged in one go.
// If the arrangement is done separately, not only does the "add + arrange" become two steps,
// but if enough extra vertices are drawn at (0, 0, 0), some graphics drivers will crash.
// It is still possible to do this (by manually setting x,y,z to 0,0,0 and specifying no arrangement),
// but then it becomes the malicious user's fault.
```

Just wanted to check that this wasn't an old ticket on the board and to clarify the way it may have been caused further to the commented code.

**Comment by arcturus2** [comment]
I followed the code and got to the same section and I think you are right, this has been fixed. This is a recent fix (thank you @algol60) so happy to close this. We had some users test the Rest Service and they could not break it but I was not sure if that involved performance testing like what you have done here.

Thank you for testing it!
