### ISSUE TITLE
Write a schema creation guide

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#37]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

As a developer
i want a how-to guide for creating schemas
so that i can extend constellation to meet my analytical needs.

**Comment by arcturus2** [comment]
This could probably be added as an extension to the developer guide.

**Comment by antares1470** [comment]
Closing as this is contained in #35
