### ISSUE TITLE
Schema View - Type Information and Searchability

### ISSUE THREAD

**Issue by cygnus-x-1** [constellation-app/constellation#373]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The Schema View tabs for 'Vertex Types' and 'Transaction Types' currently do not expose properties in the properties map of each type. Ideally all information associated with each type would be visible here.

Additionally, it would be useful to be able to dynamically filter the list of vertex and transaction types by name in a similar manner to the filtering on the 'Attributes' tab.

**Comment by Auriga2** [comment]
Hi @cygnus-x-1 I tried to work on this but cannot find how to add the `properties`. I presume this section is the `properties map` (which already has some properties there)

![image](https://user-images.githubusercontent.com/64826928/82165042-b5edf580-98f2-11ea-8468-ac5c16f4a931.png)

And looking at the code, it's trying to add more properties from vertexType.getProperties().keySet() and transactionType.getProperties().keySet() but the properties there are always empty. (On experimental graphs I tried)
![image](https://user-images.githubusercontent.com/64826928/82164881-01ec6a80-98f2-11ea-9b01-bb8b1f3c7bb7.png)
![image](https://user-images.githubusercontent.com/64826928/82165127-f9486400-98f2-11ea-93a4-36b681be810f.png)

How do I add properties to vertex and transaction types here?

**Comment by arcturus2** [comment]
Hi @Auriga2 if you have a look at `SchemaVertexType` for example you will see there are top level attributes and as you've pointed out correctly, they are visible already in the Schema View. There is also a "properties map" which you can add custom attributes - this was a way to allow the `SchemaVertexType` to be extended.

Note that in the "Core" version there are no properties which is the reason why you are seeing `null`. To test this out can you please temporarily modify (but don't commit) say the `AnalyticConcept` by adding the following `setProperty()` calls to the `GRAPH` vertex type and make them appear?

```
public static final SchemaVertexType GRAPH = new SchemaVertexType.Builder(String.format("%s Graph", BrandingUtilities.APPLICATION_NAME))
                .setDescription(String.format("A node representing a %s Graph", BrandingUtilities.APPLICATION_NAME))
                .setColor(ConstellationColor.AZURE)
                .setForegroundIcon(AnalyticIconProvider.STAR)
                .setProperty("some key", "some value")
                .setProperty("some key2", "some value2")
                .build();
```

So you should be able to see "some key" with the value "some value" and ditto for the second custom property.

Let me know if you need any further clarifications.

**Comment by Auriga2** [comment]
I can see them added in both sections. (by hard coding in VertexType and TransactionType properties in the AnalyticConcept class.)
![image](https://user-images.githubusercontent.com/64826928/82183703-9c19d600-9925-11ea-9de3-f58c1c911d7d.png)

This could be a problem with the integration of  the other side?

**Comment by cygnus-x-1** [comment]
Essentially we should make sure that all properties of each type is exposed in this view, including any arbitrary properties stored in the property map described by @arcturus2, and types should be searchable (maybe including these properties?).

**Comment by Auriga2** [comment]
From what I can see, the properties are all exposed already as long as they are available in the properties map of each type. The problem could be with populating these custom properties maps.

**Comment by Auriga2** [comment]
Hi @arcturus2, Feels like the issue `(The Schema View tabs for 'Vertex Types' and 'Transaction Types' currently do not expose properties in the properties map of each type.)` is beyond the core, because I can see the hard coded properties. Can you please verify?

Anyway, I can add the filters `to filter the list of vertex and transaction types by name in a similar manner to the filtering on the 'Attributes' tab. `->(1 in below image)
But if we have to filter the properties, like cygnus-x-1 mentioned above, we might need to add a separate filter box in the properties map of each type (2 in below image). What do you think? 

![image](https://user-images.githubusercontent.com/64826928/82509736-e67a9d00-9b47-11ea-8369-63cda9fe500d.png)

**Comment by arcturus2** [comment]
> Hi @arcturus2, Feels like the issue `(The Schema View tabs for 'Vertex Types' and 'Transaction Types' currently do not expose properties in the properties map of each type.)` is beyond the core, because I can see the hard coded properties. Can you please verify?

I think if the hard coded properties work then it that is pretty much what we expect so you should be fine. Consider this part solved and thanks for testing it.

The filter you have there is pretty neat and it should cover both cases (i.e the top level properties of a Type and the custom properties which is what is in the properties map). If your hard coded properties show can be filtered then consider this working as requested.

**Comment by cygnus-x-1** [comment]
The hard-coded properties are working fine - it was just the ephemeral properties inside that properties map that were not working... perhaps that was fixed at some point?

On the filter bar - it looks great, but ideally there would just be one at the top which would filter against both type name and properties (a unified search).

**Comment by arcturus2** [comment]
> it was just the ephemeral properties inside that properties map that were not working... perhaps that was fixed at some point?

tested and working @cygnus-x-1

**Comment by Auriga2** [comment]
@cygnus-x-1 Do you want me to hide the properties that do not match the filter text? In a normal unified search I'd assume yes, but here it's different, because when you type in the filter(1), it'll only show the Types (in the upper section), and you need to click on individual types to see the properties in the section below (properties section). If I implement a  unified search filter, and (say) the text matches only the Type, should I display or hide the properties in the properties section when the user click on that Type?

**Comment by cygnus-x-1** [comment]
I'd probably expect the filter to hide types in the tree, but display all properties of any selected type (perhaps highlighting the search term hits in those properties).

**Comment by arcturus2** [comment]
@Auriga2 did some testing and the search works really well and highlighting the word is a great idea and good UX.

I'm happy to close this as done though I wanted to let you know of a small issue I found during testing which @mimosa2 also noted. See below gif which shows that when you go out of focus from the input text field, what you typed is not shown until you give focus back to the input text field.

![testing schema view search](https://user-images.githubusercontent.com/39325530/84681771-fbe0bc80-af77-11ea-93e0-7bf3a9290f95.gif)

**Comment by antares1470** [comment]
> I'm happy to close this as done though I wanted to let you know of a small issue I found during testing which @mimosa2 also noted. See below gif which shows that when you go out of focus from the input text field, what you typed is not shown until you give focus back to the input text field.
> My guess is the bug is with the style sheet (css) file which is a pain to debug so I'm ok to do it later if you decide not to spend time on it.

@arcturus2 Maybe I happened to get a good view with my screen but when you go out of focus from the input text field, the text appears to turn black (I can see this as it is a slightly darker colour compared to the background colour). So you are probably right that it is a CSS thing

**Comment by Auriga2** [comment]
@arcturus2 <https://github.com/arcturus2>   Ahh yes, it's the same
behaviour in the Attributes tab (before these changes) as well. I'll log a
separate case to fix all of them

**Comment by Auriga2** [comment]
Logged https://github.com/constellation-app/constellation/issues/585 to cover the above case.
