### ISSUE TITLE
Table View Column Selection - Split Attributes into Source/Destination/Transaction

### ISSUE THREAD

**Issue by cygnus-x-1** [constellation-app/constellation#374]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The column selection menu in the Table View becomes unwieldy to use when you have a lot of attributes available. This could be improved by change the layout of the menu so that the attributes are split up by source/destination/transaction instead of all being in one big list.

**Comment by serpens24** [comment]
@arcturus2  - I've pulled this ticket in as a good first issue for Auriga2 - I'm not sure if you have set up their access yet  ?

Anyway, the following screenshot shows one possibility for solving the problem:
It provides 3 additional 'Filter' options which allow source/destination/transaction records to be turned on/off. This works interchangeably with the Filter text field, so in the example below, the user has said they only want to view source and destination fields, and return any containing ".y".

These three 'Filter Source/destination/transaction' options can probably be only visible when required ... 
We went for this over nested menus for each as they are a little harder to use when wanting to search for text across multiple types.
![image](https://user-images.githubusercontent.com/58677108/81357995-5afb1800-9114-11ea-995b-aef2c9e86b0e.png)

**Comment by arcturus2** [comment]
@serpens24 sorry mate the access for @Auriga2 should be waiting for them now.

In my mind I had assumed the solution would be 3 sub menus and possibly a filter at each sub menu but I think your saying that is much harder to implement? If so I think this is OK and achieves the requirement.

@cygnus-x-1 I'd be grateful for any feedback you have when you get a moment?

**Comment by serpens24** [comment]
> @serpens24 sorry mate the access for @Auriga2 should be waiting for them now.
> 
> In my mind I had assumed the solution would be 3 sub menus and possibly a filter at each sub menu but I think your saying that is much harder to implement? If so I think this is OK and achieves the requirement.
> 
> @cygnus-x-1 I'd be grateful for any feedback you have when you get a moment?

I don't know if its definitely 'harder' to implement, but this method allows a single filter to operate over all types, rather than having to filter each individually. This was the initial design we (myself and @Auriga2 put together.

**Comment by Auriga2** [comment]
We can implement that as well: (Removed the current filter from the main menu.)
![image](https://user-images.githubusercontent.com/64826928/81535436-f0163f00-93a8-11ea-899e-2a4df6e8881d.png)

But as @serpens24 mentioned, it would not filter across all types. 
![image](https://user-images.githubusercontent.com/64826928/81534020-6a918f80-93a6-11ea-8f15-7f08877f9f9d.png)

**Comment by Auriga2** [comment]
Based on feedback, separate sub menus is the preferred option by people. ( #507)
