### ISSUE TITLE
One-to-many element relationships in the Histogram View

### ISSUE THREAD

**Issue by cygnus-x-1** [constellation-app/constellation#376]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The Histogram View in Constellation is currently designed to only map one-to-one element-attribute relationships. Changing the framework so that it can handle one-to-many relationships would allow for creating formats such as viewing all keys of dictionary style attributes, or plotting multiple regex captures with the String Find formatter.

**Comment by antares1470** [comment]
Moved to [Brainstorm Ideas](https://github.com/constellation-app/constellation/wiki/Brainstorm-Ideas) and closing this issue for now.

**Comment by arcturus2** [comment]
@cygnus-x-1 said:

One-to-many element relationships in the Histogram View - this would be very useful for complex attribute types, and might even be a good first step towards 'multi-valued attribute' support. As an example, if i create a complex attribute which holds a list of strings ('one', 'two', 'three') and then display it in the Histogram, it'll currently show up on one row as [ 'one', 'two', 'three' ] (or whatever the string output format is), whereas with this improvement it'd show up over three rows as 'one', 'two' and 'three' (which also means each value in the list would be counted individually and combined with other same values).
