### ISSUE TITLE
A Type should be able to specify 'alias' rules

### ISSUE THREAD

**Issue by cygnus-x-1** [constellation-app/constellation#377]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

It would be useful if SchemaElementType could specify alias rules to specify multiple different representations. For example, you might specify that a telephone number type can be represented in normalised form (+612 411 111 111), or localised form (0411 111 111). Type objects should provide convenience methods to make accessing and validating against these representations seamless.

**Comment by antares1470** [comment]
Moved to [Brainstorm Ideas](https://github.com/constellation-app/constellation/wiki/Brainstorm-Ideas) and closing this issue for now.

**Comment by arcturus2** [comment]
@cygnus-x-1  said:

A Type should be able to specify 'alias' rules - this would be easy to implement on the surface, just add a list of aliases property to the Type classes. The tricky bit is what follows as the idea here was to be able to do things like auto-generate hash values (or other known variants) for internet identifiers and auto-query against all aliases.
