### ISSUE TITLE
Replace Quality Scores with Categories

### ISSUE THREAD

**Issue by cygnus-x-1** [constellation-app/constellation#378]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The Quality Control View is currently designed to run 'rules' across data in a graph in order to identify data quality issues, and to provide feedback on these issues in the form of a quality 'score' (0 to 100 - with 100 representing the worst quality) and a 'reason' for that score. Since these scores are essentially arbitrary (what does a score of 70 actually mean?), I propose we instead move to a system where we replace data quality scores with data quality categories, which I believe would be more interpretable. I imagine these categories might work much like a logging system, where there is a hierarchy of categories representing the severity or impact of the data quality issue (ie. FATAL, ERROR, WARNING, INFO). We could then assign each rule to a category - so the 'unknown type' rule might map to the 'INFO' category, whereas the 'blocked by compliance' rule would map to the 'FATAL' category. You might also add the ability to configure the rank of each category, so a user could specify which categories are important to them.

**Comment by aldebaran30701** [comment]
I was thinking of implementing a menu which would allow the user to map any rule to a category like mentioned above. Possibly using a linking system like how the Map View uses any class registered with a provider annotation. It could be a dynamically loaded list where the drop down options allow mapping.

I was thinking of having them effect elements so that the "label" or "category" was added to it. instead of showing the quality in a score, it would append labels. ie. IdentifierInconsistentWithTypeRule + UnknownTypeRule would both appear.

This is just going by my understanding of the QCV, and assumed ability to have multiple rules broken or satisfied by a single element.

I'm thinking for ease of use, it might be better to have a set of categories predefined and not allow the user to change them - just map them differently.

I'd like to hear your input on this, @cygnus-x-1 @arcturus2 etc.

**Comment by arcturus2** [comment]
> I was thinking of implementing a menu which would allow the user to map any rule to a category like mentioned above.

Not sure about this @aldebaran30701. Having predefined rules like they presently exist is probably more important than the ability to allow a user to create their own mappings. Supplying pre-defined rules help give a consistent Constellation experience amongst users.

> Possibly using a linking system like how the Map View uses any class registered with a provider annotation. It could be a dynamically loaded list where the drop down options allow mapping.

Using a Service Provider and LookupService is a great idea :+1:. In fact almost all views are extensible and it is done using this approach.

> I was thinking of having them effect elements so that the "label" or "category" was added to it. instead of showing the quality in a score, it would append labels. ie. IdentifierInconsistentWithTypeRule + UnknownTypeRule would both appear.

This is a good idea, however, the advantage of a score (current approach) or category (proposed approach) is that it helps triage potential data quality issues on the graph into something that is relatable with users. A category like "ERROR" is something that is easy to understand. The proposed categories from FATAL all the way down to INFO have an inbuilt "priority" order. Presenting "UnknownTypeRule" is not as intuitive (to me) and can be difficult to know if it something I need to fix (like FATAL) or a minor warning (meaning I can ignore and continue with my analysis).

Is any of my feedback useful @aldebaran30701? Do you agree with any of it? I'd be happy to go into more detail etc if you like.

**Comment by aldebaran30701** [comment]
>You might also add the ability to configure the rank of each category, so a user could specify which categories are important to them.

@arcturus2 I must have misunderstood this line of the ticket. Now I'm understanding that you'd want the user to be able to rank the category (INFO, WARNING, FATAL etc.) Thinking over this again,it seems like allowing the user to switch the ranking and effectively the meaning of the category would be redundant. Maybe at best a filtering system such as the `PluginReporter` uses. 

> Presenting "UnknownTypeRule" is not as intuitive (to me) and can be difficult to know if it something I need to fix (like FATAL) or a minor warning (meaning I can ignore and continue with my analysis).

I agree, I must have been in two worlds when writing my response. What would be the defined behaviour if an element failed checks in two rules? Append both rules? Use highest priority?

>Is any of my feedback useful @aldebaran30701? Do you agree with any of it? I'd be happy to go into more detail etc if you like.

Of course, I'll be looking up some stuff on ServiceProviders and using examples from the code-base to get some rules linked up

**Comment by aldebaran30701** [comment]
In terms of UI - I'd like to get your thoughts on something like this @arcturus2 . It's just a Paint mock up.
Pre-defined categories, which can be filtered to show only a certain category.

![QCV](https://user-images.githubusercontent.com/58677759/88866364-a6bbea00-d249-11ea-8016-d61d63e3225f.PNG)

**Comment by arcturus2** [comment]
@aldebaran30701 I was going to ask if you could do a wire-frame so thanks for this. It makes it way easier to talk to.

My feedback is as follows:
* We won't need Score. That would be replaced with a the Category. I think you realised this if I understood your "EDIT" comment?
* Seeing the reason is still useful for advanced analysts so having that there would be good.
* Good to see you thinking outside the box and adding in a filter like the Plugin Reporter. However I think this could cause cases where analysts don't see FATAL errors if they accidentally turn it off. I would prefer we didn't add this filter for this view.

**Comment by aldebaran30701** [comment]
>However I think this could cause cases where analysts don't see FATAL errors if they accidentally turn it off. I would prefer we didn't add this filter for this view.

@arcturus2 so would this implementation have any way of allowing the user to "set ranks" as in 
>*You might also add the ability to configure the rank of each category, so a user could specify which categories are important to them.*

Or would you suggest a ranking system instead of the filter? Just trying to think up a UI option for ranking items if this is what is needed for the view.

**Comment by arcturus2** [comment]
I didn't read the description of the issue properly that @cygnus-x-1 wrote. The user ranking bit wasn't something I was considering so apologies for any confusion @aldebaran30701.

> You might also add the ability to configure the rank of each category, so a user could specify which categories are important to them.

@cygnus-x-1 can you explain a bit more about what you mean here? Are you suggesting a user could map a rule from FATAL to INFO? I'm all for giving users the ability to customise but I am not keen on this idea.

**Comment by aldebaran30701** [comment]
This is ready for review, it appears that the 2 sonar warnings are false positives. Unless the issue is staring me in the face!

**Comment by mimosa2** [comment]
Good work @aldebaran30701. I tested this and looks good. Few minor changes may be; 
1. Giving a label to the preference json (see below) like "customRules=" similar to the recentValues.    
={"Missing type":"WARNING","Unknown type":"DEFAULT","Identifier inconsistent with type":"INFO"}

2. The alert box w/o the rule(see attached) can display a message like "No rules exist for this Identifier"
![Rules_Alert](https://user-images.githubusercontent.com/54261086/89751270-b8877200-db12-11ea-8368-8cf93c99aa10.PNG)
