### ISSUE TITLE
Web-compatible Constellation companion tool

### ISSUE THREAD

**Issue by cygnus-x-1** [constellation-app/constellation#379]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

It would be fantastic to have a a kind of 'Constellation-lite' which was built on web-technologies in order to allow it to be embedded in browsers/jupyter notebooks/etc. This would allow much more flexibility for those wishing to share Constellation graphs, and provide a lower point of entry for new users.

I'd imagine a Constellation-lite would at a minimum require;
- compatibility with the Constellation graph format
- ability to Scroll, pan and zoom around the graph
- labels and attributes be visible (maybe via popup on hover)
- ability to search across the graph for attribute values

**Comment by antares1470** [comment]
Refer to work being down here https://github.com/constellation-app/constellation-web for more info
