### ISSUE TITLE
Write an update centre creation guide

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#38]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

As a developer
i want a how-to guide for creating an update site
so that my users installation of constellation is always up to date.

**Comment by arcturus2** [comment]
Again, without creating new guides - we could probably append the required info to the existing developer guide.

**Comment by antares1470** [comment]
For this @arcturus2 reckons we can possibly redirect people to an existing Netbeans page for this kind of thing: https://netbeans.org/community/guidelines/au-management.html though that page isn't the best one

**Comment by antares1470** [comment]
Closing as this is contained in #35
