### ISSUE TITLE
Log when a view is opened, docked and closed

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#39]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

As a developer,
I want to enhance log files with view status data,
so that i am able to recreate a users instance for debugging

When looking at Constellation log files, knowing which views are opened, docked and closed will be really useful.
Maybe they could generate a plugin call because we could then see them in audit/usage logs.

### Steps to Reproduce

1. Open the Attribute Editor
2. Close the Attribute Editor

**Expected behaviour:** 2 log entries should exist referencing the open and close actions of the Attribute Editor

**Comment by cygnus-x-1** [comment]
FYI - I'm working on this now.

**Comment by cygnus-x-1** [comment]
I've hooked logging up to the AbstractTopComponent class. TopComponent offers listeners for opened/closed, as well as showing/hidden (is the view visible) and activated/deactivated (is the view in focus). Opened/closed answers this issue, but while i'm at it could there be value in logging the other modes? Showing/hidden would tell us when a view is minimised/expanded, and activated/deactivated would tell us when a view is being actively used.

**Comment by arcturus2** [comment]
> could there be value in logging the other modes? Showing/hidden would tell us when a view is minimised/expanded, and activated/deactivated would tell us when a view is being actively used.

Yes definitely @cygnus-x-1. When going through the logs it is unclear what views are in which state so the more we can log the more context we get and makes it just a little bit easier to understand what was going on.
