### ISSUE TITLE
SimpleGraphTopComponent and VisualGraphTopComonent should be in separate modules

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#40]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

`SimpleGraphTopComponent` and `VisualGraphTopComonent` can both used to visualise the graph and are treated as the main document.

The idea is that `VisualGraphTopComonent`, the default, provides an interactive JOGL representation of the graph, and if the system isn't capable of rendering that, you could fall back to `SimpleGraphTopComonent` which provides a Swing table representation of the graph.

Both of these currently exist in the same package in the Core Functionality module, meaning there is no way to switch between them.
By moving them out to separate modules, you could, for example, disable the module containing `VisualGraphTopComonent` to force Constellation to use `SimpleGraphTopComponent`.

**Comment by cygnus-x-1** [comment]
This task will be taken care of as part of https://github.com/constellation-app/constellation/issues/42.
