### ISSUE TITLE
Schema View causing the application to lag

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#406]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

With the Schema View open, switching between graph tabs can start to lag impacting other views from updating. Further investigation is required by profiling Constellation with the Schema View opened. The lag was very noticeable, probably more than 10 seconds. Closing the Schema View made the lag disappear.

### Steps to Reproduce

1. Open 2 graphs
2. Open the schema view
3. Repeatedly switch between the 2 graph tabs

**Expected behaviour:** Constellation should change to the switched tab and all views should update to reflect values on the new graph

**Actual behaviour:** The Schema view takes a few seconds to update and other views to update.

**Reproduces how often:** 90%

### Additional Information

On higher end hardware with faster CPU's this will be less noticeable. The issue seems to be symptomatic of processing work (i.e non graphic) running on the EDT (graphics thread).

**Comment by aldebaran30701** [comment]
I couldn't get this replicating and seems to be fine. I was switching graphs quickly and could only manage to replicate #560 but no lag
