### ISSUE TITLE
Timeline View out of memory error

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#407]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The timeline view can cause Constellation to crash with an out of memory exception if you open a graph with too many transactions. All of the graphics you see in the timeline view are JavaFX objects which take up a considerable amount of memory.

The following line seems to be where the memory shoots right up on a large graph:
https://github.com/constellation-app/constellation/blob/c997b6ff4a6f9bc18494c8726f085e11d1a4c5c0/CoreTimelineView/src/au/gov/asd/tac/constellation/views/timeline/TimelinePanel.java#L354

### Steps to Reproduce

1. Experimental -> Build Graph -> Sphere Graph
2. Enter a large number and this will depend on your hardware specs and how much memory you have allocated to Constellation. For example 50,000 transactions.
3. Open the timeline view

**Expected behaviour:** The timeline view and the rest of the application should be responsive

**Actual behaviour:** The application should be responsive to mouse selections

**Reproduces how often:** 100%

### Additional Information

I'm not sure how much we can do to fix this though it is worth investigating and seeing what optimisations we can make to the timeline view.

**Comment by Nova-2119** [comment]
Hmm, it does use a fair amount of memory for me but nothing unreasonable, not enough to cause the issues described in the ticket?
Ive managed to reduce the memory usage a little, and the amount of memory it is using seems comparable to the amount used when opening the same graph. It's also only a temporary increase (there is a permanent increase in memory usage but not on that level).

Ill put up a pull request for the small improvement I made but i'm tempted to say nothing to see here unless someone can confirm this is still an issue?

**Comment by Nova-2119** [comment]
My thinking being that from what I am seeing if you can open the graph you should then be able to run the timeline view on it as the memory required is roughly on par?
