### ISSUE TITLE
Gremlin View

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#408]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Add support to use Gremlin traversal language on a Constellation graph. This will be useful to those familiar with Gremlin.

For more information see https://tinkerpop.apache.org/gremlin.html.

### Additional Information

Most of the work has been done in a different java project and this task will involve porting it to Constellation.

**Comment by cygnus-x-1** [comment]
I presume this is here because we've got one of these we can add?
