### ISSUE TITLE
Break out colours and formatting into separate CSS files

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#414]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The JavaFX CSS style sheets contain formatting and colours in the one file which means that trying to change the colour scheme becomes difficult. The scope of this ticket is to look at separating them into a colours css and another for everything else.

**Comment by antares1470** [comment]
Closing as this ticket is encapsulated in #308
