### ISSUE TITLE
Remove the Map View module dependency on the Core Import Export module

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#43]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

Nothing should depend on Core Views but the Map View breaks this principle. Moving the related import/export classes from Core Map View to Core Functionality and using a Lookup would break the hard dependency.

**Comment by cygnus-x-1** [comment]
FYI - I'm working on this now.
