### ISSUE TITLE
Add a way to identify attributes that have had data ingested into them

### ISSUE THREAD

**Issue by CrucisGamma** [constellation-app/constellation#433]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

As a developer, I would like a way to iterate over any attributes that have had non-default or non-null data loaded into it.  For example, from a CSV import dialog box, would be nice to have it recognised that say data in RAW has been loaded in from one of the columns in the ingested file (likewise for JSON).  This way, I wouldn't have to programmatically determine which attributes are sensible to display if giving the end user an option of filled in attributes.

### Additional Information

Have talked a little about this with @arcturus2 and I don't think there's a definitive way as yet to say that say RAW or SOURCE or any other attribute is actually being used at the current time.

I could see it being a simple flag (say 'isUsed') type added into Attribute.java.

**Comment by cygnus-x-1** [comment]
Attributes can already have arbitrary properties, so there's no reason you couldn't add some utility functions to set and check an 'inUse' or even 'owner' property for any arbitrary attribute. The hard part would be enforcing that system is used, given the many ways (and many outside our control) that attributes are populated.

**Comment by CrucisGamma** [comment]
I had a form of this going (basically looking at "nonDefault" attributes.  But it's slightly sketchy in that if you have a random node that doesn't have it set to a nondefault value, it bypasses it.  And how many nodes do you look at was another question I couldn't successfully work out how to do.
