### ISSUE TITLE
Add a plugin to set various attributes values by comparing to a supplied CSV for another attribute's value

### ISSUE THREAD

**Issue by CrucisGamma** [constellation-app/constellation#444]
We could possibly add in a script in the 'Attributes Calculator' to populate the latitude and longitude for the center of a given country based on that attribute having a given country's flag.  Would probably be only applicable for attributes that don't already have those attributes populated.

**Comment by cygnus-x-1** [comment]
How about a polygon of the country (_geo.shape_) as well as its centroid (_geo.lat_, _geo.lon_)? Centroids can be confusing for geospatial analysis - and this way if you really did want the centroid, you could just delete the _geo.shape_ attribute to fall back to it.

**Comment by CrucisGamma** [comment]
I think my ideas on this one have evolved since writing it.  I would now like the following:
I have say 10 nodes with a given attribute (say ATTRIBUTE1).  Based on the value set in ATTRIBUTE1, I want to set ATTRIBUTE2 and ATTRIBUTE3 to be say X and Y.  This mapping will come from a user supplied CSV file that would have say 
ATTRIBUTE1_VALUE (key), ATTRIBUTE2_VALUE (value), ATTRIBUTE3_VALUE (value).

I think we could supply some standardish ones (the FLAG/GeoLat/GeoLong) but then other analysts could add in their own as required.

So it would be essentially a hash based on the expected key value in a single attribute* and the values of that being imposed on the 1 or more other attributes.  This could be used for example to make coloured spreadsheets for say a particular demographic within different Electorates or postcodes or streets.

* Note: This assumption may be incorrect to impose, and maybe it should be on a combination of ATTRIBUTE1/ATTRIBUTE2

**Comment by CrucisGamma** [comment]
I'd say that this functionality has been pretty much delivered (in the manner that I thought of at the time) as part of the hashmod plugin.
