### ISSUE TITLE
Drag from Attribute Editor to Graph View results in Exception

### ISSUE THREAD

**Issue by serpens24** [constellation-app/constellation#448]
### Description
Exception thrown when dragging from Attribute Editor to Graph. This occurs for both left click & drag and right click and drag.

If the drag operation is valid, then Exception needs to be addressed, if it is not a valid operation, then it sholdn't be permitted.

### Steps to Reproduce
1. Start Consty
2. Open a new graph
3. Open the attribute Editor
4. Left click in Attribute Editor, drag to the Graph View and release
5. Right click in the Attribute Editor, drag to the Graph View and release

**Expected behaviour:**
Steps 4 and 5 should NOT throw exceptions. Need to discuss with others to confirm if somethign should be copied to Graph View or not.

**Actual behaviour:** 
An exception is being thrown - see attached image

**Reproduces how often:** 
100%

### Additional Information

nil

**Comment by serpens24** [comment]
![Exception](https://user-images.githubusercontent.com/58677108/79836803-cbedc080-83ef-11ea-9e99-a344d135ce09.jpg)

**Comment by antares1470** [comment]
I can confirm that after playing around this issue also happens with non-empty graphs. Will update the ticket name accordingly
