### ISSUE TITLE
Null Pointer when right-clicking on graph

### ISSUE THREAD

**Issue by formalhaut69** [constellation-app/constellation#449]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Constellation will throw a null pointer when right clicking on a graph.

### Steps to Reproduce

1. Make a new graph
2. Right click on the graph
3. [and so on...]

**Expected behaviour:** A context menu appears

**Actual behaviour:** Null pointer exception is thrown

**Reproduces how often:** 100%

### Additional Information
![image](https://user-images.githubusercontent.com/58677762/79929327-93e48d00-8484-11ea-930d-814130952d23.png)

**Comment by arcturus2** [comment]
Tested and works fine! Thanks @formalhaut69
