### ISSUE TITLE
Drag and Drop .star files not working

### ISSUE THREAD

**Issue by Cable-326827** [constellation-app/constellation#450]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Dragging .star files into the Graph View from File Explorer does not copy/open the graphs.
Constellation recognises the files and has the + Copy text appear under the cursor, but nothing happens.

### Steps to Reproduce

1. Dragging .star files into Graph View of Beta version

**Expected behaviour:** Graph to Open

**Actual behaviour:** Nothing

**Reproduces how often:** Attempted repeatedly in two session.
[SupportPackage-2020-04-22-14-50-13.zip](https://github.com/constellation-app/constellation/files/4513846/SupportPackage-2020-04-22-14-50-13.zip)

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.
Using Windows 10.

**Comment by cygnus-x-1** [comment]
@Cable-326827 are you dropping the file onto a graph, or onto the empty (grey) background? I don't think we ever implemented drag and drop onto an open graph (although we should), but it should work if you drop it onto an empty space next to the graph tab (the thing with the graph's name on it).

**Comment by Cable-326827** [comment]
Dropping onto the grey part, next to the Tutorial tab.

**Comment by sol695510** [comment]
![Drag and Drop v2 0 0](https://user-images.githubusercontent.com/58677774/80776737-33e79800-8ba2-11ea-814f-174274f73c85.gif)

@cygnus-x-1 @Cable-326827 I tried it out and found that you can open a graph by dragging it and dropping it into an empty graph and it'll open in a new tab. However it won't ever open when dropping it into the grey part.

**Comment by formalhaut69** [comment]
I can confirm that in 1.3 dragging and dropping to the grey area works correctly and opens the .star file that was dragged and dropped. Dragging and dropping a .star file when a graph is already open will open the .star file in another graph.

**Comment by sol695510** [comment]
![DefaultDropHandler CHANGES](https://user-images.githubusercontent.com/58677774/81637178-ddf1da80-9454-11ea-9b7c-df95e968e50f.PNG)
@cygnus-x-1 on line 105, what was the purpose of changing the comparison operator? I believe this is where the issue lies because I altered it back to what it was before in v1.3 and the drag and drop functionality performs as expected.

It was part of this commit of yours if that helps: https://github.com/constellation-app/constellation/commit/5cb47fa008e17b7ff857e6424b93b3dd9b0508e1

**Comment by sol695510** [comment]
@cygnus-x-1 @arcturus2 when dragging a graph file to open, if the **Debug GL** checkbox is enabled in **Setup** > **Options** > **CONSTELLATION** > **Developer**, the following exception occurs:

![dragndropERROR](https://user-images.githubusercontent.com/58677774/81637822-7b014300-9456-11ea-9ee6-c0fd22772355.PNG)

This only occurs in v2.0 and not v1.3.

**Comment by cygnus-x-1** [comment]
> ![DefaultDropHandler CHANGES](https://user-images.githubusercontent.com/58677774/81637178-ddf1da80-9454-11ea-9b7c-df95e968e50f.PNG)
> @cygnus-x-1 on line 105, what was the purpose of changing the comparison operator? I believe this is where the issue lies because I altered it back to what it was before in v1.3 and the drag and drop functionality performs as expected.
> 
> It was part of this commit of yours if that helps: [5cb47fa](https://github.com/constellation-app/constellation/commit/5cb47fa008e17b7ff857e6424b93b3dd9b0508e1)

Ahhh that is quite clearly a typo. Go ahead and revert it :)

**Comment by sol695510** [comment]
> > ![DefaultDropHandler CHANGES](https://user-images.githubusercontent.com/58677774/81637178-ddf1da80-9454-11ea-9b7c-df95e968e50f.PNG)
> > @cygnus-x-1 on line 105, what was the purpose of changing the comparison operator? I believe this is where the issue lies because I altered it back to what it was before in v1.3 and the drag and drop functionality performs as expected.
> > It was part of this commit of yours if that helps: [5cb47fa](https://github.com/constellation-app/constellation/commit/5cb47fa008e17b7ff857e6424b93b3dd9b0508e1)
> 
> Ahhh that is quite clearly a typo. Go ahead and revert it :)

Is line 207 a typo too because the comparison operator changes there as well.

**Comment by aldebaran30701** [comment]
To note also, In the gif posted by @sol695510 in https://github.com/constellation-app/constellation/issues/450#issuecomment-622220051
When dragging a file into Constellation, the file is loaded but the name is not kept consistent. 
`Analyticgraph1.star` looks to be loaded as `Analyticgraph1.star6` or `Analyticgraph1.star7` etc.

This may have some overlap with #189 In the fact that the same method may be altering the graph name on load.
