### ISSUE TITLE
Need a colourize feature to colourize nodes in response to a given value

### ISSUE THREAD

**Issue by CrucisGamma** [constellation-app/constellation#458]
So if you had a sea of say Cosine or sine points, you would be able to colourize them (from say deep blue up to deep purple) in response to the Z value (or x and y values).  Not sure if something like this exists already.

**Comment by cygnus-x-1** [comment]
This sounds like the sort of task that the Attribute Calculator or Scripting View was made for - i don't think it's ubiquitous enough to demand it's own plugin. Perhaps we could add a default script to the Attribute Calculator to achieve this?

**Comment by CrucisGamma** [comment]
Yep, agreed @cygnus-x-1 (on reflection :)).  This and possibly the flag icon back-filling into geo-lat and geo-long (and maybe shape) would be good.  I'll add some extra thoughts on the other 'flag' script.

**Comment by aldebaran30701** [comment]
I've added this to the [brainstorm ideas](https://github.com/constellation-app/constellation/wiki/Brainstorm-Ideas) wiki for future consideration. Closing this as there is some overlap with the current toolset available within Constellation.
