### ISSUE TITLE
Null Pointer when selecting "Show Key Columns" with no graph open

### ISSUE THREAD

**Issue by sol695510** [constellation-app/constellation#465]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

When the Table View is opened when no graph is opened or loaded, selecting "Show Key Columns" causes a Null Pointer.

### Steps to Reproduce

1. Open Constellation 2.0.0.
2. Open the Table View.
3. Select the "Column Visibilty" button (first button at the top on the left side of the Table View) then select "Show Key Columns".

**Expected behaviour:** Do nothing.

**Actual behaviour:** Causes Null Pointer.

**Reproduces how often:** 100%

### Additional Information

![Table View - Show Key Columns no graph loaded with error](https://user-images.githubusercontent.com/58677774/80445280-022cc200-8953-11ea-871f-bfdffe4f2098.PNG)

**Comment by formalhaut69** [comment]
Took a look at this in v1.3. Clicking the Show Key Columns option does nothing so this is definitely new to v2. Here's the call stack of the exception;
![image](https://user-images.githubusercontent.com/58677762/80554338-fcdf7e00-8a0b-11ea-8858-ccddfdd57aa5.png)
