### ISSUE TITLE
Add a new SARS-CoV-2 visualisation data sample set

### ISSUE THREAD

**Issue by CrucisGamma** [constellation-app/constellation#469]
Not entirely sure if it's possible, but I think mapping out the SARS-CoV-2 DNA sequencing would be something to be able to do and may open up Constellation to different fields that may not have looked at it previously.  

I've downloaded the SARS-CoV-2 genome (from here I believe https://genexa.ch/sars2-bioinformatics-resources/) but it's only the  ACGT type data for the nucleotides(?)
```
>NC_045512 |Severe acute respiratory syndrome coronavirus 2 isolate Wuhan-Hu-1| complete genome
ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGTAGATCT
GTTCTCTAAACGAACTTTAAAATCTGTGTGGCTGTCACTCGGCTGCATGCTTAGTGCACT
CACGCAGTATAATTAATAACTAATTACTGTCGTTGACAGGACACGAGTAACTCGTCTATC
TTCTGCAGGCTGCTTACGGTTTCGTCCGTGTTGCAGCCGATCATCAGCACATCTAGGTTT
CGTCCGGGTGTGACCGAAAGGTAAGATGGAGAGCCTTGTCCCTGGTTTCAACGAGAAAAC
```
etc

I'm not entirely sure where the spatial data for constellation is as in how the spatial information for the parts of the dna that fold back on itself and forms the 'spike' for the ACE-2 receptor but being able to get that information from somewhere would allow a pretty cool default data set to have and to be able to display in 3d (something that looks a bit like this: https://cdn.geekwire.com/wp-content/uploads/2020/02/200219-cov19-1-630x344.jpg)

**Comment by CrucisGamma** [comment]
![200219-cov19-1-630x344](https://user-images.githubusercontent.com/62917181/80560354-f65d0080-8a23-11ea-8cfe-e06948440531.jpg)

**Comment by Guilty-Spark-343** [comment]
Yeah I love this idea!
Were you thinking of having a a few samples to show what Constellation can do or a plugin to pull these proteins and map them?
I'm not sure how you'd go about mapping the above biological assembly but we can definitely map the the atom structure.  I had a go today and it looks like this...

**Comment by Guilty-Spark-343** [comment]
![COVID19_spike_snap](https://user-images.githubusercontent.com/63685177/80688739-9f345a00-8b0f-11ea-863d-c3d7b1bc9c68.PNG)

**Comment by Guilty-Spark-343** [comment]
[Constellation_covid19_spike_glycoprotein.zip](https://github.com/constellation-app/constellation/files/4557061/Constellation_covid19_spike_glycoprotein.zip)
I've attached the star graph and a 10sec video panning around the protein

**Comment by spjspj** [comment]
Wow, that's awesome dude

**Comment by CrucisGamma** [comment]
@Guilty-Spark-343  Where did you get the data source?  I wasn't really sure what to look for

**Comment by Guilty-Spark-343** [comment]
Yeah it worked really well, super happy how it turned out!
I pulled the structure from https://www.rcsb.org/structure/6VXX as a PDB file (Protein Data Bank) which is the atom structure then constellated it in a simple notebook with biopython.  We can't generally go from the nucleotide sequence to structure but RCSB has thousands of structures in that PDB format.

**Comment by arcturus2** [comment]
Wow @Guilty-Spark-343 that is super amazing! Well done!

**Comment by aldebaran30701** [comment]
Closing this but adding it to the ticket #850 as it would be a worthy addition to the website to advertise what Constellation is capable of.
