### ISSUE TITLE
Redo the UI icons

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#47]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

As a user
I want updated icons
so that constellation does not look outdated.

The UI icons are outdated and need a refresh. When the darcular theme was applied, the GUI icons looked terrible.

**Comment by cygnus-x-1** [comment]
This is also about giving the UI a consistent look and feel.
