### ISSUE TITLE
Build Graph options should create a new graph if there isn't one open

### ISSUE THREAD

**Issue by formalhaut69** [constellation-app/constellation#474]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
At the moment if you want to use the build graph options you have to create a new graph manually. It would be nice if the build graph options created a new graph if there isn't one currently open.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behaviour:** [What you expect to happen]

**Actual behaviour:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by cygnus-x-1** [comment]
We had conflicting opinions about this last time I brought it up - I fell on this side of the fence, so i'm happy to see this ticket.

**Comment by formalhaut69** [comment]
If there was conflicting opinions about this issue then I'd like to hear @arcturus2's opinion before having a go at making this enhancement.

**Comment by arcturus2** [comment]
@formalhaut69 and @cygnus-x-1 catching up on this which I missed on responding to.

I'd be happy to support both of you and see this implemented. Build Graph does not seem as useful when merged with an existing graph so it makes sense to save people the trouble of having to create a new graph.

...for some reason I thought this was implemented but may be I'm dreaming.

**Comment by formalhaut69** [comment]
> ...for some reason I thought this was implemented but may be I'm dreaming.

@arcturus2 You might just be remembering the fact that I did have a go at developing this. We spoke briefly on the gitter about this feature. I couldn't get it working so I moved onto other issues. I had trouble with the timing of the build graph plugins because I was never able to generate a new graph before the build graph plugin ran.

**Comment by aldebaran30701** [comment]
Closing this issue as it is now covered in the Welcome Page. A one-click button is available to create a new sphere graph for testing.
