### ISSUE TITLE
Add context managers to the graph API

### ISSUE THREAD

**Issue by cygnus-x-1** [constellation-app/constellation#479]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Java 7 introduced the "try with resources" pattern often seen used with streams. If applied to the graph API, this pattern would allow us to automatically release any read or write locks taken.

**Comment by cygnus-x-1** [comment]
I've implemented try-with-resources for `ReadableGraph`, but not for `WritableGraph` as there was an issue. 

Our default implementation of `Graph` is `StoreGraph`, which is extended by `LockingStoreGraph` in order to add support for read and write locks. `LockingStoreGraph` achieves this by implementing both `ReadableGraph` and `WritableGraph` and if both of those implemented try-with-resources then you'd have a conflict on the `close` method. We'll need to refactor `LockingStoreGraph` in order to allow try-with-resources for both read and write locks.

**Comment by aldebaran30701** [comment]
Adding this to https://github.com/constellation-app/constellation/wiki/Brainstorm-Ideas as graph framework change for low value for devs only. Closing.
