### ISSUE TITLE
Include more information about queries in Plugin Reporter

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#49]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

As a user, 
I want to be able to see more detail about queries that I have run in the Plugin Reporter, 
so that I have a better understanding of the workflow that got to this point. 

This would help with looking at graphs that are older, too.
 Information that would be useful would include:
 - Nodes queried
 - Number of results returned
 - DateTime query was run, and results returned
 - The query sent to the data source

**Comment by GammaVel** [comment]
It would be good to spilt this ticket up into smaller tasks when it gets worked on

**Comment by andromeda-224** [comment]
![Image](https://github.com/user-attachments/assets/766dde30-023d-488f-9801-a9d69cb4d2d3)

In the attached image of the plugin reporter, the parameters, tags and start time was added.
Would something like this be sufficient?

**Comment by antares1470** [comment]
> ![Image](https://private-user-images.githubusercontent.com/174286651/374459358-48ff4d3c-fbb1-4b88-823b-a6fda2289c29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NDk1MzQsIm5iZiI6MTcyODQ0OTIzNCwicGF0aCI6Ii8xNzQyODY2NTEvMzc0NDU5MzU4LTQ4ZmY0ZDNjLWZiYjEtNGI4OC04MjNiLWE2ZmRhMjI4OWMyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOVQwNDQ3MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zN2E2MmNhY2I3NjdiMDE1Mjc1MzM0Y2NkNDY2ZjQzZmVmOGU4MWU1MDBkZDY5MWVlNTk1ZjhiNzQ3ZmUxMmY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Raoez39ejGAu0r-Uh-2QBJV6oPRtTlWxI3mnrJLr6x0)
> 
> In the attached image of the plugin reporter, the parameters, tags and start time was added. Would something like this be sufficient?

@andromeda-224 I would potentially omit the tags but otherwise something what you've added would work (inputs and time). Potentially could add how many nodes a plugin was run on?

**Comment by HolandCrick** [comment]
@andromeda-224 thanks for help to extend the Plugin Reporter info details. The plugin added the time but showing our local time as GMT time !
![Image](https://github.com/user-attachments/assets/bf09c343-9db4-4989-b4a3-0968da0740fc)

**Comment by andromeda-224** [comment]
> [@andromeda-224](https://github.com/andromeda-224) thanks for your help to extend the Plugin Reporter info details. The plugin added the time but showing our local time as GMT time ! ![Image](https://github.com/user-attachments/assets/bf09c343-9db4-4989-b4a3-0968da0740fc)

How about displaying it as 'Time: 2024-11-13T11:47:31.267+1030', would this be clearer?

**Comment by HolandCrick** [comment]
@andromeda-224  - Thanks for fixing the Plugin Reporter bug. It's working now as expected.

![Image](https://github.com/user-attachments/assets/574fcd6d-f1d3-44f3-bb25-64bedfd662fb)
