### ISSUE TITLE
Add the ability to move elements in spatial arrangements based on a supplied formula

### ISSUE THREAD

**Issue by CrucisGamma** [constellation-app/constellation#492]
In order to construct a proper planetarium, I would like the option to have a 4D scattergram. 

This would allow the following:
The sun to remain stationary, the Earth and other planets (not you Pluto) to start rotating around the sun in their respective elliptical orbits.  Then you could add in the Earth's moon, Jupiter's 53 moons, etc.  Having them in relative size to each other would also doable.  

Having the correct tilt as well on Earth would allow you to see the seasons, why there are the Tropic of Capricorn and Cancer.  

I guess it could also be used to show the movement of a individual elements within a network as well (so you could get a sine wave that moves, perhaps how a tsunami may form the wave as it races up a beach by modelling many individual water molecules, how DNA does its splitting trick perhaps as well).

**Comment by CrucisGamma** [comment]
This is not entirely serious, but I think it would be an interesting feature to develop and may lead to interesting outcomes in terms of analysis of complex networks that change over time.

**Comment by CrucisGamma** [comment]
So if someone wants to make constellation do something like this automatically, that would be a proper job...
https://www.reddit.com/r/signal/comments/gejpvw/gource_animation_of_signalandroid_development/

**Comment by aldebaran30701** [comment]
Closing this but noted that it has been added to [Brainstorming Ideas](https://github.com/constellation-app/constellation/wiki/Brainstorm-Ideas) as it is a really neat concept.
