### ISSUE TITLE
Increase Error visibility

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#50]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

As a user
I want error information to be more visible
so that constellation doesn't seem to quietly fail

Sometimes when errors occur during plugin execution, there is no pop up; rather a small icon on the bottom right so the user does not know there was an error.

**Comment by antares1470** [comment]
`ConstellationDialog` might be something to look at if we go down the dialog box path

**Comment by aldebaran30701** [comment]
I've had a decent look into the way Constellation handles its exceptions. Currently, I've got a PR which needs a little more work to get it over the line, but this PR increases some consistency of the error handling capabilities.

The fundamental issue with error logging to the user is that if the unexpected exception is not thrown within code running on the default plugin environment, we cannot catch it and handle it (display to user).

**Run Constellation in debug through Netbeans**
- Raise an unexpected exception from code not running in plugin environment = Netbeans handles it as an exception and displays a pop up with the error.
- Raise an expected exception from code not running in plugin environment = ConstellationDialog handles it as an exception and displays a pop up with the error.

**Run Constellation in release**
- Raise an unexpected exception from code not running in plugin environment = Netbeans does not display anything to the user. **Constellation code cannot capture this case.**
- Raise an expected exception from code not running in plugin environment = ConstellationDialog handles it as an exception and displays a pop up with the error.

**Comment by arcturus2** [comment]
@aldebaran30701 I found the answers in https://netbeans.apache.org/wiki/DevFaqUnexpectedExceptionDialog.asciidoc.

**show every error**
```
./constellation -J-Dnetbeans.exception.report.min.level=1 -J-Dnetbeans.exception.alert.min.level=1
```

**hide all errors** (more for FYI but not what we want)
```
./constellation -J-Dnetbeans.exception.report.min.level=99999 -J-Dnetbeans.exception.alert.min.level=99999
```

**Comment by aldebaran30701** [comment]
Awesome find @arcturus2 
Do you feel that anything further is necessary for this ticket other than adding those parameters?

**Comment by arcturus2** [comment]
Honestly as a minimum I think that should be fine with those parameters and its a quick win. I have been looking at the message handing in general and have some ideas but that can be a future task I feel. I will document it all and send through a PR. I am also keen to continue from your branch `feature/error-visibility` if that's OK @aldebaran30701?

**Comment by aldebaran30701** [comment]
@arcturus2 totally okay with me - I think the review comments were only about the fact that the unhandled exceptions weren't displaying. Probably worth checking that with the new parameter, that they don't get duplicated in the release versions.

**Comment by antares1470** [comment]
Just need this PR to be merged in from the constellation-applications project: https://github.com/constellation-app/constellation-applications/pull/2

**Comment by GammaVel** [comment]
This is looking good and a really excellent idea to highlight the errors to the end users. Thanks @aldebaran30701 for your efforts to improve Constellation!
