### ISSUE TITLE
View State implementation rework

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#506]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
Currently the State in both **Analytic view** and **Layers view** works as intended.
The problem is the structure in which they work is not ideal. **Layers View** currently passes the pane object into a plugin as a way of updating the pane. 

An ideal solution would involve the `AttributeValueChangeHandler` refreshing the Layers View pane upon changing of the Layers View State Attribute.

### Steps to Reproduce

N/A

**Expected behaviour:** [What you expect to happen]
Low coupling of classes and satisfactory consistency achieved.
**Actual behaviour:** [What actually happens]
Highly coupled methods which are not consistent with other views
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Additional Information
#454  
Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by arcturus2** [comment]
Almost all views write their state to the graph (i.e taking a write lock) when you change something on the view or more worrying is when you change graph tabs, all views write their state changes to the graph. If you have a lot of views open then that is a lot of write locks chaining one after another.

The Find View (one of the oldest views) seems to want to write its state twice so all of this builds up and creates performance issues.

Perhaps writing the views state should be handled by the Views Framework which could help standardise and perhaps optimise how the views write their state.

**Comment by Delphinus8821** [comment]
Closing as this has been completed over other tickets.
