### ISSUE TITLE
Closing the close graph prompt exits graph without save

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#508]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
Constellation should be consistent with close file behaviour from other systems (Windows apps)
Closing a graph when unsaved changes exist produces the Close graph prompt.
Clicking save produces the Save File Dialog.
Closing the Save File dialog using the X button closes the graph without saving or re-prompting.
Closing the Close graph prompt using the X on windows still produces the Save File Dialog. 

This to me goes against the usability of Constellation, especially coming from Windows where the below behaviour exists:

Close unsaved application
     - prompt Save | Don't Save | Cancel
    
Save - opens Save File Dialog
Don't Save - closes unsaved application
Cancel - disrupts the close event AND the save event
Top right X - disrupts the close event AND the save event

Save File Dialog
Save - Saves file
Cancel - closes Save File Dialog but application with unsaved changes remains open
Top right X - closes Save File Dialog but application with unsaved changes remains open

### Steps to Reproduce
_**Case A**_
1. Open new graph
2. Make a change
3. X on graph tab to close
4. X on close prompt

**_Case B_**
1. Open new graph
2. Make a change
3. X on graph tab to close
4. Save
5. Close Save File Dialog || Press Cancel

**Expected behaviour:**
_**Case A**_
Operation is cancelled. - No Save File Dialog opening

_**Case B**_
Close operation is cancelled unsaved graph still exists

**Actual behaviour:**
_**Case A**_
Save File Dialog opens
![SaveGraph](https://user-images.githubusercontent.com/58677759/81650008-5b771400-9470-11ea-9d5f-221f80ffca42.gif)

_**Case B**_
Unsaved graph closes without prompt
![SaveGraphB](https://user-images.githubusercontent.com/58677759/81650018-5f0a9b00-9470-11ea-9d0e-0b37ef3b5761.gif)
**Reproduces how often:** 
100%

### Additional Information
This is an enhancement to the usability of the application and may help in the future if a file was accidentally deleted - like I did myself.
Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by arcturus2** [comment]
This works really well and again is going to be a major saving grace for users. Thanks @aldebaran30701 and @Auriga2 for this.
