### ISSUE TITLE
Multi-choice menus need select all and deselect all options

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#51]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

As a user
I want a (de)select all buttons on drop-downs
to increase the UX of Constellation

Multi-choice drop down menus (both the javafx and swing versions) are tedious to use when there are more than a few options - which is often the case. I think we need Select All and Deselect All buttons beside the menus to improve usability.

**Comment by cygnus-x-1** [comment]
Constellation currently uses ControlsFX for its multi-choice menus. An issue has been submitted to the ControlsFX project - https://github.com/controlsfx/controlsfx/issues/1044.

**Comment by GammaVel** [comment]
Noting that the ControlsFX issue is still open and doesn't look like it has been worked on, can Constellation update the ControlsFX?  This would mean there would be consistency across views.

**Comment by aldebaran30701** [comment]
Also to note is that there is an implementation currently similar within NotesView if an example is needed.

**Comment by aldebaran30701** [comment]
I think there was code in PR for the Find View Rework also that could be made modular to fix this.

**Comment by GammaVel** [comment]
Hi @capricornunicorn123 , it is great to see this longstanding issue be worked on, thank you very much for making the updates. The multi select is working really well and it is handy for drop downs with lots of values. Initially I missed that you can right click to see this on the Find, Notes and plugin reporter. It is good that this option works there.
