### ISSUE TITLE
Integrate lgtm

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#510]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Consider integrating https://lgtm.com into the CI process to give more insights into our code base and how it can be improved from a security standpoint.

**Comment by aldebaran30701** [comment]
With the new github actions implemented this should not be hard at all. Create a lgtm account, and a PR with the action linked.
The action is on github marketplace so it should be pretty easy just to use the default template for scanning.

**Comment by aldebaran30701** [comment]
@arcturus2 Would the plan be to use this in conjunction with Sonar? 
It seems there is a bit of overlap.

**Comment by GammaVel** [comment]
LGTM might have different findings, worthwhile considering what this offers and doing a comparison.

**Comment by aldebaran30701** [comment]
I did a quick google "LGTM vs SonarQube" and it seems like just on the amount of extra information and users that Sonar seems like a clear winner.
https://stackshare.io/stackups/lgtm-vs-sonarqube

Sonar integrates with a heap more tools, LGTM appears to only be supported via GitHub. Sonar also supports IDE Integration, but LGTM does not.

The last merged PR in LGTM was in 2016, but as noted in the README on that repository - the Author sees LGTTM as being Feature complete, and not a reflection of an abandoned project.

I'd vote to say this is not needed, as the tools currently in action already surpass the reward we could get from installing LGTM alone

**Comment by arcturus2** [comment]
@aldebaran30701 I'm alright with closing it based on the feedback. SQ is doing a good enough job.
