### ISSUE TITLE
Integrate Restyled

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#511]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Integrate https://restyled.io into the build pipeline to make code checked in consistent (and automated). The code style rules should follow what NetBeans uses when you auto-format code with default settings.

**Comment by aldebaran30701** [comment]
Similar to #510 this should be easy to implement due to being on the github marketplace.
A better discussion to be had would be do we need these? with Sonar and actions running tests already will we be hindering the process?

**Comment by arcturus2** [comment]
@aldebaran30701 I'd vote to have this in. I'd like code to be consistent in formatting and this will help stop changes going in that don't follow the formatting rule.

I've found that when formatting is consistent, reviewing PRs is easier and there is less chance for merge conflicts.

**Comment by aldebaran30701** [comment]
@arcturus2 Closing this as it may not be a high priority currently.
