### ISSUE TITLE
Migrate website to GitHub Pages

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#512]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

To reduce costs, move away from hosting the website externally and seriously consider moving to using GitHub pages.

**Comment by antares1470** [comment]
This is done. Closing
