### ISSUE TITLE
Setup a Newsletter

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#513]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

I'd like to setup a newsletter that anyone can subscribe to get updates, for example when we make a major release. Consider using https://mailchimp.com/ for this which is free for up to 2,000 subscribers.

This should be linked to the website and there is a painless way to do this too.

**Comment by aldebaran30701** [comment]
@arcturus2 Closing this for lower priority feature
