### ISSUE TITLE
Configure nightly builds

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#515]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Some people have expressed interest to be able to download nightly builds of Constellation. Changes to Constellation are made almost daily so this feels appropriate to have. The scope of this would be nightly builds of the standalone version.

**Comment by GammaVel** [comment]
This is just what I am after as a fan of Constellation, it is handy to have access to all the latest bug fixes and new features. Thanks again @aldebaran30701 for setting this up!!! I have found I need to be logged into Gitlab to be able to download them but that makes sense. I like the way the older ones expire automatically too.
