### ISSUE TITLE
Configure an Update Site

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#516]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

NetBeans supports the ability to download updates from an update server. Constellation is able to do the same thing. Before proceeding some logistics will need to be agreed upon such as creating a `releases` branch that the update site builds from. `master` is not appropriate.

If we do this then we just need to be mindful of the additional support burden and testing required before pushing changes out as it can break the app if a bad update is pushed.

There is also another stand alone version called the **Constellation Shell** that can be used to point to a pre-configured update site and that setup works well. Before the update site is implemented, the Constellation Shell code will need to be added to GitHub.

**Comment by aldebaran30701** [comment]
Update site has a bit of feature overlap with #515  in it's use case. Configuring an update site will have the added benefit of sharing the updates without a user downloading a new version. A by-product of this is that if a breaking change is released, we get testing earlier, but the code also breaks with the user not during developer testing. 
I'd say it's harder to set up an update site but may provide more usable features.

**Comment by antares1470** [comment]
This has been moved to [Brainstorm Ideas](https://github.com/constellation-app/constellation/wiki/Brainstorming-Ideas)
