### ISSUE TITLE
Constellation Swagger

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#517]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

To help fund the domain name registration and things like #515 and #516 we could look at developing some Constellation swagger like t-shirts, hats, mugs and use funds to pay for expenses.

**Comment by antares1470** [comment]
Sounds cool. Probably doesn't need to be a ticket though so closing
