### ISSUE TITLE
Constellation to use the System Proxy settings by default

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#52]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

You can set a proxy for Constellation to use but it would be ideal for this to be auto detected using the proxy discovery capability.

So we should be able to default to using the "System proxy settings" and then fall back to the pre-configured settings if nothing is detected.

**Comment by antares1470** [comment]
This is already done. Closing
