### ISSUE TITLE
Add icons for Circle/Proximity Arrange menu items

### ISSUE THREAD

**Issue by serpens24** [constellation-app/constellation#520]
### Description

Issue 155 recently added two new arrangement buttons to the Arrangements menu and toolbar. In adding these, icons were created corresponding to the existing grid icon.

In looking at this is was noticed that the circle and proximity arrangements do NOT have icons. This presents two problems ... 

1. these 2 options are inconsistent with others
2. because they have no icon, they are not added to the toolbar (they need to be manually turned on)

This issue is raised to add icons, and potentially revisit the icons for all arrangements to be something more visually appealing (and consistent)

NOTE: while this ticket highlights the 2D arrangements, there are also 3D options in the Arrange menu, perhaps these should be considered as well.

### Steps to Reproduce

1. Open Arrangement menu
2. Note that circle and proximity options do NOT have icon images
3. View Arrangement toolbar and confirm that circle and proximity options do NOT have icon images

**Expected behaviour:** 
Icons exist

**Actual behaviour:**
Icons do not exist

**Reproduces how often:** 100%
### Additional Information

Nil

**Comment by formalhaut69** [comment]
@arcturus2 @cygnus-x-1 @serpens24 These are the mockups I've made for the arrange in circle, grid and tree icons. If you guys like them then I'll go ahead and make some better quality versions. I wanted to keep them consistent with the select icons; 
![image](https://user-images.githubusercontent.com/58677762/81885358-5681a400-95d9-11ea-9d72-9317af568211.png)

![image](https://user-images.githubusercontent.com/58677762/81884998-8d0aef00-95d8-11ea-9065-e1710228814c.png)
![image](https://user-images.githubusercontent.com/58677762/81885014-91cfa300-95d8-11ea-9dc7-23186a2aa0ab.png)
![image](https://user-images.githubusercontent.com/58677762/81885033-9d22ce80-95d8-11ea-9ab7-041bcef42ae8.png)

I also looked into the arrange by proximity but I'm not entirely sure what it does so I'm hoping to get some suggestions for how that one should look. Same goes for the arrange by Node Attribute if anyone has any suggestions.

**Comment by arcturus2** [comment]
@formalhaut69 I think ur mockups are good so please proceed. Happy for you to wait until you get feedback from more people if you want to as well.

The arrange in proximity tried to group nodes that are close together - together, and nodes that are less connected further apart. How about a simplified version of what this looks like (with way less nodes and links) ?

<img width="692" alt="image" src="https://user-images.githubusercontent.com/39325530/82003020-a7a99a80-96a2-11ea-81ea-4e7a85b591d5.png">

For arrange by attributes it will "sort" them by an attribute so this is me sorting by colour. So again how about a mockup of a grid with different colours like this?

<img width="639" alt="image" src="https://user-images.githubusercontent.com/39325530/82003425-afb60a00-96a3-11ea-8792-dedb76e98e4b.png">

**Comment by serpens24** [comment]
How would you intend to scale these icons down to the smaller size. for instance the existing icons are 16x16. I'm not sure if there is a size restriction on the icons @arcturus2 

By means of example, the example icons you have references are 16x16, here is the bits of an individual spot:

![image](https://user-images.githubusercontent.com/58677108/82266337-94e7dc00-99a8-11ea-8e5a-a627e2120357.png)


with 16x16 we have very little room to deal with so icons need to be simple.

Heres examples of grid, vertical and horizontal using the same 4x4 images found in the other icons:

![grid](https://user-images.githubusercontent.com/58677108/82266385-b47f0480-99a8-11ea-815a-6b006af16f2c.png)
![vertical](https://user-images.githubusercontent.com/58677108/82266395-b9dc4f00-99a8-11ea-82f9-ed031e7212b2.png)
![horizontal](https://user-images.githubusercontent.com/58677108/82266402-c06ac680-99a8-11ea-96b6-5cc98b3d6df0.png)

Im just spinning up a version with a 32x32 icon to see what it does ...

**Comment by arcturus2** [comment]
>  I'm not sure if there is a size restriction on the icons @arcturus2

I think you pretty much answered this @serpens24 but for GUI icons we do default to 16x6 but all of this is configurable should we want to up them a bit.

For now I'd say stick with 16x16 if you can but we can revisit this with perhaps 24x24 up scaling?

**Comment by serpens24** [comment]
> > I'm not sure if there is a size restriction on the icons @arcturus2
> 
> I think you pretty much answered this @serpens24 but for GUI icons we do default to 16x6 but all of this is configurable should we want to up them a bit.
> 
> For now I'd say stick with 16x16 if you can but we can revisit this with perhaps 24x24 up scaling?

Thanks @arcturus2 - so @formalhaut69 I think  try grab the example (transparent0 images I provided above and see how many cases they cover.

**Comment by formalhaut69** [comment]
@arcturus2 Here's the rest of the icons. I think we should keep @serpens24's icons. If I'm being honest I think the arrange in tree icon is a little confusing, at first I didn't know what it was but I don't have any better suggestions and my mockup won't work in 16x16.

I've made two versions of Arrange by nodes but in the small 16x16 space its difficult to show grouping and transactions with this many nodes so I'm happy with any suggestions.
![ArrangeByNodes](https://user-images.githubusercontent.com/58677762/82286020-e8275200-99db-11ea-962a-75067cff95a9.png)  ![ArrangeByNodes2](https://user-images.githubusercontent.com/58677762/82286038-efe6f680-99db-11ea-9681-bf6fddb4843c.png) 

I also re-created the arrange in grid because if we go with the first option for arrange by nodes this one will be more consistent.
![arrangeInGrid](https://user-images.githubusercontent.com/58677762/82286073-055c2080-99dc-11ea-9438-649bd2fa4603.png)

Arrange by proximity.
![arrangeByProximity](https://user-images.githubusercontent.com/58677762/82286058-f9705e80-99db-11ea-83b1-ccfeee88f3bf.png)

Arrange in hierachy
![arrangeInHierachy](https://user-images.githubusercontent.com/58677762/82286096-0e4cf200-99dc-11ea-95e4-7b6cb24998a2.png)

**Comment by serpens24** [comment]
I prefer the second arrange by node attribute as it doesn't end up looking like one big grid.

**Comment by arcturus2** [comment]
I like the logos as they blend in nicely with the existing theme. I also like the new grid icon.

With regards to the arrange by nodes I would opt for the second one too and I will also like to suggest after thinking about it further to limit the colours to max 3. Based on my design experience limiting to 3 colours helps to keep to a consistent colour theme and images blend together better.
