### ISSUE TITLE
Exception when running arrange in scatter 3D 

### ISSUE THREAD

**Issue by formalhaut69** [constellation-app/constellation#522]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Running the arrange in Scatter 3D plugin with missing input will throw an exception along with an error window.

### Steps to Reproduce

1. Open Arrange in Scatter 3D
2. Don't enter anything in the options popup 
3. Click OK to run it.

**Expected behaviour:** The plugin window won't run or perhaps a window informing the user that they didn't enter all the required information

**Actual behaviour:** An exception is thrown and an error window also pops up

**Reproduces how often:** 100%

### Additional Information
![image](https://user-images.githubusercontent.com/58677762/81884195-59c76080-95d6-11ea-8970-0cddc8e7534c.png)
![image](https://user-images.githubusercontent.com/58677762/81884652-9182d800-95d7-11ea-938f-f5ca8cc63123.png)

**Comment by aldebaran30701** [comment]
Looks like an access of a graph attribute which is not existent. I did this many times. Check if you grab an attribute that if there is a possibility for it to not be on the current graph, that you use `.ensure(graph)` as opposed to `.get(graph)` because ensure will create one if it doesn't exist. 

Is this yours @CrucisGamma

**Comment by spjspj** [comment]
Hmm, possibly :)  Can look more into!

**Comment by CrucisGamma** [comment]
Fix is basically to add this to 
CoreArrangementPlugins\src\au\gov\asd\tac\constellation\plugins\arrangements\scatter\ArrangeInScatter3dGeneralPlugin.java
on line 82/83 (with a new line).
```
        if (xDimensionName == null || xDimensionName.equals("") ||
            yDimensionName == null || yDimensionName.equals("") ||
            zDimensionName == null || zDimensionName.equals("")) {
            interaction.notify(PluginNotificationLevel.FATAL, "You must supply all 3 attribute names for Scatter 3D");
            return;
        }
```

**Comment by CrucisGamma** [comment]
Hopefully this is the fix!  https://github.com/constellation-app/constellation/pull/525
