### ISSUE TITLE
Support edge and link attributes in views

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#532]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Constellation supports properties at the transaction, edge and link modes though the focus with most views (besides the Histogram) has been working with attributes on transactions.

There are use cases emerging where having edge and link attributes would be useful (i.e. using a Constellation graph to resemble a network diagram) with the ability to be able to show the ip range at the link level and IP address of interfaces via edge properties. The node-edge property should ideally be rendered closer to node (e.g. IP address on an interface) rather than the middle.

The scope of this change is:
* All Views from the Views menu (besides Histogram)
* The Graph View (requires OpenGL updates) and is equally important. Note that for this, new graph attributes similar to `node_labels_top` will be required for edge and link attributes.

**Comment by antares1470** [comment]
Closing for now given the amount of effort required to do this at this stage. This would be something easier to implement if multi-valued attributes were a thing but adding that will itself take a lot of time. This has been added to Brainstorm Ideas though so that we don't forget about it
