### ISSUE TITLE
NullPointer when making a new graph

### ISSUE THREAD

**Issue by formalhaut69** [constellation-app/constellation#537]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Got a null pointer when making a new graph. I've been using dark mode "dark metal", this may have had something to do with it but unlikely.

### Steps to Reproduce

1. Immediately after opening constellation click the new analytic graph 
2. [Second Step]
3. [and so on...]

**Expected behaviour:** Opens a new graph without issue

**Actual behaviour:** NullPointer exception was thrown

**Reproduces how often:** Could not reproduce it. 

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.
![image](https://user-images.githubusercontent.com/58677762/82397821-71985c00-9a90-11ea-95da-cad85e9366b6.png)

**Comment by arcturus2** [comment]
I think this is related to the DarkMetal theme. I saw this too when I changed to it.

**Comment by aldebaran30701** [comment]
I am not able to recreate this issue. I did some static code analysis and it appears to be an issue with line 218.
https://github.com/constellation-app/constellation/blob/master/CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/gui/VisualGraphOpener.java#L218

Adding a null check to the parameters on this line may cover up a deeper issue while silently handing the null.

**Comment by Auriga2** [comment]
I couldn't recreate either. Tried DarkMetal theme.

**Comment by arcturus2** [comment]
I was able to produce different exceptions but not this one again either 🤣 
If you can't reproduce this too @formalhaut69 should we close it for now as can't reproduce?

**Comment by formalhaut69** [comment]
@arcturus2 yeah I haven't been able to reproduce this. Happy for you to close this.
