### ISSUE TITLE
Fix to broken unit tests

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#550]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The unit tests have been broken for a little while it seems. Travis has been silently failing since migrating to NB 11.

This is current master

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/39325530/82662888-00b09a00-9c72-11ea-9f31-6aef773fedcb.png">

This is 6b4df60 (v2 beta)

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/39325530/82822182-b2f19700-9ee8-11ea-8ddd-78d818ffd7b6.png">

**Comment by mimosa2** [comment]
Looks like the expected result and testDateTime offset needs to have colon instead of a dot.
final String expResult = "2019-04-23 01:16:42.000 +**10:00** [Australia/Sydney]";
String testDateTime = "Tue Apr 23 01:16:42 +**10:00** 2019";
final String expResult = "2019-04-23 01:16:42.000 +**10:00**";
final String expResult = "2019-12-25 00:00:00.000 +**00:00**";

**Comment by mimosa2** [comment]
testDateTime Should be 
String testDateTime = "Tue Apr 23 01:16:42 +1000 2019";

**Comment by arcturus2** [comment]
After PR #579 there are only 4 left to fix

<img width="1619" alt="image" src="https://user-images.githubusercontent.com/39325530/84624718-4258fb80-af25-11ea-9e5f-b363cecfa9dd.png">
