### ISSUE TITLE
Many instances of "DAV Pane Creator" running.

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#562]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

This may be effecting performance, but either way it seems bad to just have the threads waiting endlessly.
Even after exiting the view, all creator threads remain. Launching the DAV again, does not yield more threads.

### Steps to Reproduce

1. Open new graph
2. Open Data Access View

**Expected behaviour:** less threads

**Actual behaviour:** many threads
![image](https://user-images.githubusercontent.com/58677759/83701189-05008e00-a648-11ea-853b-f550f96fed04.png)

**Reproduces how often:** 100%

### Additional Information

N/A

**Comment by cygnus-x-1** [comment]
This seems to come from `DataSourceTitledPane` in the Data Access View and is used to build parameters for a single plugin. There are many of them because `Executors.newFixedThreadPool` is being used, although I don't know why they are not cleared once the parameters are created - perhaps that executor implementation ensures some number of threads are always available? I didn't actually write this code so i'm not sure if this was the intended behaviour, but it does seem odd to me.

**Comment by arcturus2** [comment]
This is something I had in my internal todo list to clean up so a good find @aldebaran30701. We can double check with @algol60 who wrote this part to speed up the performance and reduce the load time for the Data Access View.

I don't think we need the threads lying around after the DAV pane has been *fully* created and I tried to have the threads die but I was not able to get it to work. Hopefully you or someone else will have better luck.

**Comment by antares1470** [comment]
To quote the javadoc for `Executors.newFixedThreadPool`: "The threads in the pool will exist until it is explicitly `shutdown`".

Having had a quick look in the code, it doesn't appear `shutdown()` is called so this is probably why the threads are lingering

**Comment by aldebaran30701** [comment]
After some investigation, the threads of the thread pool executor stick around because they might be used later on to create new DAV tabs (runs). If the executor was shut down after the initial loading of tab 1 parameters, there was no noticable saving in memory or gain in performance. When a new tab (run) needed to be added, the executor would then need to initialise a new thread pool as the previous one was closed. This may introduce more performance degradation than leaving the threads running. 

From the below photos, you can see that there is negligible difference in either keeping them around or getting rid of them.
I think from this investigation, it is obvious that the best course of action to leave the current implementation alone.

With threads running:
![image](https://user-images.githubusercontent.com/58677759/150447278-1c701939-5ab4-471c-8f96-e5d146be9b8c.png)

Without threads running:
![image](https://user-images.githubusercontent.com/58677759/150447353-2a6c1e68-3bbc-4d5f-bb6d-0e0eb77fe07c.png)

I vote to close this ticket with no further action.
