### ISSUE TITLE
Cannot run exe file. Error: "Connot find 'platfom*' folder!"

### ISSUE THREAD

**Issue by Syn-co-pat-ed** [constellation-app/constellation#565]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behaviour:** [What you expect to happen]

**Actual behaviour:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by arcturus2** [comment]
Hi @Syn-co-pat-ed, sorry that you are getting this error. I've never seen it before. To assist further can you let me know which version you downloaded and perhaps share a screenshot so I can see exactly what you are seeing?

Please update the ticket description with as much information as you can.
