### ISSUE TITLE
Implement Material Design

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#569]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Material Design is Google's design guidelines for developing applications (web or native andriod apps). For more information see https://material.io.

The JavaFX library I've been following for some time that is trying to follow the Material Design is https://github.com/jfoenixadmin/JFoenix and I would like to start using these components instead.

For example the ripple button effect is great because it gives immediate feedback that the button was clicked. For more information read https://material.io/components/buttons#properties and can be implemented by using something like http://www.jfoenix.com/documentation.html#Rippler

With the flat LAF (look and feel) theme now available in NB11.3 onwards and JFoenix could make Constellation look like a modern app and be able to adopt recent UX design principles.

**Comment by antares1470** [comment]
This has been moved to [Brainstorm Ideas](https://github.com/constellation-app/constellation/wiki/Brainstorming-Ideas)
