### ISSUE TITLE
Allow pinning of nodes to the graph

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#57]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

As a user
i want to be able to pin a node to its location
so that i can arrange other nodes around them

Pinning nodes to the graph would be great.

Being able to fix particular nodes in place and then rearrange any unpinned nodes (especially for new nodes) around them would be great.

**Comment by serpens24** [comment]
@arcturus2 - how would you propose this would work if say 2 nodes were pinned, and both selected, and the user selected to arrange in a grid (or for instance a new horizontal or vertical line) ...... how would you propose it would work .. would the pinned nodes just stay where they are (as if not selected) ?
The reason I ask, is this sort of 'arrangement' operation could potentially conflict with the pinned postion of nodes.

**Comment by arcturus2** [comment]
Hi @serpens24 the intended behaviour would be as if they are not selected. By being pinned, they really should not move from that x,y,z position. Noted that other arrangements could sit on top of them and that will probably be something we have to deal with down the track like arranging nodes in a place that doesn't overlap with existing nodes. That isn't something our arrangement framework currently supports and would be out of scope for this implementation.

I made a poor/failed attempt at keeping nodes positioned at the same place which is the "Freeze graph view" feature you will see on the toolbar (blue snowflake). This implementation was mainly around the Data Access View and the scenario of running a data access plugin which finishes off by doing some arrangement. If a user has their graph laid out in a particular way, running plugins shouldn't re-arrange them if they don't wont them to.

I say that my implementation is broken because it only works for plugins that implement `RecordStoreQueryPlugin` and each plugin has to have an if check to see if the Freeze graph view is enabled or not. 

**Base on feedback this feature was proposed and the implementation should ideally be down at the OpenGL level for maximum efficiency and to also not require any plugin to know/care if nodes are pinned.**

Does that make sense?

**Comment by Guilty-Spark-343** [comment]
Which would people prefer, a single button that toggles the pinned state of the nodes or two separate buttons, one for pinning/locking, the other for un-pinning/unlocking.  At the moment I just have a toggle and I'm finding that a little inconvenient but happy to keep it that way if others prefer.  

Other styling questions:

-  Are we happy to use a lock icon to symbolize pinning/locking and does it fit in with the other icons?
![image](https://user-images.githubusercontent.com/63685177/83102429-c45cbe00-a0f7-11ea-8697-3aac821648bd.png)

- Is there any preference to where the lock on the node sits? Currently I have it on the bottom right hand corner.  
![image](https://user-images.githubusercontent.com/63685177/83102478-e8200400-a0f7-11ea-942b-c8858d09aadd.png)

**Comment by arcturus2** [comment]
I'm sure what you come up with is better than my original freeze graph implemenation @Guilty-Spark-343 so happy to try it out.

> Are we happy to use a lock icon to symbolize pinning/locking and does it fit in with the other icons?

With the icon I always had something like https://pixabay.com/vectors/drawing-pin-pushpin-push-pin-pin-151658/ in mind but that doesn't work with the flat theme we have going to the padlock is cool and fits in with the existing icons.

>Is there any preference to where the lock on the node sits?

Would it be possible to have them stay where they are?

**Comment by serpens24** [comment]
The main thing to do here in terms of the actual mechanics of locking these nodes is as follows:
1. Provide an attribute for vertexes indicating whether a vertex is locked. ( position_locked )
2. In AbstractInclusionGraph, add code such that when nodes to move are determined (in several loops) a check of this noew attribute is made, and nodes maked as locked are ignored.
3. Provide new actions/toolbar links which can trigger the lock/unlock of selected vertexes.

NOTE: This solution does not currently overlay an additional decoration to locked nodes. As it sits, a tick or cross can be turned on linked to the attribute, however, IF this is required, we would need to convert the position_locked  from a boolean to an enum or similar to ensure a unique data type for decoration calculation ..... OR, modify the calculation of decorations to allow specification of boolean true/false icons.

**Comment by GammaVel** [comment]
@serpens24 to review and address a couple of minor issues after review

**Comment by antares1470** [comment]
I've done some further testing with this and note that the pinned attribute is only set as a decorator in new graphs. For old graphs, this doesn't get added as a decorator by default and so you don't get the visual indicator that a node is pinned without manually editing the decorators. Perhaps we could add a schema updater to fix this?

**Comment by GammaVel** [comment]
Freeze graph icon also needs to be removed from the toolbar and the Display menu.
