### ISSUE TITLE
Allow import of delimited files that don't contain column headings

### ISSUE THREAD

**Issue by serpens24** [constellation-app/constellation#573]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

Consider the following csv data:
![image](https://user-images.githubusercontent.com/58677108/84330244-0a208880-abc6-11ea-8bff-3519113a9f5d.png)
Its clear the first row represents headings, while subsequent rows represent data. When parsed via the importer the follwoing is seen:
![image](https://user-images.githubusercontent.com/58677108/84330386-684d6b80-abc6-11ea-8a49-6662d75f3a67.png)

Consider now the same csv but without the header row:
![image](https://user-images.githubusercontent.com/58677108/84330435-8a46ee00-abc6-11ea-926a-73d6349e8fef.png)

Attempts to import this takes the first row and uses it as headings:
![image](https://user-images.githubusercontent.com/58677108/84330473-a2b70880-abc6-11ea-8e9e-56d431464951.png)

It would be useful to be able to flick a switch to indicate there is no header row. This could sit alongside the "Initialize With Schema" checkbox.

### Steps to Reproduce

1. Import CSV file that doesn't contain headers, ie:
![image](https://user-images.githubusercontent.com/58677108/84330435-8a46ee00-abc6-11ea-926a-73d6349e8fef.png)
2. Confirm the first row of real data is treated as headers

**Expected behaviour:** 
User has ability to indicate there is no header row, in which case, column headers are constructed, ie:
![image](https://user-images.githubusercontent.com/58677108/84330671-2cff6c80-abc7-11ea-9821-5a53c649f510.png)

**Actual behaviour:** 
First row of data is treated as column headers, ie:
![image](https://user-images.githubusercontent.com/58677108/84330473-a2b70880-abc6-11ea-8e9e-56d431464951.png)

**Reproduces how often:**
100%

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by GammaVel** [comment]
Thanks for making all the improvements here :-)
