### ISSUE TITLE
Import invalid XML file (applies to all delimited import parsers)

### ISSUE THREAD

**Issue by serpens24** [constellation-app/constellation#574]
### Description

Created a text file containing the following:
```
This is bad data
This is bad data
This is bad data
This is bad data
```
Try to import it using the XML importer - exceptions occur, then the importer reports successful import with a heap of exceptions.

### Steps to Reproduce

1. Create a file containing the above lines and save as baddata.xml
2. Select File->Import->From Delimited File...
3. Set Import file Parser to XML, then press the "+" button and locate the file, and press Open.
4. Acknowledge warning dialog twice (this is an issue - see below)
5. On the main import dialog press the Import button. (this is enabled despite no data being valid in file)
**Expected behaviour:** [What you expect to happen]

**Actual behaviour:** 
At step 3, the following dialog is shown (twice)
![image](https://user-images.githubusercontent.com/58677108/84336132-c3d32580-abd5-11ea-96b9-a2255e999078.png)
After acknowledging twice, user is returned to main Import dialog, with the Import button enabled .... 

At step 5, despite data being invalid - so nothing to import, a dialog is raised suggesting "X" lines of data were imported along with multiple Exception dialogs. See below:
![image](https://user-images.githubusercontent.com/58677108/84336391-4d82f300-abd6-11ea-9d3d-7ff164b1f744.png)

**Reproduces how often:** 100%

### Additional Information

One of the issues here is the code generating the "Success dialog" is independant of the actual import and just counting lines of text in the file.

So there are really 4 problems:
1. Invalid XML files don't get neatly handled up front ... a single warning should be displayed.
2. The import button is enabled (I can live with that if it doesn't die ugly) - but when clicked tries to import invalid data.
3. Press the import button and excpetions are thrown (ugly) 
4. The number of "rows" imported is in no way correlated to rows of records .... in fact, this occurs even if the import XML is successful as the counter is assuming one record per line is is the case for CSV files. Surely we can get the number of records from the importer record list instead ?

This problem really needs to be checked for all importers in case there is similar.

Note: I fond the warning dialogs seem to pop up behind the import dialog generally so are hard to see... which means context is taken away from the user and the tool becomes un-useable until usr clicks back on the main window ... at which point the warning dialogs appear.

Note 2: The "Success" dialog is displayed before the data is imported.... surely you can only show success after the import is completed.

**Comment by serpens24** [comment]
Lines 134 and 169 of CoreImportExportPlugins\src\au\gov\asd\tac\constellation\plugins\importexport\delimited\SourcePane.java

Are the two locations that result in a call to ImportFileParser.preview ... this code may need to be refactored to clean this duplciate call up ... OR apply a flag to determine if the warnng dialog should be displayed in one of these cases.

**Comment by serpens24** [comment]
I believe some refactoring related to the import dialog needs to be done to do 2 things:
1) Dont provide the Import button unless it is known that there is data to import
2) Refactor the dialog indicating how many rows were imported to use the actual values - rather than the number of lines in the source file ... this is being created in CoreImportExportPlugins\src\au\gov\asd\tac\constellation\plugins\importexport\delimited\ActionPane.java line 92:

`                    displayAlert("Success", "Successfully imported " + noOfRows
                            + " rows from the following file(s):\n" + String.join("\n", filenames), true);`

**Comment by serpens24** [comment]
My current thoughts are the import mechanism is two step. Step one selects the file to import and loads a preview. The Import button shouldn't be enabled if the preview failed .. as user wont have allocated columns... but should a failed parse/preview prevent the file from even being added ? Theres probably an argument to say yes. Ie, if the file is invalid, it probably shopuldnt be shown in "Files" list.

**Comment by Auriga2** [comment]
Hi @arcturus2  Moving this to "In progress" as we are still working on this case.

**Comment by serpens24** [comment]
Needed to find a warning icon, found the following free set in 48x48: http://www.softicons.com/toolbar-icons/status-icons-set-by-iconleak/yes-icon
![success](https://user-images.githubusercontent.com/58677108/86865055-6b784080-c10d-11ea-8e1e-ba5ea553d78d.png)
![warning](https://user-images.githubusercontent.com/58677108/86865091-7c28b680-c10d-11ea-843d-8ec9d7122826.png)


I note the existing code has a locally stored success icon. (success.jpg) this doesn't lend itself well to maintaining a common set of icons for use in the tool. @arcturus2 - any tho8ughts on whehter we should maintain a common icon set somewhere ... or if one exists ?

**Comment by arcturus2** [comment]
> Actually - I've noticed that by using Alert and Alert.AlertType a set of precanned built in icons for info, confirmation, warning and error are available. I can refactor the improt delimited dialogs to use these.

Yep I agree, just use them. Thanks @serpens24
