### ISSUE TITLE
Run_plugin endpoint in the Rest API should return a valid error when an incorrect graph_id is supplied

### ISSUE THREAD

**Issue by Auriga2** [constellation-app/constellation#577]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
If you specify an invalid value for `graph_id - The id of a graph to run the plugin on (optional)`
it doesn't run the plugin, but returns 200, as if it was successful. Instead it should return error 422.
(The valid graph_id could be retrieved from the `get_graph` endpoint.)

![image](https://user-images.githubusercontent.com/64826928/84459666-2ba57100-aca7-11ea-9d22-c840c69e0063.png)

### Steps to Reproduce

1. Load the Rest API (Tools-Start REST Server)
2. Try out POST - `run_plugin` with an invalid text for `graph_id`

**Expected behaviour:** Return error 422.

**Actual behaviour:** Returns 200, as if it was successful.

**Reproduces how often:** 100%

**Comment by Auriga2** [comment]
Current code doesn't support custom responses. In a similar scenario,  in SetGraph.java, it throws `RestServiceException` with 500 code.

**Comment by arcturus2** [comment]
Thanks for the investigation @Auriga2. Based on this we would need an elegant solution to refactor the code to be able to support custom HTTP error codes. It looks like you have assigned yourself to this one which is cool. If you want to have a discussion around implementations feel free to do a mini write up here or if its easier to just send a PR that is fine too.

In case if @algol60 is interested whom recently refactored the Rest API code then feel free to make suggestions if you had already thought about this but decided it was not necessary at the time to implement customised HTTP exit codes.

**Comment by Auriga2** [comment]
I managed to get it to work by passing the `HttpServletResponse response` object to the services classes. But tricky to refactor the FileListener.java class.

![image](https://user-images.githubusercontent.com/64826928/84625506-8dbdda80-af22-11ea-8322-f671bab7eed7.png)

**Comment by arcturus2** [comment]
>But tricky to refactor the FileListener.java class.

@Auriga2 What part is tricky, maybe we can help. I think testing this would also be problematic?

**Comment by arcturus2** [comment]
No worries thank you @Auriga2. `FileListener` is involved to get working and OK to skip at this point.
