### ISSUE TITLE
Delimited File Import: Preview table issues

### ISSUE THREAD

**Issue by serpens24** [constellation-app/constellation#580]
### Description

When importing a small set of data the preview window shows duplicate entires

### Steps to Reproduce

1. Create a file containing the follwoing, and call it tst.csv
`
a,b,c,d
1,2,3,4
5,6,7,8`
2. Select 'Import' -> 'From Delimited File' and ensure CSV is selected.
3. Press the + button, locate the file and click 'Open'
4. Duplicate entries are seen:
![image](https://user-images.githubusercontent.com/58677108/84725990-02e4ea80-afcb-11ea-8593-e7dbc9d6fba4.png)

**Expected behaviour:** 
no duplicate entries

**Actual behaviour:**
As per image above, duplicates of early rows are seen in reverse order from the bottom of the table. i've seen this sort of thing before in tableview, so suspect theres something systematic.

**Reproduces how often:**
100% I think

**Comment by Auriga2** [comment]
@serpens24 I cannot recreate this. Tried debugging the latest in master and the released v2.0.0-beta5 exe.
![image](https://user-images.githubusercontent.com/64826928/85099724-52325180-b23d-11ea-879c-8a9e3a722ea7.png)

**Comment by Auriga2** [comment]
serpens24 means to use the 'Enter' instead of the 'spaces' in the csv file. 
But still cannot recreate if you just try the `+ button` once. You need to add one more file, or Use `- button` and add it again, to recreate the issue.
When there are multiple files added, the mirror image even appear/disappear randomly when clicking between the files.

**Comment by GCHQDeveloper601** [comment]
I had a play around with this issue today. Not sure of the root cause of it but calling refresh on the panel after setting the data seems to resolve the issue. I'll create a PR for it now.
