### ISSUE TITLE
Schema View filter text invisible when out of focus

### ISSUE THREAD

**Issue by Auriga2** [constellation-app/constellation#585]
When you go out of focus from the input text field in the filter, what you typed is not shown until you give focus back to the input text field. Same behaviour on the filters on Attributes, Node Types and Transaction Types tabs.

![testing schema view search](https://user-images.githubusercontent.com/39325530/84681771-fbe0bc80-af77-11ea-93e0-7bf3a9290f95.gif)

arcturus2: My guess is the bug is with the style sheet (css) file which is a pain to debug ...

**Comment by aldebaran30701** [comment]
I can't recreate this in the current master running on debug mode locally. 
I can however recreate it with V2 Beta 5 running from the .EXE
Something to look out for to see if it works in the next release or even try to build a .EXE locally using current master to test.

**Comment by Auriga2** [comment]
I could recreate in debug mode when I created the issue, but it worked abruptly then. Maybe it's fixed by a commit since?

**Comment by formalhaut69** [comment]
@arcturus2. The fix I made in the pull request https://github.com/constellation-app/constellation/pull/627 appears to only work on my machine. Strange issue. 
![schemaViewFix](https://user-images.githubusercontent.com/58677762/86673947-503b0180-c037-11ea-8904-3dbcf06f383d.gif)

**Comment by Auriga2** [comment]
This is really a  weird issue,  because after a while the bug disappears (it stops turning black) when debugging. I had to clean and build again to recreate the issue. Otherwise it'll pretend it's fixed, until you rebuild. Also the issue happens only when you click on the graph area and `treeView` section, or another view. It doesn't happen if you click on other areas and even the `detailsView` section in Node Types and Transaction Types tabs.
Using Bootstrap doesn't apply the css changes.

**Comment by arcturus2** [comment]
> Using Bootstrap doesn't apply the css changes.

Using the bootstrap saves time running Constellation. You still need to compile the changes but you should be able to set the main project to the bootsrap (Run -> Set as main project) and be able to use F6 to launch it for testing. Let me know if that is not the case.

**Comment by Auriga2** [comment]
Ah yes that part works although I cannot use F6 other times when I need to "Apply code changes". (Not really needed here.) May be there's another short cut key for that?

**Comment by Auriga2** [comment]
I did a workaround until someone figures this out, by making the filter text black and filter background grey, so that when the text is changed to black (in the mysterious place), it' not visible to the user. 
![image](https://user-images.githubusercontent.com/64826928/91941331-374d8480-ed38-11ea-8b5b-f64218f7f356.png)

Tried below to no avail:
 in the css :
.text-field{
    -fx-text-inner-color: yellow; //white
}
.text-field:focused {
    -fx-text-inner-color: red; //white
}

.text-field{
    -fx-text-fill: yellow; //white
}
.text-field:focused {  
    -fx-text-fill: red; //white
}
Also tried     
    -jfx-focus-color: white;
    -jfx-unfocus-color: white;

**Comment by antares1470** [comment]
Taking a stab at what might be happening here, it could be that there are two competing css rules (either in the same or different files) changing the colour of the text and by default, it is going with the rule changing the text to black. If that is the case, it could be worth checking for any rules in the css that change the text to black and seeing what difference it makes if you alter the colour that is set there

**Comment by Auriga2** [comment]
Agree, but I couldn't find any such line. Tried changing blacks to
different colors in modena.css and changing .text-field colours in
caspian.css. Is there an easier way to see which style sheets are applied?

**Comment by arcturus2** [comment]
> Is there an easier way to see which style sheets are applied?

I think so @Auriga2 and would you be able to try `getStyle()` or `getStyleClass()` and see if you have any luck?
