### ISSUE TITLE
Exception when using infomap

### ISSUE THREAD

**Issue by formalhaut69** [constellation-app/constellation#588]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
Clicking on the info map menu selection within the cluster menu will throw an IndexOutOfBounds Exception if the graph is empty.

### Steps to Reproduce

1. Click on infomap with an empty graph
2. [Second Step]
3. [and so on...]

**Expected behaviour:** No exception is thrown

**Actual behaviour:** Exception is thrown

**Reproduces how often:** 100%

### Additional Information

Also occurs when the user selects the infomap... option and clicks OK on an empty graph.

![image](https://user-images.githubusercontent.com/58677762/84966890-ce4f6b00-b151-11ea-8cd7-87260177f5fb.png)

**Comment by Auriga2** [comment]
I tried with the executable and it pops up this error message nicely. But when debugging I get them as exceptions, same behaviour illustrated above. Feels like the message should be meaningful to the user anyway.
![image](https://user-images.githubusercontent.com/64826928/85093971-be588980-b22c-11ea-8593-7acc635133c7.png)
