### ISSUE TITLE
Layers causing DualGraph Attributes to become out of sync

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#589]
The issue at hand seems to be the Dual Graphs becoming out of sync. So one StoreGraph within the DualGraph contains a float value for the layers visibility attribute as 1.0, while the other has 0.0. This behaviour is also seen with layerMask attributes for holding the bitmask of each vertex. 

The graphs will switch between themselves on any attribute value change so that obviously causes issues with consistency.

![layers](https://user-images.githubusercontent.com/58677759/84987496-66177e00-b17f-11ea-8c50-315a90cde4de.gif)

To get to this state, I added 3 elements, added query "color == #ffffff" <#ffffff should be replaced with a correct node colour>
I then selected that layer, then changed that HEX value to one of the other elements. I then could get the element to appear on and off of the graph depending on graph changes such as camera movements. I deleted the other elements for simplicity.

Layers view may be accessing or modifying the attribute values incorrectly or somehow at an incorrect time where both graphs are not sharing the change. I am currently trying to build a unit test to properly reproduce this issue more efficiently to debug and future proof.

**Comment by arcturus2** [comment]
Thank you @aldebaran30701 for the write up. I will have a go at this too and see if I can help.

**Comment by arcturus2** [comment]
>The graphs will switch between themselves on any attribute value change so that obviously causes issues with consistency.

The 2 `StoreGraph`s change roles when the write lock is released. The graph that was written to last will be the graph that is given to the next plugin that asks for a read or write lock. Meanwhile in the background it will apply all of the changes to sync up the outdated graph...and it repeats like this alternating with one another.

Given there are 2 graphs you are correct that they will be out of sync but they are supposed to sync up before it is ready to take new read or write operations.

**Comment by aldebaran30701** [comment]
I switched out these sections of code with ```StoreGraph.setFloatValue(...)``` https://github.com/constellation-app/constellation/blob/master/CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/StoreGraph.java#L2158-L2161

This caused the bug to reproduce earlier and more often. 
![singlenode](https://user-images.githubusercontent.com/58677759/85090563-95cc9180-b224-11ea-9929-308f2012fc6c.gif)

I built a test case which follows a series of steps that will replicate the issue when manually entered from the application, but the problem does not exist during running of the test case. The test does not run multi-threaded so that may hint to what the issue is.

**Comment by aldebaran30701** [comment]
I've been tracking the inconsistency down by stepping through the debugger, but have found using trace statements capture the state of both graphs better. I can see changes to each `storegraph` in the `.commit(...)` method and also track the execution of plugins when they run. 

I am yet to find the exact moment that both instances of the graph become out of sync. I am hoping to find something illegally modifying one of the graphs that somehow avoids having the second graph instance updated to match the original graph instance.

**Comment by aldebaran30701** [comment]
So when a checkbox on the LV is set, I first run a plugin to grab the entries from the UI and write them ([layerQueries](https://github.com/constellation-app/constellation/blob/master/CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/StoreGraph.java#L180-L208)) onto the graph object. I have added a future on this so that when the next plugin runs ([updateGraphBitmask](https://github.com/constellation-app/constellation/blob/master/CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/utilities/UpdateGraphBitmaskPlugin.java)) it sees the updated queries and not the ones that have not been saved (race condition) yet.

At [this ](https://github.com/constellation-app/constellation/blob/master/CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/LayersViewController.java#L99) line I add a future, which is used to ensure that the layer queries are set before updating the graph bitmask because it is called in the order 
```submit()```
```execute()```
[This ](https://github.com/constellation-app/constellation/blob/master/CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/LayersViewPane.java#L117-L119)is where it is called in that order

Hi @arcturus2 @cygnus-x-1 @algol60 
My question is, When I set the layer queries within `StoreGraph.java` [here](https://github.com/constellation-app/constellation/blob/master/CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/StoreGraph.java#L180-L208), how do I ensure that the `DualGraph` saves that edit to the other instance of the graph? Currently one graph within the dualgraph is correct and the other does not get updated at the exit of the plugin execution.
