### ISSUE TITLE
Exception when using compare graphs

### ISSUE THREAD

**Issue by formalhaut69** [constellation-app/constellation#590]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Using compare graphs without selecting a second graph

### Steps to Reproduce

1. Run the compare graphs plugin without selecting a second graph
2. [Second Step]
3. [and so on...]

**Expected behaviour:** Perhaps a single error window with a message would look cleaner

**Actual behaviour:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

![image](https://user-images.githubusercontent.com/58677762/85089272-5ea8b100-b221-11ea-9996-1d712b54c4b5.png)

**Comment by arcturus2** [comment]
@serpens24 worked on a fix to get one error message to appear and we probably need to implement that solution for this case too. I dont have the PR numbet handy.

**Comment by Auriga2** [comment]
I tried with the executable (few weeks older) and it pops up this error message nicely. But when debugging I get them as exceptions, same behaviour illustrated above.
![image](https://user-images.githubusercontent.com/64826928/85094494-0fb54880-b22e-11ea-8498-5a1ca3ca9cef.png)

**Comment by aldebaran30701** [comment]
@arcturus2 Seeing as this issue only relates to users running it from Netbeans and not the .exe version, should this still be rectified?
The code only contains one line which triggers the error to appear. 
```        
if (originalGraphName == null || compareGraphName == null) {
            throw new PluginException(PluginNotificationLevel.ERROR, "You must choose two graphs to compare");
}
```
The fix @serpens24 implemented was to remove an extra level of error handling which is seen here: https://github.com/constellation-app/constellation/pull/440/files
It would not work in this situation.

**Comment by arcturus2** [comment]
Going to close this @formalhaut69 as the issue seems to only be happening when run locally from NetBeans. Cool?

Thanks for responding @Auriga2 and @aldebaran30701.

**Comment by formalhaut69** [comment]
> Going to close this @formalhaut69 as the issue seems to only be happening when run locally from NetBeans. Cool?

@arcturus2 no worries.
