### ISSUE TITLE
The resulting .exe from build .zip fails to run properly

### ISSUE THREAD

**Issue by formalhaut69** [constellation-app/constellation#592]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The .exe that is produced by the build-zip in Netbeans fails to run properly and is missing all of constellation's functionality.

### Steps to Reproduce

1. Build the .zip in netbeans
2. extract and then run the .exe
3. Click yes on the resulting window

**Expected behaviour:** .exe runs constellation without issue

**Actual behaviour:** A window that is missing all of constellation's functionality loads

**Reproduces how often:** 100% of the time on my machine also occurred on @aldebaran30701's machine. 

### Additional Information

![image](https://user-images.githubusercontent.com/58677762/85097090-8b66c380-b235-11ea-981f-056c4d8b85a4.png)

The application window that runs;
![image](https://user-images.githubusercontent.com/58677762/85097152-c9fc7e00-b235-11ea-99ef-27f7dfec1e82.png)

**Comment by formalhaut69** [comment]
This may be related to issue https://github.com/constellation-app/constellation/issues/565

**Comment by arcturus2** [comment]
@formalhaut69 this is kind of expected. I actually moved the functionality to build a "zip with the JRE" into constellation-app/constellation-applications. I did this so there was only 1 `build.xml` file to keep updating. The `build-zip` works as before which is a Netbeans defined `ant` target which will built a zip of the code minus the JRE.

Clicking "yes" to try the default JRE would have used whatever you have defined in your system path which my not be Java 11. That might be why Constellation looks broken there. Please clarify.

**Comment by formalhaut69** [comment]
@arcturus2 we just checked and the default JRE in our machine's system path is Java 11. @aldebaran30701's theory is that it might be looking for a specific name; "jdkhome: jre" or at least part of it. We're not entirely sure though. What is the name of your path?

**Comment by arcturus2** [comment]
@formalhaut69 well the path would be set in `etc\constellation.conf` so that might be what's going on.
