### ISSUE TITLE
Odd behaviour and exceptions when running merge nodes 

### ISSUE THREAD

**Issue by formalhaut69** [constellation-app/constellation#593]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Running merge nodes and then undoing the merge nodes issue caused the current graph to freeze and then threw a exception. Constellation has also thrown an array out of bounds exception instead. 

### Steps to Reproduce

1. Ran the sphere graph builder
2. Ran the merge nodes plugin
3. Pressed undo

**Expected behaviour:** Undo, reverses the merge nodes plugin's resulting action.

**Actual behaviour:** On occasion, constellation will throw an exception and the graph will freeze

**Reproduces how often:** Less than 50%?

### Additional Information

![image](https://user-images.githubusercontent.com/58677762/85097975-5c058600-b238-11ea-89e4-0b2a1acc4509.png)

**Comment by arcturus2** [comment]
@formalhaut69 I haven't been able to reproduce this. If you haven't seen this for a while are you OK if we close this one?
