### ISSUE TITLE
Delimited File Import: Issues in the preview with multiple file types

### ISSUE THREAD

**Issue by Auriga2** [constellation-app/constellation#600]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The Delimited File Import is not intended to work across file types.
So we can disable selecting of different file types to import, or change the file type automatically when clicking between the files at least.

### Steps to Reproduce

1. For instance, select a CSV file and an Excel file at the same time.
2. click on the Excel file. It throws the error below because the CSV was the default type selected. (If you manually select the correct `Import File Parser`, it seem to work)
![image](https://user-images.githubusercontent.com/64826928/85358356-a47fb500-b552-11ea-8dba-68809686ee71.png)

**Expected behaviour:** When switching between files, no error message is thrown and preview is rendered.

**Actual behaviour:** When switching between files an error message is thrown and the preview is not rendered.

**Reproduces how often:** 100%

**Comment by Auriga2** [comment]
Hi @cygnus-x-1, Can you please check the below options? We prefer 1 because you said "The Delimited File Import is not intended to work across file types." But if it needs to support multiple types for any reason, we can implement Option 2. What do you think?
Option 1:
Restrict the file type in the file selection pop up to only contain the selected `Import File Parser` type, and once a file is added, that drop down will be locked, to avoid adding other types later.
![Allow Single File Type](https://user-images.githubusercontent.com/64826928/85482875-eb2ce800-b602-11ea-83cf-0839aff4da97.gif)

Option 2:
Change the file type automatically in the `Import File Parser`, when clicking between the files.

**Comment by arcturus2** [comment]
Just chiming in here too @Auriga2. I like option 1 too. If you remove all files then does the file type become enabled again?

**Comment by Auriga2** [comment]
@arcturus2 Yes. File type is enabled again. I'll push a PR for this.
