### ISSUE TITLE
Timeline Filtering Functions, Labelling, and Selection Expansion, Timeline Scaling behaviour

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#61]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

**Filtering functions**

The timeline needs to the ability to, in addition to "show selected only", allow users to filter on a selection. Currently, selecting a timerange within the timeline viewer will reset you graph selection, making it difficult to analyse discrete parts of your graph .

**Labelling**

Labels are overlapping on events corresponding to the same entities (see screen shot 1-A), making them un-interpretable. One label would suffice on a given Y-Axis line. It would also be nice to have labels appear on grouped events (1-B).

**Transaction Selection Expansion**

Having the ability to expand your selection, either in the timeline or on the graph, on a entity A<->B pairing would be really helpful. For example, if I select transactions in September, it would be nice to have a simple way to select all other, historical/older, transactions between those entities that were active.

**Timeline Scaling Behaviour**

When scrolling horizontally the Y-Axis changes dynamically to fit content, it would be nice to have this static to more easily identify trends across multiple time periods.

**Comment by aldebaran30701** [comment]
This could be done at the same time as a rewrite. #63

**Comment by sol695510** [comment]
Has been consolidated into work for ticket #63
