### ISSUE TITLE
Large data sets causing application (v2beta5) to hang when following Tutorial 6 Map view and Location Kaggle dataset

### ISSUE THREAD

**Issue by forestfairy** [constellation-app/constellation#611]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Uploading the large data set  as .csv causes application (v2beta5) to hang in the Import from Delimited File window 
### Steps to Reproduce

1. Go to Kaggle as per the tutorial "Map View and Locations"
2. Download Uber Car data set as instructed
3. Open Constellation from constellation64.bat
4. File>Import>From Delimited File.... go to location of Uber dataset and click on "import"
5. ...

**Expected behaviour:** 
Application to scan first hundred rows of data and display them in preview window to allow allocation of attributes

**Actual behaviour:** 
Application hangs

**Reproduces how often:** 
For this file) 100%
For other files of this size downloaded from Kaggle 0%
For other files of this size 

### Additional Information

This issues only seems to occur when using the dataset from downloaded for Tutorial 6 from Kaggle, using alternate datasets doesn't appear reproduce this error. This is a minor issue with limited consequence impacting users working through tutorials.

**Comment by arcturus2** [comment]
@forestfairy just letting you know I got the preview to work in a flash - I will let you know when it makes it into the next released version.
