### ISSUE TITLE
Uploading and joining inconsistently formatted datasets causes attribute error v2beta5 win

### ISSUE THREAD

**Issue by forestfairy** [constellation-app/constellation#612]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Uploading and joining inconsistently formatted .csv datasets, such as joining geo locations to times and networking causes error with attribute allocation.

### Steps to Reproduce

1. With Constellation v2beta5 open, go to a dataset with identifiers, physical attributes and activities
2. Set up attributes as described in tutorials
3. Import
4. Go to a second dataset, such as one with identifier attributes and locations,
5. Set up attributes
6. Import

**Expected behaviour:** 
Expected to have attributes locked in position in each of the datasets (even though the set up of the columns in the datasets are a different order) and the application to map to the attributes as they were set

**Actual behaviour:** 
Application switches the attributes so that they are the same order over the two datasets. While this causes errors in the analysis that are immediately evident in the tutorial exercise, however this could cause issues if undetected in other analysis. 

**Reproduces how often:** 
100% in the tutorial datasets

### Additional Information

Likelihood = low in experienced users, high in inexperienced or external users
Consequence = low (in tutorial analysis) to very high if undetected in other datasets

**Comment by antares1470** [comment]
@arcturus2 believes we have fixed this issue. Closing
