### ISSUE TITLE
Review how state changes are written to the graph

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#614]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Almost all views write their state to the graph (i.e taking a write lock) when you change something on the view or more worrying is when you change graph tabs, all views write their state changes to the graph. If you have a lot of views open then that is a lot of write locks chaining one after another.

The Find View (one of the oldest views) seems to want to write its state twice so all of this builds up and creates performance issues.

Perhaps writing the views state should be handled by the Views Framework which could help standardise and perhaps optimise how the views write their state.

**Comment by aldebaran30701** [comment]
#506 is similar and can be either merged or closed with the introduction of this ticket.

**Comment by arcturus2** [comment]
Smart minds think alike 😉
