### ISSUE TITLE
Turning off Interactive in K-Truss Clustering does not properly restore colours

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#62]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

Turning off Interactive in K-Truss Clustering does not properly restore colours.

### Steps to Reproduce

1. Open the K-Truss view from Tools -> Cluster -> K-Truss
2. Click Cluster
3. Click Interactive
4. Click Interactive again to turn it off

**Expected behaviour:** The colours on the graph restore to before running K-Truss

**Actual behaviour:** The colours on the graph are not restored

**Reproduces how often:** 80%

**Comment by serpens24** [comment]
I can't get this to happen exactly as described as yet, but I can get close.... I'm using the following CSV data:
----------------------------------------------------
src,dest,Timestamp
A,D,20190101111111
A,B,20190101111111
D,B,20190101111111
D,C,20190101111111
C,B,20190101111111
A,C,20190101111111
A,E,20190101111111
E,D,20190101111111
B,F,20190101111111
A,F,20190101111111
G,F,20190101111111
H,A,20190101111111
----------------------------------------------------

I mapped src to source, dst to destination, and Timestamp to DateTime for Transaction attributes.
After imported, I set the colour of all nodes to blue and saved the graph.

I then selected Tools->cluster->K-Truss and selected Cluster - I found that **Interactive** was already selected hence clicking it the first time turned it off, and clicking it the second time turned it back on - which would explain the observations, however, I turned interactive back on, selected **dimmed** and **Colour Nested K-Trusses** - I then killed the K-Truss window entirely ...... what I found was that the K-Truss colorings and dimming were sitll in action.

@arcturus2 - is this the behaviour you are after here ?


What I found interesting was that after following the steps listed in the description, if I then closed the K-Truss window and re-opened it, then started toggling the Interactive button I get striange behaviour in line with what was mentioned .... its much more apparent if you first enabled 'Colour Nested K-Trusses' then the issues become much more apparent.

**Comment by arcturus2** [comment]
Thanks @serpens24.

>...what I found was that the K-Truss colorings and dimming were sitll in action. @arcturus2 - is this the behaviour you are after here?

Closing the K-Truss window should restore the graph to how it was before.

> Note 2: this issue looks pretty similar to #64 - perhaps we should consider together

Happy to do that.

**Comment by serpens24** [comment]
OK, so having played with the tool a little, the following was discovered.

Firstly, the issue as documented in the description didn't seem to reproduce exactly as documented, I performed some investigation to determine how to trigger the condition, also, as pewr above comments, I confirmed that closing the K-truss panel should turn off the interactive display.
Below are two scenarios that trigger issues:


**Option 1:  Use Colour Nested K-Trusses**
1. Open a graph with suitable clustering data for display.
2. Select Tools->Cluster->K-Truss.
3. Press the Cluster button. (Interactive is on by default)
4. Check Colour Nested K-Trusses.
5. Turn off interactive by pressing the Interactive button.

**Expected**
Colours on graph reverted to state from before K-Truss was used.

** Actual**
Colours on graph remain in line with active coloured K-Truss.


**Option 2:  Close K-Truss component while active**
1. Open a graph with suitable clustering data for display.
2. Select Tools->Cluster->K-Truss.
3. Press the Cluster button. (Interactive is on by default)
5. Close the K-Truss component (hitting X in tab header).

**Expected**
Colours on graph reverted to state from before K-Truss was used.

** Actual**
Colours on graph remain in line with active K-Truss.

The solution is as follows:
