### ISSUE TITLE
Schema View Display Duplication

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#631]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
The schema view seems to load incorrectly and duplicate it's columns. - even just opening it on no graph
I also noticed a tonne of JFX errors when following the reproducer. 

### Steps to Reproduce

1. fresh constellation open
2. new graph
3. while new graph is still loading, click schema view to open it.

**Expected behaviour:** loads normally
**Actual behaviour:** duplicates columns and also causes some JFX exceptions.

**Reproduces how often:** 100% on my machine, 0% on another machine

### Additional Information
Below is only opening the Schema View
![schemaview](https://user-images.githubusercontent.com/58677759/86678485-c5a8d100-c03b-11ea-8558-1c4abce4d35e.gif)

**Comment by formalhaut69** [comment]
Was able to reproduce this. The issue caused an infinite number of NPEs to appear making constellation unusable. 
![image](https://user-images.githubusercontent.com/58677762/86680659-f2f67e80-c03d-11ea-865a-9a585d8c07e6.png)

**Comment by arcturus2** [comment]
@aldebaran30701 @formalhaut69  I'll take a look now. Thanks for finding this!

**Comment by arcturus2** [comment]
I'm seeing 2 sets of tabs and its because the execution goes like this:

```
INFO [au.gov.asd.tac.constellation.views.schemaview.SchemaViewTopComponent]: createContent
INFO [au.gov.asd.tac.constellation.views.schemaview.SchemaViewTopComponent]: componentShowing: clear and populate
INFO [au.gov.asd.tac.constellation.views.schemaview.SchemaViewTopComponent]: handleComponentOpened: populate
```

Will see what the root cause is and fix it.

**Comment by aldebaran30701** [comment]
> Will see what the root cause is and fix it.

This looks like it could be as a result of the View listening framework changes I introduced. I'm thinking I've used a section of code which updates not only the state but also the UI. This would be getting triggered on component opened, and maybe component shown - Just speculating at this stage though.

**Comment by arcturus2** [comment]
It's all good @aldebaran30701. It turns out to be my modifications to the `componentShowing()` I added and was to do with me not understanding how the view was built to work. I've gotten most of it working now and just testing.
