### ISSUE TITLE
Turning off Interactive in Hierarcical Clustering does not properly restore dimming

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#64]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

Turning off Interactive in Hierarcical Clustering does not properly restore dimming

### Steps to Reproduce

1. Click Tools -> Clusters -> Hierarchical
2. Click on Cluster
3. Click on Interactive
4. Click on Interactive to turn it off

**Expected behaviour:** Nodes are restored to their original dim/undimmed state

**Actual behaviour:** Nodes dimmed during the interactive analysis remain dimmed

**Reproduces how often:** 80%

**Comment by aldebaran30701** [comment]
I would just like to clarify my thinking; 
Creating a new graph, and loading nodes + transactions from Sphere graph builder
Opening Tools -> cluster -> Hierarchical Clusters
Running Cluster on the full graph.

From the scenario, if we close the graph which has been edited by the clustering tool, should it keep it's current displayed state (rearranged nodes, removed or hidden transactions). Or, should it revert them. 
From the Clustered graph created after clustering, should the state and appearance of the graph be the same after a cycle of Interactivity? ie. interactivity does not mutate the graph.

My intention was to add code to the switching of interactivity to ensure dimming was restored to previous state. 
https://github.com/constellation-app/constellation/blob/c968184e866a76049d50df69b27b6304f7b739b5/CoreAlgorithms/src/au/gov/asd/tac/constellation/algorithms/clustering/hierarchical/HierarchicalControllerTopComponent.java#L447-L465

**Comment by aldebaran30701** [comment]
Stepping through the code in both the KTruss and Hierarchical classes seem to show similar workings. KTruss has issues disabling colours, wheras Hierarchical has issues disabling dimming.
At first this sounded like a case of stepping through both classes to notice a difference in the update or switching of states. But, both classes, although providing different functionality, seem to be sound. This leads me to believe that the issue may be deeper rooted. 

Eg. a call to run the plugin Undim All, still leaves the transactions dimmed in appearance and in attribute state.
Will update as I progress.

**Comment by arcturus2** [comment]
>From the scenario, if we close the graph which has been edited by the clustering tool, should it keep it's current displayed state (rearranged nodes, removed or hidden transactions). Or, should it revert them.
From the Clustered graph created after clustering, should the state and appearance of the graph be the same after a cycle of Interactivity? ie. interactivity does not mutate the graph.

As you mentioned @aldebaran30701, in interactive mode the state of the graph does not change. If however, you cluster the graph and hit save and close the graph then it should open back up just like it was when saved. I think this part works OK based on a quick test.

>Will update as I progress.

OK no worries thank you for this!
