### ISSUE TITLE
Opening a view with a few graphs open will cause lag and resizes

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#645]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

If you open a view when you have a few graphs opened (ie. 8 graphs) it will display an odd visual bug as well as a slight amount of lag. 
The more graphs opened, the worse the problem is.

![views](https://user-images.githubusercontent.com/58677759/86877049-2e1fad00-c125-11ea-9c14-c78a66ee4b46.gif)

Also occurred in previous beta releases

### Steps to Reproduce

1. open 8 new graphs
2. open histogram view - Any view will do
2a. visual bug occurs
3. close histogram view
3a. visual bug occurs

**Expected behaviour:** fast switching with no visual bug

**Actual behaviour:** visual bug and lag when opening

**Reproduces how often:** 100%

### Additional Information

The more graphs opened, the more it lags.

**Comment by formalhaut69** [comment]
@aldebaran30701 and I were discussing this and we believe that what's happening is each individual graph is being resized when a view is open, which would be why it lags more depending on how many graphs you have open. A potential solution could be to only resize the active graph and then resize the other graphs individually later on as necessary.

**Comment by Auriga2** [comment]
The flicker with a single graph is also noticeable and good if we can fix. 
(Slow motion:)
![slowed-flicker](https://user-images.githubusercontent.com/64826928/88005381-750b9a80-cb48-11ea-8d3f-cfdbb4219b31.gif)

**Comment by GammaVel** [comment]
Confirmed this is still happening with version 2.3.

**Comment by GammaVel** [comment]
This seems to have resolved itself now and is no longer happening with R2.10 (latest nightly build). I will close this issue off seeing it can't be replicated any more.
