### ISSUE TITLE
Analytic View to support clustering and content analytics

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#65]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

Constellation's goal is to make it easier to perform complex tasks in a simple and intuitive way. If the analytic view could support clustering and content analytics then this will be a great milestone. Currently, the clustering functionality exists but isn't part of the analytic view.

**Comment by GammaVel** [comment]
Moved to [Brainstorm Ideas](https://github.com/constellation-app/constellation/wiki/Brainstorm-Ideas) and closing this issue for now.
