### ISSUE TITLE
Word Cloud View

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#655]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Add support for generating and interacting with word clouds from a Constellation graph

### Additional Information
Most of the work has been done in a different java project and this task will involve porting it to Constellation.

**Comment by HolandCrick** [comment]
Thank you @Delphinus8821 for adding this new feature. It looks great. I did notice that, if running new feature "Word Cloud View" on a smaller screen such as laptop, the "Generate Button" is not displayed on the screen. It goes down and it is not visible. It would be ideal to have a scrollbar to navigate up/down. #1961
