### ISSUE TITLE
Add custom 'Example Value' in the Rest API 'Request body' 

### ISSUE THREAD

**Issue by Auriga2** [constellation-app/constellation#665]
### Description

The `Request body` sections in the REST API endpoints below can be improved with a custom `Example Value`

`plugins` parameter in `run_plugins` endpoint
`args` parameter in `run_plugin` endpoint
`data` parameter in `add_recordstore` endpoint

### Steps to Reproduce
1. Open Swagger (Run constellation and `Tools`->`Start Rest Server` then`then Display Rest Server Documentation`)
2. Check above endpoints 

**Expected behaviour:**
Custom `Example Value`s displayed in the Request Body

**Actual behaviour:** 
 `Example Value` is empty:
![image](https://user-images.githubusercontent.com/64826928/87123506-01ef6200-c2c6-11ea-9abd-ce49a2d4a5ec.png)

**Reproduces how often:** 100%

**Comment by serpens24** [comment]
Refer to https://swagger.io/specification/ for Swagger JSON spec.

**Comment by Auriga2** [comment]
Looks like we need to hard code them for the specified 3 end points, so if anyone knows good examples, I can add them, otherwise I am going to add the below random values. 

**/v2/service/get_recordstore**
```
{
  "columns": [   
    "source.Label",   
    "source.visibility",   
    "source.dim",    
    "source.Identifier", 
    "source.selected"   
  ],
  "data": [
    [      
      "New Node1",
      true,
      true,
      "New Node1",
      true

    ]
  ]
}
```
**/v2/service/run_plugin**
```
{
 "SelectTopNPlugin.mode": "Node",
    "SelectTopNPlugin.type_category": "Online Location",
    "SelectTopNPlugin.type": "\n\u2713 Online Location\n",
    "SelectTopNPlugin.limit": 2
}
```
So it doesn't really make sense until the users edit the relevant Plugin arguments, or the graph is changed as required. E.g. For the above parameter to work, you need to have a node selected already, and for it to select a node with `Online Location` Type, it has to be connected to the selected node. But I guess the users get the general formatting etc. and can continue with this.

**/v2/service/run_plugins**

**Comment by Auriga2** [comment]
I had to use `plugin_args` instead of  `args`, to get the `/v2/service/run_plugins` end point working, so fixed the typo there.

It'd be nice to have Example Value added in all the Responses as well, (if it's worth the effort because someone has to go through all the plugins and determine this), probably in a different ticket.
E.g.:
![image](https://user-images.githubusercontent.com/64826928/134460668-cb5a3f76-aa70-4026-945e-f90d03884ef7.png)

To look like below, as appropriately:
(Images copied from https://api.exceptionless.io/docs/index.html#!/Event/ApiV_versionEventsPost)
![image](https://user-images.githubusercontent.com/64826928/134461067-630cd294-e11f-4810-be39-b8695f392017.png)
or
![image](https://user-images.githubusercontent.com/64826928/134461260-7543b6d3-ca60-4df2-b00e-73837032875a.png)

Also it'd be nice to add an `Authorize` section (As in the above link) rather than adding the secret in all end points if the users are going to use it through swagger? (Or was it added this way to support the notebook?)
![image](https://user-images.githubusercontent.com/64826928/134610656-06a3d408-fe92-4623-9185-d55c8841e3eb.png)

**Comment by arcturus2** [comment]
Hi @Auriga2 I've been reading along though didn't respond yet.

OK with hard coding the values for the 3 endpoints. That will be of great help. OK with your examples.

>It'd be nice to have Example Value added in all the Responses as well, (if it's worth the effort because someone has to go through all the plugins and determine this), probably in a different ticket.

Yes this will definitely help and worth making a different ticket. Might as well link this ticket to it too.

Regarding the presentation of the responses in Swagger based on the images above I like the how they are formatted. The blue background is for GET's and green is for POST's so it depends based on the endpoint.

I think the authorize button is cool. If that can be put in once and then referenced in all the endpoints without having to put it in each time that would be great.

Please feel free to make another ticket with your ideas if you don't want to get them done in this one.

Anyway looking forward to reviewing the PR when you're ready.

**Comment by Auriga2** [comment]
Cannot reuse ` "$ref"` in the `example ` like below:
("$ref": "#/components/examples/runPluginExample/example/" or "$ref": "#/components/examples/runPluginExample/example/" )prints the same in the example.
```
 "runPluginsExample":
            {
                "type": "array", 
                "items": {
                    "$ref":"#/components/examples/runPluginsExampleObject"
                },  
                "example":[
                    {                      
                        "plugin_name": "DESELECTBLAZES"                  
                    },
                    {                      
                        "plugin_name": "ZZZ"                  
                    },
                    {
                        "plugin_name": "SELECTTOPN",
                            "plugin_args":{
                                "$ref": "#/components/examples/runPluginExample/example/"
                            }
                   }
                ]
            }   
```

**Comment by GammaVel** [comment]
Thanks @Auriga2 for adding in the sample text, it is a really great idea !  
Just wondering when I checked the text I noticed there was a little tick in the sample code for the plugins parameter in run_plugins endpoint and args parameter in run_plugin endpoint:
![image](https://user-images.githubusercontent.com/83679004/135571297-b046081c-f9f8-40f5-a1e8-74073ef3d371.png)

I don't think this should be there, what do you think?  I'll move this back to in progress so you see it there.

**Comment by Auriga2** [comment]
Added it as per `the multichoice parameters section` in https://github.com/constellation-app/constellation-scripts/blob/master/JupyterNotebooks/notebooks_and_constellation.ipynb and it works (Runs the plugin correctly)

Let me know if it works without that, and I can remove it.

**Comment by GammaVel** [comment]
That explains where the tick came from. I think it is best to keep it. Thanks for getting back to me @Auriga2 so fast!  Very speedy.
