### ISSUE TITLE
Improvements to generate_test_cases.py

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#670]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The script `generate_test_cases.py` was used to generate the content in #667. This is a placeholder issue to track improvements that could be made to the script.

### Steps to Reproduce

1. `cd constellation`
2. `python ../constellation-miscellaneous/TestCaseGenerator/generate_test_cases.py` > output

### Suggestions
* [x] Sort the list of views and plugins alphabetically
* [ ] Fix the cases where the menu option is empty
* [ ] The script should be able to accept multiple folders so you could generate it for `constellation` and `constellation-adaptors` in the one script
* [ ] exclude any disabled actions or plugins
* [ ] some actions missing like "Arrange by Layers"
* [ ] There's no item to test `Tools/Cluster > Hierarchical`, and `K-Truss` should be listed as `Tools/Cluster >K-Truss`

**Comment by formalhaut69** [comment]
I've noticed that some actions such as the arrange in group action plugin are disabled in constellation but are still included in the generated test cases. Perhaps the script should ignore them if possible.

**Comment by Auriga2** [comment]
Not sure if this can be fixed in the script: There's no item to test `Tools/Cluster > Hierarchical`, and K-Truss should be listed as `Tools/Cluster >K-Truss`

**Comment by sol695510** [comment]
The Arrange by Layers action in the test cases isn't present in rc2 as well.

> I've noticed that some actions such as the arrange in group action plugin are disabled in constellation but are still included in the generated test cases. Perhaps the script should ignore them if possible.

**Comment by aldebaran30701** [comment]
@antares1470 did your changes to the 2.3 rc test cases manage to cross any of these off the list?

**Comment by antares1470** [comment]
> @antares1470 did your changes to the 2.3 rc test cases manage to cross any of these off the list?

@aldebaran30701 Sadly no. The changes I made were post-script execution rather than on the script itself

**Comment by arcturus2** [comment]
@GammaVel I'd be interested to know if you have any suggestions for things you would like to see added as output to the script during testing. Should the wording change or are there generic use cases that should be covered?

**Comment by arcturus2** [comment]
I was thinking of having more specific instructions for each view. For example the table view could have steps like checking the column sorting works etc. I was thinking of having mini files like `CoreTableView.txt` that the script would look for when its looping through the modules it would append the instructions in said files.

These files would of course would have to be typed out manually to start with...

**Comment by Auriga2** [comment]
`Testing Drag (and drop) (DragAction.java)` mentions about a menu, but there's no menu item for it. I guess this is the action performed when drag+drop using mouse? If so, it'd be good to re-word the instructions.

**Comment by Auriga2** [comment]
File/Import features are not listed
