### ISSUE TITLE
Dark mode visual updates

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#673]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
Generic ticket for dark mode visual consistency. 
#### Find View 
The find view presents adequately within standard light mode, but should support dark mode on the advanced tab
![image](https://user-images.githubusercontent.com/58677759/87363673-ce0b8980-c5b0-11ea-9228-d04854760df7.png)
![image](https://user-images.githubusercontent.com/58677759/87363713-e67ba400-c5b0-11ea-8f8b-0c2666b1c687.png)

#### Named Selections
With no active graph, the find view displays a white box. 
![image](https://user-images.githubusercontent.com/58677759/87483178-35d5d900-c672-11ea-8f2f-58ff4467545f.png)

#### Dialogs
This is more of a proposition, would it be preferred if this was dark mode also?
![image](https://user-images.githubusercontent.com/58677759/87483421-d75d2a80-c672-11ea-8cea-067f2b4a56ce.png)

**Expected behaviour:** visuals to be consistent

**Actual behaviour:** white box around all inner components

**Reproduces how often:** 100%

**Comment by aldebaran30701** [comment]
To add to this list, The Quality Control View buttons could be spaced out more and possibly represented in a better color scheme.
![image](https://user-images.githubusercontent.com/58677759/108016906-8461b080-7063-11eb-8b91-da684532cf5b.png)

**Comment by HolandCrick** [comment]
@aldebaran30701, @antares1470 , @Centauri0320001 - thanks you all for addressing the dark mode visual issue. Looks like almost perfect. Need very minor modification in "text next to check box in Ctrl+F -> Advance Tab -> Click on + sign. Next to "Replace Selection dropdown list". You will see text next to check box (black on black hard to read).

![image](https://github.com/constellation-app/constellation/assets/157770877/ac766a03-830d-41b6-808e-49ae16e6a2d0)

**Comment by Delphinus8821** [comment]
> @aldebaran30701, @antares1470 , @Centauri0320001 - thanks you all for addressing the dark mode visual issue. Looks like almost perfect. Need very minor modification in "text next to check box in Ctrl+F -> Advance Tab -> Click on + sign. Next to "Replace Selection dropdown list". You will see text next to check box (black on black hard to read).
> 
> ![image](https://private-user-images.githubusercontent.com/157770877/308425422-ac766a03-830d-41b6-808e-49ae16e6a2d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNzA4MjksIm5iZiI6MTcxMDM3MDUyOSwicGF0aCI6Ii8xNTc3NzA4NzcvMzA4NDI1NDIyLWFjNzY2YTAzLTgzMGQtNDFiNi04MDhlLTQ5YWUxNmU2YTJkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QyMjU1MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjI3NTg1YTIwNjdiZTE0MDQwZDI5OTYzOTdhOGEyNjRmNDM5NWU5YTAxNzA2MDJkNmJhZTY4ODRmZDM2MGYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jTsndebJKqsrUcB85kdaYyWpLwUtmUrnzWujBsX_QxY)

This issue has already been brought up in ticket #1963 so this ticket can be closed.
