### ISSUE TITLE
Constellation crashes when popped out graph is dragged into main window

### ISSUE THREAD

**Issue by Nova-2119** [constellation-app/constellation#678]
### Description

Problem will reoccur every time the program is opened or a graph is moved, until the user logs off and back on. Constellation freezes completely.

### Steps to Reproduce

Non-given

**Expected behaviour:** [What you expect to happen]

When a popped up graph is added to the main window it should seamlessly be added, like dragging a tab from a different browser window into window.

**Actual behaviour:** [What actually happens]
Constellation crashes.
java.lang.IllegalArgumentException: adding a container to a container on a different GraphicsDeviceJava.lang.IllegalArgumentException: adding a container to a container on a different GraphicsDevice at ...

**Reproduces how often:** [What percentage of the time does it reproduce?]
Unknown.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by formalhaut69** [comment]
I can't seem to reproduce this issue.

**Comment by antares1470** [comment]
Doesn't seem to be an issue any more. Closing
