### ISSUE TITLE
OpenGL renderer error

### ISSUE THREAD

**Issue by Nova-2119** [constellation-app/constellation#679]
### Description

Occasional error when opening a graph on a new terminal.
au.gov.asd.tac.constellation.visual.opengl.utilities.RenderException: Can't initialise once a batch has been finalised on a GL context. Dispose it first.

### Steps to Reproduce
Unknown

**Expected behaviour:** [What you expect to happen]

There should never be an error when opening a graph on a new terminal

**Actual behaviour:** [What actually happens]

Sometimes there is an error as described above

**Reproduces how often:** [What percentage of the time does it reproduce?]

Unknown

**Comment by aldebaran30701** [comment]
https://github.com/constellation-app/constellation/issues/646#issuecomment-655809676 outlines some further information and replication steps for seemingly the same exception.

**Comment by antares1470** [comment]
Should be resolved with other work that has been done
