### ISSUE TITLE
Levenshtein distance attribute parameter is broken

### ISSUE THREAD

**Issue by Nova-2119** [constellation-app/constellation#680]
### Description

The attribute selection parameter for the Levenshtein Distance analytic plugin displays transaction attributes where it should display node attributes.

### Steps to Reproduce

None given

**Expected behaviour:** [What you expect to happen]
Node attributes should be displayed.

**Actual behaviour:** [What actually happens]
Transaction attributes are displayed.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Unknown

**Comment by serpens24** [comment]
The list of attirbutes that user can select is determined in CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/analytics/LevenshteinDistanceAnalytic.java https://github.com/constellation-app/constellation/blob/master/CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/analytics/LevenshteinDistanceAnalytic.java, in the following block of code:
![image](https://user-images.githubusercontent.com/58677108/89149772-6be4e980-d59c-11ea-9bd7-f7b2aa9af9fd.png)

**Comment by serpens24** [comment]
We discussed this in weekly standup meeting ...... the bullet point list of attributes is being constructed by getting list of attributes registered for the schema .. this is not what we want, what we want is the lost of VERTEX atrributes actually in use for actual nodes/veretexes ... ie - more in line with attribute editor list (but only those that are strings)
