### ISSUE TITLE
Table View Column Filtering is Broken.

### ISSUE THREAD

**Issue by Nova-2119** [constellation-app/constellation#684]
### Description

If you right click on a column in the Table View you are presented with a dialog box allowing you to filter based on values in that column. This includes a search bar which appears to be disabled by default and never becomes available.

### Steps to Reproduce
Unknown

**Expected behaviour:** [What you expect to happen]
Search bar should be available.

**Actual behaviour:** [What actually happens]
As above

**Reproduces how often:** [What percentage of the time does it reproduce?]
Unknown

**Comment by serpens24** [comment]
This is an issue, although it doesnt happen all the time. I'll try and determine what triggers the failed case:

**Comment by Auriga2** [comment]
This filter is a ControlsFX TableFilter , added by the below line in `TableViewPane->updateData`. Nothing there seems to change this behaviour of the filter.
![image](https://user-images.githubusercontent.com/64826928/90608641-110cec80-e242-11ea-96a9-3db17278ef95.png)

Also tried to catch the right click event and set focus on the table but nothing below worked:

```
        this.table.setOnMouseClicked(e -> {
            if (parent.getCurrentState() != null && !parent.getCurrentState().isSelectedOnly()) {
                TableViewUtilities.copySelectionToGraph(table, rowToElementIdIndex,
                        parent.getCurrentState().getElementType(), parent.getCurrentGraph());
            }
            this.table.focusedProperty();
            this.table.getSelectionModel().focus(0);
            this.table.setFocusTraversable(true);
            this.table.clipProperty();
            this.table.requestFocus();
            this.table.refresh();
            this.filter.getTableView();
        });
```

**Comment by Auriga2** [comment]
http://fxexperience.com/2016/03/introducing-the-controlsfx-tablefilter/

**Comment by arcturus2** [comment]
I'm going to close this based on discussions that it all works when you click on the table view (to bring it into focus) and right click it works.
