### ISSUE TITLE
Table selection not working after Ctrl + U

### ISSUE THREAD

**Issue by Nova-2119** [constellation-app/constellation#687]
### Description
Open a new graph with Ctrl + U and the table view stops responding to graph selections etc.
This might be specific to certain graphs as its not reproduced on new graphs.

### Steps to Reproduce
Non- given

**Expected behaviour:** [What you expect to happen]
After opening a new graph with Ctrl + U the table view should continue to respond as normal

**Actual behaviour:** [What actually happens]
As described in description

**Reproduces how often:** [What percentage of the time does it reproduce?]
Unknown

**Comment by serpens24** [comment]
I have tried to reproduce with v2.0.0 without success ... given the trigger condition of Ctrl + U, this ticket may well be related to #697 - as this ticket also relates to behaviour when a new graph is opened with Ctrl + U.

**Comment by serpens24** [comment]
Refer to comments in #697 - I suspect this issue is now fixed, and hence OBE as I have not been able to reproduce.
