### ISSUE TITLE
Map view dances around before settling at a location

### ISSUE THREAD

**Issue by Nova-2119** [constellation-app/constellation#688]
### Description
When using the map view in Constellation, if you move around the map, or zoom in/out the map renders a few times with random minor offsets before settling on a location.
This becomes more noticeable the more you zoom in.

### Steps to Reproduce
Non-Provided

**Expected behaviour:** [What you expect to happen]
The map view should render once without minor offsets?

**Actual behaviour:** [What actually happens]
As described in the description

**Reproduces how often:** [What percentage of the time does it reproduce?]
Unknown

### Additional Information
COMMENT:
This is due to the animation that occurs on zooming to smooth it out. Turning this off resulted in a jarring zooming experience so I opted to leave it on. I believe there was a fix for this at some point in the Unfolding Maps project.

**Comment by cygnus-x-1** [comment]
Like you said, this is caused by the smoothing animation provided by Unfolding Maps. There is supposed to be a fix in for it but there hasn't been an official release, so we'd need to build a new jar from source if we want to try it out.
