### ISSUE TITLE
Current graph out of sync with helpers etc

### ISSUE THREAD

**Issue by Nova-2119** [constellation-app/constellation#689]
# Description
My current Constellation session has gotten out of sync. The histogram and stats in the bottom right of the tool are not for the active graph, but are stuck on one of the other graphs I currently have open. Changing between graph tabs is not updating this.

### Steps to Reproduce
Non-Provided

**Expected behaviour:** [What you expect to happen]
Histogram and stats should always be in sync with the current graph.

**Actual behaviour:** [What actually happens]
Histogram and stats get out of sync with current graph.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Unknown

**Comment by aldebaran30701** [comment]
#328  Duplicate
