### ISSUE TITLE
Integrate new JOGL version for the JDK 11 migration

### ISSUE THREAD

**Issue by rsabhi** [constellation-app/constellation#69]
### Description

As part of JAVA 11 migration, there is a requirement to upgrade JOGL dependent libraries.
Current we use JOGL version 2.3.2 which is compliant to JDK8. 
As per JOGL forum they are progressing to release JOGL update (2.5) for  Java11.
Here is the update from JOGL [forum](http://forum.jogamp.org/jogl-gluegen-available-for-java-11-td4039870.html)

**Comment by aldebaran30701** [comment]
The most current release is currently on JOGL rc 2.4.0 but they have not got the file hosted on maven repository. Investigating other solutions to either get it hosted, or download it from their archives. Would that be a bad solution? It would effectively be like the jhall and javahelp files except from their own repository. I'm just scraping the surface with understanding module dependencies and the maven and ivy work.

**Comment by arcturus2** [comment]
@aldebaran30701 would you have time to follow this up with the JOGL devs via the forum to find out what the reason might be for them not uploading 2.4.0? They may have forgotten.

To get things working it's ok to host the .jar locally as a temporary fix so you can progress with testing.

**Comment by aldebaran30701** [comment]
> would you have time to follow this up with the JOGL devs

Already done. 
http://forum.jogamp.org/Upgrading-from-JOGL-2-3-2-to-Current-master-for-Java-11-support-td4040335.html

**Comment by aldebaran30701** [comment]
Update: 
I added the files locally to the release/modules/etc of dependencies, and on a clean/build it compiled fine with the new JOGL version. 
The thing with this is it deletes the whole directory when doing update-dependencies-clean-build. 
One option would be to mess around with references in the project to point to a local lib folder containing the permanent files.

I've also added file references to the ant build.xml which automatically download the jogl files straight from the servers at [jogamp](https://jogamp.org/deployment/archive/rc/v2.4.0-rc-20200202/).
This implementation seems to work just fine even with update-dependencies-clean-build.
The only issue is reliability of their server and any downtime that url may face. 

I've got a query regarding how to progress wrt deprecated warnings. @arcturus2 
Blue is the additions I put including the suppression of the warning as .md5() still exists, and the deprecation only served as a warning to it's cryptographic security.
![image](https://user-images.githubusercontent.com/58677759/74209658-9f734500-4cd8-11ea-8f7a-59a387cb3c1c.png)

Would this be suitable given the situation? 
There are a few other deprecated warnings coming from constellation classes - how would you like these handled?

In the meantime I'll have a go at creating a folder to direct the local copies of files so they are recognized by import statements within the project

**Comment by arcturus2** [comment]
> The thing with this is it deletes the whole directory when doing update-dependencies-clean-build.
One option would be to mess around with references in the project to point to a local lib folder containing the permanent files.

You mentioned later on that you added a download for it in `build.xml` so it is OK. Is the only issue that the url not always available?

> I've got a query regarding how to progress wrt deprecated warnings. @arcturus2

Greatly appreciate the effort to investigate these warnings. With regards to the `postToNifi` method I think we can change it to support sha256 based on https://nifi.apache.org/docs/nifi-docs/components/org.apache.nifi/nifi-standard-nar/1.11.1/org.apache.nifi.processors.standard.HashContent/.

So as a way forward, perhaps remove the suppression warning and update it to use sha256...but I'd like to suggest this be done outside of the JOGL upgrade branch. We should limit the scope of this to just what is required to upgrade to NB 11 and JDK 11 which intern makes it easier to test and push to master when its ready. 

With regards to warnings, I think we should do that as a separate effort. Perhaps we can consolidate all of the warning and discuss how we want to tackle them upfront (i.e ignore or fix) and then make code changes. Is that OK @aldebaran30701?

> In the meantime I'll have a go at creating a folder to direct the local copies of files so they are recognized by import statements within the project

Is this problem related to `project.xml` not updating dependencies correctly?

**Comment by aldebaran30701** [comment]
>You mentioned later on that you added a download for it in build.xml so it is OK. Is the only issue that the url not always available?

Yes. Would you prefer to:
- Distribute Constellation with the 2.4.0 version of JOGL (Update would require changing of files)
- Have the dependencies download from the JOGL repository but opens up to risks regarding availability.

Both work and have been confirmed. I would like you to let me know which is best.

>With regards to the postToNifi method I think we can change it to support sha256

I'll make an issue for this so when I can focus on it, I can ensure no other components are effected from this change.

>With regards to warnings, I think we should do that as a separate effort. 

Agreed @arcturus2

>Is this problem related to project.xml not updating dependencies correctly?

Thats what I changed to get it working, the files had to point to the correct directory, was working like a charm once they were linked properly.

**Comment by arcturus2** [comment]
> Yes. Would you prefer to:
>
> * Distribute Constellation with the 2.4.0 version of JOGL (Update would require changing of files)
> * Have the dependencies download from the JOGL repository but opens up to risks regarding availability.

@aldebaran30701 apologies I'm a bit slow today. I don't think I fully understand the problem. Perhaps I'm going off on a tangent and I apologies for that...but can we host the jar in https://github.com/constellation-app/third-party-dependencies and download it from `build.xml` ?

If my suggestion adds more pain then for now, do what is easiest and we can take it from there 😄

**Comment by aldebaran30701** [comment]
That is also an option; It solves the problem of having the possible availability issues, and also reduces the download size for constellation. These are the required files for the newest version of JOGL. If you would like to add those to the repository. I got them from picking through [here](https://jogamp.org/deployment/archive/rc/v2.4.0-rc-20200202/jar/)

**Comment by arcturus2** [comment]
@aldebaran30701 would you be able to please send me a PR to that repo?
