### ISSUE TITLE
Parameter values are not recorded when saving a workflow

### ISSUE THREAD

**Issue by Nova-2119** [constellation-app/constellation#694]
### Description
Recalling a saved workflow in the Data Access View using Options > Load, appears to restore only global parameters and plugin selections, but not the plugin specific parameters.

### Steps to Reproduce
Non_provided

**Expected behaviour:** [What you expect to happen]
All parameters should be saved.

**Actual behaviour:** [What actually happens]
Only global parameters are saved

**Reproduces how often:** [What percentage of the time does it reproduce?]
Unknown

### Additional Information

Linked to Issue https://github.com/constellation-app/constellation/issues/25

**Comment by aldebaran30701** [comment]
I've just tried this multiple times with `extract types from text` and `merge modes` and all parameters are saving and loading correctly. I'm wondering if this has been since fixed

**Comment by arcturus2** [comment]
Yeah i think your correct. This was probably fixed in b7747ac. Going to close. Thank you for confirming @aldebaran30701.
