### ISSUE TITLE
The Plugin Reporter does not display messages from child plugins.

### ISSUE THREAD

**Issue by Nova-2119** [constellation-app/constellation#695]
### Description
As it stands if a plugin spawns another plugin on the same thread, the plugin reporter will place the report for the child plugin inside the report for the parent plugin. This is not the case if the child plugin is run on another thread. To fix this, I think plugins should optionally be able to nominate another plugin thread as their parent, and the plugin reporter should look for this and merge reports as appropriate.

Currently all plugins that use the WorkflowQueryPlugin template will produce many (rather than one) plugin report. The issue also occurs with Analytic View plugins.

In addition the use case I have in mind here is that if a plugin creates a child plugin, and that child plugin fails, then the plugin should be able to lookup the report of the child plugin in order to itself report why it failed.

### Steps to Reproduce
Non-Provided

**Expected behaviour:** [What you expect to happen]
Messages from child plugins should be reported by the plugin reporter.

**Actual behaviour:** [What actually happens]
Messages from child plugins are not reported.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Unknown

**Comment by aldebaran30701** [comment]
#323 Duplicate
