### ISSUE TITLE
Named Selections View issues

### ISSUE THREAD

**Issue by Auriga2** [constellation-app/constellation#696]
### Description

Named Selections View: The named selections do not highlight in the graph when clicked on the them. (I assumed they should). So there is no way to see the named selections added using the button. The ones added using `Control-Shift-Number` gets selected when `Control-Number` is pressed.

If I delete all the selections, the graph still keeps the last selection if `Dim unselected elements` button was clicked, even after the Named Selection Window is closed.
![Named selection view issues](https://user-images.githubusercontent.com/64826928/87495189-e7cfce00-c68f-11ea-8271-a72ab8b5fe58.gif)

### Steps to Reproduce

1. Open a graph, and open the Named Selection Window
2. Add named selections using the Add button

**Expected behaviour:** Highlight the selection when clicked on the items in the Named Selection Window, and clear the selection when the Named Selection Window is closed while the `Dim unselected elements` button is clicked.

**Actual behaviour:** Doesn't highlight the selection when clicked on the items in the Named Selection Window, and it doesn't clear the selection when the Named Selection Window is closed while the `Dim unselected elements` button is clicked.

**Reproduces how often:** 100%

**Comment by Auriga2** [comment]
1. Found how to highlight the selection. Click on the Red square and then double check the selection item. I think we should update the help page to mention this. The tool tip in the Red square is self explanatory but I didn't think of double clicking.

2. Still a problem.

**Comment by aldebaran30701** [comment]
Hi @arcturus2 and @Auriga2 Just wondering the status of this ticket now, If it should be closed or a new ticket made re: updating the help as per below.
>Found how to highlight the selection. Click on the Red square and then double check the selection item. I think we should update the help page to mention this. The tool tip in the Red square is self explanatory but I didn't think of double clicking.

**Comment by Auriga2** [comment]
The linked PR solved the issue, as it clears the selection and dimming when deleting a Named selection.
Agree that we should keep the last selection when the Named Selection Window is closed, because the named selections are stored with the graph.
So this can now be closed.

**Comment by arcturus2** [comment]
>Agree that we should keep the last selection when the Named Selection Window is closed

Also agree.
