### ISSUE TITLE
Multiple star graph cache issues

### ISSUE THREAD

**Issue by Nova-2119** [constellation-app/constellation#697]
### Description
When working on more than one graph in a single Constellation session, it is impossible to select nodes or use any views on any graph beyond the first one which you opened in the session. The problem can only be resolved by closing your Constellation session, and starting again. Looks like a cache issue?

### Steps to Reproduce

1. Open any graph
2. Make a new graph by Ctrl + U 
3. Highlight some different nodes on the original graph
4. Then try highlighting the nodes on the new graph

**Expected behaviour:** [What you expect to happen]
Should be able to select nodes and use views as normal.

**Actual behaviour:** [What actually happens]
As described in the description

**Reproduces how often:** [What percentage of the time does it reproduce?]
Unknown

**Comment by aldebaran30701** [comment]
I cannot seem to replicate this

**Comment by serpens24** [comment]
I'm also not seeing this occur - @Nova-2119 are you able to identify the version of Constellation you are using ... and perhaps what operating system you are running on.

**Comment by Nova-2119** [comment]
@serpens24 i'm not the original creator of this ticket :( and haven't seen this behavior myself. I copied this over from another system.
It would not be a surprise if this has since been fixed.

**Comment by serpens24** [comment]
Thanks @Nova-2119. I spoke to @arcturus2 and its possible that this (and other) tickets are OBE. I also notes #687 talks about behaivour following CTRL+U being used and ity couldnt be reproduced either. Perhaps both are no longer issues.
