### ISSUE TITLE
Current process has used all of its system allowance of handles for Window Manager objects

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#701]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

```
INFO [au.gov.asd.tac.constellation.visual.opengl.utilities.SharedDrawable]: Took 0 seconds to retrieve a GL3 profile
WARNING [au.gov.asd.tac.constellation.views.tableview2.TableViewPane]: InterruptedException encountered while updating table data
WARNING [null]: Last record repeated again.
SEVERE [global]
java.lang.InternalError: The current process has used all of its system allowance of handles for Window Manager objects.

	at java.desktop/sun.awt.windows.WToolkit.eventLoop(Native Method)
	at java.desktop/sun.awt.windows.WToolkit.run(Unknown Source)
[catch] at java.base/java.lang.Thread.run(Unknown Source)
SEVERE [null]: Last record repeated 3 more times.
WARNING [org.netbeans.core.TimableEventQueue]: too much time in AWT thread org.netbeans.modules.sampler.InternalSampler@2ce7e912
SEVERE [global]
java.lang.InternalError: The current process has used all of its system allowance of handles for Window Manager objects.

	at java.desktop/sun.awt.windows.WToolkit.eventLoop(Native Method)
	at java.desktop/sun.awt.windows.WToolkit.run(Unknown Source)
[catch] at java.base/java.lang.Thread.run(Unknown Source)
WARNING [au.gov.asd.tac.constellation.views.tableview2.TableViewPane]: InterruptedException encountered while updating table data
SEVERE [global]
```

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behaviour:** [What you expect to happen]

**Actual behaviour:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by arcturus2** [comment]
@WCWarrior1 can you please try to reproduce this in v2.0.0-rc2 ?

**Comment by arcturus2** [comment]
I've managed to make this happen again.

**Comment by aldebaran30701** [comment]
Would you happen to be able to retest, and add a reproducer onto the ticket with more more info @arcturus2

**Comment by arcturus2** [comment]
@aldebaran30701 so that's the hard part. It was random when I was just trying to close Constellation and I didn't have it happen to me since. I tried to search for a fix and the first google result that came up was this ticket :laughing: so I re-opened it. Without a reproducer it is hard to justify keeping this open so I will close it again...
