### ISSUE TITLE
The pop up message when starting Rest Server is hiding behind the graphs.

### ISSUE THREAD

**Issue by Auriga2** [constellation-app/constellation#711]
### Description

When the `Tools` -> `Start Rest Server` is clicked, the below message pops up, but it's only visible if there are no graphs opened. When any graph is opened, only the bottom part is visible, although you can see the status by clicking on the orange triangle, which displays status of all the services.

![image](https://user-images.githubusercontent.com/64826928/87628638-90555f00-c770-11ea-9538-c87b4fc3b08b.png)

And maybe it should not allow new services to be started on the same port?
![image](https://user-images.githubusercontent.com/64826928/87628699-afec8780-c770-11ea-99d7-f2dfeb69a823.png)

### Steps to Reproduce

1. Open a graph, then click `Tools` -> `Start Rest Server`.
2. Check the notification at the bottom right corner. 

**Expected behaviour:** The pop up message should appear at the front

**Actual behaviour:** The pop up message should appear behind the graph

**Reproduces how often:** 100%

### Additional Information

Same behaviour in v2.0.0-beta5

**Comment by Auriga2** [comment]
1. Recreatable in the v2 exe, only if the focus was on the graph (it works if the focus was on a view), but not in debug mode. 
2. It's not really starting multiple web servers, but displaying the same message pretends so. As  a fix we can display "Web server already started" instead of  "Web server started" to reduce confusion.

**Comment by arcturus2** [comment]
> It's not really starting multiple web servers, but displaying the same message pretends so. As a fix we can display "Web server already started" instead of "Web server started" to reduce confusion.

Yep that would be a good idea.

**Comment by Auriga2** [comment]
1. Clicking on the graph also brings the notification to the front. And this is the same behaviour in beta 5. It's hard to fix because we can't recreate in debug mode. @arcturus2 Should we put more effort to fix this, given it's a minor issue? If so who'd have the best advice?
2. Easy fix.

**Comment by arcturus2** [comment]
1. @Auriga2 I support the 90/10 Principle. To fix this edge case I feel will take a long time and I do agree this is a low priority. Though not ideal from a user perspective; to fix this there is a chance you will need to get stuck into the NetBeans source code to fix this given the pop-ups are coming from NetBeans. I would suggest not spending the time to fix this; your time could be better spend helping with other bugs on the backlog.
2. Cool, if its an easy fix then that would be great to have.

Apologies for the delayed response.

**Comment by aldebaran30701** [comment]
From the discussions above, is the consensus to close this issue as it is probably not something we will look to fix?

**Comment by Auriga2** [comment]
Yes, closed.

**Comment by antares1470** [comment]
I think there is an argument to keeping this open. Tagging it with "wontfix" doesn't make the bug go away so it think it could be worth keeping open just to acknowledge that while we won't be able to fix it, it is still an issue and this may prevent tickets for the same problem being created later down the track

**Comment by Auriga2** [comment]
I am not sure, but why do we want to keep it open if we won't fix it?
People can still search closed issues..?

**Comment by antares1470** [comment]
> I am not sure, but why do we want to keep it open if we won't fix it? People can still search closed issues..?

People can search closed issues yes but I know from my experience that I don't tend to go through the closed issues without a reason (and I certainly don't think to go through them if I'm looking for whether I bug I've found has been already has a ticket).

I acknowledge that my opinion is probably in the minority. It's certainly not an uncommon practice to close any ticket they won't work on (regardless of the nature of the ticket) and so we can keep the ticket closed. I just thought I'd offer a different perspective as I think it is good to distinguish between "won't fix" and "can't fix".
