### ISSUE TITLE
Constellation - Tutorial Page/Quick Start Guide - Font to small

### ISSUE THREAD

**Issue by WCWarrior1** [constellation-app/constellation#712]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
Constellation-v2.0.0-rc2 - Tutorial/Quick Start Guide - the font on the right side is way to small and is very hard to read, this needs to be made bigger. 

Check snip attached.
![Tutorial Tab and fonts example](https://user-images.githubusercontent.com/66282538/87627265-add6f880-c771-11ea-965f-604d1b733e08.jpg)

### Steps to Reproduce

1. **Not required**
2. [Second Step]
3. [and so on...]

**Expected behaviour:** [What you expect to happen]

**Actual behaviour:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by arcturus2** [comment]
Thanks @WCWarrior1 will have a look. I felt it looked small too.
