### ISSUE TITLE
When enabled, direction indicators should animate at all times.

### ISSUE THREAD

**Issue by formalhaut69** [constellation-app/constellation#716]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Currently, when direction indicators are enabled they only animate when the user moves a node or the camera.

**Comment by cygnus-x-1** [comment]
This issue could be expanded to something like 'Animations should render in an interactive loop' or something as the core issue applies to all animations - currently you can only run them in a locked loop (so the graph is not interactive) or have them update with the graph (as with direction indicators).

**Comment by aldebaran30701** [comment]
Logged in [Brainstorming Ideas](https://github.com/constellation-app/constellation/wiki/Brainstorm-Ideas/) So we will close this ticket until a later time.
