### ISSUE TITLE
Analytic view loses plugin results on view re-open

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#718]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Opening the Analytic view, running a question and reviewing the results happens all ok. The issue is when the user switches to another view like Attribute Editor and then back to the Analytic View. Doing so will require the user to re-run the question to view results. This only occurs when the user opens the other view over the top of Analytic View. It makes me think it is an issue regarding `componentShown(...)` and an unnecessary refresh.

### Steps to Reproduce

1. Open graph - draw mode w/a few nodes
2. Open Analytic View -> run betweenness centrality. or others.
3. Open Attribute Editor over the top
4. Switch back to Analytic View

**Expected behaviour:** State is kept

**Actual behaviour:** View is refreshed.

**Reproduces how often:** 100%

**Comment by cygnus-x-1** [comment]
While individual analytic results are saved to the graph (degree centrality, cosine similarity, etc), the aggregated results displayed in the Analytic View are not. The intention was to save the aggregated result set for each tab to the Analytic View state... but first we need to give the Analytic View a state.
