### ISSUE TITLE
Selection > Select Half Hop Induced Subgraph doesn't select anything

### ISSUE THREAD

**Issue by Auriga2** [constellation-app/constellation#724]
### Description

The menu item `Selection` >` Select Half Hop Induced Subgraph` (SelectHalfHopInducedSubgraphAction.java) does not seem to select anything.
`Selection` > `Select One Hop Induced Subgraph` (SelectOneHopInducedSubgraphAction.java) seems to work. 

### Steps to Reproduce

1. Open a graph
2. Select some Source nodes 
3. Click `Selection` >` Select Half Hop Induced Subgraph`

**Expected behaviour:** The transactions selected  by  clicking `Select One Hop Induced Subgraph` to highlight.

**Actual behaviour:**  No new part of the graph is highlighted

**Reproduces how often:** 100%

### Additional Information

![HalfHopInducedSelectionBroken6](https://user-images.githubusercontent.com/64826928/87755301-e5af7000-c845-11ea-8224-e8db0441186c.gif)

**Comment by arcturus2** [comment]
![half induced sub graph](https://user-images.githubusercontent.com/39325530/87876846-0df1c700-ca1e-11ea-9d4a-7d45700e7578.gif)

@Auriga2  so it depends on the graph structure. See gif above. I'm going to close this if that's ok.

**Comment by Auriga2** [comment]
Agree  following the definition (from cygnus-x-1):

> half-hop induced subgraph should select transactions between any selected nodes which are directly connected, one-hop induced subgraph should select nodes and transactions between any selected nodes which are connected by one intermediary node.
