### ISSUE TITLE
Duplicate Types with v1 and v2

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#730]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

New nodes added in v2 from an existing graph from v1 will produce duplicates. After further debugging the issue seems to be related to the Types being different under the hood. We changed the detection and validation regex which is part of the type. The solution would be to upgrade the types using the Schema upgrade framework when opening old graphs.

### Steps to Reproduce

1. Open Constellation v1
2. Go into draw mode and add a node
3. Open the attribute editor and change the Type to "Ipv4 Address"
4. Press F5
5. Save and close
6. Open Constellation v2
7. Go into draw mode and add a node
8. Open the attribute editor and change the Type to "Ipv4 Address"
9. Press F5. You should have Vertex #0<Ipv4 Address>and Vertex #1<Ipv4 Address>. So far so good.
10. Select Vertex1 and in the attribute editor select Edit next to Identifier
11. Change it to Vertex #0 and click OK
12. Press F5

![duplicate nodes](https://user-images.githubusercontent.com/39325530/87904058-d5470180-caa0-11ea-99d2-683824f60252.gif)

**Expected behaviour:** The nodes should merge into 1

**Actual behaviour:** There are 2 nodes on the graph!

**Reproduces how often:** 100%

### Additional Information

This should be fixed for all types.

**Comment by cygnus-x-1** [comment]
Unless the graph data-structure is completely broken, this is likely caused by the Type attribute, ie. one of the IPv4 types has an additional property or something.
