### ISSUE TITLE
Constellation Startup: Splash Screen Flicker

### ISSUE THREAD

**Issue by serpens24** [constellation-app/constellation#731]
### Description

This may be a cached image issue ? But still seems odd. After installing Constellation 2.0.0 (exe), as it starts up the spash screen switches between 2 images - see gif below. This DOES NOT happen if run from debugger.

Does something need to be deleted to celar any old images ?

### Steps to Reproduce

1. Start Constellation exe

**Expected behaviour:** 
Splash screen is consistent

**Actual behaviour:** 
Splash screen image changes

**Reproduces how often:** 
100% - for my exe install

### Additional Information

![ConstellationStartup](https://user-images.githubusercontent.com/58677108/87906567-04aa3e00-caa2-11ea-8e2f-61adc536bbc5.gif)

**Comment by arcturus2** [comment]
Hi @serpens24. There are some temporary files that is likely causing this to happen. If you click on Help -> About and then look at the **cache dir** and **user dir**, try removing these 2 folders and run it again.

**Comment by serpens24** [comment]
@arcturus2 - that fixed the problem. I'm not sure theres an automatic way to fix it other than creating some form of installer. I guess given the fact the issue doesn't stop anything working we can just leave as is !!

**Comment by antares1470** [comment]
@serpens24 Can this ticket be closed or is there something else that needs to be done for this issue?

**Comment by arcturus2** [comment]
@serpens24 I've had a think about what we could do to clean the cache but it gets messy and difficult quickly. I feel that it is better to not do anything in this case.
