### ISSUE TITLE
Copy/paste from Histogram

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#741]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Selecting property values in the Histogram selects the corresponding nodes or transactions on a graph but does not allow the user to copy those property values to the clipboard (using ctrl-c or right-click copy). Doing this at the moment requires the user to open the Table view, show the column for the desired property and copy from there. This is far more time-consuming than the ability to copy directly from the Histogram view.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behaviour:** [What you expect to happen]

**Actual behaviour:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by cygnus-x-1** [comment]
You can copy data directly from the Histogram View by clicking the 'Actions' button and selecting 'Copy Bins to Clipboard'. It'll get the job done, but i'd agree that it's clunky and implementing Ctrl+C / Ctrl+V would be a much nicer experience.

**Comment by sol695510** [comment]
@antares1470 do you want ctrl + c to copy the entire histogram or just the selected bar in red on the histogram? Currently it copies the entire histogram, mimicking the functionality of the clicking "Actions" > "Copy Bins to Clipboard".

**Comment by sol695510** [comment]
> @antares1470 do you want ctrl + c to copy the entire histogram or just the selected bar in red on the histogram? Currently it copies the entire histogram, mimicking the functionality of the clicking "Actions" > "Copy Bins to Clipboard".

What I've implemented:

If you right click on the Histogram, you'll get a context menu with two options; Copy Bar or Copy Histogram. Copy Bar will copy the value of just the bar you right clicked on, while Copy Histogram mimics the Copy Bins to Clipboard action.

Ctrl + C on the Histogram mimics the Copy Bins to Clipboard action.

**Comment by antares1470** [comment]
> @antares1470 do you want ctrl + c to copy the entire histogram or just the selected bar in red on the histogram? Currently it copies the entire histogram, mimicking the functionality of the clicking "Actions" > "Copy Bins to Clipboard".
@sol695510 sorry for taking my time with responding. I submitted this ticket on behalf on someone else so I was just waiting to get their thoughts.

They reckon the default behaviour should be to copy the property value of selected bar(s) only (since it's easy for to select the entire histogram as you've noticed). 

They also noticed that right-clicking in the histogram has the same effect as left-clicking and so suggested changing right-click to provide options for copy values (same as ctrl-c) and copy both values and counts
