### ISSUE TITLE
Split Nodes Plugin always adding Correlation between the split nodes

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#742]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

When running the Split Nodes plugin, the transaction type created between the nodes is always a Correlation regardless of what is actually selected

### Steps to Reproduce

1. Draw 2 nodes and draw a transaction between them
2. Rename one of the nodes to 'abc;def;ghi'
3. Open up Data Access View and go to Split Nodes plugin
4. Set the split character as ';' and the transaction type to any type other than a Correlation
5. Ensure the renamed node is selected and run the plugin

**Expected behaviour:** The transaction(s) formed from the plugin are of the type selected for the Transaction Type parameter

**Actual behaviour:** The transaction(s) formed from the plugin are of the type Correlation

**Reproduces how often:** 100%

**Comment by Auriga2** [comment]
@arcturus2 : This is due to the below code from SplitNodesPlugin.java
Therefor if "Correlation" exists in the list, it'll overwrite the selection.

>             if (types.contains(AnalyticConcept.TransactionType.CORRELATION.getName())) {
>                 SingleChoiceParameterType.setChoice(transactionType, AnalyticConcept.TransactionType.CORRELATION.getName());
>             }

What is the exact behaviour required here? May be default it only if no value is selected?

**Comment by arcturus2** [comment]
>What is the exact behaviour required here? May be default it only if no value is selected?

Precisely @Auriga2; if there is no value then lets default to a correlation, otherwise the plugin should use what the user has selected. Good debugging!

**Comment by Auriga2** [comment]
@arcturus, similar code  in `Extract words from text plugin`, if the "Content" is present in the drop down. (I couldn't see the behaviour because I couldn't get "Content" in the drop down) Could this be made so for a reason? Or should I add a null check here as well?

**Comment by arcturus2** [comment]
@Auriga2 to get the Content attribute to appear, open a graph and go to the Attribute Editor -> Transactions ->Little plus icon -> Content -> Content.

Now you will have the Content attribute added to the graph.

Normally the content attribute gets added to the graph as a result of importing data or running a plugin but this is how you can do it manually.

I think the thinking behind this plugin was that words would be in the Content attribute so if it exists then it should use it by default (if nothing is selected) but if another attribute is selected then it should use that for sure. The bug with split nodes was that even if we selected a different transaction type, it would still use Correlation which is wrong.

**Comment by Auriga2** [comment]
It has a similar code, so if the "Content" is there in the drop down, it'll use "Content" instead of the user selected value.  I'll add a check there as well.

**Comment by Auriga2** [comment]
@arcturus2  Also I noticed that these drop downs do not populate if you open the graph after the DAV. Is it expected behaviour? When I have to test, I have to `close DAV, then close Constellation and then open it, load a graph, open DAV` to refresh the list. Is there a better way to refresh these drop downs?

**Comment by arcturus2** [comment]
@Auriga2 the way it's meant to work is that `updateParameters` should be called when you open a graph or switch graphs. This method gets a chance to update the parameters it has in context of the graph you have. The Analytic schema has registered transaction types defined and the Split Nodes Plugin drop down should update. If you then go to File -> New Graph -> Visual Graph (which has no transaction types registered) it should call `updateParameters` and set the drop down list to empty.

I noticed whilst testing just now that I had the same issue you described above (which is broken) but then ran it in debug mode and it seemed to work. That is the drop down list did populate after opening up an Analytic graph with the DAV already open.

I then tried to open a Visual Graph and noticed that though `updateParameters` was called, the drop down list did not go back to being empty. This is a bug.

In general, any time a graph is open or you switch to another graph all views need to update. The DAV updates its drop down lists. The Schema View for example interrogates the schema on the graph and updates its registered attributes, node and transaction types. You should not need to open the views or graph in a specific way for them to update. That is another bug then @Auriga2.

**Comment by Auriga2** [comment]
I'll log a separate ticket for that.
Additionally I fixed a bug where the drop down wasn't displaying the user selected item when debugging. It was weird, I just had to move below lines after the ArrayList is sorted. 
```
@SuppressWarnings("unchecked") //ATTRIBUTE_PARAMETER will always be of type SingleChoiceParameter
 final PluginParameter<SingleChoiceParameterValue> contentAttribute = (PluginParameter<SingleChoiceParameterValue>) parameters.getParameters().get(ATTRIBUTE_PARAMETER_ID);
```

**Comment by antares1470** [comment]
I've tested this and it appears to be working properly now
