### ISSUE TITLE
Add more examples to the example-module

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#746]
This issue refers to constellation-app/constellation-module-example.

Consider adding more example plugins such as
* `SimpleReadPlugin`
* `SimpleEditPlugin`
* `RecordStoreQueryPlugin`
* `SimplePluginAction`
* `DataAcessPlugin`
* An arrangement plugin
* A `JavaFxTopComponent`

**Comment by aldebaran30701** [comment]
Closing this
