### ISSUE TITLE
v2.0.0-rc2 Difficulty uploading time from capture due to time formatting options

### ISSUE THREAD

**Issue by forestfairy** [constellation-app/constellation#748]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

v2.0.0-rc2 Difficulty uploading time from capture due to time formatting options

### Steps to Reproduce

1. Using a .csv file converted from a .pcap files from wireshark
2. File>Import>.csv
3. file uploads into upload window

**Expected behaviour:** [What you expect to happen]
When assigning variables, an option in the self assigned variables to format the time as (*just*) seconds (such as in seconds from capture) 

**Actual behaviour:** 
When assigning variables, there is no option in the self assigned variables to format the time as seconds (such as in seconds from capture) 

![image](https://user-images.githubusercontent.com/25699425/88879727-602cb680-d26e-11ea-9cdf-846ad31781c9.png)

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% or the few attempts that I have made so far

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by forestfairy** [comment]
This file was originally pcap but was uploaded as .csv ... not sure  if that altered things in any way?

**Comment by cygnus-x-1** [comment]
The DateTime attribute is exactly that - a **Date**Time. If you've only got time information, then you should create a custom attribute of type 'Time' (which should be able to interpret int/long/etc). That being said, the values in that column are less than 3 - does this column data represent a duration or time from some known starting point?
