### ISSUE TITLE
v2.0.0 Error in data sequencing when uploading .csv files from .pcap

### ISSUE THREAD

**Issue by forestfairy** [constellation-app/constellation#749]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

v2.0.0 Error in data sequencing when uploading .csv files from .pcap

### Steps to Reproduce

1. Convert capture .pcap files from Wireshark to .csv 
2. Upload through File>upload>.csv
3. When data is examined int he upload window, it appears scrambled

**Expected behaviour:** [What you expect to happen]
Data to be uploaded in order, to be assigned 
 
**Actual behaviour:** [What actually happens]

Data rows and no. appear to be scrambled
![image](https://user-images.githubusercontent.com/25699425/88880372-ec8ba900-d26f-11ea-8797-8eda4b3bb6d1.png)

**Reproduces how often:** [What percentage of the time does it reproduce?]
??% When uploading .csv files form WS

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by cygnus-x-1** [comment]
I might be missing something obvious here - but this looks fine to me. The 'Row' column in the table preview is automatically generated and applied to all preview data, and all other columns and rows seem to line up with the Excel spreadsheet image above.

**Comment by forestfairy** [comment]
My apologies, I've tried to reproduce the error in the diagrams above, one of the students actually had the error and I wasnt able to import the those screenshots into git.
