### ISSUE TITLE
Integrate processing-core jar file compliant to JAVA11

### ISSUE THREAD

**Issue by rsabhi** [constellation-app/constellation#76]
### Description

As part of JAVA 11 migration, there is a requirement to upgrade "core" dependent libraries.
Currently we use processing.core jar file which is compliant to java 8. This need to be upgraded with java11. I would prefer to use this after we integrate latest version of JOGL 2.5 because processing.core have transitive dependency with JOGL jar files.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behaviour:** [What you expect to happen]

**Actual behaviour:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by neilcsmith-net** [comment]
@rsabhi sorry to contact via here, but not sure of any other way to get in touch! It looks like we're working through same tech stacks and issues (NetBeans, Processing, JOGL, etc.), including this one - maybe there's a way we can share some workload here?  Feel free to email me - on my GitHub profile.

**Comment by arcturus2** [comment]
@neilcsmith-net some sort of collaboration definitely sounds like a good idea. When I chatted with @rsabhi last, we were waiting for JOGL 2.5 to be released which was possibly going to happen towards the end of this month. See http://forum.jogamp.org/jogl-gluegen-available-for-java-11-td4039870.html. For now, further work is on hold.

Happy to continue discussions here or via email if that's what you prefer.

**Comment by neilcsmith-net** [comment]
@arcturus2 possibly email for now? There's potentially a few things that sync up here across issues.  Have emailed with @rsabhi already.

Have been following the JOGL progress, but also looking at alternatives currently, and am also working on modularizing and mavenizing Processing Core.  Saw your application via a NetBeans contact - my work is also on top of a NetBeans system, and I'm on the Apache PMC.  So all-in-all feels like there might be a few useful conversations there anyway ...

**Comment by sampottinger** [comment]
Not sure if it is helpful but just a humble link drop to https://github.com/sampottinger/processing <3. My work isn't on top of NetBeans though and my edits into core were much more shallow so @neilcsmith-net's work might be more relevant for you depending on your goals.

**Comment by arcturus2** [comment]
> Not sure if it is helpful but just a humble link drop to https://github.com/sampottinger/processing <3. My work isn't on top of NetBeans though and my edits into core were much more shallow so @neilcsmith-net's work might be more relevant for you depending on your goals.

All good thank you @sampottinger. I'll check it out and let you know if I have any success :+1:

**Comment by aldebaran30701** [comment]
Fixed with #274
