### ISSUE TITLE
Levenshtein Distance Analytic doesn't update 

### ISSUE THREAD

**Issue by formalhaut69** [constellation-app/constellation#768]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The Levenshtein distance analytic doesn't update when changes to the graph are made. It's onPrerequisiteAttributeChange method should be getting called to update the analytic along with it's UI. 

### Steps to Reproduce

1. Make a change to the graph
2. Open the Levenshtein distance analytic's options

**Expected behaviour:** The options will update to reflect what is currently in the graph

**Actual behaviour:** The options are permanently stuck as whatever was loaded into the UI originally

**Reproduces how often:** 100%

### Additional Information
There are several other classes that use this method so this issue may not be exclusive to the Levenshtein distance analytic

**Comment by formalhaut69** [comment]
https://github.com/constellation-app/constellation/pull/764 PR for progress with fixing the Levenshtein distance analytic

**Comment by antares1470** [comment]
Have created #842 which was found while testing this
