### ISSUE TITLE
Review default values with attribute descriptions

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#778]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

It looks like there are cast exceptions occurring due to a mismatch between the default value and `convertFromString`. So `DateAttributeDescription` is one of them but there could be more. Write some tests and review it.

**Comment by antares1470** [comment]
@arcturus2 I did a bit of research into this one and discovered that `TimeAttributeDescription` also appears to have this issue in the same way `DateAttributeDescription` does. Haven't identified an issue in any of the others as of yet
