### ISSUE TITLE
Quality Control View Click bug

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#784]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

There appears to be a bug where the first time you single-click on a row in the quality control view, it performs the double-click action as well. This doesn't happen for subsequent clicks with the current selection of nodes/transactions.

### Steps to Reproduce

1. Open Quality Control View
2. Create a sphere graph (some nodes should be selected by default)
3. In Quality Control View, click on one of the rows
4. Observe the rules dialog box that normally only pops up when you double-click the row

**Expected behaviour:** Single-click selects a row in QCV

**Actual behaviour:** Single-click also performs double-click action the first time around

**Reproduces how often:** 100%

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by formalhaut69** [comment]
After some analysis of this issue, it appears that the bug is some functionality within the JavaFX tableView and not our code. I put some code into our table view to test if the initial click is registered as a double click and it is. I googled this bug but found nothing.

**Comment by arcturus2** [comment]
It is interesting though that this behaviour didn't seem to occur in v1. Perhaps a behaviour has changed since the upgrade of Java from 8 to 11 perhaps?

**Comment by GammaVel** [comment]
Confirmed this is still an issue in version 2.3. I did see that sometimes the message box is hidden behind Constellation too which is not ideal.  
Try upgrading to the latest version of Java and JavaFX. If it is still a problem with the latest upgrade version and not Constellation, log JavaFX issue.

**Comment by aldebaran30701** [comment]
The issue appears to be the Table view, but could also be an issue caused by the way Constellation uses that component. Agreed, retest on the next update of Java.

**Comment by GammaVel** [comment]
Brilliant!  Thanks @Centauri0320001 for investigating this inconsistent behaviour. It is great that all the rows behave the same way now in the QC view. Thanks for making time to look at an older issue and getting it sorted!
