### ISSUE TITLE
Optimise renderer taking advantage of depth of field

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#800]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Constellation can handle a million nodes with high end graphics cards. If we want to push the limits and get to multi-million nodes with ease, can we use the depth of field to our advantage? That is, nodes that are further away into the distance should reduce the load on the graphics card.

Presently, labels render when they are closer to you and disappear when you zoom out. Could something similar be done with nodes and transactions whereby when you zoom out a lot and nodes are on top of one another, less nodes are actually rendered and therefore graph load time and interaction can improve dramatically.

### Steps to Reproduce

1. Open a new graph
2. Experimental -> Build Graph -> Sphere Graph and set to 1,000 nodes and 1,000 transactions
3. Click OK
4. Save the graph
5. Close the graph
6. Open the graph and notice the time it takes to load the graph
7. Zoom out a lot so you see a tiny node, which is barely visible
8. Save the graph
9. Close the graph
10. Open the graph and notice the time it takes to load the graph

**Expected behaviour:**
The load time should be considerably quicker in step 10 compared to step 6

**Actual behaviour:**
The load times are the same regardless of how many nodes are visible.

**Reproduces how often:**
100%

**Comment by GammaVel** [comment]
This is a nifty idea that is being moved to brainstorming.
