### ISSUE TITLE
Preference for loading Tutorial View on start-up

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#808]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

There may be a need for the tutorial view to load on start up - I myself find that I end up closing it every application load. Maybe a prompt which asks if you would like to not see it again ?
I pose this as more of a question to gauge interest in the use of this functionality.

**Comment by arcturus2** [comment]
Hi @aldebaran30701 in Setup -> Options -> Constellation we do have a preference where you can have the tutorial view not show on startup.

**Comment by aldebaran30701** [comment]
I'm happy to close this as it was an oversight. I'll be using this. 👍

**Comment by aldebaran30701** [comment]
Reopening this as a prompt for the user may be useful on the tutorial page itself. 
**ie.** Tutorial view has a check box or option to not load it on startup.

**Comment by arcturus2** [comment]
It's their "Start Page" and the source code will be https://github.com/apache/netbeans/tree/master/nb/welcome/src/org/netbeans/modules/welcome/ui

![image](https://user-images.githubusercontent.com/39325530/91363255-9181ad80-e83f-11ea-99e6-36cd02d796e8.png)

**Comment by formalhaut69** [comment]
This issue is about 90% complete. I've got the checkbox working on the startpage and it looks nice. (This code starts on line 126 of TutorialViewPane)
```
ShowOnStartUpCheckBox = new CheckBox("Show On Startup");
            rightVBox.getChildren().add(ShowOnStartUpCheckBox);
            rightVBox.setAlignment(Pos.TOP_RIGHT);
            rightVBox.setBackground(new Background(new BackgroundFill(Color.valueOf("#333333"), CornerRadii.EMPTY, Insets.EMPTY)));
            rightVBox.paddingProperty().set(new Insets(5, 5, 5, 5));
            ShowOnStartUpCheckBox.selectedProperty().addListener(new ChangeListener<Boolean>() {
                @Override
                public void changed(ObservableValue<? extends Boolean> ov,
                        Boolean old_val, Boolean new_val) {
                    final Preferences prefs = NbPreferences.forModule(ApplicationPreferenceKeys.class);
                    prefs.putBoolean(ApplicationPreferenceKeys.TUTORIAL_ON_STARTUP, new_val);
                }
            });
            ShowOnStartUpCheckBox.setSelected(true);
```

The one part I couldn't finish was adding a listener to the on start up preference which can be found in the ApplicationPreferenceKeys class and is called TUTORIAL_ON_STARTUP. The new checkbox which I've added to the TutorialViewPane needs to listen to changes to the preference because there is another checkbox which also modifies the preference in constellation's settings. These need to stay in sync.
