### ISSUE TITLE
Improve the split logic in the Split Nodes plugin

### ISSUE THREAD

**Issue by Auriga2** [constellation-app/constellation#822]
### Description

Current split logic is inconsistent, for instance, when the `Split Characters` present consecutively in the middle or at the beginning, it duplicates the selected node in addition to the other new nodes splitted from the rest of the identifier. If the `Split Characters` present consecutively in the end, it just split the rest of the identifier.

This is the proposed criteria:

Split on first occurrence: (ALL_OCCURRENCES = False)
,,, split by , => create one node with ,,
vvv split by v = create one node with vv
v,,v split by , = create 2 nodes (v and ,v) as between ,, is no identifier
,,v split by , = create 1 node (,v) as nothing between the first two ,,s
v,,  split by , = create 2 nodes (v and ,) 

Split on all occurrences:: (ALL_OCCURRENCES = True)
,,, split by , = not create anything because of nothing between delimiters.
vvv split by v = the same as above.
v,,v split by , = create 2 nodes (v and v) as between ,, is no identifier
,,v split by , = create 1 node (v) as nothing between the first two ,,s
v,,  split by , = create 1 node (v) 

### Steps to Reproduce
Example scenario:
Create below nodes and split `a;;b` node with `;` in the `Split Characters` and with `Split on All Occurrence` set to true.
![image](https://user-images.githubusercontent.com/64826928/91514982-43e07000-e927-11ea-9f5c-c94a3301f0b7.png)

**Expected behaviour:** A new node with the same identifier `a;;b` should not be created among the other new nodes.

**Actual behaviour:**  A new node `a;;b` is created

**Reproduces how often:** 100%

**Comment by Auriga2** [comment]
`v,,v split by , = create 2 nodes (v and v) `
This should produce 2 nodes with same identifier, so only one is added in the graph, with a transaction to itself. In the unit test it appears to add a new node with the same identifier. Is this behaviour expected?

**Comment by antares1470** [comment]
> `v,,v split by , = create 2 nodes (v and v) `
> This should produce 2 nodes with same identifier, so only one is added in the graph, with a transaction to itself. In the unit test it appears to add a new node with the same identifier. Is this behaviour expected?

@Auriga2 As you've said, since the nodes created would have the same identifier, they become one node (with a loop to itself if not using the new split functionality). From what I've tested, the current functionality seems to create a new node with the old identifier if a blank node would've been created (e.g. in case of `v,,v` splitting on all occurrences). I'm not sure this should be correct though but rather, as has been specified, the blank should just be ignored (i.e. no new node created for the blank)

**Comment by Auriga2** [comment]
@antares1470  Yes, This is same behaviour as before I presume. It's ignored in the new fix here. I'll create a PR shortly.
