### ISSUE TITLE
Using shortcut to deselect all layers doesn't update the graph

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#823]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

When using Ctrl-Alt-D to deselect all layers, the layers are clearly deselected in the layers view but the graph isn't updated to reflect this. This isn't an issue when pressing the 'Deselect all layers' button

### Steps to Reproduce

1. Create a sphere graph
2. Open layers view and select layer 2 (the graph should disappear)
3. Press Ctrl-Alt-D and notice the graph doesn't reappear
4. Click on the 'Deselect all layers' button and notice the graph reappears

**Expected behaviour:** Changes made using layers view shortcut buttons should be reflected in the graph

**Actual behaviour:** Graph isn't updated when using shortcut to deselect all layers

**Reproduces how often:** 100%

### Additional Information

Related to work done in #725

**Comment by antares1470** [comment]
@aldebaran30701 I've just tested this and it seems that with the new changes made to the Layers View that the opposite is now the problem. i.e. Using Ctrl-Alt-D to deselect all layers will update the graph but pressing the "Deselect All Layers" button does not

**Comment by aldebaran30701** [comment]
I'll get onto this asap, Cheers for testing!

**Comment by antares1470** [comment]
> I'll get onto this asap, Cheers for testing!

Having done some further testing, it would appear that the issue I identified also extends the other parts of the layers view (e.g. layers turning on and off layers doesn't seem to update the graph as expected)

**Comment by aldebaran30701** [comment]
Just wanted to provide an update on this: I'm currently working through some other bugs in the Layers View, which may be related to why it isn't working well with queries.

**Comment by aldebaran30701** [comment]
UPDATE: I've managed to get deselection working as intended for both hotkey and manual deselection button. 
I've currently been working on enabling a layer via a hotkey.
