### ISSUE TITLE
Betweeness Centrality AssertionError

### ISSUE THREAD

**Issue by Nova-2119** [constellation-app/constellation#826]
### Description

Running the Betweeness Centrality analytic can cause an AssertionError

### Steps to Reproduce

1. Open new graph
2. Place two nodes in the graph with one transaction between them using the draw feature
3. Open analytic view
4. Run Betweeness Centrality analytic

**Expected behaviour:** [What you expect to happen]
No error should occur

**Actual behaviour:** [What actually happens]
Error

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

**Comment by cygnus-x-1** [comment]
Tested - no error is thrown for the reproducer, but I did manage to throw an exception by attempting to modify the default parameters (try changing the Aggregation Method, for example).

**Comment by Nova-2119** [comment]
Hey @cygnus-x-1 I am struggling to recreate the error you described, do you remember exactly what you did to cause it?

**Comment by antares1470** [comment]
Was unable to recreate the issue described. If it comes up again, a new ticket can be created
