### ISSUE TITLE
Retain drop down value when switching graphs

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#829]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Currently, single choice parameters are refreshed every time you switch graphs. There are some cases though where it may be preferred to retain the selected value rather than going through and re-selecting the desired choice (e.g. creating a subgraph).

What I propose is that when switching graph, a check should be done for whether the selection in the old graph is available in the new graph and retaining that selection if so

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behaviour:** [What you expect to happen]

**Actual behaviour:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Related to work done in #752

**Comment by aldebaran30701** [comment]
Would this be related to #25 ?
You'd effectively like the `updateParameters()` method to keep the previous selection if one is available? Should this be the default behaviour of all `SingleChoiceParameters` ?

**Comment by arcturus2** [comment]
@aldebaran30701 I see what you mean. Yeah in that case they are almost the same thing. In #25 the focus was retaining the last chosen option when you restart Constellation but I guess switching graphs could utilise the same logic

I think though the difference to my mind was that this ticket was a bug fix to prevent the `SingleChoiceParameter` from resetting to empty.

**Comment by antares1470** [comment]
Done some testing and this doesn't appear to be occurring anymore

**Comment by mimosa2** [comment]
I did some tests on this and couldn't replicate the error. I believe this issue has been fixed.
