### ISSUE TITLE
Basic RDF Support

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#840]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

- Move the RDF Types node attribute into a Type property
- Blank Nodes are currently stored in a Graph attribute. Possibly these could be drawn in the graph, in a separate layer
- OWL inferencing
- Constellation Sail
- After executing any plugin, the newly created graph is drawn on top of the existing graph, in a new layer. This increases the visibility of the actions and the idea was to turn off the previous layers to see only the resulted/inferred data set. This doesn't work properly because currently this removes nodes from previous layers when the same node is drawn in a new layer. Need to fix/improve this as required.
- SPARQLE quering on consty graph
- More items in the scope doc

If possible, (similar to WebVOWL)
- Scalable inferencing level
- Ability to explore schema, by adding hyperlinks, probably in attributes

**Import and implement Types:**
1. Import `constellation.ttl` and  mapping file (E.g.: `example-mapping.ttl`) and populate `SchemaVertexType`  and apply this Type.
2. When no Type  is specified, apply Consty default types (?how) and if they do not map, use `Undefined` or `Unknown`
3. If multiple types are specified, add something similar to `VertexDominanceCalculator `

**Custom node attributes:** 

4. Add the custom node attributes back in the model, in `RDFUtilities.addNodeAttributes` The current version uses `graph.getObjectValue` but it doesn't work on custom attributes because they are stored as strings. 
Add the Predicate IRI as the attribute name and store only the object as a string value. Then we can use `graph.getStringValue` and add a method to generate the Statement back from these and the node's `rdf_identifier` which is the subject. (Complete)
5. Test and verify whether the custom node attributes do not lose data, if multiple attributes present with the same attribute name (same predicatename). This is still needed, because there can be multiple items with a given predicate IRI. E.g., When the  literal is a language-tagged string.
How can we differentiate between the two following descriptors?
```
<rdfs:label xml:lang="en">LaReine</rdfs:label>
<rdfs:label xml:lang="pt">LaReine</rdfs:label>
```

**Transactions:**

6. Resolve transaction Type from RDF Type, probably similar to resolving Node Type
7. Test and verify transaction directions are accurate
8. Add the triples that are specifically categorized as `Transaction` as a Transaction in the graph. (Currently these are also added as a node in the graph) Otherwise, transactions are the predicates of IRI triples. (Current implementation)

**Other attributes**

9. Check whether we can add the `Label` attribute irrespective of the `Identifier` attribute. (In Analytic schema, label is based on the Identifier). If so, add `RDF_Identifier` in the `Identifier` attribute and populate `Label` attribute based on the `Label` triple in the RDF data. Use it's object value as the consty label, and if there's no label associated with it, use the LocalName of the node. (Current value in the `Identifier` attribute) 
10. If 9 works, set `Identifier` attribute as the primary key.  Remove the `RDF_Identifier` attribute and change all the references to use `Identifier` attribute.

**Searching**
1. Search RDF databases from a transaction

**Testing**

1. Add more unit tests
2. Core functionality of plugins
2. Backward compatibility
3. Test other data stores on `Query an RDF Data Store` plugin (Only the DBPedia is tested)

### Additional Information

I think this would need to be implemented in Constellation Adaptors.

**Comment by Auriga2** [comment]
TO DO:

- Move the RDF Types node attribute into a Type property
- Blank Nodes are currently stored in a Graph attribute. Possibly these could be drawn in the graph, in a separate layer
- OWL inferencing

**Comment by Auriga2** [comment]
TO DO in this increment:

1. Import `constellation.ttl` and  mapping file (E.g.: `example-mapping.ttl`) and populate `SchemaVertexType` 
2. Add the custom node attributes to the model in 
2. Resolve transaction Type from RDF Type, probably similar to resolving Node Type
3. Test and verify transaction directions are accurate

**Comment by Auriga2** [comment]
**RDFS Inferencing Plugin**

1. Plugin adds a duplicate set of `RDF_Types` when the plugin is run a second time.

**Comment by GammaVel** [comment]
This issue has been added to the list of brainstorming ideas for future consideration in development tasks.  The existing branch will be kept for reference. Closing for now.
