### ISSUE TITLE
Investigate long term solution for Invisible text appearing in Schema View

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#841]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Following on from the work done in https://github.com/constellation-app/constellation/issues/585, a work around solution was done because all options where exhausted at the time. This task will be to potentially undo the change in PR https://github.com/constellation-app/constellation/pull/836 and identify the root cause.

**Comment by Auriga2** [comment]
Looks good in master-2021-10-11
