### ISSUE TITLE
Levenshtein Distance Single Choice fields resets everytime a graph selection change is made

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#842]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

With the changes made to the single choice parameter type (work done as a part of #768), the single choice parameters in the levenshtein distance are updating/resetting every time a change is made to the graph; including changes to graph selection. This constant updating could be frustrating to users particularly when it doesn't seem necessary such as when changing the graph selection.

An option might be to look at maintaining the selection if it exists when a graph change occurs or (a possibly more difficult change to make) not updating if nothing relevant to the parameter has changed.

### Steps to Reproduce

1. Open a new graph and generate a sphere graph
2. Open Analytic View and select the Levenshtein Distance Analytic
3. Change the selected value in the Compare Attribute parameter
4. Change the selection made in the graph (either deselect everything or make a new box selection)
5. Observe the parameter reset to it's original value

**Expected behaviour:** Single Choice parameter doesn't reset every time a change in graph selection occurs

**Actual behaviour:** Parameter resets every time a change in graph selection is made

**Reproduces how often:** 100%

### Additional Information
Example of this occurring:
![levenshteinupdate](https://user-images.githubusercontent.com/62311243/92433668-1033fe80-f1e1-11ea-928b-25e8cb89f7e8.gif)

A few other things I observed in relation to the bug that might help:
- it may occur in other analytics with single choice parameters (although I didn't test this thoroughly)
- it doesn't seem to occur in other types of parameters in the Analytic view
- it doesn't seem to occur in other views (e.g. Data Access view)

**Comment by Polaris5514** [comment]
Through looking into this I have found that this bug has been there since the initial release and occurs on the aggregation method selection for all of the Category selection in Analytic View, Question Selection seems fine. The parameter reverts back to initial state every time a Transaction is selected/deselected on the graph.
The Aggregation method selection will also throw an IndexOutOfBounds Exception when the change of selection occurs. 
Will continue to look for the source of the parameter revert
