### ISSUE TITLE
Find and Replace search history

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#856]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The Find and Replace plugin's "Find what" text box does not allow the user to recall previous (or subsequent) searches using ctrl+z/ctrl+y

**Expected behaviour:** ctrl-z recalls previous search and ctrl-y recalls next search
**Actual behaviour:** This functionality isn't implemented

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Atlas139mkm** [comment]
I was just looking into this one. Is the intended use for this to simply retrieve the users previous searches? or do we specifically want ctrl + z and ctrl + y? I was thinking if we just want the users previous searches, would a drop down of previous searches be easier to implement and achieve the same outcome potentially in a easier way? 

There isn't too much info on this issue so wanted to get clarification.
@arcturus2 thoughts?

**Comment by arcturus2** [comment]
@Atlas139mkm sorry about the lack of info on this. The functionality would be as per other tools like Word that allow you to undo/redo text in the input text field. I don't think a drop down list is required and the added complexity that could bring. Being able to mimic what other tools do would be good for consistency at this stage.

Let me know if you need any more information.

**Comment by Atlas139mkm** [comment]
@arcturus2 I'm currently looking into extending the JTextField to add some extra functionality with it to undo and redo. I'll try implementing that on a small scale first and if it works well I can work on replacing the JTextFields with the new Custom version that has the better functionality.

**Comment by GammaVel** [comment]
This is handy functionality and I have confirmed it is working on the basic find, find and replace and the advanced find. Some other feedback has gone onto the Find ticket #55 .
