### ISSUE TITLE
Find and Replace enhancements

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#857]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Please add a "Find/Replace in all open graphs" button to the Find and Replace plugin. Similar to the "Add results to current selection" check box, please add options to "Remove results from current selection" and "Delete results from graph".

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by GammaVel** [comment]
The search across all graphs is finding the values on the other graphs that I have open but it is not automatically displaying the graph where the value is present. 

Is it supposed to @antares1470?  

In the below gif I have 3 graphs which all have the same added component which has the value "Sarah". Constellation doesn't show the graph that has the value. I have to manually open it and look for the red highlighted value. If I compare this to excel and searching an entire workbook, it does open the worksheet when you click on Find next if the value is in a new worksheet. 

![FindonAllGraphs](https://user-images.githubusercontent.com/83679004/165415918-960ad4b9-e1d8-445d-b32f-baeeeff94412.gif)

**Comment by GammaVel** [comment]
Hi @antares1470. There is no option to delete from the current selection which was a requirement listed above. Is this acceptable? 
![image](https://user-images.githubusercontent.com/83679004/165418237-ec539506-1cca-48cc-b3bc-de4510951d1d.png)

**Comment by antares1470** [comment]
> The search across all graphs is finding the values on the other graphs that I have open but it is not automatically displaying the graph where the value is present.
> 
> Is it supposed to @antares1470?
> 
> In the below gif I have 3 graphs which all have the same added component which has the value "Sarah". Constellation doesn't show the graph that has the value. I have to manually open it and look for the red highlighted value. If I compare this to excel and searching an entire workbook, it does open the worksheet when you click on Find next if the value is in a new worksheet.

@GammaVel Given that is something you see in Excel (and presumably other apps), I think it makes sense that search all actually switches graphs as you flick through. Maybe I'm naive but I would guess if it is possible to search across all graphs then it would be possible to display the graph a result is in as well. The challenge may be figuring out when to jump to each graph

**Comment by GammaVel** [comment]
Thanks again @antares1470 for your careful consideration of my comments. Based on your feedback I have raised a new enhancement to display the graph automatically - see #1696. I also added a new ticket for an improvement to the Current Selection and Ignore options which will take into account the delete option #1695.
