### ISSUE TITLE
Table View arrange columns bug

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#859]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Reordering columns in the Table view (by dragging and dropping them) does not update the column values and changes which column columns are shown in the Table view. 

e.g. I untick the transaction.Identifier column and then move the transaction.DateTime column to the very left. Now the transaction.DateTime header is shown at the very left but the column values are actually the transaction.Identifier ones. Doing this also seems to remove non-key columns that I had originally selected from the View 

### Steps to Reproduce

See example

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behaviour:** Moving columns around Table view should update the table with new column arrangement

**Actual behaviour:** Column data doesn't always follow the column headers when they are moved

**Reproduces how often:** Sometimes

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by GammaVel** [comment]
I took another look at this and for the most part it is working well however it got into a state where none of the column headings matched the column data, it was all out of sync. The only way I could get it back was to close and restart Tungsten. There is still some issue lingering here.

**Comment by GammaVel** [comment]
This is looking good in the latest nightly build and I am unable to replicate this issue -  I can't replicate the columns getting out of order. I'll close this off and it can be reopened if we see it happening again. Another MR must of fixed this.
