### ISSUE TITLE
Add numeric sort option to Histogram

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#861]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The Histogram View's Sort by Label option is fine for properties whose value is an ASCII string, however numeric values are better suited to a numerical sort function.

Probably best to implement this by offering both sort functions and naming them clearly, such as "Label (string)" and "Label (number)", keeping the string sort as default.

**Comment by arcturus2** [comment]
So attributes that are numbers do the correct thing. The case here is when the property is a String but has numerical values.

**Comment by aldebaran30701** [comment]
The old table view is still kept around because it currently works well for numeric sort. Worthwhile checking that out if we need ideas on how to implement into the new table view and also the histogram.

**Comment by GammaVel** [comment]
Thanks @Atlas139mkm on making this update so now I can sort by number values on the Histogram view. It is good how there are now two options to sort by number or text. Thank you!!!
