### ISSUE TITLE
Simpler Attribute Descriptions

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#863]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Attribute descriptions currently have a long list of methods for setting and getting them as various primitive types. Not only is this a messy API but also means there are a number of available operations that simple throw UnsupportedOperationExceptions.

A prototype system for simplifying attribute descriptions has been developed which allows attribute values to be set and retrieved as their native type with a single method, both primitive and object values.

This prototype system needs to be integrated into the application, which would likely involve a change to the graph framework itself and hence also require a large body of testing.

**Comment by GammaVel** [comment]
Closed for now. Has been added to Brainstorming ideas.
