### ISSUE TITLE
Improve help in the Analytic View

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#865]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Suggested the Analytic view help could appear similar to the DAV or Schema View
- Could include pre-requisite information of how the graph should be structured before running some analytics
- The help documentation could include example graph diagrams to help explain how they work
- Some of the help documentation is still too technical

**Comment by aldebaran30701** [comment]
Closing this as it duplicates #340 
All info necessary has been transferred into that ticket.
