### ISSUE TITLE
Composite nodes version 2

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#867]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

We've identified issues with composite nodes on large graphs (especially those with a lot of transactions) and unexpected behaviours when you copy composite nodes between graphs.

The existing version will remain an experimental feature with a plan to create a newer version from lessons learned. Re-writing is the way to go because trying to fix the issue created other problems.

With the current implementation the approach was to go with a "light" implementation which means it didn't affect the structure of the core graph. This has created limitations so with the new version we will be creating a composite node element on the graph which will require an update to the schema.

**Comment by arcturus2** [comment]
Until composite nodes gets used in anger I'm tempted to close this and move it to the wiki backlog.

**Comment by aldebaran30701** [comment]
Closing this ticket and adding to the Brainstorm Ideas List.
Large ticket, where the current implementation does work, just not well for large compositions. This can get reopened if there is a specific need to completely review the current composite implementation.
https://github.com/constellation-app/constellation/wiki/Brainstorm-Ideas
