### ISSUE TITLE
Support for different languages (localisation)

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#868]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Providing support for different languages in Constellation.

NetBeans supports localisation and uses Bundle.properties files to implement this. Localisation was not considered part of the plugins being developed so there are hard coded strings that should be put into the Bundle.properties files.

**Comment by aldebaran30701** [comment]
Closing as there is a heap of work to revert all variables in text to bundle.properties files. English currently is the only and main supported language. Added to the brainstorming ideas wiki page.
https://github.com/constellation-app/constellation/wiki/Brainstorm-Ideas
