### ISSUE TITLE
Compare graph transactions are sometimes the wrong colour

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#872]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

When comparing two graphs, sometimes transactions are not the colour indicated by the compare graphs schema (that appears when you select compare graphs). It looks like for some transaction types the colour is being overwritten by the default for that transaction type.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behaviour:** Transactions are the colour indicated by compare graphs

**Actual behaviour:** Transaction colours are being overwritten by the transaction type colour

**Reproduces how often:** ???

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by sol695510** [comment]
@antares1470 I've had no luck replicating this issue. Is there any further information that may help?

**Comment by antares1470** [comment]
> @antares1470 I've had no luck replicating this issue. Is there any further information that may help?

@sol695510 I'll see if I can get a reproduce for you

**Comment by antares1470** [comment]
So after a bit time trying to get a reproducer, I couldn't get one. The closest I got was with comparing two identically created sphere graphs (so the only differences were icons, labels, normalised values, etc). All the transactions were grey but only some of them were indicated as such in the overlay_color attribute (the others had no value for that attribute). That might be a different bug though

**Comment by aldebaran30701** [comment]
I made a new graph, built a default sphere graph.
I then copied the whole graph to a new graph.
I then added a transaction and vertex.
I then compared the graphs, and added transactions were specified to be displayed as green.
Upon comparing, they were green, as intended.

I did not find any issue with this, on multiple attempts.
