### ISSUE TITLE
Hide data access view categories

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#875]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Data Access view categories such as "Developer" do not need to be visible by default. Make hiding these categories a preference that can be changed from Setup -> Options

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by GammaVel** [comment]
This new functionality is super handy, thanks for implementing it @mimosa2 !  it is working really well at hiding categories I am not interested in during my graph data analysis. 
I had a couple of new small enhancements where I thought it could be even better - #1680 , #1681 and #1682 . Just some small suggestions for improvement.

**Comment by mimosa2** [comment]
Thanks @GammaVel for the testing and review. Great enhancement ideas.  They are very useful.
