### ISSUE TITLE
Explore graph interaction performance improvements

### ISSUE THREAD

**Issue by Nova-2119** [constellation-app/constellation#878]
### Description
This is a broad ticket designed to capture attempts at improving performance when interacting with the graph. This includes dragging nodes, zooming and panning/rotating.

As we are not sure where performance gains are to be had this tickets will be exploratory in nature and includes looking for performance improvement opportunities and implementing them.

**Expected behaviour:** [What you expect to happen]
There should be minimal lag when interacting with the graph.

**Actual behaviour:** [What actually happens]
There is a noticeable lag when interacting with the graph. This is most noticeable for large graphs, however it can still be observed on even relatively small graphs.

**Comment by Nova-2119** [comment]
Have made two changes so far to improve performance of dragging nodes.

The first change is a change to gatherSelectedNodes to use a vertexStream when obtaining a list of selected vertexIds. This is one of the slower method calls when dragging nodes and this increases its performance a noticeable amount as shown below:
Original:
![image](https://user-images.githubusercontent.com/66700235/97372201-fbcbd280-1902-11eb-80f0-1767927d4328.png)

With modification:
![image](https://user-images.githubusercontent.com/66700235/97372239-143bed00-1903-11eb-91d4-dbe5239b2747.png)

Account for the different number of invocation you can see that it originally took just shy of 500ms on average but now takes just under 200ms on average.

**Comment by Nova-2119** [comment]
The second is to change the argument of scheduleXYZChangeOperation to an integer array of the selected nodes (and hence the nodes that have moved) instead of the number of nodes. This changes the processing in SceneBatcher.updateBufferTask so that it only updates for nodes that have moved instead of every node. This makes the performance of dragging nodes less dependent on the size of the graph and more dependent on the size of the selection.
The difference can be seen below:
Original:
![image](https://user-images.githubusercontent.com/66700235/97374402-1f454c00-1908-11eb-812d-072397e13422.png)

With Modification:
![image](https://user-images.githubusercontent.com/66700235/97374359-06d53180-1908-11eb-8757-8963a74dd24a.png)

**Comment by Nova-2119** [comment]
Both of the examples above were captured using a graph of 300,000 nodes with 30,000 nodes being dragged.

**Comment by arcturus2** [comment]
@Nova-2119 can you create a PR for the above fixes please?

**Comment by Nova-2119** [comment]
DefaultInteractionEventHandler.gatherSelectedNodes now uses a vertexStream for improved performance. I tried using a parallel stream but opertaions down the stack are not threadsafe, in particular the whole undoGraphEdit framework is not threadsafe.

getMixedVertexCoordinates and setMixedVertesCoordinated now have a version with input parameters for the various attribute ID's required so that these are retrieved once instead of multiple times. The operation to get the id of an attribute type is quite expensive and was being performed hundreds of thousands of times for large selections.

**Comment by Nova-2119** [comment]
![image](https://user-images.githubusercontent.com/66700235/98610885-9cc57f00-2340-11eb-9c22-f206960ea359.png)
Profile of dragNodes - Look at the cpu time for setFloatValue and getFloatValue. Sure there are alot of invocation but thats a product of a large selection, not much we can do about that.

**Comment by Nova-2119** [comment]
Moved onto examining potential improvements to zoom responsiveness.

**Comment by Nova-2119** [comment]
Zooming is essentially performed by DefaultInteractionEventHandler.mouseWheelMoved. As thise method does not run when called, and instead the body is added to queue to be called later I moved the vast majority of the body into its own method called actionWheelMoved so that this is called from queue when the zoom is actioned. I did this so that I could profile it easily (profiling mouseWheelMoved would have been pointless).

Below is part of the initial profile when zooming in on a 300,000 node graph:
![image](https://user-images.githubusercontent.com/66700235/98756897-5b55d200-241b-11eb-853c-84f5563a3cd5.png)
As you can see the method InteractiveGLVisualProcessor.closestNodeCameraCoordinates takes up almost all of the actual and cpu time.

**Comment by Nova-2119** [comment]
I have hence refactored closestNodeCameraCoordinated in an effort to speed it up. I have refactored it to take advantage of parallel streams and the built in reduce method.

Here is part of the profile when zooming on a 300,000 node graph after the refactor:
![image](https://user-images.githubusercontent.com/66700235/98757180-e33bdc00-241b-11eb-94e8-f5dfa651e453.png)

It is of course an imperfect art attempting to get two roughly equal zooms across profiling runs. However you can see that even adjusting for the number of invocation it is quicker than previously.

**Comment by Nova-2119** [comment]
Creating a comparison gif is difficult as you cannot see the scrolling input and variations in scrolling speed mean getting a true like for like comparison is prohibitively difficult.

However when doing a back to back test their was a noticeable improvement in responsiveness.
