### ISSUE TITLE
Change calls to getActiveGraph within plugins

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#882]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
A need has arisen from multiple bugs and undefined behaviour from using getActiveGraph within the executed plugins. This is to be solved by actually running the plugin on only one graph. There is a structure available that you can get the graph you want via the graphmanager.getdefault() manager. This will require the graph id to fetch the graph object.

Fixing this fundamental issue will alleviate the below issue and also ones relating to long data access view plugins running on different graphs. 

Below is the original issue.
------------------------------------------------------------------------------------------------
If you generate a graph while also waiting for another, it will render both onto one graph.
I'd say due to how hard it is to reproduce during normal operation that it is not a high priority, but has the potential to occur possibly even with importing data into a graph.

I followed the steps below quickly.
open new graph -> generate structured graph builder (1000) backbone size
open new graph -> generate sphere graph (10000)
open new graph -> generate sphere graph (1000)
While it was all trying to load, I switched between graphs and while it happened to try and load the sphere, I was on the structured graph. It loaded those elements onto that graph instead of the sphere graph.
See the below gif for the behavior

**Expected behaviour:** Sphere graph to display on graph 2

**Actual behaviour:** Sphere graph generates all on 0,,0,0 in graph 1.

**Reproduces how often:** 100%
### Additional Information
N/A

**Comment by antares1470** [comment]
My gut would say (without looking at the code) that there may be a call to `getActiveGraph()` that might be resulting in this behaviour

**Comment by aldebaran30701** [comment]
Tested, seems to be no issues from the #1524 PR. 
This ticket could include a closer look at things like the chaining of plugins. Where the `.getActiveGraph()` may be used for things like running arrangements after plugins are executed.
