### ISSUE TITLE
NullPointerException when importing from delimited file and quickly changing the Import File Parser option

### ISSUE THREAD

**Issue by sol695510** [constellation-app/constellation#886]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

A NullPointerException occurs when you quickly change the Import File Parser option from the dropdown menu after opening the component for importing from delimited file.

### Steps to Reproduce

1. Open clean build of Constellation.
2. File > Import > From Delimited File...
3. Select any other option from the dropdown menu for Import File Parser.

**Expected behaviour:** Any new Import File Parser option is selected without a NullPointerException occurring.

**Actual behaviour:** NullPointerException occurs.

**Reproduces how often:** 100%

### Additional Information
The issue lies in RunPane.java at the top of the constructor at line 140, where the thread is not being returned in time for the dropdown menu and so a NullPointerException occurs.

![image](https://user-images.githubusercontent.com/58677774/98205818-bd7c8600-1f88-11eb-8886-1fa9e08c22d7.png)

(GIF of issue being reproduced will be added here)

**Comment by serpens24** [comment]
@arcturus2  - as discussed, the problem relates to the changes made in https://github.com/constellation-app/constellation/pull/847

What is occuring is that in some cases if you start trying to import a file using the dialog too soon the rowFilter member has not yet been set.

It may be worth backing out this change for the time being ?

**Comment by arcturus2** [comment]
@serpens24 I'm OK if you want o back out the change then and we can investigate option 2 a bit more as there may be a better fix than what I came up with.

**Comment by serpens24** [comment]
Theres no basis for this as yet, other than several tickets loosely related to delimited file import perofrmance, but is this ticket in any way related to: https://github.com/constellation-app/constellation/issues/1426

**Comment by Auriga2** [comment]
Looks like this is the same issue as https://github.com/constellation-app/constellation/issues/968 and fixed now by the last line in 9460eb8
