### ISSUE TITLE
Scope select all (ctrl+a) to UI element in focus

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#888]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Even when the cursor shows up in a particular UI element, such as a text field in the Data Access View or Histogram, pressing ctrl+a selects all nodes and transactions in the graph. Properly scoping the select all function to just the element in focus would make it faster to copy/paste data into and out of Constellation.

### Steps to Reproduce

1. Create a new graph with a few nodes and transactions
2. Open Data Access View
3. Place the cursor in any string plugin parameter and type a few characters
4. Press ctrl+a

**Expected behaviour:** Ctrl+a only highlights everything in the current scope (in this case, the string parameter)

**Actual behaviour:** Ctrl+a highlights everything in the current scope as well as everything in the graph

**Reproduces how often:** 100%

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by sol695510** [comment]
@antares1470 Confirmed this also occurs in Attribute Editor and Conversation View. I resolved it in Conversation View by using an event filter to consume the event, and then manually perform a select all on any text in the text element. 

`editTranslationArea.addEventFilter(KeyEvent.KEY_PRESSED, e -> {`
`if (e.isShortcutDown() && e.getCode() == KeyCode.A)) {`
`e.consume();`
`editTranslationArea.selectAll();`
`}`

**Comment by sol695510** [comment]
This behaviour only occurs when you first open the graph and doesn't seem to happen after deselecting and then subsequent ctrl+a presses.

![ctrl+a bug](https://user-images.githubusercontent.com/58677774/109921823-5ab7b300-7d0c-11eb-9ea8-d5d8f4c78521.gif)

**Comment by antares1470** [comment]
> This behaviour only occurs when you first open the graph and doesn't seem to happen after deselecting and then subsequent ctrl+a presses.

I too got this when testing purely in Core. When I added the Adaptors module suite on top of that though, I started seeing it happen every time ctrl-a is pressed (even in subsequent ctrl-a presses)

**Comment by sol695510** [comment]
My proposed solution to this issue is to not use the program wide shortcut but instead execute the the select all plugin from a key listener on the graph listening for ctrl+a.

The problem is I am not sure where to place this key listener. I've tried implementing them in GraphNode.java, SimpleGraphTopComponent.java, FrameworkGraphManager.java, GraphDisplayer.java and GraphRenderable.java but none of them trigger the listener at all.

The attempts are on this branch: https://github.com/constellation-app/constellation/tree/bugfix/Scope-select-all-to-UI-element-in-focus-%23888 

@antares1470 @cygnus-x-1 do you have any ideas what I can do here?

**Comment by antares1470** [comment]
> My proposed solution to this issue is to not use the program wide shortcut but instead execute the the select all plugin from a key listener on the graph listening for ctrl+a.
> 
> The problem is I am not sure where to place this key listener. I've tried implementing them in GraphNode.java, SimpleGraphTopComponent.java, FrameworkGraphManager.java, GraphDisplayer.java and GraphRenderable.java but none of them trigger the listener at all.
> 
> The attempts are on this branch: https://github.com/constellation-app/constellation/tree/bugfix/Scope-select-all-to-UI-element-in-focus-%23888
> 
> @antares1470 @cygnus-x-1 do you have any ideas what I can do here?

Have you removed (or are you able to remove) any existing listener on ctrl+a? If not, chances are that regardless of where you put the listener, that other listener will still be triggered and execute alongside any listener you come up with (I'm not sure exactly whether this is what you're seeing but I encountered something similar to this working on #757)

**Comment by arcturus2** [comment]
@sol695510 have you tried `VisualGraphTopComponent`, `JavaFxTopComponent` and `SwingTopComponent` ? The `VisualGraphTopComponent` is the Top Component for the analytic graph and the other 2 Top Components are used by the various views.

I am not a fan of adding the `KeyListener` to the `GraphNode` though but if you are doing it a test then that is fine. The `GraphNode` is the bridge between NetBeans and the Constellation frameworks and I'd like to keep that as lean as possible. Let me know how you go.

**Comment by aldebaran30701** [comment]
#342 is a close relation to this.

**Comment by GammaVel** [comment]
This is working really nicely now,  thank you for fixing it @OrionsGuardian.  It is great it turned out to be a simple fix in the end.
