### ISSUE TITLE
Results from some analytics not appearing in analytic view

### ISSUE THREAD

**Issue by Nova-2119** [constellation-app/constellation#895]
### Description

Results from the analytics in the "Has Closest Relationship?" question do not appear in the analytic view after running.

### Steps to Reproduce

1. Open a graph
2. Open analytic view
3. Select any of the analytics under the question "Has closest relationship"
4. Run with default arguments
5. Observe that the view reports no results although results are visible on transactions in the attribute editor

**Expected behaviour:** [What you expect to happen]
Results appear in the analytic view, or their is a disclaimer stating that results are not expected to appear in the analytic view.

**Actual behaviour:** [What actually happens]
Analytic view reports no results. This implies that results should appear here and that none were calculated, this is not true.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

**Comment by GammaVel** [comment]
This was looked at this with version 2.3 and the analytic view is returning results, there is a lag which is covered by a separate bug. Updating issue to be done.
