### ISSUE TITLE
Table View issues

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#902]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Some issues have been identified with the table view:
1) When in Selection only mode, Export to CSV/Excel (Selection) only exports the last selected row
2) When selecting rows in the table view, you lose the selection you have as soon as you try select another row on another page (even when holding down Ctrl key)

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behaviour:** Export selections from table view as expected and selections persist across pages

**Actual behaviour:** Above issues

**Reproduces how often:** 100%

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by cygnus-x-1** [comment]
I've tested the pagination issues mentioned during our last catch-up, and had a general play with the Table View. I didn't find any bugs and really like how pagination has been implemented!
