### ISSUE TITLE
Timeline summary pane is sometimes not visible

### ISSUE THREAD

**Issue by cygnus-x-1** [constellation-app/constellation#910]
### Description

The summary pane in the Timeline appears to have a max size set, which means when the Timeline is resized to a small enough size, it can force the summary pane to completely closed to the point it no longer looks like it exists. This is a problem in cases where the Timeline is initialised at such a small size as it's impossible to tell that the summary pane exists.

### Steps to Reproduce

1. Open the Timeline, ensuring you can see the summary pane.
2. Slowly resize the Timeline, making it narrower on the y-axis and observe the summary pane disappear... tada!

**Comment by aldebaran30701** [comment]
Confirmed, here are some pictures that show what I believe to be the issue above.

Arrow 1 is the top of the menu for Timeline View (Half-hidden)
Arrow 2 is the start of the summary pane becoming covered up. The grey bar slowly creeps up higher to eventually completely cover the summary pane as it is scaled down vertically.
![image](https://user-images.githubusercontent.com/58677759/101556569-17022580-3a0b-11eb-80ea-59e19f670ad1.png)

Below is what occurs when the timeline view is scaled to just the wrong size. It makes the view unusable at that size.
![image](https://user-images.githubusercontent.com/58677759/101556439-c5599b00-3a0a-11eb-820e-708d4fd25266.png)

**Comment by arcturus2** [comment]
umm...I merged this before testing it and when I did test it in `master` i get this @Delphinus8821 

![issue with timeline preview](https://user-images.githubusercontent.com/39325530/108008254-1497f980-7054-11eb-902f-8eb71b959109.gif)
