### ISSUE TITLE
Change cursor when Draw Mode is enabled

### ISSUE THREAD

**Issue by sol695510** [constellation-app/constellation#921]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

It would be useful to have the cursor change to reflect that "Draw Mode" has been enabled/disabled, especially when switching between graphs that have it toggled on/off or using the shortcut to activate/deactivate it.

### Additional Information

CoreInteractiveGraph\src\au\gov\asd\tac\constellation\graph\interaction\plugins\draw\MenuSetDrawModeAction.java

CoreVisualGraph\src\au\gov\asd\tac\constellation\graph\visual\utilities\VisualGraphUtilities.java

**Comment by GammaVel** [comment]
This is a really nifty improvement, thanks for fixing it @Centauri0320001. This was always one thing that I found confusing and it is much easier to know when you are in draw mode now.
