### ISSUE TITLE
Analytic View Aggregation method initially has incorrect list of options to pick from

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#926]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

By default Analytic View opens up with the "Connects the Network Best?" question selected. When you first open it up, the Aggregation method drop-down is incorrectly populated with a number of options that aren't available for the question. This is corrected after another question is selected (with only one option) but really this should be correctly populated from the start.

### Steps to Reproduce

1. Open Analytic View
2. Observe Aggregation method drop-down list (unexpected list)
3. Select a different question and back again and observe only one option available in drop-down (expected list)

**Expected behaviour:** Aggregation method drop-down is populated with only one option for "Connects the Network Best?" question

**Actual behaviour:** Initially, the aggregation method drop-down is populated with other options that aren't available for the question

**Reproduces how often:** 100%

**Comment by aldebaran30701** [comment]
I've done some digging into this, but have not been able to get to the bottom of it. 
What I have found is that it happens some time during the first or second selection of a different question. The most recent thing I was investigating was the UpdateParameters() method - which I had a suspicion of it clearing all of the other possible options to select.

I've decided to switch gears and take a look at another issue in the meantime.

**Comment by arcturus2** [comment]
Does this happen in v1?

**Comment by Delphinus8821** [comment]
In version 1.3.1 the aggregator method drop down is greyed out for all questions. 

![Version 1 3 1 Aggregator](https://user-images.githubusercontent.com/73083035/106834957-533dc380-66e6-11eb-8402-1b285551db22.PNG)

**Comment by Delphinus8821** [comment]
Version 2.0.0 only has one option available in the aggregation method drop down for all of the questions.

**Comment by antares1470** [comment]
Doing a quick dig I found this in `AnalyticConfigurationPane.updateGlobalParameters()`:
```
final List<AnalyticAggregatorParameterValue> aggregators = new ArrayList<>();
...
} else if (questionListPane.isExpanded() && currentQuestion != null) {
    final Class<? extends AnalyticAggregator<?>> questionAggregatorType = currentQuestion.getAggregatorType();
    aggregators.add(new AnalyticAggregatorParameterValue(AnalyticUtilities.lookupAnalyticAggregator(questionAggregatorType)));
    SingleChoiceParameterType.setOptionsData(aggregatorParameter, aggregators);
    SingleChoiceParameterType.setChoiceData(aggregatorParameter, aggregators.get(0));
}
```

`AnalyticUtilities.lookupAnalyticAggregator()` only returns one aggregator so in when a question is selected, you are only ever going to have a list of one to pick from (there is a `AnalyticUtilities.lookupAnalyticAggregators()` which is called when a category is selected). This means that either 1) It is incorrect to call `lookupAnalyticAggregator()`, or 2) The original drop-down that is available when you first load Constellation is incorrect (i.e. the one item drop-down list is correct). I'm not sure I have the answer to that right now though

**Comment by antares1470** [comment]
It appears that having one option for the question dropdown is expected and therefore the actual bug is the initial drop-down list having options to select from (when there should only be one). Updating the ticket accordingly

**Comment by Nova-2119** [comment]
The only methods that update the available aggregators are createGlobalParameter and updateGlobalParameters. If we chuck a debug in these and open the analytic view we can see that on initial opening both createGlobalParameters and updateGolbalParameters are run. 
Interestingly if you follow it through you can see that when you initially open the  analytic view updateGlobalParameters believes that the categoryListPane is expanded even though it view starts with the questionListPane expanded. This behaviour only occurs on initial opening, afterwards it correctly knows which of the panes is open.

Therefore I have set categoryListPane.expanded to be false upon creation. This seems to have fixed the issue :)


However it may be worth noting that updateGlobalParameters is called multiple times....kind of feel like it should only be called once. I wonder if its tied to the performance issues with the pane.
