### ISSUE TITLE
Migrate to GitHub Actions

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#929]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Our build pipeline has stopped working since December. Look at moving to GitHub Actions.

**Comment by serpens24** [comment]
Some code coverage inclusion issues arecaptured in this ticket: https://github.com/constellation-app/constellation/issues/998
