### ISSUE TITLE
Export to JDBC

### ISSUE THREAD

**Issue by cygnus-x-1** [constellation-app/constellation#938]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Now that we have the Import from JDBC plugin, we should offer an equivalent Export to JDBC plugin. This could allow users to back-up their graphs to the database of their choice.

**Comment by aldebaran30701** [comment]
@cygnus-x-1 Did you have any extra info for this ticket? Just questioning the need to export data other than to have an inverse action for importing :D

**Comment by cygnus-x-1** [comment]
I don't know that we have a specific requirement for it - but the experimental JDBC importer also came with an exporter. At the very least it might be handy to save a graph to SQLite, like to can save to CSV.
