### ISSUE TITLE
Select on graph in Conversation View no longer working

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#939]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

In v2 it looks like the context menu to select a conversation on the graph no longer works in the Conversation View. I'd checked and it does work in v1. Graph is attached and see the gif of how it should work in v2.

![show on graph in conversation view](https://user-images.githubusercontent.com/39325530/104551908-dd68ae00-568b-11eb-9097-2c45de0a8eef.gif)

Note that `TextConversationContributionProvider` is the class that adds the context menu, its running but I'm not able to figure out why its not working.

### Steps to Reproduce

1. Open the `conversation example.star`
2. Open the Conversation View
3. Select "Vertex #0" on the graph
4. Right click on the conversation

**Expected behaviour:** [What you expect to happen]
An option should exist with a "Show on Graph"

**Actual behaviour:** [What actually happens]
The "Show on Graph option is missing

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Additional Information

If you want to test in v1 and don't have a copy then go to https://github.com/constellation-app/constellation/releases/tag/v1.3.1 and download it

**Comment by sol695510** [comment]
@arcturus2 I believe I've restored the functionality on the branch linked below for issue #887.
https://github.com/constellation-app/constellation/tree/conversation_search_option
