### ISSUE TITLE
"Submit a Ticket" opens wrong URL

### ISSUE THREAD

**Issue by nhairs** [constellation-app/constellation#95]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description
Appears that `Submit a Ticket` points to old `data61` GitHub account, not `constellation-app` account.

### Steps to Reproduce
1. On main toolbar
2. `help` -> `Submit a Ticket`
3. Have browser window open.

**Expected behaviour:**
Open new browser window/tab to the location: `https://github.com/constellation-app/constellation/issues/new` (or equivalent)

**Actual behaviour:**
Redirect to `https://github.com/data61/constellation` which returns 404.

**Reproduces how often:**
4/4 (100%)

### Additional Information
Note - using version available on website (https://www.constellation-app.com/download)
```
Product Version: CONSTELLATION_CORE 201705191307
Java: 1.8.0_212; OpenJDK 64-Bit Server VM 25.212-b04
Runtime: OpenJDK Runtime Environment 1.8.0_212-b04
System: Linux version 4.15.0-47-generic running on amd64; UTF-8; en_AU (constellation)
```
[SupportPackage-null-2019-08-18-16-30-24.zip](https://github.com/constellation-app/constellation/files/3512748/SupportPackage-null-2019-08-18-16-30-24.zip)

**Comment by arcturus2** [comment]
@nhairs good pickup, ill get this fixed.
