### ISSUE TITLE
Histogram filter on selecting in Link mode

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#952]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Filtering in the histogram in **Link** mode causes a null pointer. Refer to gif for a reproducer.

![histogram filter on selection null pointer](https://user-images.githubusercontent.com/39325530/106090797-1e2df000-617f-11eb-9535-4717e7540ae7.gif)

```
java.lang.NullPointerException
	at au.gov.asd.tac.constellation.views.histogram.HistogramFilterOnSelectionPlugin.edit(HistogramFilterOnSelectionPlugin.java:69)
	at au.gov.asd.tac.constellation.plugins.templates.SimpleEditPlugin.describedEdit(SimpleEditPlugin.java:207)
[catch] at au.gov.asd.tac.constellation.plugins.templates.SimpleEditPlugin.run(SimpleEditPlugin.java:115)
Caused: java.lang.RuntimeException
	at au.gov.asd.tac.constellation.plugins.templates.SimpleEditPlugin.run(SimpleEditPlugin.java:135)
[catch] at au.gov.asd.tac.constellation.graph.node.plugins.DefaultPluginEnvironment.lambda$executePluginLater$0(DefaultPluginEnvironment.java:129)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Steps to Reproduce

1. Open a graph with a transaction
2. Histogram -> Link mode
3. Select an attribute (e.g. Source Node Attribute)
4. Select the bar in the histogram
5. Click on the Filter on Selection button

**Expected behaviour:** [What you expect to happen]
The histogram should show the highlighted bars

**Actual behaviour:** [What actually happens]
Error 😞 

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

**Comment by serpens24** [comment]
the 'parameters' parameter passed into the edit method is null which triggers the error on line 69 when trying to calculate elementType.

**Comment by serpens24** [comment]
OK, so the issue basically is that when HistogramTopComponent.filterOnSelection() is called, a cal is made to setObjectValue which triggers the following call stack:

![image](https://user-images.githubusercontent.com/58677108/106418485-5480ad80-64a6-11eb-8e24-acef8d836a0b.png)

In setChoiceData, this.options contains two values: "Node" and "Transaction (no merging)" , for the case in question the passed in choice value is "Link" - this doesnt match any available choices so this.choice is never set.
For successful cases, ie - Node a match is found and the value set.

**Comment by serpens24** [comment]
As a test of the above assertion, I added the lines: 
        elementTypes.add(new ElementTypeParameterValue(GraphElementType.EDGE));
        elementTypes.add(new ElementTypeParameterValue(GraphElementType.LINK));

to HistogramFilterOnSelectionPlugin.createParameters(). This change has removed the exception that is occuring but the filter is not doing anything. I suspect HistogramFilterOnSelectionPlugin.edit may now need to be revised to handle these potential new elementType values. Will investigate how this works now.
