### ISSUE TITLE
Convert JDBC Import Connector to Top Component Framework

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#956]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
As done previously with the Import Delimited, #806 
For consistency, the JDBC import connector should be also switched to use the framework.

Changes in #806 will allow a similar approach to be taken during work for this ticket.

**Comment by GammaVel** [comment]
@aldebaran30701 to check for merge conflicts.
