### ISSUE TITLE
Scroll to search result in Conversation View

### ISSUE THREAD

**Issue by sol695510** [constellation-app/constellation#958]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Add functionality where the conversation automatically scrolls to the position of the first result of the given search if it is not already visible in the pane.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by GammaVel** [comment]
It would also be great to be able to click next for any subsequent search results, similar to what happens in excel and word.

**Comment by mimosa2** [comment]
Tested and found working fine.
