### ISSUE TITLE
Notes View enhancements

### ISSUE THREAD

**Issue by sol695510** [constellation-app/constellation#959]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Some enhancements to implement into the current version of the Notes View:

- ~~Should be very selective about which types of plugins are recorded. There's no real benefit to capturing every selection that is made, but there probably is when it comes to adding/deleting elements, for example. The plugin reporter already provides the ability to tag plugins, could make use of this (and presumably update plugin tags to suit).~~
- ~~The edit/delete buttons take up a lot of space on manual notes, could be moved to the header line, or only appear on hover or something similar to reduce clutter.~~
- ~~Manual notes support HTML or Markdown for a bit more expressiveness.~~
Moved to new ticket #1754 
- ~~Similarly, also the ability to customise the colour of each note.~~
Moved to new ticket #1760 
- ~~The UI for creating a new note takes up a lot of space on the pane that could be used to view more notes, suggest moving the create a new note functionality to a pop-up window.~~
Covered in a new ticket #1762
- ~~The UI for the notes themselves are bigger than needed, so not as many notes are visible at a given time. Resolve this by reducing how the information on each note is displayed.~~
Covered in a new ticket #1762

### Additional Information

Crossed out have been addressed to some degree in other tickets.

**Comment by GammaVel** [comment]
Suggestion to move the Edit/Remove buttons to the top of the Notes as they can be hard to find when they are in the middle of a long note, also ability to navigate between notes.

**Comment by sol695510** [comment]
> Suggestion to move the Edit/Remove buttons to the top of the Notes as they can be hard to find when they are in the middle of a long note, also ability to navigate between notes or add in a time based filter.

Edit/Remove suggestion adressed in #1762 
Time-based filter suggestion addressed in #1761

**Comment by sol695510** [comment]
All enhancement suggestions in this ticket have been covered or moved to new tickets.
