### ISSUE TITLE
Layers View Usability Improvements

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#970]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

From review of the layers view, it appears that there are some refinements that need to be made so it is user friendly.

1. The ability to delete a layer. (Reduces the clutter of the view when many layers are not needed)
2. Make keyboard shortcuts more obvious. (deselecting all layers (ctrl+alt+d) and toggling layers (ctrl+alt+1-9) Creating a new layer (Ctrl+alt+L) Could possibly be tooltips, hint panel ?)
3. Increase Query Error Visibility. (Direct quote from https://github.com/constellation-app/constellation/issues/223#issuecomment-762569337 - The query language is a little obtuse. My first query (transactions - Identifier startswith 2) caused a hash error popup as i'd not surrounded a number in quotation marks. There were also queries i just couldn't get to work (dim == 'true' gave me "ExpressionException: Unable to find implementation of operator: EQUALS"). There should be validation applied before attempting to execute the query, and the result of that **should be visible to the UI (a red box to say my query is broken)**.)

### Steps to Reproduce

N/A

### Additional Information

#223

**Comment by GammaVel** [comment]
Thanks for making all the improvements @aldebaran30701, I am enjoying how the new layers are working and it is great I can delete layers. There was an issue with deleting layers when no graph was open, I have submitted a ticket for this #1334.
