### ISSUE TITLE
Create custom attribute dialog pops under main window on Linux v2.1.1

### ISSUE THREAD

**Issue by mckeowbc** [constellation-app/constellation#977]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

On the Linux version of v2.1.1 when trying to import from a delimited file, the + buttons to add a new custom attribute brings up the dialog behind the main window. This requires moving the window each time to find the dialog.  Additionally in the Ubuntu 20.10 window manager you cannot Alt-Tab to these dialogs.

### Steps to Reproduce

1. Open Constellation
2. Select File->Import->From Delimited File...
3. Add a source file
4. Click on one of the + buttons under attributes to attempt to create a custom attribute.

**Expected behaviour:** Dialog box appears above main window

**Actual behaviour:** Window pops behind main window

**Reproduces how often:** 100%

### Additional Information

OS: Ubuntu 20.10

[SupportPackage-mckeowbc-2021-02-18-16-26-34.zip](https://github.com/constellation-app/constellation/files/6005984/SupportPackage-mckeowbc-2021-02-18-16-26-34.zip)

**Comment by aldebaran30701** [comment]
I'm yet to test if this is an issue with windows, but am working on similar code and it looks like the `NewAttributeDialog.java` class calls `initOwner(...)` with the parent window. 
There may be a call to something that isn't correct for Linux or the call to get the parent window is not correct.
Another option which may be worth pursuing is to set the modality using `initModality()` to `Modality.APPLICATION_MODAL` which  may cause the focus to be on that window even when the parent window is not set correctly.

**Comment by aldebaran30701** [comment]
UPDATE: Tested on Windows using NetBeans debug to launch, the dialog initially pops up on top of the window, but it is not appearing to be modal as you can select Constellation behind it. The .executable version of Constellation also displays the same behaviour.

**Comment by aldebaran30701** [comment]
@mckeowbc Are you able to test out #1020 to verify that it solves the problem you have experienced?

**Comment by arcturus2** [comment]
@aldebaran30701 @mckeowbc I gave it a test and I can see the dialog is opening behind Constellation but one time it came at the front.

![add dialog opening behind](https://user-images.githubusercontent.com/39325530/116927013-70127480-ac9e-11eb-8ea5-4c9967786361.gif)

**Comment by aldebaran30701** [comment]
@arcturus2 you tested master, or the bugfix branch ?

**Comment by arcturus2** [comment]
@aldebaran30701 that was on the bugfix branch.

**Comment by GammaVel** [comment]
Hi @mckeowbc. Thank you for reporting this issue. It is fixed now, if not simply let us know and we will look into it.
Cheers,
Gamma

**Comment by arcturus2** [comment]
Hi @mckeowbc this should make it into v2.9 and it is currently in our nightly build if you wanted to run it from https://github.com/constellation-app/constellation/actions/workflows/nightly-build.yml. Thank you again for reporting this and if you find any more issues please report them.
