### ISSUE TITLE
Opening conversation view locks up v2.1.1

### ISSUE THREAD

**Issue by mckeowbc** [constellation-app/constellation#978]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Shortly after opening the Conversation View panel the entire app  locks up.

### Steps to Reproduce

1. Open the Cornell_Movie-Dialogs_Corpus-Enemy_of_the_State.star graph from analyst training exercise 7.
2. Open the Conversation view panel
3. Attempt to move, manipulate, or select anything on the graph.

**Expected behaviour:** App continues to function

**Actual behaviour:** App stops responding

**Reproduces how often:** 100%

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

OS: Windows 10
Attempted using both v2.1.1 and 2.2-beta, behavior was observed in both version.
Observed continual memory growth in task manager before forcefully killing the app.

[SupportPackage-benja-2021-02-19-14-14-33.zip](https://github.com/constellation-app/constellation/files/6012449/SupportPackage-benja-2021-02-19-14-14-33.zip)

**Comment by Nova-2119** [comment]
This behaviour only seems to be present in the prebuilt version of Constellation, I was unable to reproduce this behaviour when building constellation from source in Netbeans (regardless of the version).
The behaviour is also relatively inconsistent, I can't get it to occur consistently and I have not figured out how to reliably get it to reproduce.

After chatting to @arcturus2 and @antares1470 the theory is that perhaps it is an error in the settings when creating the build, possibly not including a library or something that should be included.

**Comment by antares1470** [comment]
I have given this a test in 2.3.0-rc1 on Windows 10 and I don't see this issue occurring
