### ISSUE TITLE
Improve renderTextAsLigatures speed.

### ISSUE THREAD

**Issue by Nova-2119** [constellation-app/constellation#984]
### Description

The method GlyphManagerBI.renderTextAsLigatures is much slower than the implementation prior to V1.3. In this upgrade it underwent a complete refactor to expand Constellation's comparability with different fonts.

However this had led to a significance performance impact in loading and interacting with graphs as it slows down refreshing the graph on the canvas. Performance improvements to renderTextAsLigatures will hence make an obvious impact to Constellation performance and should be explored.

Note: There is no guarantee that performance improvements are there to be had and any improvements will likely require a complete refactor rather than just tidying things up and doing things a bit more efficiently.

### Steps to Reproduce

1. Open a 100,000 node graph in the current version
2. Observe how long it takes (with multithreading)
3. Open a 100,00 graph in the [original version of Constellation uploaded to github](https://github.com/constellation-app/constellation/releases/tag/v1.20190929.144916)
4. Notice the speed (without multithreading)
5. Alternately instead of opening the current version open [original V2 without multithreading improvements](https://github.com/constellation-app/constellation/releases/tag/v2.0.0) for a more even comparison.

**Expected behaviour:** [What you expect to happen]
 Current version should be comparable to V1 in speed.

**Actual behaviour:** [What actually happens]
Current version is significantly slower than V1 for core graph features should as deleting nodes, opening graphs etc.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Additional Information

This ticket is likely to be quite involved, it would really suit someone looking to learn about rendering and/or after a substantial project to get stuck into.

**Comment by arcturus2** [comment]
Just to show you how crazy it is, `renderTextAsLigatures` compared in v1.2 back in 2018 with `master` on the 16th of March.

* in v1 the method is called 3x as much and is 10x faster.

![renderTextAsLigatures v1 2 vs master 16 Mar 2021](https://user-images.githubusercontent.com/39325530/111241328-02a87700-8651-11eb-9592-1a898efa017d.png)

![renderTextAsLigatures v1 2 vs master 16 Mar 2021 telemetry](https://user-images.githubusercontent.com/39325530/111241703-c0cc0080-8651-11eb-9490-53d0ae83805d.png)

**Comment by arcturus2** [comment]
Interesting to note that just by removing all the threading, the `renderTextAsLigatures` runs nearly twice as fast on a 1k node and 1k transaction graph.

![image](https://user-images.githubusercontent.com/39325530/111284466-42448280-8694-11eb-8e3e-d4f08a483e77.png)

**Comment by arcturus2** [comment]
Overall performance comparing v1.2 with `master` and this branch. This is testing on a 30k node and transaction graph.

The performance improvements was gained by caching the bulk of the work done by `renderTextAsLigatures` and removing calls to `synchronize` which and therefore required all the threading to be removed. As a result the memory spikes are a lot less meaning GC work is less intense and the CPU spikes are less too.

![image](https://user-images.githubusercontent.com/39325530/111921494-00c73380-8ae9-11eb-877a-79644b5c0f6d.png)

v1.2 opening graph 1st time:
![v1 2 30k nodes and links 1st open](https://user-images.githubusercontent.com/39325530/111921526-2fdda500-8ae9-11eb-904c-9a37d9a82f30.png)

v1.2 opening graph 2nd time:
![v1 2 30k nodes and links 2nd open](https://user-images.githubusercontent.com/39325530/111921542-3ff58480-8ae9-11eb-8c91-536370f8db7c.png)

v1.2 deleting half of the graph:
![v1 2 30k nodes and links delete half](https://user-images.githubusercontent.com/39325530/111921550-4be14680-8ae9-11eb-8a75-491e7176cdb1.png)

master opening graph 1st time:
![master 30k nodes and links 1st open](https://user-images.githubusercontent.com/39325530/111921637-babe9f80-8ae9-11eb-98b1-83c7628c03e5.png)

master opening graph 2nd time:
![master 30k nodes and links 2nd open](https://user-images.githubusercontent.com/39325530/111921640-c01bea00-8ae9-11eb-8b23-ec2d2ad9c739.png)

master deleting half of the graph:
![master 30k nodes and links delete half](https://user-images.githubusercontent.com/39325530/111921643-c4480780-8ae9-11eb-8cc6-caf181cf3966.png)

latest opening graph 1st time:
![latest 30k nodes and links 1st open](https://user-images.githubusercontent.com/39325530/111921661-d4f87d80-8ae9-11eb-9a09-5d99617b74cf.png)

latest opening graph 2nd time:
![latest 30k nodes and links 2nd open](https://user-images.githubusercontent.com/39325530/111921663-d9249b00-8ae9-11eb-81e1-651184bf7c34.png)

latest deleting half of the graph:
![latest 30k nodes and links delete half](https://user-images.githubusercontent.com/39325530/111921669-df1a7c00-8ae9-11eb-83ec-6dbdd130edac.png)
