### ISSUE TITLE
JDBC Importer UX Improvements

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#988]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The following UX issues were identified by @cygnus-x-1 during testing of the JDBC importer:

- The workflow is add a driver > add a connection using that driver > query a database using that connection, however the UI asks you to set this up in the reverse order.
- When adding a driver, the file dialog should limit to only relevant file types (JAR presumably).
- There is no way to modify a driver or connection once it has been created short of removing and re-adding it.
- The content is enough such that it is put into scrollable pane, which cuts off the 'Cancel' and 'Import' buttons. Perhaps a more compact layout would be beneficial?

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Auriga2** [comment]
Another issue: If the constellation window is minimized, the column headers area overlaps the instructions in the 'Configuration' pane. It looks worse if the query doesn't return any row.
![image](https://user-images.githubusercontent.com/64826928/119916608-038c4c00-bfa4-11eb-8d86-4437fe38c39c.png)

**Comment by GammaVel** [comment]
I have the text overlap on my laptop screen when opening this up. I also noticed that there is no horizontal scroll bar when the text extends beyond the pane. See below: 
![image](https://user-images.githubusercontent.com/83679004/119918952-bcef1f80-bfac-11eb-8bf3-b62b337e850c.png)

**Comment by cygnus-x-1** [comment]
When managing connections;
![image](https://user-images.githubusercontent.com/39781856/120725613-b404cd80-c519-11eb-8bf7-216c43517a1e.png)

- The modal dialog box can be lost behind the main application window.
- There are also no confirmation/cancel buttons; it feels wrong to have to close the dialog using the X.
- There's a large amount of space at the bottom of the dialog.
- Adding a driver/connection with the same name as an existing one will overwrite it with no warning.

**Comment by cygnus-x-1** [comment]
When importing data;
![image](https://user-images.githubusercontent.com/39781856/120725820-1fe73600-c51a-11eb-8b5e-a0dc5d1a9420.png)

- You can integgorate an SQLite DB for table/column information (i'm using `SELECT * FROM sqlite_schema` above to see table info) - it'd be handy if the importer did this for you to help guide queries.
- It's possible for the columns in the preview table to be quite wide, which makes it hard to preview the data - perhaps the preview pane should be resizable?

**Comment by GammaVel** [comment]
Another suggestion to restrict the file type to be .JAR files on the Driver import. 
![image](https://user-images.githubusercontent.com/83679004/120948136-dd756180-c784-11eb-9f4f-8f65789b6423.png)

**Comment by Auriga2** [comment]
@cygnus-x-1 I have questions about your last comment:
1. Not clear where to display the table/column information. The query is also different depending on the DB 
2. This is already resizable, you can resize the column widths using the column header area. You can even drag and drop the pane into the graph area to  make them even bigger.

**Comment by Auriga2** [comment]
The field names here are hard to read:
![image](https://user-images.githubusercontent.com/64826928/121310841-f1ff5880-c942-11eb-80da-74e0fe5c59b9.png)

**Comment by Auriga2** [comment]
These are some of the changes I made, open for suggestions:

> The workflow is add a driver > add a connection using that driver > query a database using that connection, however the UI asks you to set this up in the reverse order.

I thought about moving everything into the main window, but that's going to utilize more space. Ideally a new collapsible pane above the Source pane would be nicer, which would add only the space of almost a single line, but requires more work because the code is common to 2 importers. As a quick/lazy fix, just changed the tabs inside the `Manage Connections` window, because the connections are needed to be set up only when required.

Added  `Edit` button, and changed the order of buttons to `Add`, `Edit`, `Remove` in the connections tab. There's nothing to edit in the Drivers tab, so changed the order of buttons there to `Add`, `Remove` .

Removed the `Param.setDescription` as it was duplicating information in the `Substring Parameters` window , (unlike in the DAV)
Now it looks like below: 
![image](https://user-images.githubusercontent.com/64826928/122315040-65fbbb00-cf58-11eb-8ee1-db277bf7be1f.png)

**Comment by GammaVel** [comment]
That is looking good!  As  suggestion could you consider swapping the Drivers and Connection tabs around on the Manage Connection Screen as the instructions say the Drivers should be added first.

![image](https://user-images.githubusercontent.com/83679004/122499162-c14eab80-d033-11eb-9223-7a739cdc0a7d.png)

**Comment by cygnus-x-1** [comment]
> @cygnus-x-1 I have questions about your last comment:
> 
> 1. Not clear where to display the table/column information. The query is also different depending on the DB
> 2. This is already resizable, you can resize the column widths using the column header area. You can even drag and drop the pane into the graph area to  make them even bigger.

1. I think it'd have to be a in a new section - after choosing a connection, something (pane? side-bar? drop-down?) would be populated with hints/helpers based on what type of connection it is.
2. The view is resizable and the column widths can be adjusted - the issue i ran into was that certain columns had data large enough that the row width would be larger than the preview pane's width to accommodate it. A simple solution would be to cut off the text at a certain length to avoid this, but I think it'd be more useful if the preview pane could be vertically resized.

**Comment by cygnus-x-1** [comment]
> The field names here are hard to read:
> ![image](https://user-images.githubusercontent.com/64826928/121310841-f1ff5880-c942-11eb-80da-74e0fe5c59b9.png)

This is a dialog-related bug I'd also found (there might be a ticket?) - you can also see it in `File > Export > GeoJSON`.

**Comment by Auriga2** [comment]
Yes I had already swapped the tabs in the `Manage Connections` window, as a quick fix. The `feature/JDBC_UX_Improvements` branch in now published. I'll try the other suggestions above now.

**Comment by Auriga2** [comment]
V2.3.0 has slightly different text sizes:
![image](https://user-images.githubusercontent.com/64826928/123203158-0de32c80-d4f5-11eb-8560-2a4b289caa1f.png)
The name and description are narrower because the width of the `name` field is smaller. (Same behavior in DAV)

**Comment by Auriga2** [comment]
@cygnus-x-1 
> 1. I think it'd have to be a in a new section - after choosing a connection, something (pane? side-bar? drop-down?) would be populated with hints/helpers based on what type of connection it is.

This seems more complicated because of the supported DB range and because the queries depend on the DB. Can't think of a dynamic implementation here. Also the user is supposed to be fluent (or capable of googling) in querying to use the query editor afterwards anyway. Do you think it's still worth the effort?

> 2. The view is resizable and the column widths can be adjusted - the issue i ran into was that certain columns had data large enough that the row width would be larger than the preview pane's width to accommodate it. A simple solution would be to cut off the text at a certain length to avoid this, but I think it'd be more useful if the preview pane could be vertically resized.

When the content is larger it already cuts off and adds 3 dots. 
![image](https://user-images.githubusercontent.com/64826928/123365859-4d258200-d5b6-11eb-8138-5cb9d9e6a26d.png)

I am not sure what you mean by vertically resizing the preview pane. If you shrink the `Source` and/or `Attributes` pane, the  table expands. If you need more space, you can even drag and drop the entire tab into the graph area:
![image](https://user-images.githubusercontent.com/64826928/123367116-8e1e9600-d5b8-11eb-9612-feaf2e22744e.png)

**Comment by cygnus-x-1** [comment]
> When the content is larger it already cuts off and adds 3 dots.
There's an example of what I was referring to in the Consty Chat (4/06 9:22 am), perhaps it's more to do with new lines in the text than large text?

> I am not sure what you mean by vertically resizing the preview pane. If you shrink the Source and Attributes panes, the table expands.
I don't think I noticed that the Source and Attribute panes were collapsible when I was testing - that would certainly help. What I was suggesting was adding the ability to make each pane thinner or thicker by clicking and dragging the edges (vertically resize), that way I could give each pane as much room as I want without completely collapsing them.

**Comment by Auriga2** [comment]
1) I guess you mean the `sql` column here. You can widen this column width by clicking on the border of the header. Do you want to expand a row similarly, to see more content? From what I can see, that is not how most (if not all) of the sql editors work. 
![image](https://user-images.githubusercontent.com/64826928/124554797-8216bc00-de75-11eb-8867-37ee67f2a007.png)

![image](https://user-images.githubusercontent.com/64826928/124554694-627f9380-de75-11eb-979e-4bf8caaec3f2.png)

2) Not sure it's worth the effort when we already have the ability to collapse. Also this is how the other views like `Data access view` work already.
