### ISSUE TITLE
Delimited File Importer automatically arranges imported data

### ISSUE THREAD

**Issue by cygnus-x-1** [constellation-app/constellation#99]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

Imported data is automatically arranged using the 'pendants arranger' which overrides any layout you might have set using the x, y, z attributes.

### Steps to Reproduce

1. Open the Delimited File Importer tool and choose a file.
2. Drag and drop the source.Identifier attribute onto a column with multiple values in the preview pane.
3. Drag and drop the x, y, z attributes onto numerical columns in the preview pane (or right click > set default value if no numerical columns are available).
4. Click the Import button.
**Expected behaviour:** [What you expect to happen]

Nodes on your graph are arranged according to the x, y, z values specified during the import.

**Actual behaviour:** [What actually happens]

Nodes on your graph are arranged neatly, ignoring your x, y, z values (you can also see that the 'Pendants Arranger' was run immediately after importing your data in the Plugin Reporter).

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% of the time.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by serpens24** [comment]
NOTE: This initial analysis is not considering importing multiple files at once ... YET

Firstly, some background.

ImportDelimitedPlugin.edit() after extracting data from src files completes execution using the following code:
`        interaction.setProgress(1, 1, "Arranging", true);

        graph.validateKey(GraphElementType.VERTEX, true);
        graph.validateKey(GraphElementType.TRANSACTION, true);

        // unfortunately need to arrange with pendants and uncollide because grid arranger works based on selection
        final VertexListInclusionGraph vlGraph = new VertexListInclusionGraph(graph, AbstractInclusionGraph.Connections.NONE, newVertices);
        PluginExecutor.startWith(ArrangementPluginRegistry.GRID_COMPOSITE)
                .followedBy(ArrangementPluginRegistry.PENDANTS)
                .followedBy(ArrangementPluginRegistry.UNCOLLIDE)
                .executeNow(vlGraph.getInclusionGraph());
        vlGraph.retrieveCoords();`

This is the code that triggers the arrangement. Now, IMO, I don't beleive the solution is to modify these arrangers as such, rather I beleive the solution is to determine **IF** the arrangers should be called at all. 

now the earlier processing in this fiunction makes a check to see if the imprt definitions are importing a SOURCE_VERTEX, DESTINATION_VERTEX, or a TRANSACTION. My thoughts are:

If we are importing a source vertex ONLY
    if at least the X and Y attribute have been tagged for import then **DO NOT call the arranger**
    else **call the arranger**
If we are importing a destination vertex ONLY
    if at least the X and Y attribute have been tagged for import then **DO NOT call the arranger**
    else **call the arranger**
if we are importing a transaction
     if at least the X and Y attribute have been tagged for import for both source and destination then **DO NOT call the arranger**
    else **call the arranger**

**Comment by serpens24** [comment]
TODO: Need to verify what is imported whn importing a transaction - does it split out source and destinaiton vertexes (I ssupect it must)

**Comment by arcturus2** [comment]
Hey @serpens24 I think the logic you've outlined in the proposed `hasPosition` method will work. If transactions are imported with no positions on vertices I think it makes sense to do the arrangement (i.e. your third dot point).

> we onl yauto arrange if source/destination vertex posiitnos were not supplied

For some background, the reason why we need to do an arrangement is because without it, all nodes appear at position 0,0,0 (x,y,z) and importing thousands of nodes on top of each other crash the graphics card. The reason this happens is because our renderer sends everything to the card, not just what the user can see. If we were to figure out how to send only the textures and layers that the user can see then it wouldn't be a problem because we would just be sending one node, the top most node.

**Comment by serpens24** [comment]
Thanks @arcturus2. So I guess on your preferred optino above:

> I think it makes sense to do the arrangement (i.e. your third dot point).
> > we only auto arrange if source/destination vertex positions were not supplied

What this would mean is that:
- if we imported vertexes in one import with x,y positions they will use these positions
- if we then (as a second import) imorted connections between them, they would get re-arranged (because the second imoort) didn't supply positions. From your background info, it seems this is acceptable.

Also in reference to your background info, and trying to avoid thousands of nodes all appearing at 0,0,0, if data is imported with invalid x,y,z positions then I expect these will all end up at 0,0,0 and could trigger the problem, but from what I saw, the improter highlights this sort of issue in red, so I guess its a case of bad data - bad results.

**Comment by arcturus2** [comment]
I'd say that would be fine @serpens24. Do you have any feedback @cygnus-x-1?

**Comment by cygnus-x-1** [comment]
I think this solution is fine, but would suggest one modification - add an 'auto-arrange' checkbox to the delimited file importer. When checked the automatic layout (grid, pendants, uncollide) will happen, and when unchecked no layout will happen. Any provided positional attribute values should override this behaviour, and this could be reflected in the UI by disabling the checkbox if you map a positional attribute to a column. This would be consistent with Constellation's goal of not doing things automatically on the users behalf.
Aspirationally, you could make the concept of positional attributes more generic by setting a 'positional' property on x/y/z/whatever attributes in the _VisualConcept_. This would require _SchemaAttribute_ to have a properties map (like _SchemaElementType_ currently does), so would be a larger change, but would allow any new attributes to be tagged as positional (or anything else).

**Comment by serpens24** [comment]
@arcturus2 - what are your thoughts on @cygnus-x-1 proposal above.

My thoughts are there are two parts to this.

The first part being a checkbox which allows auto arrange to be turned off for an import (even if no positional data exists) ... I expect the side-effect of this would be that if the user was to uncheck this 'auto-arrange' checkbox and import a heap of data without positional info that these nodes would all stack on top of each other .... I'm happy to implement if you are ... perhaps this use case is the improt of a small amount of data that you don't want auto arranged and are willing to import then drag/drop to arrange.

The second (aspirational) part is probably best handled via a new issue if it is agreed that its a good idea to preserve the specifc purpose of this ticket and allow the aspirational design to be handled thoroughly.

**Comment by arcturus2** [comment]
@serpens24 i think the 'auto-arrange' checkbox @cygnus-x-1 has proposed is a great idea. If your happy to do that under this ticket then great.

I'd agree the second aspiration idea about creating a 'positional' attribute would be a separate ticket and a lower priority.
